### ISSUE TITLE
Removing highcharts.com link credits

### ISSUE THREAD

**Issue by ghermans** [ConsoleTVs/Charts#102]
Is it possible to add a setting option to set the credits to false?

http://api.highcharts.com/highcharts/Chart.credits
http://stackoverflow.com/questions/15459224/removing-highcharts-com-link-credits

**Comment by ConsoleTVs** [comment]
Hello, Did you purchase highcharts?

**Comment by ghermans** [comment]
Actually that was not the question but i already fixed it, thanks anyway

**Comment by ConsoleTVs** [comment]
I know but seems like highcharts credits must be given if the library is not bought!

**Comment by mailnike** [comment]
@ghermans how did you fix this? it seems it is free for non commercial use and require no license.

**Comment by ConsoleTVs** [comment]
You need to remove it with the highcharts option in the highcharts template on this package

**Comment by ConsoleTVs** [comment]
Will probably be added in 3.1
