### ISSUE TITLE
Problem with Morris Charts in Bootstrap Tabs

### ISSUE THREAD

**Issue by kinsaz** [ConsoleTVs/Charts#105]
I am having a problem using Morris charts with Bootstrap 3 tabs. The charts render fine on the active tab, however, the charts are a mess if rendered on inactive tabs (when the page loads). If I refresh the page the charts get fixed on the new active tab and the other tabs do not render properly.

Any ideas on how to address would be greatly appreciated.

**Comment by ConsoleTVs** [comment]
Hey! I ran into the same issue last week, so here's how to deal with it.

https://erik.cat/projects/Charts/docs/3.0#charts-in-tabs

I've added a tutorial in the docs, have fun!

**Comment by kinsaz** [comment]
Thanks. This solution worked very well for me!!

**Comment by ConsoleTVs** [comment]
You're welcome!

**Comment by DigitalCoder** [comment]
You can try to add this if you are using [https://getbootstrap.com/javascript/#tabs](https://getbootstrap.com/javascript/#tabs)

```
        var canvasMinHeight = '400px';
        $(function() {
            $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
                $($(e.target).attr('href')).find('canvas').height(canvasMinHeight);
            });
        });
```

enJoy & bE haPPy !

**Comment by ConsoleTVs** [comment]
Haha, this may work for some libraries, but in fact, you got multple solutions out there!

**Comment by DigitalCoder** [comment]
Yes indeed,
It must then be adapted for the other libraries
I had problem with 'chartjs' but not with 'highcharts

But for my current needs, I do not have too much time to adapt for other :D

**Comment by ConsoleTVs** [comment]
Sure, nice one tho ^^

**Comment by kinsaz** [comment]
Aleks Kins has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=946634442539-bpj9bmemdvoedu8d3or6c69am3mi71dh.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.gdocs.pro%2Fg.php&customparam=customparam>

**Comment by nam-co** [comment]
Hi Erik, thanks for the package, I was wondering if you have a solution for bootstrap 4 tabs? I tried your charts-in-tabs link but its blank, appreciate any help

**Comment by ConsoleTVs** [comment]
You mean this? https://erik.cat/projects/Charts/docs/4#charts-in-tabs
