### ISSUE TITLE
group by with count()

### ISSUE THREAD

**Issue by leonh12** [ConsoleTVs/Charts#106]
Can I put the info in the picture in like a bar, pie, donut chart. I used an inner join to get this data. So I want a see the name of the education and the amount of students of that education.

<img width="133" alt="screen shot 2016-12-20 at 11 37 24" src="https://cloud.githubusercontent.com/assets/23411290/21347411/c5e16118-c6a8-11e6-9c48-eff645f0ce6a.png">

**Comment by ConsoleTVs** [comment]
You need to build the data array yourself. Like this:

```
$labels = ['law', 'cs'];
$values =  [10, 23];
$chart = Charts::create('bar', 'material')->values($values)->labels($labels)->elementLabel('Ammount Of Students')->title('My Chart');
```

The variables $labels and $values should be direct from the database like this:

```
// This is your database model
use App\Education;

$labels = [];
foreach(Education::all() as $edu) {
    // Assumed a column 'name' that displays the name of the education
    array_push($edu->name);
}
$values = [];
foreach($labels as $l) {
    array_push($values, count(Education::where('name', $l)->get()));
}

// Create the chart
$chart = Charts::create('bar', 'material')->values($values)->labels($labels)->elementLabel('Ammount Of Students')->title('My Chart');
```
