### ISSUE TITLE
[FEATURE] Add AM Chart

### ISSUE THREAD

**Issue by san3jaya** [ConsoleTVs/Charts#107]
Hello guys,
Is there any chance to add [AM charts](https://www.amcharts.com/).

**Comment by ConsoleTVs** [comment]
They will probably be added for 2.1 :)

**Comment by strikermdd** [comment]
This and Echarts will be a great new feature for this package.

**Comment by ConsoleTVs** [comment]
They will be added soon :)

**Comment by poxin13** [comment]
Would also love to see AM Charts

**Comment by Daniel-HBK** [comment]
did you added it to version 6 ?

**Comment by Gnapstar** [comment]
I'd love to see this as well
