### ISSUE TITLE
How can I use groupByMonth

### ISSUE THREAD

**Issue by minedun6** [ConsoleTVs/Charts#108]
Hey Erik,
Is it possible to use the groupby function on the `Charts::create`.
problem is that when I do a 
`Charts::database` it only returns a count of my data, but I need to extract the sum of transaction done for that day as well as display all the months of the year, that way I get a representation per month/perday
of the money generated on that day/month.

**Comment by ConsoleTVs** [comment]
I remember somebody had similar issues with this and made a PR (https://github.com/ConsoleTVs/Charts/pull/99)

I don't know if this will be usefull for you but if not, you can always made this yourself :p 

Anyway I find your problem "not away from reality" so I might give it a chance for a future feature :D

**Comment by minedun6** [comment]
it should my friend becuase I think that the concept of charts is not just showing the number of records on a given day, but maybe we want to show the $ made during that day, the AVG, which can be done using the create function but it can be much more nicer to show this in a a yearly/monthly period not only the dates where there were transactions or not, you need to show for example that during a day/month, we didn't make any transactions or any income but since the create method needs the values/labels, you need to take care of that alone which defies the purpose of a package if I can say so.

**Comment by ConsoleTVs** [comment]
Well, it does not defie the purpose of the package since you don't really need to write around 50/100 lines of javascript to create it but I understand the problem.

**Comment by minedun6** [comment]
Hey Erik, so how did it go, anything new on this ?
Reminder of the problem, I need to calculate the sum (price column) instead of simple count when using the database builder. Perhaps even extract your own method to use some of the most used aggregate function like sum/avg/count/...

Happy New Year.

**Comment by ConsoleTVs** [comment]
hello, wont be able to work on anything till end of this month. Final exams atm.

**Comment by minedun6** [comment]
Oh boy here comes the exams, good luck my friend.

Closing this issue then.

**Comment by ConsoleTVs** [comment]
Nono, keep it open so i can remember it :p

**Comment by oceanapplications** [comment]
I think my addition in #99 should do exactly what you're looking for 👍 .

**Comment by ConsoleTVs** [comment]
I agree, should be done already, thanks @oceanapplications

**Comment by minedun6** [comment]
Ended up doing a big long sql query instead of using the functions of the package, this is the query I ended up with 
```
DB::select("SELECT SUM(IF(MONTH = 'Jan', total, 0)) AS 'Jan',SUM(IF(MONTH = 'Feb', total, 0)) AS 'Feb',SUM(IF(MONTH = 'Mar', total, 0)) AS 'Mar',SUM(IF(MONTH = 'Apr', total, 0)) AS 'Apr',SUM(IF(MONTH = 'May', total, 0)) AS 'May',SUM(IF(MONTH = 'Jun', total, 0)) AS 'Jun',SUM(IF(MONTH = 'Jul', total, 0)) AS 'Jul',SUM(IF(MONTH = 'Aug', total, 0)) AS 'Aug',SUM(IF(MONTH = 'Sep', total, 0)) AS 'Sep',SUM(IF(MONTH = 'Oct', total, 0)) AS 'Oct',SUM(IF(MONTH = 'Nov', total, 0)) AS 'Nov',SUM(IF(MONTH = 'Dec', total, 0)) AS 'Dec'
            -- SUM(total) AS total_yearly
            FROM
              (SELECT DATE_FORMAT(played_at, '%b') AS MONTH,
                      SUM(price) AS total
               FROM historics
               WHERE played_at <= NOW()
                 AND played_at >= Date_add(Now(),interval - 12 MONTH)
               GROUP BY DATE_FORMAT(played_at, '%m-%Y')) AS sub")
```
and I tried doing what @oceanapplications suggested, the functions doesn't exist even though I'm on version 3.0.9 and this function was added in 3.0.7.
Something else that would be welcomed is some docs on this feature since it was added.

if there is a better way to write this, I'm all ears.

**Comment by ConsoleTVs** [comment]
1. You need to get the database rows for each montg (should not be hard, use ->whereMonth in models)
2. Use a laravel collection to collect the data

**Comment by oceanapplications** [comment]
`$data = Orders::select('orders.created_at', DB::raw('count(orders.id) as aggregate'))->groupBy(DB::raw('Date(orders.created_at)'))->get(); //must alias the aggregate column as aggregate

  $chart = Charts::database($data)->preaggregated(true)->lastByDay(7, false);` 
That's what is in the docs. Try something like 

`$data = Orders::select('orders.created_at', DB::raw('sum(orders.total) as aggregate'))->groupBy(DB::raw('Month(orders.created_at)'))->get(); 
`
