### ISSUE TITLE
Cannot change the color for Highchart area chart

### ISSUE THREAD

**Issue by DesmondPang** [ConsoleTVs/Charts#109]
Cannot change the color for Highcharts -Area chart. When I call colors() function, it give empty chart.

**Comment by ConsoleTVs** [comment]
Can you provide me the code you use to generate the area chart?

**Comment by DesmondPang** [comment]
```php
public function index(){
        
        $chart = Charts::create('area', 'highcharts')
            ->title("Sale")
            ->colors(['#2b908f'])
            ->elementLabel("NO.")
            ->values([5,20,100])
            ->responsive(true);
        
        return view('seller.dashboard.index', ['chart' => $chart]);
}
```
It gives empty chart. If I remove the colors() or change area into line, it works. Thanks.

**Comment by ConsoleTVs** [comment]
Hello, you're missing the labels! A chart needs values and labels for each value!

```
public function index(){
        
        $chart = Charts::create('area', 'highcharts')
            ->title("Sale")
            ->colors(['#2b908f'])
            ->elementLabel("NO.")
            ->values([5,20,100])
            ->labels(['label1', 'label2', 'label3'])
            ->responsive(true);
        
        return view('seller.dashboard.index', ['chart' => $chart]);
}
```

**Comment by DesmondPang** [comment]
@ConsoleTVs  Thanks. I found that the problem is not about the labels(). It should be about the colors() function. If I remove the colors() function it can generate a chart with "No Data Set" labels.
Therefore, I think there is a bug caused by the colors() function.

**Comment by DesmondPang** [comment]
I understand that you mentioned some of chart cannot change the color. eg: highcharts and chartist can't change the color of this Donut / Doughnut. Is it a bug or you forgot to list it in the API doc?

**Comment by ConsoleTVs** [comment]
Some frameworks can change the colors but it's difficults (must be done with css sometimes) or just too complicated. this might only apply to some framework's type of chart. Have your tried another library rather than highcharts with the code you have?

**Comment by DesmondPang** [comment]
Yes. It is fine to other libraries such as chartist. However, my option is Highchart as it has more features like export the chart to jpeg and pdf.

**Comment by ConsoleTVs** [comment]
I fixed a potential issue regarding to this for 4.0 version. Stay ready for the next release!
