### ISSUE TITLE
[QUESTION] How generate image chart

### ISSUE THREAD

**Issue by serobalino** [ConsoleTVs/Charts#11]
What is the point of PHP integrating and rendering JS?, how did it generate an image graph with your library

**Comment by tabacitu** [comment]
Valid question. The point of this library is to provide a uniform API for multiple chart JS libraries. Yes, you could create one JS api to "rule them all", not a PHP one. It's a matter of opinion, if you prefer writing JS or PHP.

You can't create an image graph with this library.

Hope it helps!
