### ISSUE TITLE
Bug report on ChartJS on pie and donut views with default (randomized) colors

### ISSUE THREAD

**Issue by fsasvari** [ConsoleTVs/Charts#110]
Hi there,

I found a bug on **ChartJS** blade views on **pie** and **donut**. There was a problem when colors() are not set, and default ones are being generated in blade views.

resources/views/chartjs/**pie.blade.php**, line **29**:
`"{{ sprintf('#%06X', mt_rand(0, 0xFFFFFF)) }}" // comma (,) missing on the end of list`

resources/views/chartjs/**donut.blade.php**, line **29**:
`"{{ sprintf('#%06X', mt_rand(0, 0xFFFFFF)) }}" // comma (,) missing on the end of list`

Haven't changed other views but maybe there are more problems with missing commas. I was using ChartJS so I figured it out.

**Comment by ConsoleTVs** [comment]
Thanks! Should be fixed now :)
