### ISSUE TITLE
Highcharts Yaxis unchanged !!

### ISSUE THREAD

**Issue by minedun6** [ConsoleTVs/Charts#112]
This is a continuation of this issue : [highcharts-yaxis-title](https://github.com/ConsoleTVs/Charts/issues/61)
Hey, Erik problem still persisting when using the 
```
Charts::multi 
```
it still outputs 'Values' even with me adding the elementLabel.

       $chart = Charts::multi('bar', 'highcharts')
       ->elementLabel('My nice label')
       ->title('Income in ' . config('app.currency'))
       ->labels($data[0])
       ->dataset($currentMonth->format('m') . ' - ' . $currentMonth->year, $data[1])
       ->dataset($lastMonth->format('m') . ' - ' . $lastMonth->year, $secondData[1])
       ->responsive(true);

**Comment by ConsoleTVs** [comment]
Whops! Fixing it now!

**Comment by ConsoleTVs** [comment]
Fixed in: https://github.com/ConsoleTVs/Charts/releases/tag/3.0.11
