### ISSUE TITLE
Join Multiple database charts?

### ISSUE THREAD

**Issue by mpixelz** [ConsoleTVs/Charts#113]
Hi,
just found out about this library and i really love it!
thanks..
one question though...
i have 2 linecharts displaying admins and students.
how can i display these into one chart instead?
here are my charts:
```
$studentchart = Charts::database(\Role::findOrFail(2)->users, 'line', 'chartjs')
    ->title('')
    ->elementLabel("Total")
    ->responsive(false)
    ->dateColumn('created_at')
    ->lastByMonth(12, true);
$adminchart = Charts::database(\Role::findOrFail(3)->users, 'line', 'chartjs')
    ->title('')
    ->elementLabel("Total")
    ->responsive(false)
    ->colors(['#00a65a'])
    ->dateColumn('created_at')
    ->lastByMonth(12, true);
```
ive been trying to draw two lines on the same chart..
thanks.

**Comment by mpixelz** [comment]
any help on this?

**Comment by ConsoleTVs** [comment]
You can't use the database function to create a multi chart yet.

You need to create a chart using the Charts::multi method and add two diferent datasets. You'll need to create the data yourself getting the array of each month and adding it. I'm working on a multi-databse feature but its not yet available. Sorry

**Comment by ConsoleTVs** [comment]
Should be done for 4.0.
