### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by minedun6** [ConsoleTVs/Charts#114]
Hey Erik,
Is there a way to disabled the menu on the right hand side where you can download the chart in jpg/png...
As well as the Highcharts.com in the bottom left side.

**Comment by ConsoleTVs** [comment]
Yeah, they are pointed for 3.1

**Comment by ConsoleTVs** [comment]
The credits can already be disabled using ->credits(true) / ->credits(false)

**Comment by ConsoleTVs** [comment]
You can disable exporting removing the export module from the highcharts scripts in the config.
