### ISSUE TITLE
Compatibility with Laravel 5.4

### ISSUE THREAD

**Issue by DenzoNL** [ConsoleTVs/Charts#115]
Because this package depends on ```illuminate\support``` being on a version of 5.3.* or below, I currently cannot upgrade to Laravel 5.4 (because I want to keep using this amazing package!).

I haven't tried adjusting composer.json myself, but I'm pretty sure 5.4's changing are drastic enough that it should break anything.

If you don't have time for this, I'm willing to look into it and submit a PR :)

Thanks in advance!

**Comment by ConsoleTVs** [comment]
Hello! As far as today, i finished exams, so i'm free to look forward some minor issues that might be causing . Will look into it shortly, thanks!

**Comment by ConsoleTVs** [comment]
It's fixed already! :)

**Comment by v01061374** [comment]
Hi
Despite you said it is fixed
Still i can not install it in 5.4 because of dependency on illuminate/support

**Comment by ConsoleTVs** [comment]
Hello, I'm using it on laravel 5.4 without any issues, I don't know... You probably have conficting packages, we allow any illuminate/support from 5.*, that includes 5.4

**Comment by tegar09** [comment]
Hi, iam using laravel laravel 5.4 
i already add 'ConsoleTVs\Charts\ChartsServiceProvider::class,' into the provider but it still give an error messages like this : [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'ConsoleTVs\Charts\ChartsServiceProvider' not found

**Comment by tegar09** [comment]
Hi, iam using laravel laravel 5.4 
i already add 'ConsoleTVs\Charts\ChartsServiceProvider::class,' into the provider but it still give an error messages like this : [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'ConsoleTVs\Charts\ChartsServiceProvider' not found

**Comment by ConsoleTVs** [comment]
Read the first lines of the docs. You're adding the wrong service provider path.

**Comment by cherniyosser95** [comment]
Call to undefined method ConsoleTVs\Charts\Builder\Chart::setView()
--
what's wrong i have chart version 5.0
