### ISSUE TITLE
Unknown chart library / type combination

### ISSUE THREAD

**Issue by Ssankau** [ConsoleTVs/Charts#116]
Hi,

When i try to display piechart on a view i am getting the above error.Any idea on how i can solve it.

Thanks.

**Comment by Ssankau** [comment]
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Transactions;

use App\MessageMap;

use Charts;

class ChartController extends Controller
{
    public function index()
    { 
       $chart = Charts::create('pie', 'highcharts')
       ->view('custom.pie.chart.view') 
       ->title('My nice chart')
       ->labels(['First', 'Second', 'Third'])
       ->values([5,10,20])
       ->dimensions(1000,500)
       ->responsive(false);
       return view('chart',['chart' => $chart]);

    }
}

**Comment by Ssankau** [comment]
@extends('admin_template')

@section('content')
   
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">View Transactions</h3>           
               <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            
            <div class="box-body">            
                 
                 <center>

                  {!! $chart->render() !!}

                 </center>
            
            </div>
         
        
        <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Terminal Activity</h3>
              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <div class="box-body">
              <center>

                 Line chart will display here

              </center>
          </div>
        </div>
            
            <div class="box box-success">
                <div class="box-header with-border">
                  <h3 class="box-title">Bar Chart</h3>
                  <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                  </div>
                </div>
          <div class="box-body">
            <center>

                 Bar chart will display here

            </center>
          </div>
          </div>
          </div>
            
          </div>
          
        </div>
        
      
    </section>
    
@endsection

**Comment by Ssankau** [comment]
controller and view are as above

**Comment by ConsoleTVs** [comment]
Where is your custom.pie.chart.view view at ?

Why not using the default views provided with the package?

Charts::create('pie', 'highcharts')->...;

**Comment by Ssankau** [comment]
I do not have that view yet, the view i intent to display the chart in is chart.blade.view

**Comment by ConsoleTVs** [comment]
Hello, try this:

```
$chart = Charts::create('pie', 'highcharts')
    ->title('My nice chart')
    ->labels(['First', 'Second', 'Third'])
    ->values([5,10,20])
    ->dimensions(500,0)
    ->responsive(false);
```

**Comment by Ssankau** [comment]
@ConsoleTVs

Thanks a bunch. that worked for pie chart

**Comment by ConsoleTVs** [comment]
You're welcome!
