### ISSUE TITLE
Call to undefined method Illuminate\Foundation\Application::bindShared()

### ISSUE THREAD

**Issue by stuartowendev** [ConsoleTVs/Charts#117]
I get this error when trying to publish the vendor files. I checked and bindShared() has been replaced with singleton(). This needs to be changed in html/src/HtmlServiceProvider.php

**Comment by ConsoleTVs** [comment]
Are you using laravel 5.4 ?

**Comment by Bashilor** [comment]
Hello,
I got the same error; i am able to vendor:publish without your package; but can't when i add it to the config/app.php

**Comment by ConsoleTVs** [comment]
Can you answer the same question on the top?

**Comment by Bashilor** [comment]
About Laravel ?! Oh yeah sorry ! I'm using the  Laravel 5.4.3
EDIT : And also, i don't get the error without  the package, so I assume this is the one causing the error

**Comment by stuartowendev** [comment]
Yes, Using Laravel 5.4

**Comment by ConsoleTVs** [comment]
Will work on a fix as soon as possible :)

**Comment by stuartowendev** [comment]
Thanks! Awesome job on this though! Has made my life so much easier!

**Comment by ConsoleTVs** [comment]
Hello, I installed charts on a 5.4 and it's working fine. Since I think we don't use this dependency tho, I'll remove it for future realeases.
