### ISSUE TITLE
Displaying multiple charts on the same view

### ISSUE THREAD

**Issue by Ssankau** [ConsoleTVs/Charts#118]
Hi again,

In laravel 5.3. Using ConsolveTvs, Is it possible to display different charts all reading from different db tables on the same view but in different divs.

**Comment by ConsoleTVs** [comment]
Hello, Yes, you can use as many charts as you want, the ID of the chart is changed upong render so it can render as many times as you want.  You can either create multiple instances of charts or use 1 instance and change it's table before each render.

**Comment by Ssankau** [comment]
well i do'nt know where i am going wrong on this.I have been trying to impliment the multichart display on same view for 2 days now. I keep getting this error variable bar is not defined.

here is my controller.

<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Transactions;

use App\MessageMap;

use App\ErrorCode;

use Charts;

class ChartController extends Controller
{
public function index()
    { 
    $chart = Charts::database(Transactions::all(),'pie', 'c3')
                    ->responsive(true)
                    ->title('Summary')
                    ->dimensions(1000,500)
                    ->groupBy('FIELD_39', true)
                    ->elementLabel('Transactions')
                    ->labels(['Approved or completed successfully','Refer to card issuer','Refer to card issuer, special condition','Invalid merchant','Invalid merchant']);                     
    return view('chart',['chart' => $chart]);
    

    // RealTime Line Chart Working
    $bar = Charts::realtime(route('data'),1000, 'line', 'highcharts')
                        ->responsive(true)
                        ->title('Summary')
                        ->dimensions(400,0);                      
    return view('chart',['chart' => $bar]);
    }
}

**Comment by Ssankau** [comment]
@extends('admin_template')

@section('content')
   
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box box-success">
            <div class="box-header with-border">
              <h3 class="box-title"><b><i>View Transactions</i></b></h3>
               <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            
              <div class="box-body">
              
               {!! $chart->render() !!}


              </div>
           </div>   
         
        
          <div class="box box-success">
                <div class="box-header with-border">
                  <h3 class="box-title"><b><i>Terminals Activity</i></b></h3>
                  <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                  </div>
                </div>
          <div class="box-body">

          
          
          {!! $bar->render() !!}

          </div>
          </div>
            
            <div class="box box-success">
                <div class="box-header with-border">
                  <h3 class="box-title"><b><i>Bar Chart</i></b></h3>
                  <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                  </div>
                </div>
          <div class="box-body">
              Display Bar Graph Here    
          </div>
          </div>
          </div>
            
          </div>
          
        </div>
        
      
    </section>
    
@endsection

**Comment by Ssankau** [comment]
and this is my blade.

**Comment by Ssankau** [comment]
i want the pie chart to show in the 1st div in the view and the line chart in the 2nd div. any guidance will be very much appreciated.

**Comment by Ssankau** [comment]
Got a solution by doing this.

return view('chart',['chart' => $chart, 'bar' => $bar,]);

**Comment by ConsoleTVs** [comment]
Yey! Nice!

**Comment by fadilahasana** [comment]
i have same problem with you.. 
i want to display different chart more than 1 in one page..

for make it happen.. is the controller just have 1 function? 
i hope you both can answer me

**Comment by ConsoleTVs** [comment]
Charts 6 works with instances. Each instance is a chart, and multiple instances can be displayed.

$chart1 = new ChartName(...);
$chart2 = new ChartName(...);

return view('test', compact('chart1', 'chart2'));

In the view, simply call the container and the script for each chart you pass.

**Comment by fadilahasana** [comment]
thankyou so much
i have finished my problem :+1:

**Comment by navidmetal** [comment]
are theis tips and code work for new 7.2 !!!! i cant find any doc or help for version 7.2 . the document either work in some point
plz help i'm in a serious project
i'm want to show multiple charts in a same page and my codes are in Customchart file not controller because Charts wont work in controller and it's my second problem
