### ISSUE TITLE
Updating the package httpguzzle

### ISSUE THREAD

**Issue by minedun6** [ConsoleTVs/Charts#12]
Hi, thanks for sharing this awesome package first and foremost ^_^

Ok when I tried using this package, I got this message, "Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead."
Second part is that I think u should breakdown ur 
`Charts::assets()` 
to something like 
`Charts::style()` and `Charts::scripts()` because personally I like to keep my styles up in the head section while my scripts are before the closing body section. I'm sorry for asking this.

Something else, is it possible to use styles of any custom admin panel, I like to use metronic in these cases.

Lastly, this is my skype: minedun6, I would to ask you some questions - live feedback.

**Comment by ConsoleTVs** [comment]
Hello, want to explain this in depth, so I will add you on skype, thanks!
