### ISSUE TITLE
Is it possible to have a date selector?

### ISSUE THREAD

**Issue by filtration** [ConsoleTVs/Charts#120]
For example, we are in February now, let;s say we want to show users who registered this month groupbydays, but also from last month,  is this possible? A drop down with months on the barchart

**Comment by ConsoleTVs** [comment]
This is a PHP library, not a JS library, as such, php is synchronous and can't change it's data on the fly as a js library.

What can you do to achive this?

Every time you generate a chart you have a unique $chart->id variable containing the exact same variable used for the chart. if you're using a specific chart library learn how to change the data of the chart and use the $chart->id to update it's data based on a selector. You can update the data based on a local API for example.

I'm sorry not beeing able to help on this but as I said, it's not a JS library and we can't (Yet, as it might be a feature in a future) operate with the dom with the current library status. I'm sorry.
