### ISSUE TITLE
Suggestion: Add default colors to config file

### ISSUE THREAD

**Issue by fsasvari** [ConsoleTVs/Charts#121]
Suggestion for default colors option in config file ? On my website, I'm using this package all over the place and every time I need to set same colors.

It would be great if we can set default colors in config file and if it is not provided in `Charts `call:

```
Charts::multi('line', 'highcharts')
    ->colors(['#ff0000', '#00ff00', '#0000ff']);
```

Use from configuration file:

```
'default' => [
        'type'          => 'line',
        'library'       => 'google',
        'element_label' => 'Element',
        'title'         => 'My chart',
        'height'        => 400,
        'width'         => 500,
        'responsive'    => true,
        'colors'          => [
            '#ff0000',
            '#00ff00',
            '#0000ff'
        ],
    ],
```

**Comment by ConsoleTVs** [comment]
Nice one, will do something even better for 4.0! :D

**Comment by fsasvari** [comment]
Can't wait :)

**Comment by ConsoleTVs** [comment]
Currently coding it, expect a release today :)

**Comment by ConsoleTVs** [comment]
Done for 4.0! (with an extra unanounced feature)
