### ISSUE TITLE
ChartsServiceProvider Issue

### ISSUE THREAD

**Issue by devmahmed** [ConsoleTVs/Charts#122]
When i run this command (php artisan vendor:publish --tag=charts_config) its showing Nothing to publish for tag [charts_config]. 
What can i do now.

**Comment by ConsoleTVs** [comment]
Hello, did you add the service provider into the config of laravel?

**Comment by ConsoleTVs** [comment]
It works fine. https://i.gyazo.com/2c2284b285a3db1b8389faccc47cd6a1.png

Just follow the instructions.
