### ISSUE TITLE
changelog?

### ISSUE THREAD

**Issue by mpixelz** [ConsoleTVs/Charts#125]
Hi,
is there any changelog? so we can see what have been changed and added in the new v4? :)
thanks.

**Comment by ConsoleTVs** [comment]
In terms of coding. No code needs to be changed if u already had some charts with 3.0, But it got new features and bugfixes overall. Comparing both docs should result in the new features. No methods have been renamed.

Anyway i find it usefull to add a changelog next time, sorry! I work alone on this big project and it's kinda heavy!
