### ISSUE TITLE
Undefined Variable: ds

### ISSUE THREAD

**Issue by wilmarcarinan** [ConsoleTVs/Charts#127]
![image](https://cloud.githubusercontent.com/assets/14357042/22629587/adaae1aa-ec23-11e6-9385-a767c844dfa0.png)

And it result in an Error Exception in Chart.php line 410: Undefined variable: ds. 
![image](https://cloud.githubusercontent.com/assets/14357042/22629607/fef38620-ec23-11e6-96df-aeb42c08f17f.png)

However if I remove the two strings in the labels, it will turn out okay but the last two labels was generated by default and I don't want that.
![image](https://cloud.githubusercontent.com/assets/14357042/22629613/195f58b8-ec24-11e6-9177-110ad000c027.png)
![image](https://cloud.githubusercontent.com/assets/14357042/22629622/3c42f2f4-ec24-11e6-98e1-09a292b0423e.png)

Thank you

**Comment by ConsoleTVs** [comment]
Hello, i did not create the areaspline, i don't know how does it work. Is it really nessesary? it can't be an area / line chart ?

**Comment by ConsoleTVs** [comment]
As a result i think the guy who created it missunderstood the datasets (ds) and will take a look into it myself. Give me a second.

**Comment by ConsoleTVs** [comment]
Hello after analising the chart i've created 4.0.2 to try resolve your issue, may you please try it again with the version mentioned? Thanks.

**Comment by wilmarcarinan** [comment]
Hello, I upgraded the chart to the latest version which is 4.0.5 and it worked. Thanks

**Comment by ConsoleTVs** [comment]
Perfect, thanks for the report!
