### ISSUE TITLE
Could you please upload sources of release 5.*?

### ISSUE THREAD

**Issue by VanDuy91** [ConsoleTVs/Charts#13]
My project uses Charts ver 5.* but this release doesn't exist. So, could you please upload source code of it? Or, could you tell me how to get the source code of this release?

Thanks,

**Comment by dominik-eller** [comment]
Just have a look into your vendor folder

**Comment by VanDuy91** [comment]
I run the "composer install" command, and the vendor folder constantly will be updated with the latest version (6.*).

**Comment by Suvindran94** [comment]
Yes same issue. How to download version 5?

**Comment by pmaselkowski** [comment]
I'm working on legacy app, and there is no version 4 too. Luckyli I have it installed, just need to copy over to new app instances.

**Comment by ConsoleTVs** [comment]
Older versions and future versions were removed due a trademark notice that I received. Older versions are lost unfortunately
