### ISSUE TITLE
Package on Laravel 5.2 not working

### ISSUE THREAD

**Issue by minedun6** [ConsoleTVs/Charts#13]
I installed the package after using [https://github.com/rappasoft/laravel-5-boilerplate](url) as base, it's using Laravel 5.2 so after installing and adding the service provider and the alias.
This is my controller:

       <?php

        namespace Minedun\Http\Controllers\Backend;

        use Minedun\Http\Controllers\Controller;
        use Charts;

        class DashboardController extends Controller
        {
        public function index()
        {
             $chart = Charts::new('line', 'highcharts')
                           ->setTitle('My nice chart')
                           ->setLabels(['First', 'Second', 'Third'])
                           ->setValues([5,10,20])
                           ->setDimensions(1000,500)
                           ->setResponsive(false);
               return view('backend.dashboard')->withChart($chart);
        }
     }
`

and this is the output on the browser:
`Class 'Charts' not found`

**Comment by ConsoleTVs** [comment]
Hello, this packages works well on 5.2, I've tested it myself. Did you add the alias Charts?

If so, could you try replacing ```use Charts;``` for: ```use ConsoleTVs\Charts\Charts```

**Comment by minedun6** [comment]
Already did, as well as adding the the provider but when i try to publish the config, it says `Nothing to publish for tag [charts_config]` as if it wasn't reading the package at all.

**Comment by ConsoleTVs** [comment]
I added already, willing to see what's going on ^^

**Comment by ConsoleTVs** [comment]
Solved :D - Was a problem with https://github.com/rappasoft/laravel-5-boilerplate as it needs to refresh the config each time you add a package.

**Comment by perintahsql** [comment]
I installed package Charts in laravel 5.2 too
and i get this error
FatalErrorException in ChartsController.php line 15: syntax error, unexpected 'new' (T_NEW)

could you help me to solve the problem?

here's my controller 

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Http\Requests;
use Charts;

class ChartsController extends Controller
{
	public function charts()
	{
	$chart = Charts::new('line', 'highcharts')
            ->setTitle('My nice chart')
            ->setLabels(['First', 'Second', 'Third'])
            ->setValues([5,10,20])
            ->setDimensions(1000,500)
            ->setResponsive(false);
        return view('pages.dashboard', ['chart' => $chart]);
	}	
}

**Comment by ConsoleTVs** [comment]
Hello please check the previous answer photos, it's working fine in 5.2

**Comment by muralidharan143** [comment]
Yes it's working fine

**Comment by ConsoleTVs** [comment]
@minedun6 could you explain him how did you solve it? https://github.com/ConsoleTVs/Charts/issues/75

**Comment by ngovanhieu** [comment]
Error "ErrorException in AliasLoader.php line 66: Class 'ConsoleTVs\Charts\Charts' not found" when i install it in Laravel 5.3. Does it support in Laravel 5.3 ?

**Comment by ConsoleTVs** [comment]
It does, I think you downloaded 3.0, try this docs: https://github.com/ConsoleTVs/Charts/tree/master/docs/3.0

**Comment by asifameer** [comment]
I'm getting this error "ErrorException in AliasLoader.php line 79:
Class 'ConsoleTVs\Charts\Charts' not found"
I'm using Laravel 5.4.
Followed instructions in your video
https://www.youtube.com/watch?v=KrAvrU2XYuY

Please help.

**Comment by PSNAppz** [comment]
After installation publish 
 `php artisan vendor:publish --tag=charts_config`
Then type
`php artisan config:cache`
And try refreshing the page again.

**Comment by kaideptrai1102** [comment]
ErrorException in AliasLoader.php line 79: 
Class 'ConsoleTVs\Charts\Charts' not found'
I'm using laravel 5.4. I need help

**Comment by ConsoleTVs** [comment]
Did you add th alias to the config?

**Comment by AbdulbasitSaid** [comment]
yes it was add to alias in the config

**Comment by AbdulbasitSaid** [comment]
am also using laravel 5.4

**Comment by ConsoleTVs** [comment]
So is your problem fixed?

**Comment by AbdulbasitSaid** [comment]
No it's not fixed but it just use javescript instead.

**Comment by ConsoleTVs** [comment]
"ConsoleTVs\Charts\Charts" If you read the docs carfully you'll find out this class does not even exists. and the docs tell you to add:
```php
'Charts' => ConsoleTVs\Charts\Facades\Charts::class,
```

**Comment by xiaozhousong** [comment]
I got same problem...I tried 5.2 and 5.4...same problem with class cant found..

Class 'ConsoleTVs\Charts\Charts' not found --- If use use ConsoleTVs\Charts\Charts; and 'Charts' => ConsoleTVs\Charts\Charts::class,

**Comment by ConsoleTVs** [comment]
I already told this file does not exist anymore, I added the correct one in the last comment.

**Comment by Hyfos2** [comment]
Hello guys am trying to use  Charts::multidatabase but  am getting an error message saying "Call to undefined method ConsoleTVs\Charts\Builder::multidatabase()"

Here is my controller.Would you please guys tell me how to resolve this.

<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Charts;
use  App\User;
use  App\CaseReport;

class MainreportController extends Controller
{

  public function index()

{
$chart = Charts::multidatabase('bar', 'material')->stacked(true)
                ->dataset('Element 1', CaseReport::all())
                ->dataset('Element 2', CaseReport::all())
                ->dataset('Element 3', CaseReport::all())
                ->dataset('Element 4', CaseReport::all())
               //  $chart = Charts::multi('bar', 'highcharts')
               // Setup the chart settings
               ->title("Bar  Charts")
               // A dimension of 0 means it will take 100% of the space
               ->dimensions(0, 400) // Width x Height
               // This defines a preset of colors already done:)

               ->elementLabel("Total")
               ->dimensions(1000, 500)
               ->responsive(true)
               ->groupBy('status');

 return view('Reports.index', ['chart' => $charts] );

?>

**Comment by ConsoleTVs** [comment]
multiDatabase not multidatabase

**Comment by ConsoleTVs** [comment]
It works.

**Comment by rhipix** [comment]
C:\xampp\htdocs\stocksystem>php artisan config:cache

?[37;41m                                                             ?[39;49m
?[37;41m  [Symfony\Component\Debug\Exception\FatalThrowableError]    ?[39;49m
?[37;41m  Class 'ConsoleTvs\Charts\ChartsServiceProvider' not found  ?[39;49m
?[37;41m                                                             ?[39;49m


With Laravel 5.2 I have followed every step and this error is coming up in my terminal!!!!

**Comment by AmiBell** [comment]
i have laravel 5.6 and the problem appear in this line , please can you help me .
    }
 
        if (isset($this->aliases[$alias])) {
            return class_alias($this->aliases[$alias], $alias);
        }
    }
problem:"Class 'ConsoleTVs\Charts\Facades\Charts' not found"

**Comment by vuongdinhngoc** [comment]
@AmiBell I had the same problem. Laravel 5.6, Charts 6.x

**Comment by ConsoleTVs** [comment]
Did you read the docs of v.6? Where dis you see there was a facade of charts? Like honestly, please review the docs before posting...

**Comment by Diumanuel** [comment]
Hello. Want to know how to use my database, i cant found how in documentation, im in  v6.1 of this package.

**Comment by ConsoleTVs** [comment]
You have laravel eloquent, You have collections /arrays of data when the ORM (eloquent) has finished the query. And you can pass collections / arrays in charts.

What's the problem?

**Comment by safikhadim** [comment]
where is the docs for chart

**Comment by ConsoleTVs** [comment]
https://erik.cat

**Comment by jpam26** [comment]
hmm ConsoleTVs, having a problem with 
"Class 'App\Http\Controllers\Charts' not found"
tried searching all over the net but all i can see are from late 2016 and 2017 did try to test some fix you posted but it seems luck dont want me lol.
php v 7
charts v 6.*
laravel 5.5.*

use ConsoleTVs\Charts\Classes\Chartjs\Chart;

` $chart = Charts::multi('bar', 'material')
            ->title("My Cool Chart")
            ->dimensions(0, 400) 
            ->template("material")
            ->dataset('Element 1', [5,20,100])
            ->dataset('Element 2', [15,30,80])
            ->dataset('Element 3', [25,10,40])
            ->labels(['One', 'Two', 'Three']);`


just trying to display the sample data base on your documentations,

**Comment by ConsoleTVs** [comment]
Screenshot me where in the v.6 docs I say charts::multi().

**Comment by jpam26** [comment]
didn't mean to type it multi i was doing testing all over my search over google trying to find a solution about it even though i already tried others still having an error with Charts error not found

even using the $chat = Charts::database() still having an error with Chart

![multi](https://user-images.githubusercontent.com/6664632/41544481-71e453e4-734b-11e8-9b04-36b2d5d17ea8.png)

**Comment by jpam26** [comment]
Maybe you can help me now 👍 
![multierik](https://user-images.githubusercontent.com/6664632/41545326-859b085e-734d-11e8-9815-cc304e72c386.png)

**Comment by ConsoleTVs** [comment]
Are you aware that chsrts v.6 have nothing to do with v.5 or lower and you have the docs in the readme page????

**Comment by jpam26** [comment]
well im kinda aware of that but since reading the documentations im also trying to browser or search if someone have made or update there project since your update, so im just trying my luck maybe it will work??? but since its not working thats why i posted, since im new about this starting to learn when i tried the docu of v.6 im able to make it run ' public function chart()
 {
  $chart = new SampleChart;
  // Add the dataset (we will go with the chart template approach)
  $chart->dataset('Sample', 'line', [100, 65, 84, 45, 90]);
  return view('chart_view', ['chart' => $chart]);
 }'
 but doesnt display any graph.  so i go back to the method wherein $chart = Charts::database() then having an error with Charts not found?? just here to ask for help and learn from you, sorry if im taking much of your time. 👯‍♂️

**Comment by ConsoleTVs** [comment]
Charts v.6 does not have a Charts facade, I'm sorry. You now need to build the chart yourself. Read the documentation from start to bottom. Everything you need to know is explained there, there's not further details you need to know to make a working chart. So I suggest reading it first.

**Comment by rizkynurs** [comment]
I got this error,

![image](https://user-images.githubusercontent.com/30620983/41946013-665630de-79da-11e8-8fa4-3c269f319ca8.png)

Can you help me to fix that? Thanks

**Comment by latifiyll** [comment]
well maybe a video with more explanation will help us all and a less headache for you , not having to  answer questions for each one in person. BTW thanks for this package.

**Comment by sajidwarner** [comment]
Using version ^6.2 for consoletvs/charts
my Chart app not found. i mean class not found
 'Charts' => ConsoleTVs\Charts\Facades\Charts::class,   is red>---Facades--- thare is no file name Facades. in laravel 5.3
i also use 
'Charts' => ConsoleTVs\Charts\Charts::class, bt there is same problem

**Comment by ConsoleTVs** [comment]
Tell me qhere in the docs you see you need a facade 'Charts' => ConsoleTVs\Charts\Facades\Charts::class,

**Comment by Al3xR0** [comment]
@ConsoleTVs 

I got a strange issue here, on local server the project works, but on deployment server (using git, so it`s the same source) it gives me this error: ```Class 'ConsoleTVs\Charts\Classes\ChartJs\Chart' not found```.  It could be the php version? On local it`s 7.1 and on deployment it`s 7.2 ?

```
use ConsoleTVs\Charts\Classes\ChartJs\Chart;
class DashboardChart extends Chart {
}
```

**Comment by ConsoleTVs** [comment]
You probably need to install charts on prosuction. Composer install, you know

**Comment by Al3xR0** [comment]
> You probably need to install charts on prosuction. Composer install, you know

The class is there, but It does not work ...

**Comment by lostlian** [comment]
@Al3xR0 you need to be careful with the caps. 
`this will work -> use ConsoleTVs\Charts\Classes\Chartjs\Chart;
this wont -> use ConsoleTVs\Charts\Classes\ChartJs\Chart;`

**Comment by Al3xR0** [comment]
> @Al3xR0 you need to be careful with the caps.
> 
> ```
> this will work -> use ConsoleTVs\Charts\Classes\Chartjs\Chart;
> this wont -> use ConsoleTVs\Charts\Classes\ChartJs\Chart;
> ```

Thank you. This fixed it. I don't know how that ChartJs was there instead of Chartjs. I just used ```php artisan make:chart ...```

**Comment by AllanSampaio** [comment]
Hi Erik.
Does not Laravel 5.7 work in the same way as in version 5.6? Any other modifications?

**Comment by jawam** [comment]
I'm getting this error Class 'ConsoleTVs\Charts\Charts' not found

**Comment by jawam** [comment]
please help me if anyone can...

**Comment by ukode-kode** [comment]
how do i use  'ConsoleTVs Charts 6 on the laravel 6. please any help. thanks
