### ISSUE TITLE
Add ECharts support

### ISSUE THREAD

**Issue by strikermdd** [ConsoleTVs/Charts#131]
Please add support to graphs with ECharts (https://ecomfe.github.io/echarts/index-en.html). Its a great package with tons of graphs, animated and with a good tools and interactions.

**Comment by ConsoleTVs** [comment]
I've been looking for this library for months but the website was really slow all times. Seems their load speed is now better and english documented. Will give it a go :D

**Comment by ConsoleTVs** [comment]
BTW; Is the version you gave me the latest one? I think it's this one: https://ecomfe.github.io/echarts-doc/public/en/index.html

**Comment by strikermdd** [comment]
Yes, this is the new version.

**Comment by ConsoleTVs** [comment]
Done in the next release (already in the repository but not released yet) , just wait till I release it ^^
