### ISSUE TITLE
ErrorException in Builder.php line 220:

### ISSUE THREAD

**Issue by sugengsuprayogi** [ConsoleTVs/Charts#132]
Missing argument 2 for ConsoleTVs\Charts\Builder::ConsoleTVs\Charts\{closure}() (View: .....\Resources\Views\show.blade.php)

when in show.blade.php 

 {!! Charts::assets() !!}

**Comment by sugengsuprayogi** [comment]
i am use laravel 5.1

**Comment by ConsoleTVs** [comment]
I need more details about the error, please post a screenshot

**Comment by ksidht** [comment]
I am also getting same error using laravel 5.1, screenshot & code has been attached bellow
![chart-error](https://cloud.githubusercontent.com/assets/20462672/22820082/4271e1ce-ef9b-11e6-8f29-8a4fe3bdb274.png)

In Controller
`        $chart = Charts::create('line', 'highcharts')
                  ->title('My nice chart')
                  ->labels(['First', 'Second', 'Third'])
                  ->values([5,10,20])
                  ->dimensions(0,500);`

In Blade

`        {!! Charts::assets() !!}

            {!! $chart->render() !!}`

**Comment by ConsoleTVs** [comment]
Screenshot please?

**Comment by ksidht** [comment]
Added.

**Comment by ConsoleTVs** [comment]
Strange, I'm not familiar with this kind of error, will post on reddit.

**Comment by ksidht** [comment]
I am using Charts version 4 & Laravel 5.1 may be this cause. BTW which is the best version of Charts for laravel 5.1

**Comment by ConsoleTVs** [comment]
I started charts development when laravel 5.3 was out, so never tried 5.1 myself...

**Comment by ConsoleTVs** [comment]
@trolleycrash fixed that for you guys!
