### ISSUE TITLE
Suggestion: Custom parameter for groupByMonth() method

### ISSUE THREAD

**Issue by sabival89** [ConsoleTVs/Charts#134]
Hello **Erik**, I must commend you for the great work done so far.

Is it possible to add a custom date column as a parameter in the groupByMonth() method in order to override the deafult '**created_at**' column as specified in the construct method in the Database class?

I actually have a column titled **provisioned** in one of my tables and this column records the date which client services were provisioned (registered). I need my chart to group the column by the provisioned column.

So I did something like this in my controller class:
``` php 
...  ->groupByMonth('2016', true, 'provisioned') 

```

In the **database** class i added this in the groupByMonth method
``` php
public function groupByMonth($year = null, $fancy = false, $column = null)
    {
        $labels = [];
        $values = [];

        $date_column = ( !is_null($column) ) ? $column : $this->date_column;
```

**Result**
![capture](https://cloud.githubusercontent.com/assets/2057169/22833924/db72cf6a-efb3-11e6-9adb-7045e5b10cbe.PNG)

**Comment by whitis01** [comment]
The functionality you are looking for already exists. You can use the function dateColumn() function which is part of \ConsoleTVs\Charts\Builder\Database. This will set the column you want to use instead of the default 'created_at'. This will work across all the getBy*() that work with date. 

Concurrently, there may be an argument for using the dateColumn() function to do a check on null and default to 'created_at'.

    /**
     * Set date column to filter the data.
     *
     * @param string $column
     */
    public function dateColumn($column = null)
    {
        $this->date_column = $column !== null ? $column : 'created_at';

        return $this;
    }

**Comment by ConsoleTVs** [comment]
Indeed,  @whitis01 already answered that! Thanks for the support!

**Comment by sabival89** [comment]
Thank you all.. I have tried it and it works perfectly. Cheers!!!

**Comment by ConsoleTVs** [comment]
You're welcome :)
