### ISSUE TITLE
database multi?

### ISSUE THREAD

**Issue by johnstontrav** [ConsoleTVs/Charts#138]
Great work on this package!

How do you do a mulit for databases?

**Comment by ConsoleTVs** [comment]
https://erik.cat/projects/Charts/docs/4#multi-database-charts

This is documented already ^^

**Comment by MweuD** [comment]
This page is very useless

**Comment by ConsoleTVs** [comment]
Perhaps because new version requires few knowledge of PHP and does not give you everything done and limited :)

https://erik.cat/projects/charts

**Comment by archulal** [comment]
sds
