### ISSUE TITLE
Vuejs still up or not ?

### ISSUE THREAD

**Issue by minedun6** [ConsoleTVs/Charts#140]
U still have your planings for changing this into using VueJS ?
Other than that, is there a way to export the views to be overriten and add some controls onto it ?

I'll try to override the js section to make new calls based on a form.

**Comment by ConsoleTVs** [comment]
Hello, as far as i kbow, vuejs won't bring any improvements, so I guess not... I remember there's a function ->view that allows you to use your own view, in fact you just need to copy it from the views in the repository and extend it by adding your own logic.

As always, remember that the carts are stored mostly in variables, where the variable name is the  chart id.
