### ISSUE TITLE
Download scripts to run offline

### ISSUE THREAD

**Issue by jorgemorgado25** [ConsoleTVs/Charts#141]
Hi.
Is there a way to download all scripts and css files to run and show charts without internet connection?
I manually downloaded and copied all assets files in a folder but doesn´t work.
I need it, thanks!

My code:

    <script src="{{ asset('/consoleTv/gauge.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('/consoleTv/chartist.min.js') }}" type="text/javascript"></script>
    <link href="{{ asset('/consoleTV/chartist.min.css') }}" rel="stylesheet" type="text/css" />
    <script src="{{ asset('/consoleTv/Chart.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('/consoleTv/fusioncharts.js') }}" type="text/javascript"></script>
    <script src="{{ asset('/consoleTv/fusioncharts.theme.fint.js') }}" type="text/javascript"></script>
    <script src="{{ asset('/consoleTv/jsapi.js') }}" type="text/javascript"></script>    
    <script src="{{ asset('/consoleTv/loader.js') }}" type="text/javascript"></script>
    <script type="text/javascript">google.charts.load('current', {'packages':['corechart', 'gauge', 'geochart', 'bar', 'line']})</script>
    <script src="{{ asset('/consoleTv/highcharts.js') }}" type="text/javascript"></script>
    <script src="{{ asset('/consoleTv/offline-exporting.js') }}" type="text/javascript"></script>
    <script src="{{ asset('/consoleTv/map.js') }}" type="text/javascript"></script>
    <script src="{{ asset('/consoleTv/data.js') }}" type="text/javascript"></script>
    <script src="{{ asset('/consoleTv/world.js') }}" type="text/javascript"></script>    
    <script src="{{ asset('/consoleTv/raphael.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('/consoleTv/justgage.min.js') }}" type="text/javascript"></script>
     <link href="{{ asset('/consoleTV/morris.css') }}" rel="stylesheet" type="text/css" />
     <script src="{{ asset('/consoleTv/raphael.min.js') }}" type="text/javascript"></script>
     <script src="{{ asset('/consoleTv/morris.min.js') }}" type="text/javascript"></script>
     <script src="{{ asset('/consoleTv/d3.min.js') }}" type="text/javascript"></script>
     <script src="{{ asset('/consoleTv/plottable.min.js') }}" type="text/javascript"></script>
     <link href="{{ asset('/consoleTV/plottable.css') }}" rel="stylesheet" type="text/css" />
     <script src="{{ asset('/consoleTv/progressbar.min.js') }}" type="text/javascript"></script>
     <script src="{{ asset('/consoleTv/d3.min.js') }}" type="text/javascript"></script>
     <script src="{{ asset('/consoleTv/c3.min.js') }}" type="text/javascript"></script>
     <link href="{{ asset('/consoleTV/c3.min.css') }}" rel="stylesheet" type="text/css" />

**Comment by ConsoleTVs** [comment]
Hummm why would you want a website to run in offline mode? And anyway, it should oviously work if you downloaded each and every file generated upon {{ Charts::assets() }}

**Comment by jorgemorgado25** [comment]
It's not a website. I'll Be a system that will be in LAN. 

I cant understand this line:

<script type="text/javascript">google.charts.load('current', {'packages':['corechart', 'gauge', 'geochart', 'bar', 'line']})</script>

**Comment by ConsoleTVs** [comment]
I'am afraid google and material libraries won't work because google dont allow remote download. This line loads up the charts for google and material. You should in fact use another library offline.
