### ISSUE TITLE
Problem with non-english character 

### ISSUE THREAD

**Issue by molbi** [ConsoleTVs/Charts#145]
Hi, i am trying use your package, but i have problem with escaping title and labels in charts template. I have tried use all most function for encoding text character, but nothing help me. Problem is in blade template of each charts, actually every where labels and title of chart are rendered. 

When I changed curly brackets from escaping variant "{{ }}" to unescape {!! !}} it helps me, of course, i should publish template for char i want and change this in resources folder in my project.

I dont know if this is a issue, but this is my experience with this.

But thanks for great package ;)

**Comment by ConsoleTVs** [comment]
I dont know how to help you here but you can try creating your own view and using the ->view method.

**Comment by molbi** [comment]
Hi, thank you for very fast replay. Actually it is not an issue, may be just a little problem, which someone may have.

I will close this issue, but here is my inputs and outputs...

```php
$labels = ["Aktivní prodej"] 
```

and output in html in JS part is

```javascript
data: [ { name: "Aktivn&iacute; prodej", y: 5  } ]
```

unfortunatly this is not rerendered by browser back to "clasic" character. 

For me the, solllution was make own copy (overload) of specific view for chart.

But thanks for replay.

**Comment by ConsoleTVs** [comment]
You're welcome, I'm really sorry for the issue tho :/

**Comment by tad3j** [comment]
I've noticed this not only happens with non-english, but also with special characters like "&". Here is a screenshot: https://www.screencast.com/t/L1h1KNvxRgs

Is it maybe because package uses HTML encoding for JavaScript strings?

**Comment by molbi** [comment]
Hi, I know where problem is, in blade templates of each type of graph were titles and labels inserter with escpaing {{  }}  => 'htmlspecialchars($value, ENT_QUOTES, 'UTF-8', false); ... and this is a problem, because when use this in html part of blade template, the escaped character are rerendered by browser, but in javascript part, this doesnt happend and text is in escaped shape. 

Solution: 

1) overload views in your resource/vendor/ folder (my option)
2) in default templates use non escaping blade macro {!! !!}

**Comment by ConsoleTVs** [comment]
@molbi is right, this will be fixed in next release, thanks!

**Comment by rsmalc** [comment]
I have the same problem with (čćžšđ). My solution is to use {!! !!}. Can I create a patch for this?

**Comment by ConsoleTVs** [comment]
I'll need to modify each template when outputing the title and labels. Feel free to send a Pull Request.
