### ISSUE TITLE
HighCharts chart doesnt get displayed if one of the values is null

### ISSUE THREAD

**Issue by tad3j** [ConsoleTVs/Charts#147]
Spent more than an hour chasing down a problem where chart wouldn't display, and all charts bellow failed to display as well.

At the end it turned out that it was failing because my query was returning NULL for one date, and package generated code like this:

`
data : [
	0,
	2,
	2,
	2,
	2, ,
	0,
]
`

...notice the 2 consecutive commas.

I was able to solve this problem by adding IFNULL to query, but I thought I would post it here; was thinking....maybe package could throw an exception in such case (to save time with debugging), or use a default value (like in my case I sue 0)? ...if nothing else, I hope I'll save some time to anyone experiencing similar problems.

Btw, this problem doesn't occur with ChartJS (haven't tried others).

Oh, and here is the jsfiddle: https://jsfiddle.net/ako4apjq/

**Comment by ConsoleTVs** [comment]
Were you using eloquent? Post the code here (php one) please

**Comment by tad3j** [comment]
I was using eloquent but decided to switched to DB. Would I be better off with eloquent?

Here is my code (I stripped it down a cleaned bit since, it's quite long):

`
$dataSet = DB::table('deparments_historical_stats')
    ->selectRaw('d.name, deparments_historical_stats.day, SUM(deparments_historical_stats.' . $dataCountName . ') as ' . $dataCountName . '')
    ->leftJoin('departments AS d', 'd.id', '=', 'b.department_id')
    ->groupBy('d.id', 'deparments_historical_stats.day')
    //last x days
    ->whereRaw('deparments_historical_stats.day > NOW() - INTERVAL ' . $days . ' DAY')
    ->whereRaw('deparments_historical_stats.day < NOW() - INTERVAL 1 DAY')
    ->get();
            
/* @var \ConsoleTVs\Charts\Builder\Chart | \ConsoleTVs\Charts\Builder\Multi $chart */
$chart = Charts::multi($type, $provider);
$chart
    // Setup the chart settings
    ->title($title)
    // A dimension of 0 means it will take 100% of the space
    ->dimensions($width, $height)// Width x Height
    // template define inside charts config file
            ->template($template)
;

//prepare empty array with 0 counts for date range specified
$range = $this->generateDatesAndZeroCountsArray(
    Carbon::now()->subDays($days),
    Carbon::now()->subDay()
);

$chartDataSet = [];
foreach ($dataSet as $data) {
    $name = $data->name;
    if (!array_key_exists($name, $chartDataSet)) {
        $chartDataSet[$name] = $range;
    }
    $day = $data->day;
    $chartDataSet[$name][$day] = $data->$dataCountName;
}

//add data to chart
foreach ($chartDataSet as $key => $data) {
    $chart->dataset($key, $data);
}

//add labels to chart
$chart->labels(array_keys($range));

return $chart;
`

**Comment by ConsoleTVs** [comment]
Hi, eloquent ORM makes life easy haha, have you tried using my database method? Charts::database

**Comment by tad3j** [comment]
I've just started using your package and it's quire awesome, good job. ...so I didn't have time yet to try it out. Will test it. :)

**Comment by ConsoleTVs** [comment]
Sure, try it and tell me its well documented in my site

**Comment by tad3j** [comment]
For eloquent vs. DB: I guess I could only change **DB::table('deparments_historical_stats')->...** to **DeparmentsHistoricalStat()->...** but feel kind of strange because I'm aggregating.

Yep, I've noticed docs are quite extensive. ...will take at least a day to take all in. :)

**Comment by ConsoleTVs** [comment]
You should take a closer look at how an ORM works, because it takes the hard work into simple artisan magic. No more sql, ever.

**Comment by tad3j** [comment]
I'm kind of familiar, used Doctrine before Eloquent. But yeah, will need to look deeper into Eloquent.. :) I should start with finding Eloquent way for rawSelect first.

Thanks for the heads up! 👍

**Comment by vijaykryadav** [comment]
Hi,
I am not able to export highchart as pdf Offline. Can you please share code if you have.?
thanks
