### ISSUE TITLE
Can't show more than 1 chat in one blade [BUG]

### ISSUE THREAD

**Issue by moayad-tarig** [ConsoleTVs/Charts#15]
**Required information**
 - Charts Version [e.g. 6]
 - Laravel Version [e.g. 5.8]
 - PHP Version [e.g. 7.2]
 - Frontend JS Library Used:  [e.g. Chart.js]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Code To Reproduce**
If applicable, add a code to reproduce the problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tabacitu** [comment]
Hey @moayad-tarig , in my tests this works. You can show multiple charts in one blade file. You can see a working version of that here - https://demo.backpackforlaravel.com/admin/dashboard

If you're still encountering this issue, and you think it's a bug in the software, not something you've done, please feel free to re-open the issue. But next time, please fill in all the required information. Without that information, nobody can help.

Cheers!
