### ISSUE TITLE
error install 5.0

### ISSUE THREAD

**Issue by dodacvan** [ConsoleTVs/Charts#150]
![image](https://cloud.githubusercontent.com/assets/12047875/23331768/33b0a246-fb9f-11e6-89b5-a01f98ecc8a4.png)

**Comment by ConsoleTVs** [comment]
Laravel version ?

**Comment by dodacvan** [comment]
thanks for your reply . I just install chart version 2 instead version 4 and it work well. because i use laravel version 5.0 . it is too old.

**Comment by ConsoleTVs** [comment]
Perfect!
