### ISSUE TITLE
DrillDown functionality

### ISSUE THREAD

**Issue by minedun6** [ConsoleTVs/Charts#151]
@ConsoleTVs Is there anyway that the drilldown functionality can find its way to this package ? 
I've actually checked that most chart library on this package have something like this except for the "Chart.js" library.

**Comment by ConsoleTVs** [comment]
What is this functionality ?

**Comment by minedun6** [comment]
[Column DrillDown - HighCharts](http://www.highcharts.com/demo/column-drilldown)

Try clicking on each bar and you'll see some magic.

**Comment by ConsoleTVs** [comment]
it's something out of control for this package, i dont think it's worth my time, but if anyone wants to build it and submit a PR will be cool :)
