### ISSUE TITLE
dateFormat not working for multiDatabase chart

### ISSUE THREAD

**Issue by TUNER88** [ConsoleTVs/Charts#155]
Code for reproducing:

```php
$chart = Charts::multiDatabase('bar', 'chartjs')
            ->dataset('Users', \App\User::all())
            ->lastByDay(5, true)
            ->dateFormat('d.m.y');
```
![dateFormat_bug](https://cloud.githubusercontent.com/assets/1565397/23563434/f6ec59de-0046-11e7-9957-ece8a03d3822.png)

**Comment by whitis01** [comment]
Looks like an order of operations issue.

$chart = Charts::multiDatabase('bar', 'chartjs')
            ->dataset('Users', \App\User::all())
            ->dateFormat('d.m.y') // Set date format before sorting chart.
            ->lastByDay(5, true); // This groups the values and sets the labels with current date format.

The lastByDay takes the dataset and builds up the values and associated labels within the model.

**Comment by ConsoleTVs** [comment]
@whitis01 got that one right ^^ the databse functions build the data, so they must be called last.

**Comment by TUNER88** [comment]
@whitis01 same result with your code snippet, date format is still incorrect

**Comment by ConsoleTVs** [comment]
Just noticed the protential error, looking forward a fix.

**Comment by ConsoleTVs** [comment]
Just released a fix, try it out:

```
$chart = Charts::multiDatabase('bar', 'chartjs')
            ->dateFormat('d.m.y')
            ->dataset('Users', \App\User::all())
            ->lastByDay(5, true);
```

**Comment by TUNER88** [comment]
@ConsoleTVs Thx for Your fast response!!!

I've still same behaviour on **4.4**, still no custom data format for _multiDatabase_ charts.

Here is my code:

```php
$database = Charts::database(\App\User::all(), 'bar', 'chartjs')
    ->dateFormat('d.m.y')
    ->lastByDay(5, true);

$multiDatabaset = Charts::multiDatabase('bar', 'chartjs')
    ->dateFormat('d.m.y')
    ->dataset('Users', \App\User::all())
    ->lastByDay(5, true);
```

![kampagnen_cockpit_-_titles_show_campaign_questions](https://cloud.githubusercontent.com/assets/1565397/23613294/23b6fc50-027f-11e7-8959-0d3e7f94f596.png)

**Comment by ConsoleTVs** [comment]
Will check in later, im sorry for this issue!

**Comment by TUNER88** [comment]
@ConsoleTVs thx, I'm looking forward for the fix.
Btw: thanks for your awesome package ;)

**Comment by ConsoleTVs** [comment]
@whitis01 released a fix, try it out :)

**Comment by TUNER88** [comment]
@ConsoleTVs thx for the fix, works like a charm if I move `dateFormat()` below `dataset()`, like:
```php
$multiDatabaset = Charts::multiDatabase('bar', 'chartjs')
    ->dataset('Users', \App\User::all())
    ->dateFormat('d.m.y')
    ->lastByDay(5, true);
```

But your fix seems to affecting preaggregated charts, following code does not work anymore:

```php
$data = \App\User::select('users.created_at', DB::raw('count(users.id) as aggregate'))->groupBy(DB::raw('Date(users.created_at)'))->get();
$chart = Charts::database($data)->preaggregated(true)->lastByDay(7, false);
```

Any ideas?

![https___kampagnen-cockpit_dev_campaigns_2](https://cloud.githubusercontent.com/assets/1565397/23625558/e3b545e6-02a9-11e7-98af-0a727b063442.png)

**Comment by TUNER88** [comment]
@whitis01 thx for #159, seems to solve the aggregate issue!
