### ISSUE TITLE
dateColumn() not working in multiDatabase

### ISSUE THREAD

**Issue by wilmarcarinan** [ConsoleTVs/Charts#160]
Hello! I have this issue of not having dateColumn work in my graph. I tried changing the default column `created_at` in the source code with my `date_column` but unfortunately, it didn't work too. I have created_at column in my table but i don't want to get the date from that column. Here is my screenshot! Thanks

![image](https://cloud.githubusercontent.com/assets/14357042/23647825/d6aae10e-0352-11e7-94db-fea9961b3a5a.png)

**Comment by ConsoleTVs** [comment]
Chart's version?

**Comment by wilmarcarinan** [comment]
Just updated to the latest one, still the issue persist.

**Comment by ConsoleTVs** [comment]
Try https://github.com/ConsoleTVs/Charts/releases/tag/4.4.3

**Comment by wilmarcarinan** [comment]
It worked now. Thank you very much.  👍

**Comment by ConsoleTVs** [comment]
You're welcome!
