### ISSUE TITLE
Suggestion: Adding $options parameter to Multi->dataset() method

### ISSUE THREAD

**Issue by fsasvari** [ConsoleTVs/Charts#161]
It would be nice to add $options parameter to Multi.php (https://github.com/ConsoleTVs/Charts/blob/master/src/Builder/Multi.php), dataset() method:

```
    /**
     * Set the dataset values.
     *
     * @param string $element_label
     * @param array  $values
     * @param array  $options
     *
     * @return Multi
     */
    public function dataset($element_label, $values, array $options = [])
    {
        $this->datasets[] = [
            'label' => $element_label,
            'values' => $values,
            'options' => $options,
        ];

        return $this;
    }
```

I have many custom fields in my ChartJS view - yAxis, xAxis, yLabel, position, type etc... I would appreciate if you can add $options parameter, so I can add all my custom params to $options array and pull them in my view.

**Comment by ConsoleTVs** [comment]
It got sense, will probably add it to the main charts function so it will be available for all chart types. Will keep it up.

**Comment by fsasvari** [comment]
Yes, it would be nice to have some global option, but also some special $options for datasets. Every dataset could have it's own options (configs). Thank you very much and keep up the good work !

**Comment by ConsoleTVs** [comment]
Every dataset is an instace of a database chart, and a database chart is an instance of a chart. If i add options for charts, it will be available for datasets as well ^^

**Comment by ConsoleTVs** [comment]
Sorry, in the end I won't add this feature, please send a pull request if you're willing to.
