### ISSUE TITLE
Uncaught SyntaxError: Unexpected token { - wrong symbol in blade class

### ISSUE THREAD

**Issue by mdanro** [ConsoleTVs/Charts#162]
Hello, 
I tried to use realtime line charts but it seems that there are issues in the line.blade.php, also i think the same happens to area.blade and so on
**\vendor\consoletvs\charts\resources\views\highcharts\realtime\line.blade.php**

`            @if($model->colors) {
                plotOptions: {
                    series: {
                        color: "{{ $model->colors[0] }}"
                    }
                ,`
should be:

`            @if($model->colors) 
                plotOptions: {
                    series: {
                        color: "{{ $model->colors[0] }}"
                    }
                },`

Also in 
**\vendor\consoletvs\charts\resources\views\highcharts\realtime\area.blade.php**
` @if($model->colors) {
                plotOptions: {
                    series: {
                        color: "{{ $model->colors[0] }}"
                    }
                }`
should be changed to 
`            @if($model->colors) 
                plotOptions: {
                    series: {
                        color: "{{ $model->colors[0] }}"
                    }
                },`

**Comment by ConsoleTVs** [comment]
Will in fact take a look at it and update it! Thanks!

**Comment by ConsoleTVs** [comment]
Should be fixed here: https://github.com/ConsoleTVs/Charts/releases/tag/4.4.4

Please close the issue if fixed! Thanks!

**Comment by ConsoleTVs** [comment]
Confirmed it fixes the problem! Thanks for spotting this problem!
