### ISSUE TITLE
A chart with values instead of labels in abscissa

### ISSUE THREAD

**Issue by Francesco-1277** [ConsoleTVs/Charts#163]
Hi,

in this moment Charts allows me to create charts like this

`
      $chart = Charts::create('line', 'highcharts')
      ->title('Quantita / Sconti')
      ->elementLabel('Quantita / Sconti')
      ->labels($quantita)
      ->values($sconto)
      ->dimensions(1000,500)
      ->responsive(false);
`

![no](https://cloud.githubusercontent.com/assets/26165575/23709588/3f456258-041a-11e7-8866-dd5ab19d6f82.jpg)

in `labels('$quantita')` the values of `$quantita` are equally spaced, but I want to see real coordinates like in `values($sconto)` to obtain a chart like the one below. I'm wondering if it's possible to achieve the result

![yes](https://cloud.githubusercontent.com/assets/26165575/23709587/3edd1fe0-041a-11e7-87b8-d91e108929c4.jpg)

**Comment by ConsoleTVs** [comment]
It is indeed posible, but not with charts. With specific charts like this you'll need to find the JS library that suits you and build it manually, I'm sorry!
