### ISSUE TITLE
Realtime Highcharts line and area not working? (v4) (bar is working)

### ISSUE THREAD

**Issue by bahjaat** [ConsoleTVs/Charts#164]
Can someone confirm that this code is (not) working in v4? By 'working' I mean: there is chart on the screen, not even if it updates or not. I got a blank (white) area with the height and width I specified.

```php
$chart = Charts::realtime(url('/charts'), 1000, 'line', 'highcharts')
            ->responsive(false)
            ->title('Summary')
            ->height(400)
            ->width(600)
        ;
return view('test', compact('chart'));
```

and in my view:

```php
{!! $chart->render() !!}
```

ps: this library is awesome!

**Comment by bahjaat** [comment]
oops. Just saw this one: https://github.com/ConsoleTVs/Charts/issues/162

I thinks it has to do something with it.

**Comment by ConsoleTVs** [comment]
It does indeed, will oviously fix it now, I'm really sorry for this issue!

**Comment by ConsoleTVs** [comment]
Fixed here: https://github.com/ConsoleTVs/Charts/releases/tag/4.4.4

**Comment by bahjaat** [comment]
Thank you for the fast response and fix. Both are working again.
Keep up the good work!

**Comment by ConsoleTVs** [comment]
Thanks @bahjaat !
