### ISSUE TITLE
php artisan error [ErrorException]   when 'use Charts ', Class                                               

### ISSUE THREAD

**Issue by mjames21** [ConsoleTVs/Charts#166]
my charts work well ,but when i do artisan command I get this error 
'[ErrorException]                                                 
  The use statement with non-compound name 'Charts' has no effect'
this one works , use ConsoleTVs\Charts\Charts;

**Comment by mjames21** [comment]
maybe this will help in the documentation

**Comment by ConsoleTVs** [comment]
Hello, this is false, this is the facade: ConsoleTVs\Charts\Facades\Charts

And the docs tell you to add an alias:

```
Add the following alias to the array in: config/app.php

'Charts' => ConsoleTVs\Charts\Facades\Charts::class,
```

**Comment by mjames21** [comment]
yes I did that before
maybe my artisan was break
never mind
