### ISSUE TITLE
showing dataLable in highcharts

### ISSUE THREAD

**Issue by ommyan** [ConsoleTVs/Charts#167]
I tried to add the option dataLabel on Highcharts by adding the following code. 
I added the bar.blade.php file in the folder \ vendor \ consoletvs \ charts \ resources \ views \ Highcharts.
but has not managed, can you make this possible?

` plotOptions: {
               column: {
                   pointPadding: 0.2,
                   borderWidth: 0
               },
               bar: {
                    dataLabels: {
                    enabled: true
                  }
                 }
           },`

[http://www.highcharts.com/demo/bar-basic](url)

if we look at this chart each bar show the number, how do this?
thanks

**Comment by ommyan** [comment]
i have sucessed to display dataLable , just add :

` plotOptions: {
               column: {
                   pointPadding: 0.2,
                   borderWidth: 0
               },
               column: {
                    dataLabels: {
                    enabled: true
                  }
                 }
           },
`

**Comment by ConsoleTVs** [comment]
Hello this is the elementLabel. If you're using a multichart, it's the first argument passed into the dataset function and the same for multiDatabase.

**Comment by ommyan** [comment]
noted Erik,

thanks you verry much, itsworkfine
