### ISSUE TITLE
Mixed realtime chart data

### ISSUE THREAD

**Issue by mdanro** [ConsoleTVs/Charts#168]
Hello guys,
I really appreciate your work and i try to bring my contribution whenever i get the chance.

However i am a little stuck
I use your chart implementation of real-time charts but i want a particular behavior. My charts gets updated every 1 minute or so, so i want to load at start a standard line/bar data with previous data (20-100 samples) and after that if the interface is open i want to get updated with the latest temperature readings from the database. So basically it is a standard bar chart with real-time component or so... I just do not want to load empty data at start and wait for the temperature readings to populate.

How can i get this behavior, is there an out of the box solution or maybe even an outside-the-box workaround to get this

Thanks
Dan

**Comment by ConsoleTVs** [comment]
As far as I remember, i writted the realtime charts to add stuff into the values, so have you tried using ->values to setup the startup values? (should be less or equal to maxValues prop. (defaults to 20).

**Comment by mdanro** [comment]
Thank you for the suggestion, i will try that. However that does not help me outputting the same data over and over. For example, if the last reading of temperature is 7 degrees even if i have no more readings, it will output continuously the same 7 degrees and the chart data will keep on moving, i was interested in stopping the chart from refreshing if the value returned hadn't changed (in this case the pair of temperature and date).- something like if the data set is unchanged do not refresh, or maybe better refresh on demand...

I hope you can give me a suggestion i do not know if this was clear....

**Comment by ConsoleTVs** [comment]
Hi, this features is yet out of control from this library and it's not the goal of it. I undestand you need specific features but those can only be done manually at the moment, i can't add specific features as it would be a waste of time. Controlling +90 charts with 1 features is already too complicated to add small features like this. I'm afraid the best solution is to build it manually ^^

**Comment by mdanro** [comment]
Thank you for your consideration and your time, i understand the effort and i appreciate the fact that this product in maintained.

**Comment by ConsoleTVs** [comment]
Sure, I'm really sorry tho for any problems or features you might expect, it's the only library you'll find out there that support that many charts and libraries with the same code...
