### ISSUE TITLE
More Settings are needed

### ISSUE THREAD

**Issue by minedun6** [ConsoleTVs/Charts#17]
Is there any way u can add some custom settings/methods through the api so that we can for example set Exporting option (true or false) and any other settings that the plugin/api expose.
And is it possible to make it through Ajax so that we can change parameters of the chart on the fly without reloading the page ?

Cheers.

**Comment by ConsoleTVs** [comment]
Hi! The first thing, more settings is something I'll try to do in a future but it's complicated to handle with multiple libraries, will see what can i do. What do you mean, by changing them in the fly? why would that be usefull?

**Comment by minedun6** [comment]
I'm generating reports on my page, but i need to add filters to so that the user can change the type of chart he gets, the period of the report as well ^^
this is a feature that the client asked for.

**Comment by ConsoleTVs** [comment]
Range features will indeed be available in the following releases!

**Comment by minedun6** [comment]
could you explain it more, the range feature ?

**Comment by ConsoleTVs** [comment]
It's not done yet but will let you define 2 days and display data between thoose 2 days

**Comment by minedun6** [comment]
I think I know the feature you're refering to but I was asking if it's possible to generate differents type of reports using let's say ajax, an example, I have an invoice report (Total Invoice) but I want to check the report about Total Invoices Payed, so it will change the chart it generates but I need it to be through ajax without the need to reload the page.

**Comment by ConsoleTVs** [comment]
In this case, you'll need the "Realtime Charts"

Realtime charts currently only support few charts, will try to update them into basic charts soon! check the readme.md and look into realtime charts. The available list in in the libraries / types available

**Comment by minedun6** [comment]
Yep, already checked it out, currently limited to gauge and temperatures charts.
That and here's a site that I'm using as reference for what I want to do.
Go ahead and create an account on this site [invoicely.com](Invoicely) then go to the dashboard and check the chart widget. It

**Comment by ConsoleTVs** [comment]
I'll try to make as many things as posible but it's hard since all libraries work in diferent ways

**Comment by ConsoleTVs** [comment]
@minedun6 I've added 3 new realtime charts for the highcharts library, check them out, they might be what you were looking for!
