### ISSUE TITLE
Question about Dataset

### ISSUE THREAD

**Issue by wilmarcarinan** [ConsoleTVs/Charts#171]
Hi! I have an Adviser table in my database and I want to display all of the advisers. I can do that if the advisers mentioned are fixed, however it is not. So basically if I have 10 advisers in my Adviser table, I want to display it with their corresponding value. Thanks :)

**Comment by ConsoleTVs** [comment]
I don't understand this issue

**Comment by wilmarcarinan** [comment]
Sorry if you don't understand. I'll give some example: Here in this picture I have three datasets that are fixed which are BSIT, BSIS, and BSCS. 
![image](https://cloud.githubusercontent.com/assets/14357042/24174346/20df23f6-0ecb-11e7-9a51-66cb31f03480.png)

What I want to do is to make a graph which has many datasets. So for example, I have 5 unique names in my table, there will also be 5 datasets in my graph. 
![image](https://cloud.githubusercontent.com/assets/14357042/24174568/3d7939f6-0ecc-11e7-9529-9855424b3c7d.png)
In this picture, you can see that I have declared three fixed datasets. But what I want is check my Advisers table in my database, get all the unique names, loop through it and display it in my graph as dataset. So basically, what I want is lie this:
![image](https://cloud.githubusercontent.com/assets/14357042/24175055/1798bc54-0ecf-11e7-8f16-99d05dec5d73.png)

Thank you! I hope you understand my issue. Cheers!
