### ISSUE TITLE
Fixed Datasets Issue

### ISSUE THREAD

**Issue by wilmarcarinan** [ConsoleTVs/Charts#172]
Same issue in #171 .

I open a new issue because I cannot reopen it. 
Here in this picture I have three datasets that are fixed which are BSIT, BSIS, and BSCS. 
![image](https://cloud.githubusercontent.com/assets/14357042/24174346/20df23f6-0ecb-11e7-9a51-66cb31f03480.png)

What I want to do is to make a graph which has many datasets. So for example, I have 5 unique names in my table, there will also be 5 datasets in my graph. 
![image](https://cloud.githubusercontent.com/assets/14357042/24174568/3d7939f6-0ecc-11e7-9529-9855424b3c7d.png)
In this picture, you can see that I have declared three fixed datasets. But what I want is check my Advisers table in my database, get all the unique names, loop through it and display it in my graph as dataset. So basically, what I want is like this:
![image](https://cloud.githubusercontent.com/assets/14357042/24175055/1798bc54-0ecf-11e7-8f16-99d05dec5d73.png)

But is resulted in error saying unexpected foreach. Is there an alternative way?

Thank you! I hope you understand my issue. Cheers!

**Comment by ConsoleTVs** [comment]
```php
$chart_adviser_year = Charts::multiDatabase('bar', 'highcharts')
    ->dateColumn('thesis_date')
    ->title('Thesis Per Adviser Per Year')
    ->elementLabel('Total Files')
    ->dimensions(0, 500) // You should always use 0 as width for a responsive chart
    ->colors(['rgb(46,112,160)', 'rgb(192,65,62)', 'orange']);
foreach($advisers as $adviser){
    $chart_adviser_year->dataset($adviser->adviser, $adviser);
}
$chart_adviser_year->lastByYear();
```

**Comment by wilmarcarinan** [comment]
Thank you very much! It worked. Sorry for all the trouble :)

**Comment by ConsoleTVs** [comment]
You're welcome ^^
