### ISSUE TITLE
Database Charts

### ISSUE THREAD

**Issue by suraeyabd** [ConsoleTVs/Charts#173]
Hello,

please help me. how can i use "database chart" for student attendance report? as like everyday "present" and "absent" store in database. now how can i show this in report. As like "multi" chart. But, I can't understand how can i display dynamic value in "multi" chart.

**Comment by ConsoleTVs** [comment]
```
Charts::multiDatabase('line', 'material')
    ->title("My chart")
    ->dataset('Element 1', Students::where('present', true)->get())
    ->dataset('Element 2', Students::where('present', false)->get())
    ->lastByDay(7, true);
```

Like this?

**Comment by suraeyabd** [comment]
Thanks for your answer. Please look at this in below - here my code

$present = Attendance::where('present',1)->get();
        $absent = Attendance::where('absent',1)->get();

$chart = Charts::database($present, 'bar', 'highcharts')
                //->setElementLabel("Total")
                ->title("Total")
            //->element_label("Report")
                ->dimensions(1000, 500)
                // ->setResponsive(false)
                ->groupByDay('03', '2017', true);


N.B.  I can put "present" as parameter, but, can't put "absent" as parameter. Please help me about this. I mean, I want to show 2 bar. 1 for present and other for absent.

**Comment by ConsoleTVs** [comment]
I already writted the code for you.

```
Charts::multiDatabase('bar', 'highcharts')
    ->title("My chart")
    ->dataset('Present', Attendance::where('present',1)->get())
    ->dataset('Absent', Attendance::where('absent',1)->get())
    ->groupByDay('03', '2017', true);
```

**Comment by krazaa** [comment]
hello. How can add multiple charts with multiple data form datablse  in single page

**Comment by krazaa** [comment]
hello. How can add multiple charts with multiple data form database in single page

**Comment by ConsoleTVs** [comment]
@krazaa That's explained in the official docs. it's called multiDatabase
