### ISSUE TITLE
Add Stacked Bar 

### ISSUE THREAD

**Issue by DigitalCoder** [ConsoleTVs/Charts#174]
Hi all !

I've added stacked bar evolution in my project.
This could be interesting for the next release ?

in vendor/consoletvs/charts/src/Builder/Chart.php

after `public $responsive;`
adding : `public $stacked;`

and behind after decalration of `public function responsive($responsive)`
```
    /**
     * Set if chart is stacked (will ignore dimensions if true).
     *
     * @param bool $stacked
     *
     * @return Chart
     */
    public function stacked($stacked)
    {
        $this->stacked = $stacked;

        return $this;
    }
```

then in vendor/consoletvs/charts/resources/views/chartjs/multi/bar.blade.php
and I've changed in options :
```
        options: {
            responsive: {{ $model->responsive || !$model->width ? 'true' : 'false' }},
            maintainAspectRatio: false,
            @if($model->title)
            title: {
                display: true,
                text: "{!! $model->title !!}",
                fontSize: 20,
            },
            @endif
            scales: {
                yAxes: [{
                    display: true,
                    ticks: {
                        beginAtZero: true,
                    },
                    @if($model->stacked)
                    stacked: true
                    @endif
                }],
                @if($model->stacked)
                xAxes: [{
                    stacked: true
                }]
                @endif
            }
        }
```

After you just have to use it with `->stacked(true)` for my example 
$myChart = Charts::multiDatabase('bar', 'chartjs')->stacked(true) ...

It's up to you to play ^^

**Comment by ConsoleTVs** [comment]
stacked should be another chart type, imo, so what about you making a PR, seems you got most job done, you'll be listed as a contributor, what do you think ?

**Comment by DigitalCoder** [comment]
Hello,

Ok I'll do it as soon as possible.

Thanks for the proposal: D

**Comment by ConsoleTVs** [comment]
Perfect, will be waiting! :D

**Comment by mailnike** [comment]
Great. Waiting for the update guys.
