### ISSUE TITLE
Add Color Pattern for Pie using c3.js

### ISSUE THREAD

**Issue by DigitalCoder** [ConsoleTVs/Charts#175]
Hi all !

I've added color pattern evolution in my project, because I don't like c3.js colors
This could be interesting for the next release ?

in vendor/consoletvs/charts/src/Builder/Chart.php
before the decalration of `public function view($view)`

add :
```
   /**
     * Set chart pattern colors.
     *
     * @param array $colors
     *
     * @return Chart
     */
    public function color_pattern($colors)
    {
        $this->color_pattern = $colors;

        return $this;
    }
```

and in `vendor/consoletvs/charts/resources/views/c3/pie.blade.php` after `$model->title` existing condition
add :
```
    @if($model->color_pattern)
    color: {
        pattern: [
            @for($i = 0; $i < count($model->color_pattern); $i++)
                    "{{ $model->color_pattern[$i] }}",
            @endfor
        ]
    }
    @endif
```

After you just have to use it with for my example
$myChart = Charts::create('pie', 'c3')->color_pattern(['#8BC34A', '#FFC107', '#F44336']) ...

It's up to you to play ^^

**Comment by ConsoleTVs** [comment]
Doesn't this do the same as setting diferent chart colors? or using a color template?
