### ISSUE TITLE
lastByMonth() creates double entry for March

### ISSUE THREAD

**Issue by DanSorahan** [ConsoleTVs/Charts#176]
Appears to be related to month length, as only occurs on March 29th onwards.

![https://i.imgur.com/vQLPiJc.png](https://i.imgur.com/vQLPiJc.png)

Controller:
```
$data = \App\Models\Transaction::where(['paid' => 1])->get();
return view("charts.$name", ['height' => $height, 'data' => $data]);
```

View:
```
{!!
Charts::database($data, 'line', 'chartjs')
    ->dimensions(0,$height)
    ->aggregateColumn('amount', 'sum')
    ->lastByMonth(24, true)
    ->template('material')
    ->render()
!!}
```

**Comment by DanSorahan** [comment]
Tested with Highcharts, Google, Morris and Chartist and replicated on all four.

Will have to clean user data out of query result to get it over to you, however, no data exists before March 15th.

**Comment by whitis01** [comment]
Hmm... this is a good catch. It looks like the powers that be decided that when using strtotime(). 

Code ::
<?php

echo 'Current :' . date('d-m-Y').PHP_EOL;
echo '-0 Month :' . date('d-m-Y', strtotime("-0 Month")).PHP_EOL;
echo '-1 Month :' . date('d-m-Y', strtotime("-1 Month")).PHP_EOL;
echo '-2 Month :' . date('d-m-Y', strtotime("-2 Month")).PHP_EOL;
echo 'Last Month :' . date('d-m-Y', strtotime("Last Month")).PHP_EOL;

Out ::
Current :29-03-2017
-0 Month :29-03-2017
-1 Month :01-03-2017
-2 Month :29-01-2017
Last Month :01-03-2017

I'm taking a look into solutions that don't introduce other edge cases. This should work in a couple of days, however it still needs fixing.

**Comment by whitis01** [comment]
@DanSorahan a change has been submitted and merged. My testing was done on the strtotime() function itself, but hopefully this solves your double label issue. If you could, please update and report if it solves your issue.

**Comment by DanSorahan** [comment]
Sorry for the delay in getting back to you, all seems to be resolved now!

**Comment by ConsoleTVs** [comment]
Indeed, you're welcome!
