### ISSUE TITLE
Integer Only Scales

### ISSUE THREAD

**Issue by Samyoul** [ConsoleTVs/Charts#179]
Currently is there an integer only scale setting? I would like to show an integer only scale but currently the scale will show float values. Please see an example below:

![](https://i.gyazo.com/30183fa75f6bee6848898c4dbe487491.png)

**Comment by ConsoleTVs** [comment]
Hello, this in fact it's a setting not yet implemented. That means it will scale acording the the default values of the chart library. In fact, the values will always be (in most cases) integers, but some chart libraries tend to add higher axis to display a fancy output. However, this feature may be supported in soem libraries but in some others it might not be posible to set a scale. My suggestion for you is to use another library if possible or create a custom chart view.

**Comment by Samyoul** [comment]
Ok, thank you.
