### ISSUE TITLE
Changing Highcharts Options with Charts

### ISSUE THREAD

**Issue by alekbless** [ConsoleTVs/Charts#180]
Hello,

I have an Highchart graph with labels as JS timestamp. To get Highcharts to render this as DateTime I need to specify this type for the xAxis:
```
xAxis: {
    type: 'datetime'
}
```

In the documentation under Available Chart Settings we can set title, colors etc. But is it possible to change other specific options for graphs as well? 

For reference: http://api.highcharts.com/highcharts/xAxis.type

**Comment by alekbless** [comment]
Sorry, I can change this in resources/views/highcharts of course. Thank you for this wonderful package!

**Comment by ConsoleTVs** [comment]
Yes you can always create a view for the chart! :D but remember this is a multi-chart package, options available in one library may not be available in another!
