### ISSUE TITLE
Drilldown coming soon ?

### ISSUE THREAD

**Issue by minedun6** [ConsoleTVs/Charts#181]
I recently saw the pull request about "adding drilldown functionality" to the package,
so is there anyway we can get to see how it works ?

A second point, for the preaggregated function, can you possibly make an example on how to use it ? maybe in a complexe example ?

**Comment by ConsoleTVs** [comment]
I am not sure about anything you told me, either of this functions were made by me and in fact i have few idea how to make it...

**Comment by minedun6** [comment]
#156 this should refresh your memory no ?

**Comment by ConsoleTVs** [comment]
"repare for drill down functionality" I have no idea what this means or what he was expecting to do.
