### ISSUE TITLE
Google Chart library - multiple charts on one page

### ISSUE THREAD

**Issue by winers1290** [ConsoleTVs/Charts#185]
I'm unable to use this library to create multiple charts on the same page.

Under a foreach loop, I use the following test code: 

```
            $array[] = Charts::multi('bar', 'material')
              //chart settings
              ->title('my chart')
              // A dimension of 0 means it will take 100% of the space
              ->dimensions(0, 400) // Width x Height
              // This defines a preset of colors already done:)
              ->template("material")
              ->dataset('Element 1', [5,20,100])
              ->dataset('Element 2', [15,30,80])
              ->dataset('Element 3', [25,10,40])
              // Setup what the values mean
              ->labels(['One', 'Two', 'Three']);
```

When I call the render function on the view, only the first graph is rendered. Any ideas?

**Comment by winers1290** [comment]
Sorry, not an issue with your project. Error in my templates.

**Comment by ConsoleTVs** [comment]
No problem :)

**Comment by mwakaambrose** [comment]
@winers1290 I kind of have the same problem. Attempting to render charts from a loop. Only the first one shows. How did you fix your problem?

**Comment by ConsoleTVs** [comment]
What version of charts are you using?

**Comment by mwakaambrose** [comment]
@ConsoleTVs v5.4.0

**Comment by ConsoleTVs** [comment]
Im sorry but lost control over 5.X version. Please upgrade...

**Comment by mwakaambrose** [comment]
Ok, thanks anyway.

**Comment by mwakaambrose** [comment]
@ConsoleTVs Turns out I needed to loop and render the scripts also. I was assuming that a single`{!! $charts[0]->script() !!}` was enough since they were all charts of the same type. But had to do this to render all charts instead of just one `{!! $charts[$key]->script() !!}`.

**Comment by ConsoleTVs** [comment]
No, every container (html) needs it's script, it's where they load the data from...

**Comment by mwakaambrose** [comment]
Yea, that what I missed. Took me some digging into the vendor folder though. Thanks.
