### ISSUE TITLE
How to push my array value to setValue in Chart?

### ISSUE THREAD

**Issue by aiduc0502** [ConsoleTVs/Charts#186]
What wrong when I push array to setValues and how to fix it? Thanks!

Bug:Array to string conversion (View: C:\xampp\htdocs\demo\resources\views\admin\dashboard.blade.php)

```
public function index(){
        $arrayName = array([100,262,3040,4610,5550,600,811,929,142,109,682,217]);

        $chart=Charts::create('line','highcharts')
        ->setTitle("Total revenue by month")
        ->setLabels(['1','2','4','4','5','6','7','8','9','10','11','12'])
        ->setValues($arrayName)
        ->setElementLabel('Total');
        return view('admin.dashboard',['chart'=>$chart]);
    }
```
It run when hardcode

 `->setValues(100,262,3040,4610,5550,600,811,929,142,109,682,217)`
Blade:

```
<div class="panel panel-default">
        <div class="panel-header">Dashboard</div>
        <div class="panel-body">
            <strong>Admin</strong>
            <div class="form-group ">
                {!!$chart->render()!!}
            </div>
        </div>
    </div>
```

**Comment by imabug** [comment]
leave out the [] in your $arrayName. When using array(), you don't need them

**Comment by ConsoleTVs** [comment]
- leave out the [] in your $arrayName. When using array(), you don't need them
- These functions do not exist, they were renamed without the "set" please check the docs...
