### ISSUE TITLE
How to use double in dataset Charts::multi('line', 'c3') ?

### ISSUE THREAD

**Issue by ismaelaraujo** [ConsoleTVs/Charts#187]
Hi good morning,
I'm trying to use in the double value data set and it's rounding the value from 58.10 to 58.1 how can I solve it?
$result = Charts :: multi ('line', 'c3')
        -> title (null)
        -> responsive (true)
        -> dataset ('AERO 1', [58.03, 58.10, 52.33, 38.31, 54.77, 61.61, 75.78, 70.94, 57.97, 76.27, 30.66, 39.95, 4.46, 42.39, 40.71, 52.83, 20.30, 16.91, 57.89, 57.57, 41.72, 5.31, 48.51, 61.76, 20.89, 75.74, 52.78, 53.75, 33.24, 3.33, 6.53])
        -> template ("material")
        -> labels (['Day 1', 'Day 2', 'Day 3', 'Day 4', 'Day 5', 'Day 6', 'Day 7', 'Day 8' 'Day 10', 'Day 11', 'Day 12', 'Day 13', 'Day 14', 'Day 15', 'Day 16', 'Day 17', 'Day 18', 'Day 19' 'Day 20', 'Day 21', 'Day 22', 'Day 23', 'Day 24', 'Day 25', 'Day 26', 'Day 27', 'Day 28', 'Day 29' 'Day 30', 'Day 31'])
        -> elementLabel ("Total");

**Comment by ConsoleTVs** [comment]
Hello, math works like this, a zero in the right its useless...

**Comment by ismaelaraujo** [comment]
Thanks, I really wanted to get better visualization because in fact the values ​​are percentages that I wanted to display in the graphic
->dataset('AERO 1', ['58.03', 58.10, 52.43, 38.31, 54.77, 61.61, 75.78, 70.94, 57.97, 76.27, 30.66, 39.95, 4.46, 42.39, 40.71, 52.83, 20.30, 16.91, 57.89, 57.57, 41.72, 5.31, 48.51, 61.76, 20.89, 75.74, 52.78, 53.75, 33.24, 3.33, 6.53])

![x1](https://cloud.githubusercontent.com/assets/14362611/25714394/38714574-30ce-11e7-89b9-34fa7cb8e4f2.jpg)

Wanted to display 58.03%

**Comment by ConsoleTVs** [comment]
I dont rememver if we allow custom sufixes atm, so the "%" may not be diplayed... I'm sorry

**Comment by ismaelaraujo** [comment]
Thank you, if you can help me, thank you.

**Comment by ismaelaraujo** [comment]
Good Afternoon, I wanted to know what to put in \resource\views\c3 \multi\ line.blade.php
This code snippet:

....},
    tooltip: {
        format: {
            value: function (value, ratio, id) {
                return '{{ $model->tooltipValuePre }}' + value + '{{ $model->tooltipValuePos }}';
            }
        }
    },
...

and adjust the \vendor\consoletvs\charts\src\Builder\Chart.php

public function tooltipValuePre($value)
{
        $this->tooltipValuePre = $value;
        return $this;
 }

public function tooltipValuePos($value)
{
        $this->tooltipValuePos = $value;
        return $this;
}


This function will tooltipValuePre($value) and tooltipValuePos($value) help to use% or $ and so on before the word would be the pre and post then obviously, I await your response thanks.

**Comment by ConsoleTVs** [comment]
I don't understand... If you want to modify the template, simply publish the views and afterwards edit the chart template to add the sufix... This is no issue releated to this package...
