### ISSUE TITLE
trying to make a dynamic chart

### ISSUE THREAD

**Issue by sabina2nistor** [ConsoleTVs/Charts#188]
hii, i want to make a dynamic chart by having an array in the labels field with the titles of the projects the auth user is involved through tasks (hope i was clear)

untill now i have done this

$idUser = Auth::user()->id;

		$tasksUsed = DB::table('user_task')
            ->join('tasks', 'tasks.id', '=', 'user_task.task_id')
            ->join('projects', 'projects.id', '=', 'tasks.project_id')
            ->select('projects.title')->where('user_task.user_id',$idUser)->get();

           // dd($tasksUsed->toArray());

		$chart = Charts::create('donut', 'morris')
            // ->view('custom.line.chart.view') // Use this if you want to use your own template
            ->title('My nice chart')
            ->labels($tasksUsed->toArray())
            ->values([3,4])
            ->dimensions(300,300)
            ->responsive(false);

and it gives me this error 
Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Object of class stdClass could not be converted to string 
...\vendor\consoletvs\charts\resources\views\morris\donut.blade.php)

please, little help ^^

**Comment by ConsoleTVs** [comment]
$tasksUsed->toArray() Result? can you post it here?

Remember it needs to match the values array in count()...

**Comment by ConsoleTVs** [comment]
Few tips:

1. Use laravel Eloquent
2. Use the database / multiDatabase charts functions

**Comment by sabina2nistor** [comment]
array:2 [▼
  0 => {#239 ▼
    +"title": "titlu1"
  }
  1 => {#243 ▼
    +"title": "2000"
  }
]

**Comment by ConsoleTVs** [comment]
So the count() = 2, then it's good.

The problem is that you need this:

```php
['label1', 'label2']
```
and you have this:

```php
['title' => 'label1', 'title' => 'label2']
```

A way to fix it:

```
	$chart = Charts::create('donut', 'morris')
        // ->view('custom.line.chart.view') // Use this if you want to use your own template
        ->title('My nice chart')
        ->labels($tasksUsed->pluck('title')->toArray())
        ->values([3,4])
        ->dimensions(300,300)
        ->responsive(false);
```

**Comment by sabina2nistor** [comment]
now i understand, thank you ^^

**Comment by ConsoleTVs** [comment]
You're welcome :)
