### ISSUE TITLE
Suggestion: add option for dateFormat

### ISSUE THREAD

**Issue by northify** [ConsoleTVs/Charts#192]
I'm having issues using this with Google Analytics API where they return the date with milliseconds formatted 2017-05-15 16:32:03.000000. 
Using the dateColumn option throws an error because the Google Analytics API is formatted with milliseconds.

Would be nice to set an option to format a date column to mach the date format needed.

**Comment by ConsoleTVs** [comment]
Or you couls just truncate it...
