### ISSUE TITLE
Legend Issues for Special Characters

### ISSUE THREAD

**Issue by BrunoLagoa** [ConsoleTVs/Charts#194]
It is not displaying the caption correctly in all graphics, the text displays broken in the caption. Below is a print to understand better.

Http://prntscr.com/f92rby

**Comment by ConsoleTVs** [comment]
Chart type and library?

**Comment by BrunoLagoa** [comment]
Hello, print's are Charts :: create ('pie', 'c3'), but this is happening on all other types.

**Comment by ConsoleTVs** [comment]
Try updating the library
