### ISSUE TITLE
Removing Legend or Hiding it .for groupByDay()

### ISSUE THREAD

**Issue by javedLive** [ConsoleTVs/Charts#195]
I was trying to implement the Charts in my recent Laravel Project but i was facing one issue ie, i wanted to hide or remove the legend under the bar..Means for **groupByDay()** it show everyday date, which looks very messy to me. How do i remove or hide that section?

Here is a copy if you don't get it : http://imgur.com/a/NdA7A

**Comment by ConsoleTVs** [comment]
Publish the views and edit the template
