### ISSUE TITLE
mechanism for adding script and style tags from ->render() to blade's @push() ?

### ISSUE THREAD

**Issue by vesper8** [ConsoleTVs/Charts#196]
My Laravel app is powered by vue.js, and vue.js does not like it when there are <script> and <style> tags inside of its container.

The very easy approach to this is to create @stack('scripts') and @stack('styles') inside your header/footer blades which are outside of the scope of vue.js, and then in your blade views you do 

@push('scripts')<script>something()</script>@endpush and this way everyone is happy, vue doesn't throw a horrible wall of red text in the console and your render function still gets to use it's inline dependencies

Note that this is different from the stuff that assets() returns, which I am already handling like so

```
@push('header-mixed')
{!! Charts::assets() !!}
@endpush
```

Why render() adds more inline style/script tags I do not know.. but they are the cause of my issues

Could you possibly add this feature? Because right now displaying your charts in my app throws this:

```
app.c61e6fe….js:81071 [Vue warn]: Error compiling template:

... gigantic wall of red text comprising of the entire page's source code ...

- Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>, as they will not be parsed.
- Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>, as they will not be parsed.
- Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>, as they will not be parsed.
- Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>, as they will not be parsed.

(found in <Root>)
```
An easy way to address this would be to have the ->render() return the html separate from the js/css so I could do something like that

```
{!! $chart->renderHtml() !!}
@push('assets'){!! $chart->renderAssets() !!}@endpush
```

or

```
<?php $stuffToRender = $chart->render() ?>
@push('assets'){!! $stuffToRender['assets'] !!}@endpush
{!! $stuffToRender['html'] !!}
```

instead of

```
{!! $chart->render() !!}
```

**Comment by vesper8** [comment]
to be very clear... this is the current output of ->render() for a pie chart

```
<script type="text/javascript">
  $(function () {
    var RbnsoUpxIl = new Highcharts.Chart({
      colors: [
        "#2196F3",
        "#F44336",
      ],
      chart: {
        renderTo: "RbnsoUpxIl",
        height: 500,

        width: 1000,
        plotBackgroundColor: null,
        plotBorderWidth: null,
        plotShadow: false,
        type: 'pie'
      },
      title: {
        text:  "Genders",
      },
      credits: {
        enabled: false
      },
      tooltip: {
        pointFormat: '{point.y} <b>({point.percentage:.1f}%)</strong>'
      },
      plotOptions: {
        pie: {
          allowPointSelect: true,
          cursor: 'pointer',
          dataLabels: {
            enabled: true,
            format: '<b>{point.name}</strong>: {point.y} ({point.percentage:.1f}%)',
            style: {
              color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
            }
          }
        }
      },
      legend: {
      },
      series: [{
        colorByPoint: true,
        data: [
          {
            name: "male",
            y: 49
          },
          {
            name: "female",
            y: 57
          },
        ]
      }]
    })
  });
</script>

<div class="charts" style="background: inherit;">
    <div data-duration="500" class="charts-loader enabled" style="display: none; position: relative; top: 220px; height: 0;">
        <center>
            <div class="loading-spinner" style="border: 3px solid #000000; border-right-color: transparent;"></div>
        </center>
    </div>
    <div class="charts-chart">
        <div id="RbnsoUpxIl" style="height: 500px;

            width: 1000px;
    "></div>
    </div>
    </div>
```

and this is what I want it to be: (tested and it works fine and doesn't throw that vue error)

```
@push('header-mixed')
<script type="text/javascript">
  $(function () {
    var RbnsoUpxIl = new Highcharts.Chart({
      colors: [
        "#2196F3",
        "#F44336",
      ],
      chart: {
        renderTo: "RbnsoUpxIl",
        height: 500,

        width: 1000,
        plotBackgroundColor: null,
        plotBorderWidth: null,
        plotShadow: false,
        type: 'pie'
      },
      title: {
        text:  "Genders",
      },
      credits: {
        enabled: false
      },
      tooltip: {
        pointFormat: '{point.y} <b>({point.percentage:.1f}%)</strong>'
      },
      plotOptions: {
        pie: {
          allowPointSelect: true,
          cursor: 'pointer',
          dataLabels: {
            enabled: true,
            format: '<b>{point.name}</strong>: {point.y} ({point.percentage:.1f}%)',
            style: {
              color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
            }
          }
        }
      },
      legend: {
      },
      series: [{
        colorByPoint: true,
        data: [
          {
            name: "male",
            y: 49
          },
          {
            name: "female",
            y: 57
          },
        ]
      }]
    })
  });
</script>
@endpush

<div class="charts" style="background: inherit;">
    <div data-duration="500" class="charts-loader enabled" style="display: none; position: relative; top: 220px; height: 0;">
        <center>
            <div class="loading-spinner" style="border: 3px solid #000000; border-right-color: transparent;"></div>
        </center>
    </div>
    <div class="charts-chart">
        <div id="RbnsoUpxIl" style="height: 500px;

            width: 1000px;
    "></div>
    </div>
    </div>
```

Or if you could somehow simply have the <script> part be part of the {!! Charts::assets() !!} then that would work just as well..

thanks!!

**Comment by vesper8** [comment]
As a quickly thrown together workaround I am now using this which correctly displays all my charts (4 now, 2 line charts, 1 pie chart and 1 area chart) correctly.

But I imagine this could easily break if you start injecting inline script tags differently than you do now

```
@inject('charts', 'App\Services\ChartsService')

@push('header-mixed')
{!! Charts::assets() !!}
@endpush

@foreach($charts->getCharts() as $chart)
    <?php
    $render = $chart->render();
    $scriptEnds = strrpos($render, '</script>') + strlen('</script>');

    $script = substr($render, 0, $scriptEnds);
    $html = substr($render, $scriptEnds);
    ?>
    
    @push('header-mixed')
    {!! $script !!}
    @endpush
    
    {!! $html !!}
@endforeach
```

**Comment by ConsoleTVs** [comment]
Hey! Sorry for the inconvenience! I see where you're going and I find myself really out of time to work on this, howerver, you can just vendor:publish the assets and modify the templates you're using with the code you showed me on the 2nd comment. This will generate the correct templates when they are rendered!

**Comment by ArmandovO** [comment]
@vesper8 
From your comments, I'd understand you've got this working on laravel 5.4. I'm using vue.js but i dont know how to get this to work.. I've used the documentation i think the outcome is how i wanted but i dont get the visuals to work.. This is the outcome underneath.
https://gyazo.com/48ee390b1cb9c64df2383d5b6c6d6eee

**Comment by vesper8** [comment]
@ArmandovO hrm is it possible you are using {{ $html }} instead of {!! $html !!} ?

The code I posted works for me. This is the contents of my ChartsService.php

```
class ChartsService
{
    public static function getCharts()
    {
            $charts = [];

            $users = User::all();

            $charts['users'] = Charts::database($users, 'line', 'highcharts')
                ->title("Sign-ups per day")
                ->elementLabel("Members")
                ->dimensions(1000, 500)
                ->responsive(true)
                ->groupByDay();

            return $charts;
        }
    }
```

While I was able to get the charts working inside of my hybrid vuejs/laravel application. Prior to the above fix the charts were also working, but vuejs was throwing a fit in the console because of in the script tags it had to parse. But other than the red in the console it wasn't breaking the layout or the app.

I suggest you get the charts working normally and outside of the scope of your vue wrapper first

**Comment by ArmandovO** [comment]
@vesper8 

My controller looks like this : 

``` public function index()
    {
        $unusedLeads = Leads::whereNull('date_called')->count();
        $usedLeads = Leads::whereNotNull('date_called')->count();

        $leadChart = Charts::create('pie','highcharts')
                        ->title('Leads')
                        ->labels(['used','unused'])
                        ->values([$unusedLeads,$usedLeads])
                        ->dimensions(0,300)
                        ->responsive(true);


        return view('back.statistics.index',[
            'amountOfLeadsCalled' => $amountOfLeadsCalled,
            'amountOfProspects' => $amountOfProspects,
            'totalProspects' => $totalProspects,
            'leadChart' => $leadChart


        ]);
    }

How would i need to do it on my blade to fix this issue?

**Comment by ConsoleTVs** [comment]
use   {!! $leadChart->render() !!} instead of {{ $leadChart->render() }} to output the chart

**Comment by vesper8** [comment]
@ArmandovO what he said ^

**Comment by ConsoleTVs** [comment]
Well you said it as well, but idk, he prob did not even try

**Comment by ArmandovO** [comment]
@ConsoleTVs @vesper8 {[$leadChart->render()}} Doesnt output anything for me.. As {{!! $leadChart !!} outputs The full html and script for me.. Ill make a example asap..

**Comment by itamaradin15** [comment]
@vesper8 your "thrown together workaround" works for me  thanks
![screenshot 231](https://cloud.githubusercontent.com/assets/14314148/26809996/d0b76ca6-4a36-11e7-9761-6ac14f51d089.png)

**Comment by alariva** [comment]
@vesper8 I came up with the very same issue. I took your solution of splitting the JS and HTML parts and brought it to an adapter util class. That will kill the view file a bit cleaner and remove the red VUE warning as well.

https://gist.github.com/alariva/d94b3570bf2f6efb1712f49b99d0de93

**Comment by ConsoleTVs** [comment]
Since I'm currently developing an app with Vue, I'm a fraid I'll face this issue in few days, will see how will I handle it!

**Comment by vesper8** [comment]
@alariva brilliant! I love it!
