### ISSUE TITLE
How to render chart using Ajax

### ISSUE THREAD

**Issue by chikevyn** [ConsoleTVs/Charts#197]
My Laravel App displays 5 different charts on a single page. 
Chart 1 and 2 parameters are retrieve from DB while 3,4,5 are static.
Chart 1 and 2 have a common select box, when you select an item it displays the two charts based on your selection.
Each time you select an item it reloads the page before it shows the chart.  To avoid reloading the page i want to use Ajax to receive the selected item id, pass it to controller and render the charts.

How do i achieve this? I am using Chart version 4
![sample](https://cloud.githubusercontent.com/assets/4479042/26451774/523c1d84-4155-11e7-8441-4724db85fc02.jpg)

My Route
`Route::get('/',['uses'=>'DataController@index']);
 Route::post('/',['as'=>'view_charts','uses'=>'DataController@display']);`

**My Controller**
`public function display(Request $request)
    {
    $financials = Financial::all();
    
     $comp = DB::table('financials')->orderBy('id', 'ASC')->pluck('company','company');
     
     $v = $request->company;
    
     $ppt = DB::table('financials')->select(
            'petroleum_profit_tax_us_dollar')->whereYearAndCompany(1999,$v)->first();
     $RO = DB::table('financials')->select(
            'royalty_oil_us_dollar')->whereYearAndCompany(1999,$v)->first();
     $RG = DB::table('financials')->select(
            'royalty_gas_us_dollar')->whereYearAndCompany(1999,$v)->first();
     $GFP = DB::table('financials')->select(
            'gas_flare_penalty_us_dollar')->whereYearAndCompany(1999,$v)->first();
     $nddc_dollar = DB::table('financials')->select(
            'nddc_dollar_us_dollar')->whereYearAndCompany(1999,$v)->first();
     $cit = DB::table('financials')->select(
            'cit_us_dollar')->whereYearAndCompany(1999,$v)->first();
     $rentals = DB::table('financials')->select(
            'rentals_us_dollar')->whereYearAndCompany(1999,$v)->first();
     $edt = DB::table('financials')->select(
            'edt_us_dollar')->whereYearAndCompany(1999,$v)->first();
     $ncdmb = DB::table('financials')->select(
            'ncdmb_us_dollar')->whereYearAndCompany(1999,$v)->first();

     $ppt1999 = $ppt->petroleum_profit_tax_us_dollar;
     $RO1999 = $RO->royalty_oil_us_dollar;
     $RG1999 = $RG->royalty_gas_us_dollar;
     $GFP1999 = $GFP->gas_flare_penalty_us_dollar;
     $nddc1999 = $nddc_dollar->nddc_dollar_us_dollar;
     $cit1999 = $cit->cit_us_dollar;
     $rentals1999 = $rentals->rentals_us_dollar;
     $edt1999 = $edt->edt_us_dollar;
     $ncdmb1999 = $ncdmb->ncdmb_us_dollar;

$chart1 = Charts::multi('line','highcharts')
      ->title('NEITI Chart')
      ->colors(['#21618C', '#239B56', '#4A235A','#F4D03F'])
      ->elementLabel('Total')
      ->dimensions(0, 500)
      ->responsive(false)
      ->labels(['1999', '2000', '2001', '2002', '2003','2004', '2005','2006','2007','2008','2009','2010','2011','2012','2013'])
      ->dataset('Petroleum Profit Tax US $000', [$ppt1999, $ppt2000, $ppt2001, $ppt2002, $ppt2003, $ppt2004, $ppt2005, $ppt2006, $ppt2007, $ppt2008, $ppt2009, $ppt2010, $ppt2011, $ppt2012, $ppt2013])
      ->dataset('Royalty (Oil) US $000', [$RO1999, $RO2000, $RO2001, $RO2002, $RO2003, $RO2004, $RO2005, $RO2006, $RO2007, $RO2008, $RO2009, $RO2010, $RO2011, $RO2012, $RO2013])
      ->dataset('Royalty (Gas) US $000', [$RG1999, $RG2000, $RG2001, $RG2002, $RG2003, $RG2004, $RG2005, $RG2006, $RG2007, $RG2008, $RG2009, $RG2010, $RG2011, $RG2012, $RG2013]);

      $chart2 = Charts::multi('line','highcharts')
      ->title('NEITI Chart')
      ->colors(['#F7DC6F', '#FFEE58', '#03A9F4','#F44336','#0000FF'])
      ->elementLabel('Total')
      ->dimensions(0, 500)
      ->responsive(false)
      ->labels(['1999', '2000', '2001', '2002', '2003','2004', '2005','2006','2007','2008','2009','2010','2011','2012','2013'])
      ->dataset('NDDC US DOLLARS $000', [$GFP1999, $GFP2000, $GFP2001, $GFP2002, $GFP2003, $GFP2004, $GFP2005, $GFP2006, $GFP2007, $GFP2008, $GFP2009, $GFP2010, $GFP2011, $GFP2012, $GFP2013])
      ->dataset('CIT US $000', [$GFP1999, $GFP2000, $GFP2001, $GFP2002, $GFP2003, $GFP2004, $GFP2005, $GFP2006, $GFP2007, $GFP2008, $GFP2009, $GFP2010, $GFP2011, $GFP2012, $GFP2013])
      ->dataset('RENTALS US $000', [$GFP1999, $GFP2000, $GFP2001, $GFP2002, $GFP2003, $GFP2004, $GFP2005, $GFP2006, $GFP2007, $GFP2008, $GFP2009, $GFP2010, $GFP2011, $GFP2012, $GFP2013])
      ->dataset('EDT US $000', [$GFP1999, $GFP2000, $GFP2001, $GFP2002, $GFP2003, $GFP2004, $GFP2005, $GFP2006, $GFP2007, $GFP2008, $GFP2009, $GFP2010, $GFP2011, $GFP2012, $GFP2013])
      ->dataset('NCDMB US $000', [$GFP1999, $GFP2000, $GFP2001, $GFP2002, $GFP2003, $GFP2004, $GFP2005, $GFP2006, $GFP2007, $GFP2008, $GFP2009, $GFP2010, $GFP2011, $GFP2012, $GFP2013]);

        
        $chart3 = Charts::multi('areaspline', 'highcharts')
            ->title('Total Crude Sales : US$ 000 Million')
            ->colors(['#ff0000'])
            ->elementLabel('Million')
            ->labels(['1999', '2000', '2001', '2002', '2003','2004', '2005','2006','2007','2008','2009','2010','2011'])
            ->dataset('Crude and Gas Sales', [6000, 10000, 10000, 8000, 11000, 17000, 0, 27176, 29200, 41217, 20803, 32698, 45560]);
            

        $chart4 = Charts::multi('areaspline', 'highcharts')
            ->title('Total Flows to Federation : US$ 000 Million')
            ->colors(['#283593'])
            ->elementLabel('Million')
            ->labels(['1999', '2000', '2001', '2002', '2003','2004', '2005','2006','2007','2008','2009','2010','2011'])
            ->dataset('Total Flows to Federation',[5727,13422,13364,7574,13362,23657,27914,44314,43301,59773,27170911,41452008,63138647]);

        $chart5 = Charts::multi('bar', 'material')
            ->title('Total Production : Million Barrels')
            //->colors(['#BD00FF','#FF00BD','#00FF6C'])
            ->template("material")
            ->colors(['#2196F3', '#F44336', '#FFC107'])
            ->labels(['1999', '2000', '2001', '2002', '2003','2004', '2005','2006','2007','2008'])
            ->dataset('National Production',[772,828,862,740,844,909,917,858,801,765])
            ->dataset('Exported',[367,429,397,325,385,416,843.9,264,224,242])
            ->dataset('National Production',[66,36,84,79,44,39,72.1,154,157,163]);

        
            return view('dashboard.page', ['financials'=>$financials,'chart' => $chart,'chart1'=>$chart1,'chart2'=>$chart2,'chartt'=>$chartt,'chartt2'=>$chartt2,'comp'=>$comp]);

     
    }

`

**My View Code**
`{!!Form::open(['route'=>'view_charts', 'method'=>'POST','name'=>'selectForm'])!!}
                                    {{Form::label('company','Select Company')}}
                                    {{Form::select('company', $comp,null, ['class'=>'year form-control','onchange'=>'submitform();']) }}
                                {!!Form::close() !!}

                    <div class="col-lg-6 ">
                        {!! $chart1->render() !!}
                    </div>
                    <div class="col-lg-6 ">
                        {!! $chart2->render() !!}
                    </div>
<div class="col-lg-6 ">
{!! $chart3->render() !!}
 </div>
<div class="col-lg-6 ">
{!! $chart4->render() !!}
 </div>
<div class="col-lg-6 ">
{!! $chart5->render() !!}
 </div>

<script type="text/javascript">
 function submitform()
    {
      document.selectForm.submit();
    }
</script>

`

**Comment by ConsoleTVs** [comment]
You can perhaps use a diferent view, and load it into the page using a JS controlled iframe, like this, you can use the charts library and avoid reloading the whole page, simply reload the iframe when the user changes the data

**Comment by chikevyn** [comment]
Thanks for your response.
Please could you link me to a guide that will get me started?

Many thanks

**Comment by ConsoleTVs** [comment]
Check onlines guides, I don't have much time, sorry ^^
