### ISSUE TITLE
Maximum limit line at bar chart

### ISSUE THREAD

**Issue by ngooide** [ConsoleTVs/Charts#198]
is there possible to draw a maximum limit line at bar chart?

**Comment by ConsoleTVs** [comment]
What do you mean?

**Comment by ngooide** [comment]
to indicate whether the bar is under/hit/exceed the limit.

**Comment by ConsoleTVs** [comment]
I don't think this is possible, this feature might be available in 1 or 2 libraries, but we handle over 15-20 libraries, I'm sorry ^^

**Comment by ngooide** [comment]
No worries. Anyway, thx for the efforts!

**Comment by ConsoleTVs** [comment]
Remember this is a multi-library chart package, we need compatibility rather than features :p not all libraries can do all the features you might expect!
