### ISSUE TITLE
Value 0 for realtime justgage

### ISSUE THREAD

**Issue by andreiivascu** [ConsoleTVs/Charts#199]
Hi,

I am using version 2 of Charts and I want to use a realtime chart with "gage, justgage" options. The problem is that even though the graphic works, the value stays at 0. I saw that in your video tutorial you had the same issue. Could you please let me know if you fixed this and if yes how to do it?

Thanks.

**Comment by ConsoleTVs** [comment]
Where? This issue is not existing, where did you see it?

**Comment by andreiivascu** [comment]
You can view the issue here in your video https://youtu.be/KrAvrU2XYuY?t=42m47s

The chart is realtime, the graphic is moving, but the value is always 0, is not changing. Can I make the value change from 0?
![gague](https://cloud.githubusercontent.com/assets/29000245/26521750/bc9ed0b4-42f8-11e7-90c0-2d5855134154.PNG)

**Comment by ConsoleTVs** [comment]
I think this issue was fixed, are you using version 4.5.1 ?

**Comment by andreiivascu** [comment]
I am using version 2 because I am using an older version of laravel (5.1) and I cannot update it right now.

**Comment by ConsoleTVs** [comment]
I'm sorry to tell you the only possibility is to dig into the package core that you have installed and modify it yourself...
