### ISSUE TITLE
syntax error, unexpected 'new' (T_NEW), expecting identifier (T_STRING)

### ISSUE THREAD

**Issue by nconroy** [ConsoleTVs/Charts#20]
This seems a pretty obvious error, what am I missing?

**Comment by ConsoleTVs** [comment]
You seem to have a common error, will look into it in a few hours. Can you paste the code here?

**Comment by nconroy** [comment]
Here is the code: $chart = Charts::newChart('bar');
This doesn't happen on php 7 but I'm using php5.6. I have made a fork as I need it to work with this version. You might want to note the requirement for php 7

**Comment by ConsoleTVs** [comment]
Thanks @nconroy. Do you have any clue on what might be happening on php 5.6 ? Will require it meanwhile
