### ISSUE TITLE
ErrorException in AliasLoader.php line 79: Class 'ConsoleTVs\Charts\Charts' not found

### ISSUE THREAD

**Issue by WeMadeItMor** [ConsoleTVs/Charts#200]
I've tried anything but i can solve this

**Comment by WeMadeItMor** [comment]
<img width="766" alt="capture d ecran 2017-05-28 a 19 54 58" src="https://cloud.githubusercontent.com/assets/26638277/26531755/96709192-43df-11e7-8def-99b3bd84f4a5.png">

**Comment by WeMadeItMor** [comment]
<img width="500" alt="capture d ecran 2017-05-28 a 19 55 47" src="https://cloud.githubusercontent.com/assets/26638277/26531762/bda8dad0-43df-11e7-91b1-499f501de99e.png">
<img width="439" alt="capture d ecran 2017-05-28 a 19 55 54" src="https://cloud.githubusercontent.com/assets/26638277/26531763/bda8edf4-43df-11e7-83df-ade14fd412d3.png">
<img width="764" alt="capture d ecran 2017-05-28 a 19 55 59" src="https://cloud.githubusercontent.com/assets/26638277/26531764/bda9daf2-43df-11e7-93c2-0dc3372e474e.png">
<img width="752" alt="capture d ecran 2017-05-28 a 19 56 06" src="https://cloud.githubusercontent.com/assets/26638277/26531761/bda7dc3e-43df-11e7-906e-52a251050040.png">
<img width="406" alt="capture d ecran 2017-05-28 a 19 56 12" src="https://cloud.githubusercontent.com/assets/26638277/26531765/bdab2efc-43df-11e7-9274-4bb80780f82d.png">

**Comment by WeMadeItMor** [comment]
My code is there

**Comment by ConsoleTVs** [comment]
https://erik.cat/projects/Charts/docs/4

![image](https://cloud.githubusercontent.com/assets/6124435/26531902/e6457dfe-43f3-11e7-9672-7f9ab24dd55b.png)

This image is wrong, if you read the documentation you'll find out its:

'Charts' => ConsoleTVs\Charts\Facades\Charts::class,

**Comment by WeMadeItMor** [comment]
Thank you it works

**Comment by Sapphire97** [comment]
i have this issue but
'Charts' => ConsoleTVs\Charts\Facades\Charts::class,
doesn't work. it says "Class 'ConsoleTVs\Charts\Facades\Charts' not found"

**Comment by ITNhatLam** [comment]
help me, Class 'ConsoleTVs\Charts\Facades\Charts' not found

**Comment by ConsoleTVs** [comment]
1. Read the docs
2. Read the other 184727263 issues with the same problem as yours.

**Comment by tpharaoh** [comment]
@ITNhatLam 
*what version of charts
*did you do composer dumpautoload
*what version of laravel

there are plenty of comments in this repo of people with sameproblem and solved it, so search a bit

**Comment by ITNhatLam** [comment]
@tpharaoh 
- laravel 7.0
- i don't know version of charts

**Comment by tpharaoh** [comment]
@ITNhatLam I guess you mean php 7.0, Laravel is 5.X
I guess if you look in composer.json you can see charts version

**Comment by tpharaoh** [comment]
A newer Laravel will auto discover.
If not, you will need to add the providers by hand... there are instructions in the docs and in various threads on git.

**Comment by hamzabenali95** [comment]
ErrorException (E_WARNING)
Class 'ConsoleTVs\Charts\Facades\Charts' not found


![c__users_ars_desktop_pfe_pfe_config_app php pfe - sublime text unregistered 18_05_2018 16_57_27](https://user-images.githubusercontent.com/37031324/40245288-8782242c-5ac5-11e8-9ec5-ca8fccff5fbf.png)
![c__users_ars_desktop_pfe_pfe_config_app php pfe - sublime text unregistered 18_05_2018 16_58_07](https://user-images.githubusercontent.com/37031324/40245290-87be2bfc-5ac5-11e8-9d4c-d66df3008b61.png)
![c__users_ars_desktop_pfe_pfe_config_app php pfe - sublime text unregistered 18_05_2018 16_59_00](https://user-images.githubusercontent.com/37031324/40245291-87fbbb3e-5ac5-11e8-8bcc-07c6e862366e.png)
![c__users_ars_desktop_pfe_pfe_config_app php pfe - sublime text unregistered 18_05_2018 17_01_07](https://user-images.githubusercontent.com/37031324/40245293-88359b1a-5ac5-11e8-8a07-7a6816c238c9.png)

**Comment by ConsoleTVs** [comment]
You must be fucking kidding me

**Comment by tpharaoh** [comment]
Looks like he needs laravel docs not charts docs

**Comment by hamzabenali95** [comment]
take it easy guys @ConsoleTVs @tpharaoh i'm still learning 😢

**Comment by ConsoleTVs** [comment]
I understandu are learning, but learning means you at least took at look at the package documentation. Please tell me where do I say you haveto register a facade?

**Comment by kavyajain996** [comment]
why is laravel having so many issues? Mainly with versions we work on? Same issue again
