### ISSUE TITLE
Chart Radar

### ISSUE THREAD

**Issue by maitrepylos** [ConsoleTVs/Charts#201]
Hello, is it possible to generate Radar Chart ?

thx

https://en.wikipedia.org/wiki/Radar_chart

**Comment by ConsoleTVs** [comment]
Will soon be posible with chartjs :), 1 month or so and a new release 5.0 will be out with 2 more libraries, diferent languages and radar chart :)

**Comment by maitrepylos** [comment]
Thank you, eager to apply this new version :)

**Comment by ConsoleTVs** [comment]
You're welcome!
