### ISSUE TITLE
chartjs on mobile

### ISSUE THREAD

**Issue by nam-co** [ConsoleTVs/Charts#202]
Hi Erik, I just noticed that chartjs stop working on safari iOS, it was working before, I tested chartjs  on desktop and highcharts on mobile and their still working, Any ideas? thanks for your time in this package

**Comment by ConsoleTVs** [comment]
Hello, I did not change any code for a month or so, did it just happen randomly?

**Comment by nam-co** [comment]
Yes, I did a composer update and it stop working, maybe it's just me, but it happen in a page I haven't touch for a while and also in a new implementation I'm doing

**Comment by ConsoleTVs** [comment]
From what version did you come from?
