### ISSUE TITLE
"__toString() must not throw an exception" when rendering gauge and percentage types

### ISSUE THREAD

**Issue by khaltis** [ConsoleTVs/Charts#203]
I have managed to use the library for rendering line and bar charts, however no luck rendering some of the other types. Specifically trying to set up some realtime gauges but starting with some simple static ones first. I've copied the exact example from your documentation and have the chart object as seen in the attached image, but when rendering I'm receiving the following error:

`Method Illuminate\View\View::__toString() must not throw an exception`

Any ideas on what could be causing this issue would be great. My relevant package versions are listed below:

- Laravel version: 5.1.46
- Chart version: 4.5.1

![screen shot 2017-05-31 at 11 39 36 am](https://cloud.githubusercontent.com/assets/1954344/26612865/ad48bed0-45f6-11e7-9af9-6d7f6427b6bc.jpg)

**Comment by ConsoleTVs** [comment]
Can you past me the chart code please?

**Comment by khaltis** [comment]
The below code is inserted directly into my blade file. This is the exact snippet that I used which is directly from your examples in the documentation. I can get the line and bar charts working, this issue only appears to be relevant to some of the other chart types such as the 'percentage' and gaugue chart types.

`$chart =   Charts::create('percentage', 'justgage')
    ->title('My nice chart')
    ->elementLabel('My nice label')
    ->values([65,0,100])
    ->responsive(false)
    ->height(300)
    ->width(0);

$chart->render()`

**Comment by ConsoleTVs** [comment]
Hello, I will try them today and see if I get the same error, thanks for reporting, will answer later on ^^

**Comment by ConsoleTVs** [comment]
Works fine for me:

![image](https://user-images.githubusercontent.com/6124435/27003780-65e76b7c-4dfd-11e7-911e-676b4a72f81e.png)

```php
$chart = Charts::create('percentage', 'justgage')
            // Setup the chart settings
            ->title("My Cool Chart")
            // A dimension of 0 means it will take 100% of the space
            ->dimensions(0, 400) // Width x Height
            // This defines a preset of colors already done:)
            ->template("red-material")
            // You could always set them manually
            // ->colors(['#2196F3', '#F44336', '#FFC107'])
            // Setup the diferent datasets (this is a multi chart)
            ->values([5,20,100,15,32])
            // Setup what the values mean
            ->labels(['One', 'Two', 'Three']);
```

**Comment by khaltis** [comment]
I know what the issue is now, it seems that your package requires Laravel 5.2 and above as it is using @php within the blade files for inline php code. I'm using Laravel 5.1 so this doesn't work for me. While I've managed to modify the blade files that are using this @php syntax within the vendor folder... do you think you could just modify your package to use <?php ... ?> instead of @php(...) so that it is also backwards compatible with Laravel 5.1?

**Comment by ConsoleTVs** [comment]
Hello, I'm sorry to hear that but I myself prefer to keep the current syntax, Instead of asking packages to support an older version try upgrading your laravel version, it also comes with core fixes and security fixes!
