### ISSUE TITLE
How to change the chart default y-axis title "Values"

### ISSUE THREAD

**Issue by chikevyn** [ConsoleTVs/Charts#204]
I have been trying to change highcharts default y-axis title "Values" as shown in the image below . i have tried ->elementLabel('Total')  and several others but none worked.

Please how do i change it?

Many thanks

![demo](https://cloud.githubusercontent.com/assets/4479042/26626964/b78b661e-45f0-11e7-8e5c-f7d89c7fdcd1.jpg)

**Comment by ConsoleTVs** [comment]
Charts version ?

**Comment by chikevyn** [comment]
Charts version4 and Laravel version 5.3

**Comment by ConsoleTVs** [comment]
Later on will make some tests

**Comment by chikevyn** [comment]
Reminder on the test!

**Comment by ConsoleTVs** [comment]
@chikevyn I'm currently under lots of work / exams, problems will try to be fixed as soon as I have free time. I'm sorry but have no time right now to check issues...

**Comment by chikevyn** [comment]
Okay. Good luck your exams

**Comment by ConsoleTVs** [comment]
->y_axis_title("Sample")

**Comment by Lvm-Daud** [comment]
->yAxisTitle("Sample")
