### ISSUE TITLE
chart is not rendered, only see the spinner

### ISSUE THREAD

**Issue by massuncao** [ConsoleTVs/Charts#205]
I am trying your package for the first time and i can't render a chart. I am a newbie at laravel.

i am following the steps in the documentation for the version 4, in the controller i have the $chart defined as you stated in the docs. 

At the view i have {!! Charts::assets() !!} at the scripts section of the <head> and then {!! $chart->render() !!} in the content section.

When rendering the page, i see the spinner for a second and then the chart is not rendered. 

I have been searching for this problem for a few days and until now i found no answer.

Thanks in advance

**Comment by ConsoleTVs** [comment]
try placing the assets in the head of your document. Can you paste the chart code here?

**Comment by massuncao** [comment]
Here's the code, it is the first example at your website:
```
        $chart = Charts::multi('bar','highcharts')
            ->title("My Cool Chart")
            ->dimensions(0,400)
            ->template("material")
            ->dataset('Element 1',[5,20,100])
            ->dataset('Element 2',[15,30,80])
            ->dataset('Element 1',[25,10,40])
            ->labels(['One','two','Three']); 
       return view('pages.tasks_stats', ['chart' => $chart]);
```
About the assets, i have them in a section that is called at the head by the yield. But yes, i have tried putting the assets at the head and the result is the same

**Comment by ConsoleTVs** [comment]
Have you tried looking at the JS console output in chrome dev tools?

**Comment by massuncao** [comment]
Ok. It might be that about importing jquery twice. I'll check that tomorrow and give feedback.
Thanks a lot, twice, for the help and for having created the package

**Comment by ConsoleTVs** [comment]
Works fine for me, you must have something wrong with incompatible JS packages, eg: JS frameworks, or Jquery already imported, etc
