### ISSUE TITLE
Ignore Null values from the database

### ISSUE THREAD

**Issue by yemiwebby** [ConsoleTVs/Charts#207]
So I have a set of data that needs to be displayed on the admin dashboard.

` $chart_print_media = Charts::database(User::all(), 'pie', 'highcharts')
                ->title('Print Media Campaign')
                ->dimensions(450, 300)
                ->groupBy('print_media');
`

This works fine but NULL values were also represented in the chart.
How do I ignore NULL values please?

**Comment by ConsoleTVs** [comment]
```php
$users = User::all()->filter(function ($user) {
    return $user->print_media !== null;
});

$chart_print_media = Charts::database($users, 'pie', 'highcharts') ->title('Print Media Campaign') ->dimensions(450, 300) ->groupBy('print_media');
```

**Comment by yemiwebby** [comment]
This works fine for me. Thanks

**Comment by ConsoleTVs** [comment]
You're welcome!
