### ISSUE TITLE
Add export button to high charts

### ISSUE THREAD

**Issue by orkempire** [ConsoleTVs/Charts#209]
I would like to know how to add the button available within fusion charts that allows us to export the chart to various formats to highcharts?

**Comment by ConsoleTVs** [comment]
It's done by adding the JS of the export module on fusioncharts. Our config allows you to add the script tags or you can manually do it :)

**Comment by orkempire** [comment]
Hi Erik, 
I looked at the config file and the fusioncharts JS after you answered, but couldn't locate the parts where the export module code is. Could you tell me how to locate that, and I'd be able to integrate that into highcharts then. Thank you.

**Comment by ConsoleTVs** [comment]
Isn't already added?

https://github.com/ConsoleTVs/Charts/blob/master/config/charts.php#L121

**Comment by orkempire** [comment]
That line is there, however, the export module only appears for fusion charts, not for highcharts. I'm wondering if there's some property/method that I have to set to `true` for it to show up within highcharts?

**Comment by orkempire** [comment]
I even added the following to `https://github.com/ConsoleTVs/Charts/blob/master/resources/views/highcharts/pie.blade.php`

`navigation: {
        buttonOptions: {
            enabled: true
        }
    }`

Still not working...

**Comment by ConsoleTVs** [comment]
There's an option to enable / disable the credits... I will look at all theese things at the end of the month
