### ISSUE TITLE
Unknown chart library / type combination

### ISSUE THREAD

**Issue by minedun6** [ConsoleTVs/Charts#21]
Just got this with a big smiley face ^^

**Comment by ConsoleTVs** [comment]
What combination did you try?

**Comment by minedun6** [comment]
can u come on skype ?
and i copied ur code on the front page.

**Comment by ConsoleTVs** [comment]
On my way

**Comment by MohamedQabbani** [comment]
How you solved it?

**Comment by ConsoleTVs** [comment]
You need to select an available chart depending on the library selected, What library and chart are you trying to output?

**Comment by SandyUgale** [comment]
Im having same problem..It didn't display anything ...

**Comment by ConsoleTVs** [comment]
Paste the code here

**Comment by sabina2nistor** [comment]
hii, i'm having the same problem, here is my code

Controller:

public function getIndex(){

		$chart = Charts::create('line', 'highcharts')
            ->view('custom.line.chart.view') // Use this if you want to use your own template
            ->title('My nice chart')
            ->labels(['First', 'Second', 'Third'])
            ->values([5,10,20])
            ->dimensions(1000,500)
            ->responsive(false);

		$posts=Post::orderBy('created_at','desc')->limit(4)->get();
		return view('pages/welcome', ['chart' => $chart])->withPosts($posts);
	}

<h2>Sidebar</h2>
          {!! $chart->render() !!} 

i have also put the {!! Charts::assets() !!} in my html head.. so i've done everything according to your documentation of version 3

**Comment by ConsoleTVs** [comment]
Hello, 

```
->view('custom.line.chart.view') // Use this if you want to use your own template
```

remarking this: Use this if you want to use your own template

Please remove this line and try again. It's better explained in version 4 docs.

**Comment by sabina2nistor** [comment]
omg how fast, thank you very much, 
it works now, 
i'm super grateful

**Comment by ConsoleTVs** [comment]
You're welcome!
