### ISSUE TITLE
render aggregate Data on y-axis

### ISSUE THREAD

**Issue by younesdiouri** [ConsoleTVs/Charts#210]
Hello guys ! first I want to thank you for this chart project its very cool and easy to use :) 

I got a problem for rendering chart with datas (y-axis issue), here is my code : 

```
$data = Entree::select(
            'entree.DateOperation as date', //date
            DB::raw('SUM(X200) as aggregate'))
            ->join('directionregionale', 'entree.directionregionale_id', '=', 'directionregionale.id') //innerjoin
            ->where('directionregionale.Name', 'LIKE', $user["name"])
            ->groupBy('date')
            ->get();
        $chart = Charts::database($data, 'line', 'highcharts')
            ->elementLabel("Total 200")
            ->preaggregated(true)
            ->title('Graphiques')
            ->dimensions(1000, 500)
            ->groupBy('date');
        return view('admin.chart', ['chart' => $chart]);
```
![image](https://user-images.githubusercontent.com/22621743/26838102-b29228cc-4ace-11e7-9dc1-41ee4f105781.png)

 I don't understand why it's not displaying values of my SUM(X200) parameter, but only a value of 1 when it exists. 
![image](https://user-images.githubusercontent.com/22621743/26838169-df0a4736-4ace-11e7-93c5-0ce2d90c06f6.png)
the values of my sum(X200) column is different when the date changes, so it should be obviously a different graph ^^. 

Thanks you for your help !

**Comment by younesdiouri** [comment]
I understood the abs-x display (I put a groupbyMonth method) but still no elements on the y's 
`$chart = Charts::database($data, 'bar', 'highcharts')
            ->elementLabel("Total 200")
            ->preaggregated(true)
            ->title('Graphiques')
            ->dimensions(1000, 500)
            ->groupByMonth();
        return view('admin.chart', ['chart' => $chart]);`

**Comment by ConsoleTVs** [comment]
I have no idea how the preagretated works atm, I have not built this functionaity on charts.

However, I will try to help you. Tell me what expected result would you like to get, (just a sample) and we will proceed :)

**Comment by younesdiouri** [comment]
Thanks for your answer and your help. Actually, I'm trying to display the X200 sum column values (I grouped it by date) on the y-axis. 
Like a bar or line chart with dates on x (I can do that ) but sum(x200) values on y so it will be like : 
for 2016-02-15 -> 250000.00  and for 2016-02-16 4501452.00 .
I am doing statistics for cash management, so x200 represent the value of 200's that day. Thats why a chart like this could be very helpful for me !

**Comment by ConsoleTVs** [comment]
Well, you can always build the chart yourself using the ```create``` method. This method requires the values and the labels, so As the labels you just have to create an array with something like this:

['Day 1', 'Day 2', 'Day 3', ...] and for the data simply use a collection to sum it.

The lenght of the arrays must match. You have examples in the page. Yes, it's always fancy to use the database method, but not always usefull :)

**Comment by younesdiouri** [comment]
ok thanks for the tip! i'll try it with the` create` method, much more flexibility indeed !

**Comment by ConsoleTVs** [comment]
If you have any problem tell me!
