### ISSUE TITLE
How to edit the hover popup values.

### ISSUE THREAD

**Issue by Arthmael8610** [ConsoleTVs/Charts#211]
how would i go about changing the text on the popup really i just want to add a comma for the amount and remove the word units and place a $ at the beginning of the value. but i cant seem to find that anywhere.

Thanks,

![image](https://user-images.githubusercontent.com/1689422/26881980-0dc9a916-4b67-11e7-9c73-a0ccf5226cbb.png)

**Comment by ConsoleTVs** [comment]
Not supported. It's dependend on the library you use. I'm sorry.

**Comment by Arthmael8610** [comment]
so there is no way at all to change it.... that is just GAH

**Comment by ConsoleTVs** [comment]
Well, there is a way of doing it in highcharts, but not on the other 14 libraries... So it's useless for me to implement something only usefull in 1-2 libraries as you might understand...

**Comment by Arthmael8610** [comment]
how do you do it cause i am using highcharts? i really need it to change.

**Comment by ConsoleTVs** [comment]
You simply need to publish the views.

```
php artisan vendor:publish
```

And change the highcharts views at resources/views/vendor/charts/highcharts views to your desire ^^

**Comment by Arthmael8610** [comment]
wow didnt even think of that, lol now to find where the space is added if a number is 1000+ so that i can change it to a , :)

**Comment by ConsoleTVs** [comment]
Haha, great you found a solution mate!
