### ISSUE TITLE
Can i use bar chart with horizontal view

### ISSUE THREAD

**Issue by HuongSakada** [ConsoleTVs/Charts#214]

**Comment by ConsoleTVs** [comment]
What do you mean?

**Comment by HuongSakada** [comment]
I mean that I really don't know how to use this bar chart in horizontal not
vertical. Can you help me?

**Comment by ConsoleTVs** [comment]
Its not supported yet, only the vertical mode atm

**Comment by HuongSakada** [comment]
Let's me when it support.
Thames.
