### ISSUE TITLE
How get values of three columns from DB 

### ISSUE THREAD

**Issue by chikevyn** [ConsoleTVs/Charts#215]
Refer to Database Alternative in documentation as shown below,
$data = Shopping::all();
$chart = Charts::create('bar', 'highcharts')
             ->title('My nice chart')
             ->elementLabel('My nice label')
             ->labels($data->pluck('shoppingDate'))
             ->values($data->pluck('price'))
             ->responsive(true);

assuming i want to add more columns like income, expenditure, price etc, how do add them to ->values() method of the chart?

Many thanks

**Comment by chikevyn** [comment]
Laravel version 5.3 Chart version 4

**Comment by ConsoleTVs** [comment]
Then you want a multi chart!

https://erik.cat/projects/Charts/docs/4#multi-datasets-charts

Check the example there ^^

**Comment by chikevyn** [comment]
Yes, i have seen that but i want specific columns not all from one table. See my code

 $result = DB::table('financials')->select([
            DB::raw('year as year'),
            DB::raw('petroleum_profit_tax_us_dollar as petroleum_profit_tax_us_dollar'),
            DB::raw('royalty_oil_us_dollar as royalty_oil_us_dollar'),
            DB::raw('royalty_gas_us_dollar as royalty_gas_us_dollar'),
            DB::raw('gas_flare_penalty_us_dollar as gas_flare_penalty_us_dollar'),
            DB::raw('nddc_dollar_us_dollar as nddc_dollar_us_dollar'),
            DB::raw('cit_us_dollar as cit_us_dollar'),
            DB::raw('rentals_us_dollar as rentals_us_dollar'),
            DB::raw('edt_us_dollar as edt_us_dollar'),
            DB::raw('ncdmb_us_dollar as ncdmb_us_dollar')])
            ->whereCompany($v)
            ->get();

            //return $result;

           
        
       
        $chart1 = Charts::create( 'bar', 'highcharts')
                 
          ->elementLabel("Total")
          ->dimensions(1000, 500)
          ->responsive(false)
         ->colors(['#21618C', '#239B56', '#4A235A','#F4D03F', '#660000', '#00FF99','#F44336','#0000FF'])
          ->labels($result->pluck('year'))
          ->values([
            $result->pluck('petroleum_profit_tax_us_dollar'),
            $result->pluck('royalty_oil_us_dollar'),
            $result->pluck('royalty_gas_us_dollar'),
            $result->pluck('nddc_dollar_us_dollar'),
            $result->pluck('cit_us_dollar'),
            $result->pluck('rentals_us_dollar'),
            $result->pluck('edt_us_dollar'),
            $result->pluck('ncdmb_us_dollar')]
            );

I tried the code above but it shows only petroleum_profit_tax_us_dollar in the chart

**Comment by ConsoleTVs** [comment]
I have no idea what this is since I'm working with eloquent, can you dd($result) ?

```
$result = DB::table('financials')->select([
DB::raw('year as year'),
DB::raw('petroleum_profit_tax_us_dollar as petroleum_profit_tax_us_dollar'),
DB::raw('royalty_oil_us_dollar as royalty_oil_us_dollar'),
DB::raw('royalty_gas_us_dollar as royalty_gas_us_dollar'),
DB::raw('gas_flare_penalty_us_dollar as gas_flare_penalty_us_dollar'),
DB::raw('nddc_dollar_us_dollar as nddc_dollar_us_dollar'),
DB::raw('cit_us_dollar as cit_us_dollar'),
DB::raw('rentals_us_dollar as rentals_us_dollar'),
DB::raw('edt_us_dollar as edt_us_dollar'),
DB::raw('ncdmb_us_dollar as ncdmb_us_dollar')])
->whereCompany($v)
->get();
```
