### ISSUE TITLE
How to make Dynamic Charts label from Database?

### ISSUE THREAD

**Issue by javedLive** [ConsoleTVs/Charts#217]
I wanted to make a dynamic Chart Bar where Label is every day of month and column value will be coming dynamically from database.. I have used ConsoleTVs/Charts for making it. I have products table with id , name,amount I wanted to find total number of amount i have got perday based on products.Because same products can sell multiple time in a single day. The problem with the below code is I'm getting no of products sell on each day not total amount. How do i represent it in chart bar

$data = DB::table('products')
                ->select('products.created_at',DB::raw('sum(products.amount) as sum' ))
                ->groupBy('products.id')                
                ->get();

        //dd($data);      
        $chart = Charts::create('area', 'highcharts')
            ->elementLabel("Total")
            ->title('Monthly Collection')
            ->dimensions(1000, 500)
            ->values($data->pluck('sum'))
            ->responsive(false)
            ->groupByDay();

**Comment by ConsoleTVs** [comment]
Did you try this? https://erik.cat/projects/Charts/docs/4#database-charts

**Comment by rafael1delgado** [comment]
> Did you try this? https://erik.cat/projects/Charts/docs/4#database-charts

Broken link
