### ISSUE TITLE
Possibility to add charts in the footer

### ISSUE THREAD

**Issue by AdrianKuriata** [ConsoleTVs/Charts#220]
Hi, is possible to add charts before end body tag? I don't want load JS files first. When i have jquery in footer i getting error $ doesn't exists like a function.

**Comment by ConsoleTVs** [comment]
What happens if you disable the loader?

**Comment by AdrianKuriata** [comment]
What do you mean? Now in charts is function which loading all libraries andwe need put it into head tag because all charts js script is rendering into code and if you don't have jquery in head tag we getting error $ is not a function. My question is possible to has js libraries before end of body tag. I don't really like load JS files in head document because this slow down loading page.

**Comment by ConsoleTVs** [comment]
Charts comes with a function called loader (the chart spinner before it appears) this is done using jquery, what happens if you disable it from your charts like so:

->loader(false)

**Comment by AdrianKuriata** [comment]
Wow, i will try in thursday because i don't have a access to this, let me check and i will ping you if will be some changes.

**Comment by ConsoleTVs** [comment]
Sure!

**Comment by AdrianKuriata** [comment]
@ConsoleTVs This is not working, problem is i don't have jQuery loaded in header page and i will see `$ is not a function`. Problem is charts JS is rendered into document, not before close body tag. I have jQuery loaded in footer. Now if i want use Charts i must put Charts libraries into header page and i have jQuery loaded two times...

**Comment by ConsoleTVs** [comment]
Hello, this will be changed, don't worry

**Comment by maddeezy** [comment]
I had similar issue. .I just removed the jQuery loader in the scripts tag in config/charts.php...then everything worked perfectly.

Great package!!

**Comment by AdrianKuriata** [comment]
@maddeezy Yea, but you loading everything with jquery in `head `tag, i don't want it, i wanna load everything what is created in JS before end `body `tag.

**Comment by maddeezy** [comment]
Maybe I don't understand completely the issue...

You mention jQuery loaded 2X which will break jQuery and yeah you get $ not found issue.

In the SPA, I load assests in header (is not slow, but I am using digital ocean)...then from the controller, return the view using the blade templating...and the graph renders perfect....and fast.

So if you actually do have jQuery loading 2X, try (as a test) to comment out the script for loading jquery in the config/charts.php file.

Erik, do you see any issues with this?

**Comment by ConsoleTVs** [comment]
I just re-coded that. From the next release you'll be able to do this: (Example with VUEJS)

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Chart with VueJS</title>

        {!! \ConsoleTVs\Charts\Facades\Charts::assets() !!}

    </head>
    <body>
        <div id="app">
            {!! $chart->html() !!}
        </div>
        <script src="https://unpkg.com/vue"></script>
        <script>
            var app = new Vue({
                el: '#app',
            });
        </script>
        {!! $chart->script() !!}
    </body>
</html>

```

**Comment by AdrianKuriata** [comment]
@ConsoleTVs Hi, i see new release 5.0 is possible to download. Do you think i can upgrade your package from 4 to 5 version and everythink will be working perfectly?

**Comment by JapSeyz** [comment]
The current version still loads jQuery in the header. Something like

```html
window.onload = function(){
    if(jQuery){
        <script>Display Chart Here</script>
    }
}
```

Would perhaps allow me to use the jQuery that I am loading in the footer with webpack.

As these charts will be loaded before the footerJs right now, and that's an issue.

**Comment by ConsoleTVs** [comment]
Hello:

The Charts::assets accepts parameters that let you choose what libraries to load. even jquery.

the the latestes charts 5 version allows to split the chart HTML and SCRIPT in two sections.

The official docs are online already :)

**Comment by JapSeyz** [comment]
I saw that, but if I omit jQuery from the assets, it still throws an error. 

Even though the script tag is after the jQuery bundle. 
What does the HTML method return?

**Comment by JapSeyz** [comment]
Okay, now it's only the loader that gives me an error, but setting the config to false will still attempt to load it. Is there no way to turn the loader off, or put that script into the footer too?

The charts are now loaded outside any form for container...

I have split it up into html and script, but it loads the chart where the script is located, not the html.

![HTML](https://user-images.githubusercontent.com/2234034/29297779-f2dc17ac-816b-11e7-8cf0-00334e748590.PNG)
![Render](https://user-images.githubusercontent.com/2234034/29297778-f2dba27c-816b-11e7-9632-6fb52cb1073a.PNG)

@ConsoleTVs Is there a way to fix this?

**Comment by ConsoleTVs** [comment]
@JapSeyz Assets have styles + scripts. The loader is in the scripts section.

Instead using the assets method, use the Charts::styles() on the top and Charts::scripts() on the bottom. BEFORE the individual chart script.

**Comment by JapSeyz** [comment]
@ConsoleTVs This does still not fix the issue that the chart is rendered at the location of the $chart->script(), not the location of the $chart->html(). (As pictured in my previous comment)

**Comment by ConsoleTVs** [comment]
@JapSeyz I still dont understand what you want it to do?

The script() tag contains the JS logic to run the chart, the html() contains the html / styles of it.

the render() combines both of them in a single call.

You can chose where you want the chart to be... dunno

**Comment by JapSeyz** [comment]
@ConsoleTVs  I would like the chart to be placed where i call $chart->html(), but as you can see in the top of the two images, I've placed them into a bootstrap col-lg-6 class.

But, in the browser, (the bottom picture) you can see that the chart is rendered where I call $chart->script(). Which means it's rendered right below the other scripts.

**Comment by ConsoleTVs** [comment]
Strange. This should not happen.

Check the source code of the generated page... the script is only js that renders it to a container of a random ID.

**Comment by JapSeyz** [comment]
@ConsoleTVs I see the line in bar.blade, and correctly enough it renders a canvas, but the canvas is placed with the scripts().

Here's the HTML, see the $chart->html() is placed within two col-lg-6 divs. 
![Html Layout](https://user-images.githubusercontent.com/2234034/29329534-da10a538-81fe-11e7-9a15-f63dd23eae7a.PNG)

Here you can see that it renders the canvas along with the scripts, in the page-footer instead of the ->html() divs.
![capture](https://user-images.githubusercontent.com/2234034/29329533-da095508-81fe-11e7-8414-b63168781b54.PNG)

Here you can see that the two ->html() divs are completely empty.
![capture2](https://user-images.githubusercontent.com/2234034/29329535-da12a428-81fe-11e7-8a04-352e1757fb86.PNG)

**Comment by ConsoleTVs** [comment]
Okay then, that's the issue!, let me work on this :)

**Comment by JapSeyz** [comment]
@ConsoleTVs I think it's this line/statement. as it renders some HTML but seems to be included in the script?

https://github.com/ConsoleTVs/Charts/blob/master/resources/views/chartjs/bar.blade.php#L2

**Comment by ConsoleTVs** [comment]
It has to be like that, it's later separated.

For some reason the separation is not working.

Can you confirm the charts version using?

**Comment by JapSeyz** [comment]
I'm on 5.0.2, using chartjs

**Comment by ConsoleTVs** [comment]
Okai, give me a few minutes, looking into it.

**Comment by JapSeyz** [comment]
It seems to only be an issue for chartjs, I just tried highcharts and that works fine.

**Comment by JapSeyz** [comment]
It seems very random, as the "google" provider throws an entirely different error that none of the other two did.

**Comment by ConsoleTVs** [comment]
It works for me...

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Chart with VueJS</title>

        {!! \ConsoleTVs\Charts\Facades\Charts::styles() !!}

    </head>
    <body>
        <div id="app">
            {!! $chart->html() !!}
        </div>
        <script src="https://unpkg.com/vue"></script>
        <script>
            var app = new Vue({
                el: '#app',
            });
        </script>
        {!! \ConsoleTVs\Charts\Facades\Charts::scripts() !!}
        {!! $chart->script() !!}
    </body>
</html>
```

```php
$chart = \ConsoleTVs\Charts\Facades\Charts::multi('bar', 'chartjs')
            // Setup the chart settings
            ->title("My Cool Chart")
            // A dimension of 0 means it will take 100% of the space
            ->dimensions(0, 400) // Width x Height
            // This defines a preset of colors already done:)
            //->template("material")
            // You could always set them manually
            // ->colors(['#2196F3', '#F44336', '#FFC107'])
            // Setup the diferent datasets (this is a multi chart)
            ->dataset('Element 1', [5,20,100])
            ->dataset('Element 2', [15,30,80])
            ->dataset('Element 3', [25,10,40])
            // Setup what the values mean
            ->labels(['One', 'Two', 'Three'])
            ->responsive(false);

    return view('chart', compact('chart'));
```

**Comment by ConsoleTVs** [comment]
Google library working fine for me as well.

**Comment by JapSeyz** [comment]
That's good. I don't know what to tell you, It's not really working for me, except if I use highcharts. Chartist is doing the same thing as chartjs where it renders it in the wrong location

**Comment by ConsoleTVs** [comment]
![image](https://user-images.githubusercontent.com/6124435/29330031-276de9f0-81f8-11e7-873a-143a1ca25647.png)

![image](https://user-images.githubusercontent.com/6124435/29330055-43bf7f92-81f8-11e7-888f-d92a2ac69764.png)


![image](https://user-images.githubusercontent.com/6124435/29330077-5659b190-81f8-11e7-98ab-4cf1b3b106f9.png)


Did you try my code? If that works the only thing I can think of is the fact that jquery should be loaded by my library rather than ur app.js file, or something on the app.js is causing problems...

But it's strange anyway. The sections seems well organized for me.

**Comment by JapSeyz** [comment]
I'll try your code, give me a sec

**Comment by JapSeyz** [comment]
It works, but if I remove the six vue lines, it'll do the wrong placing of the chart again.

**Comment by ConsoleTVs** [comment]
Wait, I found something. let me check.

**Comment by JapSeyz** [comment]
Alright, let me know when you have something

**Comment by JapSeyz** [comment]
Alright, I'll check it out

**Comment by JapSeyz** [comment]
@ConsoleTVs It works like a charm. Thanks a lot!

**Comment by ConsoleTVs** [comment]
Sorry for the issue. The split was done by another person, I had to modify it myself.

It's using my support library now. So expect a good response :D

**Comment by JapSeyz** [comment]
@ConsoleTVs That's perfect, it works like perfectly now. Fast and not blocking the entire page 👍 

I do have a single issue though, double-clicking on a chart turns the entire background on the chart blue. I cannot figure out which element it's coming from, would you know by chance?

**Comment by ConsoleTVs** [comment]
Is that supposed to happen? idk, seems like what it should do, it's a browser selection after all (double clicking something)

**Comment by ConsoleTVs** [comment]
As a personal suggeriment, chartjs is not a very good library compared to others used in this library, personal recomendation on material library / highcharts / google.

**Comment by JapSeyz** [comment]
@ConsoleTVs Ahh okay, thank you. I narrowed it down to being an issue with the background: inherit; on th canvas.

About the Google library. The code that worked flawlessly for ChartJS throws this error for Google:

```
jsapi_compiled_default_module.js:85 Uncaught (in promise) Error: Row 0 has 4 columns, but must have 3
```

The code to generate is like so:

```
 $chart = Charts::create($type, 'google')
                       ->title($title)
                       ->dimensions(0, 300)
                       ->template('material')
                       ->values($values->toArray())
                       ->labels($labels->toArray());
```

I honestly don't see how that's wrong?

**Comment by ConsoleTVs** [comment]
Can you provide me with some sample data rather than $values or $type?

I need to know everything without variables

**Comment by JapSeyz** [comment]
Yes, here you go, @ConsoleTVs:

```
array:4 [▼
  "type" => "bar"
  "title" => "Ticket earnings"
  "labels" => Collection {#473 ▼
    #items: array:2 [▼
      0 => "Unique Feest"
      1 => "Jordane Goodwin"
    ]
  }
  "values" => Collection {#539 ▼
    #items: array:2 [▼
      0 => "0,66"
      1 => "0,47"
    ]
  }
]
```

**Comment by ConsoleTVs** [comment]
Oh I already saw the error. A decimal point MUST be in a point separation for javascript (and php also). a , would break the code. so 0,66 must be 0.66 and the same for the 0,47 to 0.47.

It will then work:

![image](https://user-images.githubusercontent.com/6124435/29360961-a4b6d1a0-8285-11e7-8e80-42750686445b.png)


By the way, if you're using the create method, most charts support diferent bar colors, if you want the same color change your code from this:

```php
$chart = Charts::create('bar', 'google')
       ->title('Ticket earnings')
       ->dimensions(0, 300)
       ->values([0.66, 0.47])
       ->labels(['Unique Feest', 'Jordane Goodwin']);
```

to this:

```php
    $chart = Charts::multi('bar', 'google')
       ->title('Ticket earnings')
       ->dimensions(0, 300)
       ->dataset('Earning', [0.66, 0.47])
       ->labels(['Unique Feest', 'Jordane Goodwin']);
```

Result:

![image](https://user-images.githubusercontent.com/6124435/29361024-f2c916f0-8285-11e7-990c-c51bf1c633a7.png)

**Comment by JapSeyz** [comment]
Ah okay, just odd that it doesn't crash chartjs but they must have built in something to fix that. 
Thanks a lot for the help

**Comment by ConsoleTVs** [comment]
Well, google works with arrays, the , would swap to the next item instead.

So the rows won't match the columns.

The same for chartjs, I don't even know how did it work for you :D

**Comment by JapSeyz** [comment]
Me neither, and now that you say it, it makes a lot of sense. I was just not aware that it would parse it that way.

Perhaps there's some built in failsafe in chartjs, as I only switched out the library :p Thanks for pointing it out though!

**Comment by ConsoleTVs** [comment]
I just tried it. It does render a chart because it ignores further data; so lets say:

2 labels ['test', 'test2'];

4 values: [0, 66, 0, 47]

The chart will use test at 0 and test2 at 66 and ignore 0 and 47, while google will complain.

![image](https://user-images.githubusercontent.com/6124435/29361903-d5b46d22-8289-11e7-9f05-b9224f1425c1.png)

**Comment by JapSeyz** [comment]
Ah, that could also explain the weird element labels I've had.

Thanks for all the great help! 👍

**Comment by benmadh** [comment]
Hello Can I change canvas background color ?
