### ISSUE TITLE
Change c3 colors

### ISSUE THREAD

**Issue by timgithinji** [ConsoleTVs/Charts#223]
I'm trying to change colors for the C3 js pie chart but is not working. 

`  $finished_chart =   Charts::create('pie', 'c3')
  ->title('Students who have finished quiz')
  ->labels(['Finished', 'Not finished'])
  ->colors(['#2CC185', '#ff6b6b'])
  ->values([$finished_count,$not_finished_count])
  ->dimensions(1000,500)
  ->responsive(true);`

It is working with other libraries but not the c3 one.

**Comment by ConsoleTVs** [comment]
Currently not implemented, next release will have this, thanks!

**Comment by timgithinji** [comment]
Thanks! Will be massively appreciated.

**Comment by mohitlandge** [comment]
Is is available in version 5?
