### ISSUE TITLE
Chart to Image or PDF

### ISSUE THREAD

**Issue by jyyblue1987** [ConsoleTVs/Charts#224]
Thank you very much to your chart library.

I want to export chart graph based on your library to pdf or image.

I thank if you tell me how to resolve this issue.

Thanks&Regards.

**Comment by GiacomoK** [comment]
Same request here.

**Comment by ConsoleTVs** [comment]
Hello, this cannot be done, all libraries use Js to render the chart, some of them already got some export features such as highcharts.

There's no magic way to generate an image from a JS code unless the library itself supports it. I'm sorry but you'll need to see a solution online but I'm afraid is very unlikely to be done ^^

**Comment by twf-nikhila** [comment]
@jyyblue1987 @GiacomoK @ConsoleTVs: I was working on something similar, used another package - https://github.com/barryvdh/laravel-snappy with this package. Working truly Great.

**Comment by ConsoleTVs** [comment]
Does it read javascript? Can you provide me an example of a chart to pdf with this package? I will implement if if it works

**Comment by twf-nikhila** [comment]
@ConsoleTVs: The packages I shared reads HTML and convert them to PDF. So we can include Javascript with it.

It's simple, we can echo the chart and then give that view file to this package. I used it to include Charts in a PDF and it worked.

**Comment by Himashukla** [comment]
@twf-nikhila
 I'm doing exactly same as you told. but the chart is not adding in the pdf file.
if I return view from controller then chart is showing perfectly. 
but when i try to make pdf it is not working.

**Laravel Version:  5.8.35**

Packages Version
 **"barryvdh/laravel-snappy": "^0.4.5",
 "consoletvs/charts": "6.*",**

and I'm using chartjs as my default library
 **'default_library' => 'Chartjs',**

the output is something like this:

![image](https://user-images.githubusercontent.com/51231672/64471358-6bff1e00-d16e-11e9-8952-30aa1b9f313d.png)

**Comment by ConsoleTVs** [comment]
Due the way charts work on v6 this can't be done.

This fall i will make a new release v7 with a potential server side chart.
