### ISSUE TITLE
How to groupByMonth and data as sum of table column using charts::database

### ISSUE THREAD

**Issue by Hujjat** [ConsoleTVs/Charts#226]
Hi. 
Is there any way to groupByMonth at the same time display the chart data as the sum of the table column value. 

I have an orders table.

![calculate value](https://user-images.githubusercontent.com/5115878/27815800-e4a1d5f6-603b-11e7-9272-76da1983c7b6.PNG)

When I use Charts::database like this. 

`

        $montly_order_chart =  Charts::database(Order::all(), 'bar', 'chartjs')
                  ->responsive(true)
                  ->title("Monthly Orders")
                  ->dimensions(0, 400)
                  ->responsive(false)
                  ->elementLabel('Cloths')
                  ->groupByMonth(Date('Y'),true);

`
it just renders the 4 data per month. What I want is to use Charts::database and display data based on the sum of  ` quantity`  column. 

![calculate value](https://user-images.githubusercontent.com/5115878/27815800-e4a1d5f6-603b-11e7-9272-76da1983c7b6.PNG)

It most shows 17 on the chart view. 
Is it Possible to do with Charts::database or not. 

Thank's

**Comment by ConsoleTVs** [comment]
Hello, you'll need to build your values array and labels and build the chart with the create method, the database is not that complex to do this things yet. Sorry!
