### ISSUE TITLE
groupBy integer range ?

### ISSUE THREAD

**Issue by vesper8** [ConsoleTVs/Charts#231]
I have a table containing the age of all my participants. I would like to display this in a pie chart, but rather than have a pie chart with 50+ ages. I would like to aggregate these into "age groups"

so I would like to have a group 18 and under, 18-25, 26-34, 34-42, 42 and up

Is there a way to achieve this using the groupBy?

**Comment by ConsoleTVs** [comment]
There's no way to do this using the built in database helper, the only solution is to use the "create" method. (Like I mentioned in your other issue) and build the data yourself.

Simply create a few querys and select the users within that range:

$group1 = User::where('age', '<' 25)->count();
$group2 = User::where([['age', '>', 25], ['age', '<', 34]])->count();

And so on.

Once you have all the groups you can then create an array with the values.

$values = [$group1, $group2, ...];

Attach the labels:

$labels = ['between 18 and 25', 'Between 26 and 34', ...];

And create the chart using the create method.
