### ISSUE TITLE
geo chart from database?

### ISSUE THREAD

**Issue by vesper8** [ConsoleTVs/Charts#232]
I have a table that contains these columns:

iso (2 letter country code)
name (Capitalized english country name)
users (integer containing number of users in each country)

I would like to use the awesome geo chart from this database table

I suppose I could have hacked it and plucked the iso codes, set up a function to randomly generator a color for each country, and plucked the user counts and feed all that to the example method:

```
Charts::create('geo', 'highcharts')
    ->title('My nice chart')
    ->elementLabel('My nice label')
    ->labels(['ES', 'FR', 'RU'])
    ->colors(['#C5CAE9', '#283593'])
    ->values([5,10,20])
    ->dimensions(1000,500)
    ->responsive(false);
```

However I would have preferred to use the database method directly instead.. is that possible? How do I set the label and values if using the database?

**Comment by ConsoleTVs** [comment]
Again, I'm sorry to dissapoint you but the database usage is limited. Mostly used for time calculations from past items. Complex querys have to be done with the typical create method :p

**Comment by vesper8** [comment]
Thanks a lot for your answers! Solved all 3 of my problems thanks to your explanations!

**Comment by ConsoleTVs** [comment]
You're welcome, please feel free to close the issues then ^^
