### ISSUE TITLE
export chart as image (png)

### ISSUE THREAD

**Issue by adrian-cmd** [ConsoleTVs/Charts#239]
is it possible to export rendered charts as image?

**Comment by lubehrens** [comment]
@adrian-cmd Did you figure out how to do it? I'm trying to do the same but without success until now.

**Comment by ConsoleTVs** [comment]
There are 2 libraries that support this as export option. Nevertheless, the other way would be printing a PDF out of the website.

**Comment by dfuentes141** [comment]
What libraries  use to export chart as image?
