### ISSUE TITLE
syntax error, unexpected ':', expecting ';' or '{' from vendor

### ISSUE THREAD

**Issue by AxelCardinaels** [ConsoleTVs/Charts#240]
Hi ! 

When i try to use my chart (pretty basic example from the doc) in my view, I have this error : 

FatalErrorException in /home/go4padel/staging/releases/20170823155730/vendor/consoletvs/support/Traits/Utilities.php line 16:
syntax error, unexpected ':', expecting ';' or '{'

No problem when I create the new Chart in my controller, this happens when i Had those lines to my app : 

{!! Charts::styles() !!} (in my <Head>)
{!! $chart->html() !!} (in content)
{!! Charts::scripts() !!} (at the end of my body)
{!! $chart->script() !!} (same as above)

Any idea ? Thanks!

**Comment by ConsoleTVs** [comment]
Php version? 7++ is required.

**Comment by AxelCardinaels** [comment]
Oh that's why! Thanks for the answer !

**Comment by ConsoleTVs** [comment]
Composer should have warned you about it :/

**Comment by AxelCardinaels** [comment]
I guess that COmposer probably checked my local version of PHP (7+), but our server is 5.6 so that's were the problem is :)

**Comment by ConsoleTVs** [comment]
Yes indeed, laravel 5.5 will be php 7 so i upgraded as well :3

**Comment by AxelCardinaels** [comment]
No worries ! But thanks for the answer ! 👍

**Comment by JaxTerra** [comment]
Thanks you ConsoleTVs, you just saved my ass big time!!!!!
