### ISSUE TITLE
Error in dynamic bar

### ISSUE THREAD

**Issue by pablolp95** [ConsoleTVs/Charts#244]
Hi, I'm using Charts v4 and when I use more of 4 labels,the following erro appears:
```Symfony\Component\Debug\Exception\FatalErrorException: Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Undefined offset: 3 (View: /var/www/html/tfg/vendor/consoletvs/charts/resources/views/material/multi/bar.blade.php)```
The code I'm using is:
```$chart = Charts::multi('bar', 'material')
// Setup the chart settings
->title("My Cool Chart")
// A dimension of 0 means it will take 100% of the space
// This defines a preset of colors already done:)
->template("material")
// You could always set them manually
// ->colors(['#2196F3', '#F44336', '#FFC107'])
// Setup the diferent datasets (this is a multi chart)
// Setup what the values mean
->labels(['One', 'Two', 'Three','Four'])
->responsive(true);
$chart->dataset('Element 1', [5,20,100]);
$chart->dataset('Element 2', [15,30,80]);
$chart->dataset('Element 3', [25,10,40]);
$chart->dataset('Element 4', [25,10,40]);```

If I delete one of the labels it works. Thanks.

**Comment by ConsoleTVs** [comment]
Why are you using a create:: function and a multi:: function? Either choose of it. Dataset is for multi. Labels is for create

**Comment by pablolp95** [comment]
Sorry,I have not noticed that the code is wrong. If I put the following code its give me the same error:
```
$chart = Charts::multi('bar', 'material')
    ->responsive(false)
    ->dimensions(0, 500)
    ->colors(['#ff0000', '#00ff00', '#0000ff','#0000ff'])
    ->labels(['One', 'Two', 'Three','Four'])
    ->dataset('Test 1', [1,2,3])
    ->dataset('Test 2', [0,6,0])
    ->dataset('Test 3', [3,4,1])
    ->dataset('Test 3', [3,4,1]);

**Comment by ConsoleTVs** [comment]
If you have 4 labels and 3 values ofc course it's going to break.

You either add 1 value to all datasets or remove 1 label. The number of labels and values (in this case of each dataset) must match.

**Comment by pablolp95** [comment]
Oh sorry! Too many hours working. Thanks for all.

**Comment by ConsoleTVs** [comment]
You're welcome :)
