### ISSUE TITLE
array_key_exists() expects parameter 2 to be array, null given

### ISSUE THREAD

**Issue by V1TA5** [ConsoleTVs/Charts#245]
Im getting this Error after trying your Example:

```
array_key_exists() expects parameter 2 to be array, null given
--
in Chart.php (line 146)
at HandleExceptions->handleError(2,  'array_key_exists() expects parameter 2 to be array, null given',  '/var/www/lablicate/labweb/vendor/consoletvs/charts/src/Builder/Chart.php',  146, array('l' => 'Three', 'templates' => null, 'this' => object(Multi)))
at array_key_exists('material', null)in Chart.php (line 146)
at Chart->render()in Chart.php (line 257)
at Chart->split()in Chart.php (line 243)
at Chart->html()in 4a7192505348570de78001eca18054c70f9c17b5.php (line 20)
```

It obviously requires a third param but no exmaple mentions one.

The Call is:
`$data["txchart"] = Charts::multi('bar', 'material')
            // Setup the chart settings
            ->title("My Cool Chart")
            // A dimension of 0 means it will take 100% of the space
            ->dimensions(0, 400) // Width x Height
            // This defines a preset of colors already done:)
            ->template("material")
            // You could always set them manually
            // ->colors(['#2196F3', '#F44336', '#FFC107'])
            // Setup the diferent datasets (this is a multi chart)
            ->dataset('Element 1', [5,20,100])
            ->dataset('Element 2', [15,30,80])
            ->dataset('Element 3', [25,10,40])
            // Setup what the values mean
            ->labels(['One', 'Two', 'Three']);`

Here are my Versions:
"components/font-awesome": "^4.7",
        "components/jquery": "^3.2",
        "consoletvs/charts": "^5.1",
        "datatables/datatables": "^1.10",
        "php": "7.0",
"laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "laravelcollective/html": "^5.4",
        "rogeriopradoj/respond": "^1.4",
        "twbs/bootstrap": "^3.3",

**Comment by ConsoleTVs** [comment]
Excuse me, the 2nd parameter comes from the config file. You have a wrong config file:

https://github.com/ConsoleTVs/Charts/blob/master/src/Builder/Chart.php#L145-L146

**Comment by V1TA5** [comment]
Thank you for your reply. Ill check that out as soon as i can.
