### ISSUE TITLE
How to show export button

### ISSUE THREAD

**Issue by ommyan** [ConsoleTVs/Charts#246]
Dear Erik,

just ask to you, how to show export button in chart? by default export button doesn't appear
thanks

**Comment by ConsoleTVs** [comment]
This is currently an unknown issue. The export only works with highcharts when a certain JS is imported. As Far as I know it's this one: https://github.com/ConsoleTVs/Charts/blob/master/config/charts.php#L123

But it seems it's not working...

**Comment by ommyan** [comment]
i had included JS imported in config/charts, but still not working

**Comment by shadonet** [comment]
You have just add this JS file [ 'https://cdnjs.cloudflare.com/ajax/libs/highcharts/5.0.7/js/modules/exporting.js',](url) before offline exporting file.
And if you would like to have "export in csv and xls format", just add this one also [http://highcharts.github.io/export-csv/export-csv.js](url)

**Comment by ConsoleTVs** [comment]
Charts 6 will help you out, few export() presets present.

**Comment by ommyan** [comment]
thanks eric
