### ISSUE TITLE
Suggested Charting Lib

### ISSUE THREAD

**Issue by V1TA5** [ConsoleTVs/Charts#247]
Hi,
is there any Charting lib your wrapper supports, that you would recomend.
(Maybe because you designed this with it in mind)
My use case requires me to have everything needed on my host, so it works without internet access.

I looked at echarts because it seems to be downloadable and the most flexible (as in different chart types).

**Comment by ConsoleTVs** [comment]
Any library you like may be used and downloaded offline. perhaps highcharts is the most advanced and bug-free from my experience. Keep in mind you'll need to point the library to the offline direction rather than the cdn. This may be done in the config file :)

**Comment by V1TA5** [comment]
Thank you for your suggestion i will take a look at highcharts. Regarding offline usage: At least Google doesnt offer any downloads for their charting.

**Comment by ConsoleTVs** [comment]
True, google does not offer offline usage.
