### ISSUE TITLE
Can't install. 

### ISSUE THREAD

**Issue by tisuchi** [ConsoleTVs/Charts#248]
I am having issue during install. The problem is in following image-

![screen shot 2017-09-20 at 12 02 22 pm](https://user-images.githubusercontent.com/2137978/30626303-7370e6bc-9dfb-11e7-9181-a6852731f603.png)

I am using Laravel 5.2 version.

**Comment by ConsoleTVs** [comment]
This is not a charts issue. You just don't meet the requirements for this charts version. It required php 7 and everything listed there. You probably have some bad version already installed.

**Comment by tisuchi** [comment]
I see... Thanks man.

**Comment by tisuchi** [comment]
Thanks man.
