### ISSUE TITLE
FatalErrorException

### ISSUE THREAD

**Issue by JBoku8** [ConsoleTVs/Charts#25]
I get this error.
FatalErrorException in ChartController.php line 15:
syntax error, unexpected 'new' (T_NEW)
I've followed installation instructions as it is written but it throws exception.

How i can solve this problem ?

**Comment by ConsoleTVs** [comment]
I think you don't have php 7.0.8 or +, check it out!

**Comment by JBoku8** [comment]
thanks, it was php version problem

**Comment by ConsoleTVs** [comment]
You're welcome! Will be fixed soon!
