### ISSUE TITLE
Ampersands in url

### ISSUE THREAD

**Issue by aqldotcom** [ConsoleTVs/Charts#250]
We have parameters in our urls for realtime graph data and the view is encoding them to &amp;amp;

Can the below line be amended to {!! !!}, this probably applies to other views also.

https://github.com/ConsoleTVs/Charts/blob/569ab9179e0d141be9101e910b40c3b94cb12a3a/resources/views/highcharts/realtime/bar.blade.php#L64

Thanks

**Comment by ConsoleTVs** [comment]
Yes, will be reviewing that

**Comment by ConsoleTVs** [comment]
Done.
