### ISSUE TITLE
low_warning error

### ISSUE THREAD

**Issue by tpharaoh** [ConsoleTVs/Charts#251]
Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Undefined variable: low_warning (View: path/resources/views/vendor/charts/google/realtime/gauge.blade.php)

I am using the realtime guage, and the URL is returning {"value":"20"}  and {"value":"20,99"}

**Comment by ConsoleTVs** [comment]
{"value":"20,99"} is not a correct value.

{"value":"20.99"} this is a correct value.

**Comment by tpharaoh** [comment]
Note above, I also tested with this {"value":"20"} 

Perhaps there is a conflict with another file? 

Thanks for feedback

**Comment by ConsoleTVs** [comment]
Oh excuse me, does the integer fail as well? I'll perhaps look at it later.

**Comment by tpharaoh** [comment]
Yes. Even integer fails. Thanks. Anything I can do to help debug let me
know.

My page using vue if it makes a diff.

**Comment by ConsoleTVs** [comment]
Good, so the google gauge might have a problem tho ?

**Comment by tpharaoh** [comment]
Sorry for pre-maturely closing.
canvas-gauges and google are a problem for gauge. It works with justgage

**Comment by ConsoleTVs** [comment]
Let me tag this then, could you provide me the full code that did not work ? (with . or integers) please?

**Comment by tpharaoh** [comment]
$url='http://mydashboard.dev/getReport/FFFFFF-GS3-1345311109371/';
//returns {"value":"20.99"}
      $charts[]=Charts::realtime(url($url),5000,'gauge', 'justgage') // justgage works, google and canvas-gauges returns the above error
        ->title('signal strength')
        ->elementLabel('%')
        ->values([0,0,30])
        ->responsive(false)
        ->height(300)
        ->width(0);

**Comment by tpharaoh** [comment]
Tested each one FYI
canvas-gauges: low warning error
justgage : works
highcharts: works
google: low warning error
progressbarjs: works

**Comment by ConsoleTVs** [comment]
Yes, I testes them all today... Will see what I can do :)

**Comment by tpharaoh** [comment]
curious how your tests went...

**Comment by ConsoleTVs** [comment]
Yes, I noticed the errors and I know why they happen. I will fix it soon, sorry for the late response, I'm very busy :)

**Comment by tpharaoh** [comment]
Much respect Erik.... thank you for amazing work

**Comment by ConsoleTVs** [comment]
Charts 6 is out. This is no longer present.
