### ISSUE TITLE
syntax error, unexpected ':', expecting ';' or '{' in Utilities.php (line 16)

### ISSUE THREAD

**Issue by Yosef7908** [ConsoleTVs/Charts#252]
I'm running PHP version 7.0.23 and I'm still getting this error any thoughts?
syntax error, unexpected ':', expecting ';' or '{' in Utilities.php (line 16)

Thanks

**Comment by ConsoleTVs** [comment]
Charts version ?

**Comment by Yosef7908** [comment]
Sorry I didn't see your reply I got it working :)
