### ISSUE TITLE
question: running total of users per month

### ISSUE THREAD

**Issue by illuminate3** [ConsoleTVs/Charts#253]
I tried this:

`        $data = User::select('users.created_at', DB::raw('count(users.id) as aggregate'))->groupBy(DB::raw('Date(users.created_at)'))->get();
        $user_total = Charts::database($data, 'line', 'chartjs')
            ->preaggregated(true)
            ->title('Users')
            ->elementLabel("Total")
            ->lastByMonth(6, true);
        $user_total->aggregateColumn('aggregate', 'sum');
`

But all I am getting is a basic number of users created for the month. How would I show a line chart that shows the line going upward because every month more users have been added?

Thanks!

Also, thank you for a nice! package.

**Comment by ConsoleTVs** [comment]
Hello, I never worked with querys. I ALWAYS use eloquent to select that things.

Why not this?

```
$users = User::all()->sortBy('created_at');
Charts::database($users, 'line', 'chartjs')->lastByMonth(6, true);
$user_total = $users->count();
```

**Comment by illuminate3** [comment]
Thanks, I'll try that.
