### ISSUE TITLE
question: How to show only integer values on yAxis of HighChart?

### ISSUE THREAD

**Issue by ddthanhdat** [ConsoleTVs/Charts#254]
We have a set of a data that contains counts of instances of events. These can only be integers. When we display data that has a high enough yValue the yAxis labels are integers. However, when we zoom in to ranges of data that have under y = 5 we see the tick markers show things like 0.5, 0.75, 1.5, etc. How can we force the yAxis labels to only show integer values?

**Comment by ConsoleTVs** [comment]
This is perhaps something done by the library, what JS library did u choose? what version of Charts are you using ? Can you paste an example code (with sample values rather than DB querys)

**Comment by ConsoleTVs** [comment]
Charts 6 may help you out configuring it out!
