### ISSUE TITLE
[FEATURE] Just a question, can this do server-side rendering?

### ISSUE THREAD

**Issue by ghost** [ConsoleTVs/Charts#256]
It appears all of the chart libraries are client-side based, I need server-side based rendering for mass email functionality.  Can this do that?
thanks

**Comment by ConsoleTVs** [comment]
I will perhaps implement this in a near future, any server side charting library you might like?

**Comment by j88per** [comment]
No favorites, I'm looking at using jpgraph now, trying to port it into laravel (ugh), but like everyone else, I've kinda left the server-side rendering world.

**Comment by ConsoleTVs** [comment]
Well, i wont tell u 100% that I will do this in this library since the working method is diferent, but I can look it it if im bored some day, thanks

**Comment by j88per** [comment]
yeah, not high expectations, but worth the question.  Thanks

**Comment by vesper8** [comment]
If what you want to do is generate a graph and then include it in outgoing emails.. then wouldn't it make more sense to generate the graphs normally, then programatically grab a screenshot of the graph and include that in your emails?

**Comment by j88per** [comment]
That's the right idea, but screenshot isn't the right term or phrase.  Server side rendered charts were usually drawings done in a drawing library like GD, GD2, or Image Magick and rendered/exported as jpg/png files, either to the filesystem or as a string in a variable.  Then you can use either the image file name or base64 encoded string as an html image source attribute.

**Comment by davidjr82** [comment]
@j88per what maybe is telling @vesper8 is to use something like https://github.com/spatie/browsershot show you can make a controller that renders just the image of the graph that you want, take a "screenshot" with that package, saving it to disk, and after that, attach it to your email. May be that would work for you?

**Comment by j88per** [comment]
That's the problem, none of the chart libraries do server side rendering anymore to generate said image.  It's all client side.  With email clients stripping div tags and blocking js, it's harder and harder to create an informative and interactive email.  Since I have 8000 email addresses, and between 6-8 charts per email, it's easily 64k images and that's a huge load to put on a tiny server.  
Realistically, I'd prefer to send a short email, with basic content and a link to a SPA page that would be more informative and better capable, but the client seems to ignore my pleas.  
I was just hoping that this author/library might offer a server side rendered flag/feature.  It was a wild hope more than an expectation.

**Comment by ConsoleTVs** [comment]
I marked it as an feature. Ao in fact it will probably support it soon with 6.X.

**Comment by tpharaoh** [comment]
Would this method work well when using a VueJS front with API backend style resources?
Is there another preferred method?

**Comment by tpharaoh** [comment]
My apologies, I think I wrote too fast, looks like the idea solution is the API rendering in your docs

**Comment by ConsoleTVs** [comment]
Well, if you're using vue, why not use a vue library to render charts? :D

**Comment by bokideckonja** [comment]
Looking forward to this feature.

**Comment by tpharaoh** [comment]
Erik was right.

It was easy in vue directly

**Comment by ConsoleTVs** [comment]
This package aims to be a multi-library charting package, but in production you just probably need 1 of them, so yeah, using a single libray with a vue wrapper rather than using this package will probably speed it up :)
