### ISSUE TITLE
Is dataset array working?

### ISSUE THREAD

**Issue by krakenlabat** [ConsoleTVs/Charts#259]
So i have an array of values here from database

This is the code:
```
$result = DB::table('produtcs')->where('name','=','John')
        ->get( array(
            DB::raw( 'SUM(Eggs) AS Eggs' ),
            DB::raw( 'SUM(Soda) AS Soda' ),
            DB::raw( 'SUM(Biscuit) AS Biscuit')
        ));
```
And it returns this value:
`[{"Eggs":4,"Soda":2,"Biscuit":1}]`

Here is the chart code:
```
$chart = Charts::multi('bar', 'highcharts')
        ->title("Users")
            ->dimensions(0, 800) // Width x Height
            ->template("material")
            ->dataset('John', [$result])
            ->labels(['Eggs','Soda','Biscuit']);
            return view('chart', ['chart' => $chart]);
```

Apparently is does not error, but it does not render the bar graph? I'm i doing the right thing putting the $result in the dataset?

**Comment by ConsoleTVs** [comment]
Does it render the example in the docs?

**Comment by krakenlabat** [comment]
Yes it completely renders when I put static values
`->dataset('John', [4,2,1])`

**Comment by ConsoleTVs** [comment]
Then you're getting the wrong values :), I use eloquent everyday, so I have no idea how to use the DB facade

**Comment by krakenlabat** [comment]
How's that?. I want to use eloquent too, can you please share some oh how to pass data to dataset using eloquent?

**Comment by krakenlabat** [comment]
I really wanna use your charts on my project, so simple and i like it's nice feature than other chartings  :)

**Comment by Acurex** [comment]
Hello krakenlabat,

i answered to another issue #258 of yours.

Check your $result. It is an Key-Value-Array. The dataset-command just expects an Array of values.

**Comment by ConsoleTVs** [comment]
Seems fixe. thanks for the reference @Acurex

**Comment by krakenlabat** [comment]
@Acurex wow! Thank God you are there yes it work just want i want it. And thank you very much for explaining it, I'm having trouble learning laravel because I don't really have that much background in PHP, I just crash coursed learning laravel because the management wants it.

Yes the dataset-command expects an array of values, but having trouble dissecting them.

Can you please tell me where did you get `->selectRaw`, can't find it in Laravel docs. 

Once again thank you bro, you just saved me. Hope I can give you h5
