### ISSUE TITLE
Accesing the chart update url

### ISSUE THREAD

**Issue by riksnelders** [ConsoleTVs/Charts#260]
Is there anyway to access the update URL for realtime charts?

I want to filter out daterange on front end without page reload

**Comment by ConsoleTVs** [comment]
$chart->url

**Comment by riksnelders** [comment]
Yes thats accesing the url.. How to set it tho and rerender chart..?

**Comment by ConsoleTVs** [comment]
U can access the chart JS variable with $chart->id. From here u will need to push the values readingthe official ja library docs. Depending on the chosen library
