### ISSUE TITLE
How to display 2 compare chart by month

### ISSUE THREAD

**Issue by linkoffz** [ConsoleTVs/Charts#265]
How do i make a graph like this picture with data from database? x_axis is sort by date and y_axis is sort by total transaction..
![image](https://user-images.githubusercontent.com/32723850/31530218-196ca7e4-b009-11e7-9929-dea26521840a.png)

**Comment by ConsoleTVs** [comment]
Use the multi chart (without database) . Get both arrays with length = 31 (days) and containing each value.

When both arrays are set. create the labels dataset containing the days (1,2,3...) and create the 2 datasets in the chart.

**Comment by linkoffz** [comment]
I'll try that. BTW,,, You've done a great job with this package.. Thanks a lot @ConsoleTVs

**Comment by ConsoleTVs** [comment]
You're welcome :)
