### ISSUE TITLE
Any future updates for stockcharts?

### ISSUE THREAD

**Issue by filtration** [ConsoleTVs/Charts#266]
highcharts has some nice stock charts that shouldn't be too hard to implement? any new charts you're working on?

**Comment by ConsoleTVs** [comment]
I doublt I will do this, mainly because it is only available in 1-2 libraries out of the +15 this library supports.

**Comment by ConsoleTVs** [comment]
Perhaps soon in charts 6, we will see :)

**Comment by ConsoleTVs** [comment]
Meanwhile you may use sockets with the chart variable:

```
window.{{ $chart->id }}
```

You can acces it and change/add/delete data respecting the charting library.
