### ISSUE TITLE
How to display chart with data only for a chosen id ?

### ISSUE THREAD

**Issue by litrs** [ConsoleTVs/Charts#267]
Hi, this is setup: 

public function show($id)
    {
        $data = Data::find($id);
        $chart = Charts::database(Ratios::all(), 'bar', 'highcharts')
                                                            ->groupBy('curr_ratio');

        return view('datas.show', ['chart' => $chart])->with('data', $data);
    }
Chart shows all the data from the whole mysql(Ratios) column named 'curr_ratio'. However I would like to display chart with data for specific id.  

Thanks!

**Comment by litrs** [comment]
Ok, i found solution.

Now it looks like this:

  public function show($id)
    {
        $data = Data::find($id);
        //Added a where clause to filter through all the ratios ans pick the ones matching the data table rows
        $datax = Ratios::all()->where('data_id', $id);
         $chart = Charts::create('line', 'highcharts')
        ->values($datax->pluck('curr_ratio'));
 
        return view('datas.show', ['chart' => $chart])->with('data', $data);
    }

**Comment by ConsoleTVs** [comment]
That's one example :)

**Comment by umair104** [comment]
@ConsoleTVs  in upper example how i can use  multiple values... i want to make multi line chart
