### ISSUE TITLE
Installation consoletvs/charts

### ISSUE THREAD

**Issue by Amaarys** [ConsoleTVs/Charts#269]
Hello, 

I have some issues with my chart installation.

> c:\wamp\www\my-site\aspro.dev>composer require consoletvs/charts
Using version ^5.1 for consoletvs/charts
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - consoletvs/charts 5.1.0 requires consoletvs/support ^2.1.2 -> satisfiable by consoletvs/support[2.1.2, 2.2.0, 2.2.1, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4].
    - consoletvs/charts 5.1.1 requires consoletvs/support ^2.1.2 -> satisfiable by consoletvs/support[2.1.2, 2.2.0, 2.2.1, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4].
    - consoletvs/charts 5.4.0 requires php >=7.0.0 -> your PHP version (5.6.16) does not satisfy that requirement.
    - consoletvs/charts 5.3.1 requires php >=7.0.0 -> your PHP version (5.6.16) does not satisfy that requirement.
    - consoletvs/charts 5.3.0 requires php >=7.0.0 -> your PHP version (5.6.16) does not satisfy that requirement.
    - consoletvs/charts 5.2.2 requires php >=7.0.0 -> your PHP version (5.6.16) does not satisfy that requirement.
    - consoletvs/charts 5.2.1 requires php >=7.0.0 -> your PHP version (5.6.16) does not satisfy that requirement.
    - consoletvs/charts 5.2.0 requires php >=7.0.0 -> your PHP version (5.6.16) does not satisfy that requirement.
    - consoletvs/charts 5.1.3 requires php >=7.0.0 -> your PHP version (5.6.16) does not satisfy that requirement.
    - consoletvs/charts 5.1.2 requires php >=7.0.0 -> your PHP version (5.6.16) does not satisfy that requirement.
    - consoletvs/support 2.3.4 requires php >=7.0 -> your PHP version (5.6.16) does not satisfy that requirement.
    - consoletvs/support 2.3.3 requires php >=7.0 -> your PHP version (5.6.16) does not satisfy that requirement.
    - consoletvs/support 2.3.2 requires php >=7.0 -> your PHP version (5.6.16) does not satisfy that requirement.
    - consoletvs/support 2.3.1 requires php >=7.0 -> your PHP version (5.6.16) does not satisfy that requirement.
    - consoletvs/support 2.3.0 requires php >=7.0 -> your PHP version (5.6.16) does not satisfy that requirement.
    - consoletvs/support 2.2.1 requires php >=7.0 -> your PHP version (5.6.16) does not satisfy that requirement.
    - consoletvs/support 2.2.0 requires php >=7.0 -> your PHP version (5.6.16) does not satisfy that requirement.
    - consoletvs/support 2.1.2 requires php >=7.0 -> your PHP version (5.6.16) does not satisfy that requirement.
    - Installation request for consoletvs/charts ^5.1 -> satisfiable by consoletvs/charts[5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.3.1, 5.4.0].
Installation failed, reverting ./composer.json to its original content.

Please I need a help

**Comment by ConsoleTVs** [comment]
Charts require php 7

**Comment by Amaarys** [comment]
I update my php version to php7 but i have always somes issues.

> c:\wamp\www\my-site\aspro.dev>composer require consoletvs/charts:5.1
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Conclusion: remove laravel/framework 5.2.41
    - elibyy/laravel-tcpdf v0.0.1 requires illuminate/support 5.0.x -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
    - elibyy/laravel-tcpdf v0.0.2 requires illuminate/support 5.1.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - elibyy/laravel-tcpdf v0.0.3 requires illuminate/support 5.1.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - elibyy/laravel-tcpdf v0.0.4 requires illuminate/support 5.1.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - elibyy/laravel-tcpdf v0.0.5 requires illuminate/support 5.1.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - elibyy/laravel-tcpdf v0.0.6 requires illuminate/support 5.1.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - don't install illuminate/support v5.0.0|don't install laravel/framework 5.2.41
    - don't install illuminate/support v5.0.22|don't install laravel/framework 5.2.41
    - don't install illuminate/support v5.0.25|don't install laravel/framework 5.2.41
    - don't install illuminate/support v5.0.26|don't install laravel/framework 5.2.41
    - don't install illuminate/support v5.0.28|don't install laravel/framework 5.2.41
    - don't install illuminate/support v5.0.33|don't install laravel/framework 5.2.41
    - don't install illuminate/support v5.0.4|don't install laravel/framework 5.2.41
    - don't install illuminate/support v5.1.1|don't install laravel/framework 5.2.41
    - don't install illuminate/support v5.1.13|don't install laravel/framework 5.2.41
    - don't install illuminate/support v5.1.16|don't install laravel/framework 5.2.41
    - don't install illuminate/support v5.1.2|don't install laravel/framework 5.2.41
    - don't install illuminate/support v5.1.20|don't install laravel/framework 5.2.41
    - don't install illuminate/support v5.1.22|don't install laravel/framework 5.2.41
    - don't install illuminate/support v5.1.25|don't install laravel/framework 5.2.41
    - don't install illuminate/support v5.1.28|don't install laravel/framework 5.2.41
    - don't install illuminate/support v5.1.30|don't install laravel/framework 5.2.41
    - don't install illuminate/support v5.1.31|don't install laravel/framework 5.2.41
    - don't install illuminate/support v5.1.41|don't install laravel/framework 5.2.41
    - don't install illuminate/support v5.1.6|don't install laravel/framework 5.2.41
    - don't install illuminate/support v5.1.8|don't install laravel/framework 5.2.41
    - Installation request for laravel/framework (installed at 5.2.41, required as 5.2.*) -> satisfiable by laravel/framework[5.2.41].
    - Installation request for elibyy/laravel-tcpdf 0.* -> satisfiable by elibyy/laravel-tcpdf[v0.0.1, v0.0.2, v0.0.3, v0.0.4, v0.0.5, v0.0.6].
Installation failed, reverting ./composer.json to its original content.

**Comment by ConsoleTVs** [comment]
elibyy/laravel-tcpdf 0 this package is conflicting, it's not mine nor from the official laravel. This is an issue releated to another package. Cheers :)

**Comment by Amaarys** [comment]
Yes. I saw it. I removed elibyy/laravel-tcpdf and everything goes fine.

Thanks a lot.
