### ISSUE TITLE
Question: How to make all js source work offline?

### ISSUE THREAD

**Issue by anestan** [ConsoleTVs/Charts#270]
How to make js URL in `config/charts.php` to resources url?
I want make charts work offline. I am developing intranet application.

I want use chartjs & highcharts.

Thanks in advance.

**Comment by ConsoleTVs** [comment]
Just include the highcharts CSS / JS as if it was used as normal. Don't use the charts library to import it.

**Comment by tpharaoh** [comment]
So, if the JS/CSS were saved in sources, I could even use this in an app,
where Laravel sends the HTML of the chart as a response?
Maybe would not work as realtime though?

**Comment by anestan** [comment]
I've ended getting url using .env

```
'chartjs' => [
   'scripts' => [
      env('APP_URL') . '/js/chart.min.js' ,
   ],
],
```

anyway, thanks for this awesome chart package 👍

**Comment by ConsoleTVs** [comment]
Yes but this won't work if the app is hosted on a sub folder :)

**Comment by anestan** [comment]
Ok noted. 

Thanks
