### ISSUE TITLE
Real-time charts with websockets / Laravel Echo?

### ISSUE THREAD

**Issue by COLABORATI** [ConsoleTVs/Charts#271]
It looks like the current "realtime" implementation is just pulling a json from server every x milliseconds - it would be great to have this more close to what might be called "realtime" by using websockets.

**Comment by ConsoleTVs** [comment]
Yes. I would kindly accept any PR :)

**Comment by COLABORATI** [comment]
you should not use the word "realtime" when it is just polling - it is misleading.

**Comment by ConsoleTVs** [comment]
Charts 6 gives you the chart variable as:

```
window.{{ $chart->id }}
```

You may use it to change it's values with laravel echo.
