### ISSUE TITLE
Two charts in a same page

### ISSUE THREAD

**Issue by Amaarys** [ConsoleTVs/Charts#273]
Hello, 

How can i get two or more charts in a single page ?

**Comment by tpharaoh** [comment]
Loop the chart variable, and JavaScript if needed in your blade.

**Comment by ConsoleTVs** [comment]
There is no issue by creating multiple charts...

**Comment by tpharaoh** [comment]
@amaarys

Here is a sample from my code:
Controller
      $charts[]=Charts::realtime(url($url),1000,gauge, 'justgage')
      ->title($value->parameter->title.' ('.$value->device->name.')')
      ->elementLabel($value->parameter->unit)
      ->values([0,0,$value->parameter->max_value])
      ->responsive(false)
      ->height(200)
      ->width(0);
return view('home',['charts'=>$charts,'links'=>$links]);

View:
@foreach($charts as $key=> $chart)
  <div class="col-md-4" align="center">

    {!!$chart->html()!!}

  </div>
@endforeach

@foreach($charts as $chart)
  {!!$chart->script()!!}
@endforeach

**Comment by Amaarys** [comment]
@tpharaoh
I'm going to test this. Thanks a lot.

I will let you know

**Comment by ConsoleTVs** [comment]
I assume this worked for you. Cheers!
