### ISSUE TITLE
missing labels, how to default off

### ISSUE THREAD

**Issue by interludic** [ConsoleTVs/Charts#275]
Hey mate, thanks for the awesome work your doing.

After updating i no longer have labels where they once were, they are just gone?
![image](https://user-images.githubusercontent.com/6327261/32208103-7056493a-be54-11e7-9c5f-972b955a680f.png)

here is where i was suprised to find them missing
![image](https://user-images.githubusercontent.com/6327261/32208120-90ca8e42-be54-11e7-83d8-ce3d186067b0.png)

What am i doing wrong here?

**Comment by ConsoleTVs** [comment]
I've deleted it long ago since it was just on the area one. You can still modify the template to add it back :). I need to re-do a lot of things in this library. This new year there will be a major release

**Comment by ConsoleTVs** [comment]
You may now do this in charts 6.
