### ISSUE TITLE
Stacked Column Type on highcharts

### ISSUE THREAD

**Issue by Freizello** [ConsoleTVs/Charts#276]
Hi Erik, thank you for helping my project with this awesome charting library.

if you can add new type for Stacked Column specially for Highcharts. It would be great.
Demo : [https://www.highcharts.com/demo/column-stacked](url)

or, do you have alternative way to show stacked column with your chart?
Please guide me 😄 

Thank you, have a nice day

**Comment by ConsoleTVs** [comment]
This is not supported andwon't be. This is not a highcharts library, in fact, the features charts supports are mostly on all the libraries we have, so as you might understand, strange charts (out ofthe commons) are not supported. I'm really sorry for this but you'll need to build it manually or use a template for the library yourself. Cheers!
