### ISSUE TITLE
Uncaught TypeError when starting (first) data array is null

### ISSUE THREAD

**Issue by Freizello** [ConsoleTVs/Charts#277]
Hi Erik, Sorry if i looks like spamming your issues section 🙏 

i have a problem with highcharts line chart. i have an array data started with null. 
I expecting my chart will be look like this (null in first 3 month) : 

![image](https://user-images.githubusercontent.com/12061206/32360418-27abee02-c088-11e7-8e55-e07833aa4a1c.png)
http://jsfiddle.net/wo2jyL7r/

May you tell me what i missed? is it a bug? 

**Here is my code:**  
![image](https://user-images.githubusercontent.com/12061206/32360348-8ec94090-c087-11e7-815d-ecc2eff13944.png)

**Here the chart view :** 
![image](https://user-images.githubusercontent.com/12061206/32360479-bfc520fa-c088-11e7-85c3-2933247db919.png)

**and this is error in my project page :** 
![image](https://user-images.githubusercontent.com/12061206/32360449-73ef1f96-c088-11e7-9205-ce9c4a781277.png)

Thank you very much. Have a nice day. 😄

**Comment by ConsoleTVs** [comment]
I will need more help in here, click on the line u marked as: "app.js:156" and give me a screenshot of the source code you see

**Comment by ConsoleTVs** [comment]
Perhaps charts 6 may help you out hummm
