### ISSUE TITLE
Change font/colors of title?

### ISSUE THREAD

**Issue by starklmc** [ConsoleTVs/Charts#278]
Is there currently any way to change the font and/or color of the title? The title and legend text stays the #333 color, while all the other text follows the default color that I set for all the text on my site. Just curious if it's possible to change it. The font is similar enough that it doesn't really matter, but the difference in color is pretty noticeable. Any suggestions?

**Comment by ConsoleTVs** [comment]
I think the chart is inside a class="charts" or soemthing, inspect the element and apply the css classes you wish to use
