### ISSUE TITLE
Multiple Charts - order is not respected 

### ISSUE THREAD

**Issue by aleksmarcelo** [ConsoleTVs/Charts#279]
Multiple charts  are not being rendered well !

For example the code below, shows only the 2nd graph in the beginning.  Weird !!

```JS
 <body>
        <div id="b" class="app">
                {!! $temp->html() !!}
        </div>

        <div class="app">
            <center>
                {!! $chart->html() !!}
            </center>
        </div>
        <!-- End Of Main Application -->
        {!! Charts::scripts() !!}

        {!! $temp->script() !!}
        
        {!! $chart->script() !!} 
    </body>
```

**Comment by ConsoleTVs** [comment]
Are you sure you're doing it well? Can you screenshot the console in the browser?

**Comment by aleksmarcelo** [comment]
Yep, i,ve tried a lot !

Take a look :

http://spaifeel.forensicdesk.com - It´s public now

2017-11-13 17:13 GMT-02:00 Erik Campobadal <notifications@github.com>:

**Comment by ConsoleTVs** [comment]
I see it correctly :o 

![image](https://user-images.githubusercontent.com/6124435/32746682-ae13e112-c8b6-11e7-8483-ea1524ba2c9e.png)

**Comment by aleksmarcelo** [comment]
If you invert the order, the page continues to being displayed as the same.



2017-11-13 18:07 GMT-02:00 Erik Campobadal <notifications@github.com>:

**Comment by ConsoleTVs** [comment]
can you try ->render() instad of ->html() and remove the ->script()?

**Comment by aleksmarcelo** [comment]
In this way, displays nothing .


If I leave the ->script , it displays only the gauge (second one).


<body>

<div id="b" class="app">
{!! $temp->render() !!}
</div>

<div class="app">
<center>
{!! $chart->render() !!}
</center>
</div>
<br/>


{!! Charts::scripts() !!}


</body>

2017-11-13 18:51 GMT-02:00 Erik Campobadal <notifications@github.com>:

**Comment by aleksmarcelo** [comment]
The Controller :


<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use Charts;

class TemperatureController extends Controller
{
public function index()
{
$data = \App\Temperature::orderBy('created_at', 'DESC')->limit(30);

$chart = Charts::multi('line', 'highcharts')
->title('Gráfico de Temperatura do Laboratório SPAI')
->labels('Temperatura', 'Humidity')
->labels($data->pluck('created_at'))
->dataset('Humidade', $data->pluck('humidity') )
->dataset('Temperatura', $data->pluck('temperature') )
->responsive(true);

$dataTemp = \App\Temperature::orderBy('created_at', 'desc')->first();

$temp = Charts::create('percentage', 'justgage')
->title('Temperatura Atual')
->elementLabel('Graus')
->values([$dataTemp->temperature ,0, 50])
->responsive(false)
->height(300)
->width(0);


$temp2 = Charts::create('percentage', 'justgage')
->title('Temperatura Atual - Temp2')
->elementLabel('Graus - Falsos')
->values([$dataTemp->temperature ,0, 50])
->responsive(false)
->height(300)
->width(0);

// dd($chart);
return view('graphs.graph', [ 'temp2' => $temp2, 'temp' => $temp, 'chart'
=> $chart] );
}
}

2017-11-13 19:01 GMT-02:00 Marcelo Aleks <marcelo.aleks@gmail.com>:

**Comment by ConsoleTVs** [comment]
Try charts 6 now.
