### ISSUE TITLE
hello i have an issue while installing... please help.. 

### ISSUE THREAD

**Issue by umair104** [ConsoleTVs/Charts#280]
Problem 1
    - consoletvs/charts 5.1.0 requires consoletvs/support ^2.1.2 -> satisfiable by consoletvs/support[2.1.2, 2.2.0, 2.2.1, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0].
    - consoletvs/charts 5.1.1 requires consoletvs/support ^2.1.2 -> satisfiable by consoletvs/support[2.1.2, 2.2.0, 2.2.1, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0].
    - consoletvs/charts 5.4.0 requires php >=7.0.0 -> your PHP version (5.6.25) does not satisfy that requirement.
    - consoletvs/charts 5.3.1 requires php >=7.0.0 -> your PHP version (5.6.25) does not satisfy that requirement.
    - consoletvs/charts 5.3.0 requires php >=7.0.0 -> your PHP version (5.6.25) does not satisfy that requirement.
    - consoletvs/charts 5.2.2 requires php >=7.0.0 -> your PHP version (5.6.25) does not satisfy that requirement.
    - consoletvs/charts 5.2.1 requires php >=7.0.0 -> your PHP version (5.6.25) does not satisfy that requirement.
    - consoletvs/charts 5.2.0 requires php >=7.0.0 -> your PHP version (5.6.25) does not satisfy that requirement.
    - consoletvs/charts 5.1.3 requires php >=7.0.0 -> your PHP version (5.6.25) does not satisfy that requirement.
    - consoletvs/charts 5.1.2 requires php >=7.0.0 -> your PHP version (5.6.25) does not satisfy that requirement.
    - consoletvs/support 2.4.0 requires php >=7.0 -> your PHP version (5.6.25) does not satisfy that requirement.
    - consoletvs/support 2.3.4 requires php >=7.0 -> your PHP version (5.6.25) does not satisfy that requirement.
    - consoletvs/support 2.3.3 requires php >=7.0 -> your PHP version (5.6.25) does not satisfy that requirement.
    - consoletvs/support 2.3.2 requires php >=7.0 -> your PHP version (5.6.25) does not satisfy that requirement.
    - consoletvs/support 2.3.1 requires php >=7.0 -> your PHP version (5.6.25) does not satisfy that requirement.
    - consoletvs/support 2.3.0 requires php >=7.0 -> your PHP version (5.6.25) does not satisfy that requirement.
    - consoletvs/support 2.2.1 requires php >=7.0 -> your PHP version (5.6.25) does not satisfy that requirement.
    - consoletvs/support 2.2.0 requires php >=7.0 -> your PHP version (5.6.25) does not satisfy that requirement.
    - consoletvs/support 2.1.2 requires php >=7.0 -> your PHP version (5.6.25) does not satisfy that requirement.
    - Installation request for consoletvs/charts ^5.1 -> satisfiable by consoletvs/charts[5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.3.1, 5.4.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by ConsoleTVs** [comment]
consoletvs/charts 5.3.0 requires php >=7.0.0 -> your PHP version (5.6.25) does not satisfy that requirement.

You have PHP 5.6, you need 7.0
