### ISSUE TITLE
How I can display a dynamic label but still not coming from the database value ?

### ISSUE THREAD

**Issue by Johnmel15** [ConsoleTVs/Charts#283]
Dear Erik,

I want to display a statistical chart base in the following table

1. Program Table
![image](https://user-images.githubusercontent.com/33709713/32977385-65ed63ea-cc67-11e7-8eb8-42e1e1d161f6.png)
2. StudVioTracer Table
![image](https://user-images.githubusercontent.com/33709713/32977410-c5f557ac-cc67-11e7-9341-72d8429baed5.png)

If we differentiate the two table Program "BAT" is not in the present in StudVioTracer 

the output of this is like this.
![image](https://user-images.githubusercontent.com/33709713/32977433-31218b90-cc68-11e7-9b8b-b648ce20bd6d.png)

but instead of that I want the chart to be like this ..
![image](https://user-images.githubusercontent.com/33709713/32977444-6643e462-cc68-11e7-92a8-9d5d937f6994.png)

I want to display the not existing Program in the chart even though there is no data in the other table that match to the program ..

this is my code right now please help me erik .. but this code retrieve only data that match to the program in other table ..

         $chart = Charts::database(

          StudVioTracer::select(DB::raw("count(*) as count"), 'grad.*')
              ->join('programs as grad', 'grad.abbreviation', 'stud_vio_tracers.program')
              ->leftjoin('programs as gradd', 'gradd.abbreviation', 'stud_vio_tracers.program')
                   ->where("semester", '=', "1st")
                   ->where("school_yr", 'like','%'.$sy.'%')
                   ->groupBy('name', 'abbreviation')
                   ->get()

                   , 'bar', 'highcharts')
              ->title("Number of Cases Per Course")
              ->colors(['red','yellow', 'gray', '#34aadc', 'pink', 'orange', '#0088cc', 'green'])
              ->elementLabel("Total")
              ->responsive(false)
              ->height(400)
              ->width(900)
              ->groupBy('abbreviation');

I've use database() in join the two table..

hoping for your response erik :)

**Comment by Johnmel15** [comment]
hope you can help me with this erik ..

**Comment by ConsoleTVs** [comment]
If you want to add additional data, it needs to be after the groupBy, so for example:

     $chart = Charts::database(

      StudVioTracer::select(DB::raw("count(*) as count"), 'grad.*')
          ->join('programs as grad', 'grad.abbreviation', 'stud_vio_tracers.program')
          ->leftjoin('programs as gradd', 'gradd.abbreviation', 'stud_vio_tracers.program')
               ->where("semester", '=', "1st")
               ->where("school_yr", 'like','%'.$sy.'%')
               ->groupBy('name', 'abbreviation')
               ->get()

               , 'bar', 'highcharts')
          ->title("Number of Cases Per Course")
          ->colors(['red','yellow', 'gray', '#34aadc', 'pink', 'orange', '#0088cc', 'green'])
          ->elementLabel("Total")
          ->responsive(false)
          ->height(400)
          ->width(900)
          ->groupBy('abbreviation');
     $chart->labels(array_merge($chart->labels, ['BAT']))
     $chart->values(array_merge($chart->values, [10]))

**Comment by Johnmel15** [comment]
I will try this code sir .. I will put some feedback later .

**Comment by Johnmel15** [comment]
I think this is still a static way sir .. is there's no other way like this way sir ? like putting foreach for loop? because if I put a new record that corresponds to the program BAT it still represent the value as 10.

**Comment by ConsoleTVs** [comment]
it's an array. You can insert the data the way you want. Simply get the other values like that and labels as well. No need to be static, simply get them the way you need. this was just an example of extending the chart labels / values with more things

**Comment by Johnmel15** [comment]
Because there is also case that other program is not match to the other table as I present .

for example 

Program            StudVioTracer
BSIT                        BSIT
BAT                        BAT
BSED                      BSED
BPA                        
BSOA                     BSOA
BSC                        BSC
BEED                      BEED
BSBA                      BSBA

as I arrange there are other case that other program is not exist to the other table like for my example 
"BPA" is not exist in StudVioTracer Table . 

I want to make it Dynamically but how :( ? ..

**Comment by ConsoleTVs** [comment]
I don't understand your problem...

**Comment by Johnmel15** [comment]
I'm so sorry sir .. all I need is to display the program that is not match to the program name in the other table .. if the program name is not exist it still display to the chart . because when I use database() it only display the list of program that is exist in the table.

**Comment by Johnmel15** [comment]
I have 8 program list in Table Programs

and the program name that match to the other table which is the StudVioTracer is 7

Even though it is 7 , I want to display the 8 program name even though the value is 0

if just in case we add new record that the program name is BAT it will update from 0 to 1.

**Comment by Johnmel15** [comment]
![image](https://user-images.githubusercontent.com/33709713/32980658-8f85b426-cca5-11e7-855e-4a17c197428d.png)

as the picture above, ther is no record that already exist for BAT
when I render the chart it will out all courses except BAT, but I want to output the BAT even though not exist.

So if just in case we add new record and then the program name is BAT it will update the count from 0 to 1 .

hope you understand it already sir :(

**Comment by Johnmel15** [comment]
Please anyone who could help please share your idea ..

**Comment by Johnmel15** [comment]
@geekspeek @Big-Shark @ConsoleTVs @Acurex need your help ..

**Comment by Johnmel15** [comment]
any update sir ?

**Comment by Big-Shark** [comment]
@Johnmel15 Read about joins, I think you need use right join
