### ISSUE TITLE
im having an error when im using realtime charts. all other charts are working fine. 

### ISSUE THREAD

**Issue by dewilrips** [ConsoleTVs/Charts#284]
_Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Undefined variable: max (View: /Users/rifaz/Projects/larve/vendor/consoletvs/charts/resources/views/google/realtime/gauge.blade.php)_

I created a the Api route from youtube video. api works fine. but the error is about a variable called max

please help

**Comment by ConsoleTVs** [comment]
Yes, I'm sorry but they currently don't work. Will fix this in the next release but won't be anytime soon.
