### ISSUE TITLE
Undefined variable: chart

### ISSUE THREAD

**Issue by BarthFox** [ConsoleTVs/Charts#286]
Need to render charts in my view but it returns `Undefined variable: chart (View: C:\wamp64\www\adminkik\resources\views\home.blade.php)` . here is what i put in th view ` <div class="col-lg-12">
                {!! $chart->html() !!}
            </div>` and i use `use Charts in my HomeController` my HomeController@index is like this`$chart = Charts::multi('bar', 'material')
            // Setup the chart settings
            ->title("My Cool Chart")
            // A dimension of 0 means it will take 100% of the space
            ->dimensions(0, 400) // Width x Height
            // This defines a preset of colors already done:)
            ->template("material")
            // You could always set them manually
            // ->colors(['#2196F3', '#F44336', '#FFC107'])
            // Setup the diferent datasets (this is a multi chart)
            ->dataset('Element 1', [5,20,100])
            ->dataset('Element 2', [15,30,80])
            ->dataset('Element 3', [25,10,40])
            // Setup what the values mean
            ->labels(['One', 'Two', 'Three']);
        return view('home',['charts'=>$chart]);`

**Comment by ConsoleTVs** [comment]
view('home',['chart'=>$chart]);

**Comment by BarthFox** [comment]
Ok thanks ! Done !

**Comment by radityaputranto** [comment]
![image](https://user-images.githubusercontent.com/18069998/43595269-74467bac-96a6-11e8-9ef9-7a6456e3885b.png)

my chart only show one data

![image](https://user-images.githubusercontent.com/18069998/43595348-9d6ce3ae-96a6-11e8-9179-1603bafd881c.png)

![image](https://user-images.githubusercontent.com/18069998/43595395-be952258-96a6-11e8-809c-7fc78e5e7c79.png)

**Comment by Kenlock** [comment]
Did you turn the legend to be true?

**Comment by ConsoleTVs** [comment]
You did not add the labels https://charts.erik.cat/create_charts.html#add-the-chart-labels
