### ISSUE TITLE
problems using with turbolinks

### ISSUE THREAD

**Issue by vesper8** [ConsoleTVs/Charts#287]
I just noticed that highcharts breaks when Turbolinks is included in the scripts.. but works fine if not included. This includes on a page reload too

Is there a way to make it work?

Also.. I googled this package with turbolinks and found this link https://github.com/ConsoleTVs/Charts/tree/master/docs/5#installation

Is there a reason it says {data-turbolinks=false} at the top?

**Comment by ConsoleTVs** [comment]
Can you paste the view code?

It says data turbolink false because I use turbolinks on my site, andthis .md is imported on my site.

**Comment by vesper8** [comment]
Sorry haven't had a chance to isolate the problem yet but I have a feeling it's pretty easy to reproduce. I will paste you some code soon

**Comment by ConsoleTVs** [comment]
Charts 6 uses turbolinks support by default :) check it out!
