### ISSUE TITLE
Import chart to PDF 

### ISSUE THREAD

**Issue by dfuentes141** [ConsoleTVs/Charts#288]
Hi.
I want to print a chart on pdf but for some reason the chart doesn't. I use snappy pdf to create the document . Here the code

Controller
`  public function chartPDF(){

    $chart = Charts::multi('bar', 'material')
                   ->title("My Cool Chart")
                   ->dimensions(40, 100) 
                   ->template("material")
                   ->colors(['#2196F3', '#F44336', '#FFC107'])
                   ->dataset('Element 1', [5,20,100])
                   ->dataset('Element 2', [15,30,80])
                   ->dataset('Element 3', [25,10,40])
                   ->labels(['One', 'Two', 'Three']);`
      $pdf = PDF::loadView('report.chart', ['chart' => $chart]);
      return $pdf->stream();
    }

View
`<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>My Charts</title>
        {!! Charts::assets() !!}
    </head>
    <body>
      <center>
        <div style="width:400px; height:200px;">
          {!! $chart->render() !!}
        </div>
      </center>
    </body>
</html>`

Any idea why happen this? and Sorry for my english

**Comment by ikhsanfadillah** [comment]
Please anyone answer this issue

**Comment by rijans** [comment]
I also need this

**Comment by shadonet** [comment]
You have just add this JS file 'https://cdnjs.cloudflare.com/ajax/libs/highcharts/5.0.7/js/modules/exporting.js', before offline exporting file in config.charts.php file.
And if you would like to have "export in csv and xls format", just add this one also http://highcharts.github.io/export-csv/export-csv.js

**Comment by ConsoleTVs** [comment]
Libraries like fusioncharts, highcharts and echarts support this. Check the Charts 6 documentation page and use one of the mentioned libraries. There are few export() presets done already.

**Comment by tpharaoh** [comment]
so I found it with Fusioncharts in your code, great. But, I was curious in another issue they were discussing sending by email.

I can't export this to PDF as part of a JOB, then send it as attachment?

In the other post they suggested using spatie\browsershot
