### ISSUE TITLE
Bug in Builder.php

### ISSUE THREAD

**Issue by Elshaden** [ConsoleTVs/Charts#289]
Bug in line 272
in src/builder.php

missing semicolon after function };

 if ($libraries && is_string($libraries)) {
            $libraries = explode(',', $libraries);
        }

        $map = function ($value, $key) use ($libraries) {
            if (in_array($key, $libraries)) {
                return $value;
            }
            return;
        };  //  I added semicolon and it worked
       
        if ($type) {
            $map =  function ($value, $key) use ($libraries, $type) {
                if (in_array($key, $libraries) && array_key_exists($type, $value)) {
                    return $value[$type];
                }
                return;
            };  //  I added semicolon and it worked
        }

**Comment by ConsoleTVs** [comment]
It never gave me any error. PHP version?

**Comment by centrust** [comment]
PHP 7.1,

**Comment by LukaSikic** [comment]
Same here..

**Comment by ConsoleTVs** [comment]
Fear no more, charts 6 is out and have no Builder.php.
