### ISSUE TITLE
support for Infogram charts? or something equivalent?

### ISSUE THREAD

**Issue by vesper8** [ConsoleTVs/Charts#290]
I really love the charts on this page https://www.pcgamesn.com/nvidia-gtx-1070-ti-review/#benchmarks

Specifically I really love how you can paginate from one chart to the next using the left and right arrows and the data just changes very smoothly

They use Infogram which has a free tier but isn't open sourced https://infogram.com/examples

Any chance you might add support for this charts?

Otherwise, is there a chart vendor currently supported that could handle these kinds of transitions like the link above?

**Comment by ConsoleTVs** [comment]
Most JS libraries support animations, choose the one you like and modify the template (publishing the views). Feel free to add the transitions to the libraries you wish by reading it's own API docs.
