### ISSUE TITLE
multiple charts in one page

### ISSUE THREAD

**Issue by robertnicjoo** [ConsoleTVs/Charts#292]
Hi,

Is that possible to have multiple charts in same page?

I have testing method but I only can get first chart in my view:

```php
public function index()
    {
        $chart = Charts::database(User::all(), 'bar', 'highcharts')
            // Setup the chart settings
            ->title("My Cool Chart")
            ->elementLabel("Total Users")
            ->GroupByMonth()
            ->responsive(false)
            ->lastByMonth(6, true);
        $chart2 = Charts::multiDatabase('line', 'material')
          ->dataset('users', User::all())
          ->dataset('products', Product::all())
          ->groupByMonth(2017, true);
        return view('admin.charts.index', compact('chart', 'chart2'));
      }
```

And in my view I have:

```html
<p>{!! $chart->html() !!}</p>
<p>{!! $chart2->html() !!}</p>
```

but only see `{!! $chart->html() !!}`

**Comment by jkunwar** [comment]
Can it be made scrollable along y-axis instead of removing data from chart

**Comment by ConsoleTVs** [comment]
Yes it's possible did you ->script() both of them?

**Comment by robertnicjoo** [comment]
@ConsoleTvs no I didn't use any script, have no idea how to!

**Comment by robertnicjoo** [comment]
anyone can help?

**Comment by ConsoleTVs** [comment]
Can you paste the whole code? (the view)

**Comment by robertnicjoo** [comment]
```
@extends('layouts.admin')

@section('title', 'Charts')

@section('styles')
<!-- charts -->
  {!! Charts::styles() !!}
@endsection

@section('content')

<!--main content start-->
<section id="main-content">
    <section class="wrapper site-min-height">
    	<h3><i class="fa fa-angle-right"></i> Charts</h3>
    	<div class="row mt">
    		<div class="col-lg-12">
    		    <p>{!! $chart->html() !!}</p>
    		</div>
    	</div>
    </section><!--/wrapper -->
</section><!-- /MAIN CONTENT -->
<!--main content end-->

@endsection

@section('scripts')
<!-- charts -->
  {!! Charts::scripts() !!}
  {!! $chart->script() !!}
@endsection

```

**Comment by ConsoleTVs** [comment]
@extends('layouts.admin')

@section('title', 'Charts')

@section('styles')

  {!! Charts::styles() !!}
@endsection

@section('content')


<section id="main-content">
    <section class="wrapper site-min-height">
    	<h3><i class="fa fa-angle-right"></i> Charts</h3>
    	<div class="row mt">
    		<div class="col-lg-12">
    		    <p>{!! $chart->html() !!}</p>
    		</div>
    	</div>
        <div class="row mt">
    		<div class="col-lg-12">
    		    <p>{!! $chart2->html() !!}</p>
    		</div>
    	</div>
    </section>
</section>


@endsection

@section('scripts')

  {!! Charts::scripts() !!}
  {!! $chart->script() !!}
  {!! $chart2->script() !!}
@endsection

**Comment by robertnicjoo** [comment]
@ConsoleTVs thanks for help it's working now, but somehow when I visit my charts page my menu drop-down stop working!

**Comment by ConsoleTVs** [comment]
No idea why :c
