### ISSUE TITLE
Using certain column as values counted

### ISSUE THREAD

**Issue by fajarmaul** [ConsoleTVs/Charts#294]
Hi Erik, thanks for bringing us these good library
But i do have some question

I realized when we use database as input for our chart, in this case when we use Charts::database , the values returned as y-axis of the chart is always the number of how many records created in a certain amount of time (i.e we created 3 records in 17th of december), so in the x-axis is the label december, and the y-axis is 3.

My question is, can we change the values to something else?
For example
I'm using sales table, whenever a record is created, it stored amount of sales conducted within the day and the date it stored 

|sales_id | sales_amount | created_at 
---------------------------------------------------
|01         |100                 | 2017-12-12 17:42:08
|02         |200                 | 2017-12-12 18:22:20
|03         |450                 | 2017-12-13 19:29:40
---------------------------------------------------

This time i want 'sales_amount' as the values, and 'created_at' as the labels
So the values should be 300 for 2017-12-12 labels, not 2 (which is the amount of records created that day)

I noticed we can use manual way of doing it, using create method
But i'm always failed to do it

Any tips or thoughts in this case?
Thanks!

**Comment by k-kentang** [comment]
Hi fajarmaul, just add "aggregateColumn()" like this 
`$chart = Charts::database($databaseName, 'line', 'highcharts')

                ->title("Amount")

                ->elementLabel("Total Amount")

                ->aggregateColumn('sales_amount', 'sum')

                ->dimensions(800, 300)

                ->responsive(false)

                ->groupByDay();`

**Comment by fajarmaul** [comment]
@k-kentang sorry for the late reply
i've been trying using the Charts::create for sometimes, and somehow got it worked

But anyway thanks, i'm going to try your recommendation to simplify my codes haha
