### ISSUE TITLE
value percentage is zero

### ISSUE THREAD

**Issue by rakoding** [ConsoleTVs/Charts#295]
the percentage value appears zero, but already filled with the number 97 as in the example

 Charts::create('percentage', 'justgage')
    ->title('My nice chart')
    ->elementLabel('My nice label')
    ->values([**97**,0,100])
    ->responsive(false)
    ->height(300)
    ->width(0);

![persen](https://user-images.githubusercontent.com/34477229/33913112-178cb490-dfcb-11e7-927e-50eaedd866a7.png)

**Comment by luanphan1996** [comment]
responsive(false)->responsive(true) ... oke

**Comment by ConsoleTVs** [comment]
This this actually work? lmao

```
responsive(false)->responsive(true)
```

**Comment by rakoding** [comment]
not yet, still not working

**Comment by ConsoleTVs** [comment]
Charts 6 does not yet support this, will be re-written soon.
