### ISSUE TITLE
Geo Issue

### ISSUE THREAD

**Issue by robertnicjoo** [ConsoleTVs/Charts#296]
Hi,

I'm facing trouble with getting geo in my application, please help if have any idea what should I do:

**What I want**

I want get users ISO_CODE on visiting any page in my website. So I can use it in my chart as visitors country location.

**Codes**

My method using Charts

```php
//Header
use GeoIP as GeoIP;

class ChartController extends Controller
{
//.....

//Method
public function index()
    {
      //rest of my codes
      $data = array('geo' => geoip()->getLocation());
      $chart3 = Charts::create('geo', 'google')
             ->title('My nice chart')
             ->elementLabel('My nice label')
             ->labels($data = array_pluck($data, 'iso_code'))
             ->values($data = array_count_values($data))
             ->dimensions(1000,500)
             ->responsive(true);
....
}

```

**Error I get:**

> Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Undefined offset: 0

Any idea how can I achieve what I need?

Thanks in advance.

**Comment by ConsoleTVs** [comment]
Few key points:

```
$data = array('geo' => geoip()->getLocation());

This will return something like:

['geo' => ???]
```

The length of the array is 1. 

- Define the other 2 datas as diferent variables, outside the parenthesis.
- The folowing function won't work;

```
array_pluck($data, 'iso_code');

array_pluck(['geo' => ???], 'iso_code'); // This does not make sense.
```

- Then the values wont make sense as well. 


I would suggest your reading the docs on what data is waiting the application and debug what you're having on each place.

**Comment by robertnicjoo** [comment]
@ConsoleTVs  Hi,

1: What data is waiting is that I most have my user country code as labels and count of each of them as values

2:  As I can't get `pluck` directly in labels or values I'm using `$data = array('geo' => geoip()->getLocation());` to turn it into array and take each user `iso_code` out of that array (it's pure PHP method and not laravel) I attached screenshot of dd to see what is result of that code:

![screenshot-2017-12-15 http sinarmulia dev](https://user-images.githubusercontent.com/8672823/34035064-5d56ff64-e1b3-11e7-97ea-9cde4c0436cb.png)



3: Please help me get your package to work on my app I know some parts doesn't make sense, that's why I asked here to get help :\

Thanks/.

**Comment by robertnicjoo** [comment]
@ConsoleTVs  Hi, I managed to get my info out of stored data but Map will not load in view:

Here is my code:


```php
//Geo Info
        $iso = collect([
            geoip()->getLocation(),
        ]);
        $plucked = $iso->pluck('iso_code');
        $plucked->all();

        $country = collect([
            geoip()->getLocation(),
        ]);
        $countryplucked = $country->pluck('country');
        $countryplucked->all();

        $chart3 = Charts::create('geo', 'google')
               ->title('Geo Info')
               ->elementLabel('My nice label')
               ->labels([$countryplucked])
               ->values([$plucked])
               ->dimensions(1000,500)
               ->responsive(true);
```

Here is my blade:

```html
<div class="row mt-20">
    		<div class="col-lg-6">
          <p>{!! $chart3->html() !!}</p>
    		</div>
    	</div>
```
```javascript
{!! $chart3->script() !!}
```


Any idea?

**Comment by ConsoleTVs** [comment]
Geo charts will come in time again with charts 6, sorry for the issues!
