### ISSUE TITLE
Coin Miner on docs page

### ISSUE THREAD

**Issue by vivante64** [ConsoleTVs/Charts#297]
No comment

**Comment by ConsoleTVs** [comment]
You can read the docs on github.com or the downloaded repo in docs folder.

Further development on this library will be paid if i can't get some sort of result out of it. No donations ever in any of my projects.

Do you prefer advertisements?

Cheers

**Comment by ConsoleTVs** [comment]
Btw, an option to turn it off will appear tomorrow if i have time.

**Comment by tpharaoh** [comment]
I have previously suggested you give us a donate link. I am a strong
believer in your project.

**Comment by ConsoleTVs** [comment]
Alright. I'll do the following thing then:

- Add a donation link on the page
- Add a pop-up to my page explaining this and the additional option to turn it off.

I guess this is a fair solution. Thanks for the feedback everybody :)

@tpharaoh Sorry for beeing quite inactive. I'm currently under a lot of stress and literally have no time for anything.

I'm thinking in fixing all the missing pieces of the library and end up creating premium features for donators. So I guess it's a really good solution towards the future of development.

@vivante64 Do you really consider the coin miner a much worst alternative than ads? (I'm just curious tho... People don't seem to mind watching ads sometimes but when they see this sort of things they get frustrated)

**Comment by tpharaoh** [comment]
Erik, no problem at all...

In fact, I was satisfied with the solution you provided... of course better
to have all charts but, I can live with it as is.

I have very publicly tweeted I see your project becoming a go-to for
reporting. Nothing is as flexible and powerful as yours. And I am just one
person, but I would happily send something from time to time for your
projects.

Anyone using charts probably saved days of code. I am not asking for
anything more in excahnge for a donation. I think given it being a free
project  you have provided amazing support. I have seen how many people
post asking pure PHP/Laravel question which have nothing to do with you,
yet you are kind enough to help, rather then answer RTFM :)

My thanks to you, for code, and for kindness and for your time. (side note,
if you want to PM me your paypal, I'd send something as soon as you like)

**Comment by ConsoleTVs** [comment]
@tpharaoh I've added a new section to support me on the readme's page. Thanks!

@vivante64 Will add the modal warning about it and allowing to disable in my page soon.

Thanks for the feedback everybody!

**Comment by ConsoleTVs** [comment]
![image](https://user-images.githubusercontent.com/6124435/34179211-4fcd7594-e50a-11e7-8428-e178a3339f85.png)
