### ISSUE TITLE
Multiple Chart on one page 

### ISSUE THREAD

**Issue by ommyan** [ConsoleTVs/Charts#298]
Dear Erik,

let me get examples of best practices to make some charts in a page like a dashboard.
thanks 

best regard
yan

**Comment by tpharaoh** [comment]
It’s quite easy.

I think if you search closed issues you will see an example.

In controller loop charts into array charts[]

In view loop the chart array calling the html and scripts method

**Comment by tpharaoh** [comment]
https://github.com/ConsoleTVs/Charts/issues/273

**Comment by ommyan** [comment]
thanks All,
iam.not see this way on official documentation.

btw this work for me

closed

**Comment by ConsoleTVs** [comment]
Just pass diferent variables in the view and render them, Charts 6 is out, check the docs :)
