### ISSUE TITLE
[BUG]Failed to download consoletvs/charts from dist: 

### ISSUE THREAD

**Issue by sudanakunung** [ConsoleTVs/Charts#3]
**Required information**
 - Charts Version [e.g. 5.1]
 - Laravel Version [e.g. 5.5]
 - PHP Version [e.g. 7.2]

**Describe the bug**
when i run composer install this error appear

Failed to download consoletvs/charts from dist: The "https://codeload.github.com/ConsoleTVs/Charts/legacy.zip/9b27cbe8ceaf828fe5edaa597f582e52136fdad1" file could not be downloaded (HTTP/2 404 )
    Now trying to download from source

**Comment by tabacitu** [comment]
I just got the same thing, and for me the solution was:
```
composer clearcache
composer update consoletvs/charts
```
