### ISSUE TITLE
Warning docs are mining via coinhive

### ISSUE THREAD

**Issue by jamesfairhurst** [ConsoleTVs/Charts#300]
Wondering why my cpu was spiking, the docs are mining coins in the background. Bit shady if you ask me.

**Comment by ConsoleTVs** [comment]
https://github.com/ConsoleTVs/Charts/issues/297

**Comment by ConsoleTVs** [comment]
![image](https://user-images.githubusercontent.com/6124435/34179227-5cd2bb6e-e50a-11e7-9581-2979af284726.png)

Some people prefer ads, some others do not. I'm sorry to bother with this. I've linked it to the other issue and added a simple modal for people to choose!

Cheers!

**Comment by jamesfairhurst** [comment]
That's a good way of doing it, just felt a bit underhanded without notifying the user.

**Comment by ConsoleTVs** [comment]
I just needed to add the notification :)
