### ISSUE TITLE
Adding Multiple charts on a view

### ISSUE THREAD

**Issue by stacybot123** [ConsoleTVs/Charts#301]
Hi ,

Is there a way I can add more than 1 chat on a view. I tried passing two charts on the view and only one is rendering. The one with the variable name $chat is is rendering and the other one with some other name is not loading up.

**Comment by tpharaoh** [comment]
search the closed issues history, this was solved twice

**Comment by stacybot123** [comment]
Sorry . Yes I found that. I should have searched twice before asking .. Thanks @tpharaoh
