### ISSUE TITLE
Set max Y axis value for percentage

### ISSUE THREAD

**Issue by amazingdetective** [ConsoleTVs/Charts#302]
I would like to limit and set the value of the of the Y axis to 100 for displaying percentages. Is there a way to set this?

Currently if no percentage reaches close to 100 it will display to just above the upper limit, and if something is set to 100 it will display up to 125 it seems in my case, even though 100 is the max here. 

Is there a way to control this?

**Comment by ConsoleTVs** [comment]
Well yes and no. Not from the library itself, and yes by publishing the views and editing the template of the chart library you're using. As you may understand this library feature could only be supported by a few charting libraries out there so I can't just add thie feature for 2-3 libraries when we support around 15
