### ISSUE TITLE
Duplicate months displaying on chart.

### ISSUE THREAD

**Issue by jringeisen** [ConsoleTVs/Charts#304]
**Issue description**
I have been using ConsoleTVs/Charts for about 6 months now and when I visited my admin panel today I noticed there were duplicate months in the chart. The data being displayed is correct, but for some reason, the months are being duplicated.

**How to reproduce it**
Here is the snippet of code:

`$chart = Charts::database(User::whereYear('created_at', date('Y'))->get(), 'bar', 'highcharts')`
               ` ->title('Registers By Month ('.date('Y').')')`
                `->elementLabel('Users')`
               `->colors(['#d5d5d5'])`
                `->dimensions(0, 300)`
                `->responsive(false)`
                `->monthFormat('F')`
                `->groupByMonth(date('Y'), true);`

![screen shot 2017-12-31 at 7 08 02 am](https://user-images.githubusercontent.com/7864804/34463254-5f24e520-edf9-11e7-9a0a-7638a35fdf1f.png)

**Comment by ConsoleTVs** [comment]
What happens if you pas this as the 1st argument of the chart:

User::all()

rather than filtering them? The database filters them already.

**Comment by jringeisen** [comment]
Same thing, that's what I was using so I switched it to the filtered version to see if that did anything.

**Comment by ConsoleTVs** [comment]
Charts 6 does not have this, maybe it will come in time again.
