### ISSUE TITLE
syntax error, unexpected ':', expecting ';' or '{'  - /Users /dev3 /Desktop /ui /vendor /consoletvs /support /Traits /Utilities.php on line 17

### ISSUE THREAD

**Issue by Yosef7908** [ConsoleTVs/Charts#305]
I'm using PHP version  7.1.12 

this is where i'm getting the error 

/Users /dev3 /Desktop /ui /vendor /consoletvs /support /Traits /Utilities.php

    <?php
     
    namespace ConsoleTVs\Support\Traits;
     
    use Illuminate\Support\Facades\Request;
    use Illuminate\Support\Collection;
     
    trait Utilities
    {
        /**
         * Returns the real client IP adress.
         *
         * @author Erik Campobadal Fores <soc@erik.cat>
         * @copyright 2017 erik.cat
         * @return string
         */
        public static function clientIP() : string
        {
            if (!empty($_SERVER['HTTP_CF_CONNECTING_IP'])) {
                return $_SERVER['HTTP_CF_CONNECTING_IP'];
            } elseif (!empty($_SERVER['HTTP_CLIENT_IP'])) {
                return $_SERVER['HTTP_CLIENT_IP'];
            } elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
                return $_SERVER['HTTP_X_FORWARDED_FOR'];
            }
     
            return $_SERVER['REMOTE_ADDR'];
        }
     
        /**
         * Return all the currencies or the one specified.
         *
         * @author Erik Campobadal Fores <soc@erik.cat>
         * @copyright 2017 erik.cat
         * @param string|null $currency
         * @return Collection
         */
        public static function currencies(string $currency = null) : Collection
        {
            $currency = strtoupper($currency);

Arguments

    "syntax error, unexpected ':', expecting ';' or '{'"

**Comment by ConsoleTVs** [comment]
What line? lel? can u phpinfo() paste a screenshot of the first lines u see in there?

**Comment by Yosef7908** [comment]
I'll post the phpinfo() too but I figured I'll also post this.

<img width="1808" alt="screen shot 2018-01-01 at 5 48 09 am" src="https://user-images.githubusercontent.com/20997717/34468147-88175b0c-eeb7-11e7-8e10-1eca651dfe2d.png">

**Comment by ConsoleTVs** [comment]
I can tell you this is because you clearly dont have php 7 ;) perhaps u have php 7 in cli but jot in the server ;)

**Comment by Yosef7908** [comment]
You, sir, are current I just checked the phpinfo() and I still have php 5.6 on the server :) but I have php 7.1 in terminal

**Comment by ConsoleTVs** [comment]
Time to upgrade then ;)
