### ISSUE TITLE
Is it possible for the chart to span across 2 years?

### ISSUE THREAD

**Issue by shabaz-ejaz** [ConsoleTVs/Charts#307]
This is more of a question rather than an issue. Is it possible for a chart to span across multiple years? 

For example lets say I have a chart like below:

               $year = date('Y');
		   $monthly_booking_count_chart = Charts::database($bookings, 'line', 'highcharts')
		  ->title($year . " bookings received by month count")
		  ->elementLabel("Bookings")
		  ->dimensions(800, 500)
		  ->responsive(false)
		  ->lastByMonth($this->monthsPassed(), true)
		  ->template('aws-pink');
		  

This will only show the data for the current year (2018), however what if I want the chart to show 12 months with the preceding months data showing from the previous year.

So it should show Feb, March, April, May, June, July, Aug, Sept, Nov, Dec, Jan. As we are currently in January so it should show the previous 11 months.

Is this possible?

Thanks

**Comment by imabug** [comment]
Get your data using a separate query, and use Charts::create() instead to generate the graph

**Comment by ConsoleTVs** [comment]
@imabug was right, Charts 6 forces you to do something like that!
