### ISSUE TITLE
Display months in a different order

### ISSUE THREAD

**Issue by jringeisen** [ConsoleTVs/Charts#308]
I have users all over the world and they all have different tax years. So I added the ability to input their tax year but I am having a hard time figuring out how to get the chart to display based on their tax year.

For instance, I have a user in the UK and her tax year is April 1st to March 31st so I need her chart to display April to March instead of January to December. Is this possible?

This is the code for the chart:

`$chart = Charts::database($user->incomes, 'bar', 'highcharts')`
               ` ->title('Income by Month ('.date('Y').')')`
                `->colors(['#d5d5d5'])`
                `->elementLabel("Income")`
                `->dimensions(0, 300)`
                `->responsive(false)`
                `->dateColumn('date_income_received')`
                `->aggregateColumn('amount', 'sum')`
                `->monthFormat('F')`
                `->groupByMonth(date('Y'), true);`

**Comment by ConsoleTVs** [comment]
The database will respect the order comming from the 1st argument, so $user->incomes is the order used. If you want a diferent order, you're the one who need to order the results. Use Laravel collections for this :)

**Comment by jringeisen** [comment]
That makes sense. Can't believe I didn't think of this. Thank you!

**Comment by ConsoleTVs** [comment]
You're welcome :)
