### ISSUE TITLE
Google Calendar Chart support?

### ISSUE THREAD

**Issue by rijans** [ConsoleTVs/Charts#310]
No support for Google Calendar Charts? 

http://lavacharts.com/ (Google Charts Wrapper) already has it.  

Having https://developers.google.com/chart/interactive/docs/gallery/calendar support would be very nice!

**Comment by imabug** [comment]
Oooo, a calendar chart. I could use one of those in my project. I'll see what I can whip up and put in a PR when I get something that works.

In general, new chart types are fairly easy to add by just creating a new blade template in the resources/views folder

**Comment by rijans** [comment]
Currently I am using https://github.com/maddhatter/laravel-fullcalendar . But same thing support ConsoleTVs/Charts would be great!

**Comment by imabug** [comment]
Here's a first pass at a blade template that you can drop into `vendor/consoletvs/charts/resources/views/google` of a Laravel project.

https://gist.github.com/imabug/1157f8925d6135a6db7e228a4313a2c3

There are no formatting options at the moment.
`$labels` is an array containing a list of dates in YYYY-MM-DD format.
`$data` is an array containing the values for each day.

        $calChart = Charts::create('calendar', 'google')
            ->labels($labels)
            ->values($data);

Send it off to a view and you'll get a chart

Try it out and let me know how well it works. I'll spend some time trying to add some formatting options later

**Comment by ConsoleTVs** [comment]
This library is getting a full rework. Don't spend time on this...

**Comment by ConsoleTVs** [comment]
Yes. Finishing exams tomorrow. Looking forward the big update. But it will be a simploer library overall speaking. Features will be dropped. And customization will increese. I expect it to be a good update.

**Comment by ConsoleTVs** [comment]
More charts will come in time with the new release of charts 6. Thanks!
