### ISSUE TITLE
PGSQL not supported

### ISSUE THREAD

**Issue by ryanslcdevshop** [ConsoleTVs/Charts#311]
Hello,

I am using postgresql 9.5, getting error while using groupByMonth().

Illuminate \ Database \ QueryException (42883) SQLSTATE42883: Undefined function: 7 ERROR: function month(timestamp without time zone) does not exist LINE 1: ...sers” where ”users”.”deleted_at” is null group by month(crea… ^ HINT: No function matches the given name and argument types. You might need to add explicit type casts. (SQL: select COUNT as count_row from ”users” where ”users”.”deleted_at” is null group by month(created_at) order by “created_at” asc)

**Comment by ConsoleTVs** [comment]
Never faced that, but fear not, this is not present in the charts 6 implementation yet.
