### ISSUE TITLE
Can I display the value in a bar chart?

### ISSUE THREAD

**Issue by imhugos** [ConsoleTVs/Charts#314]
Hi, I need to display the value on top of each each bar in a bar chart. I know the value appears on mouseover but I need the values of all bars to be always visible. I'm using fusioncharts library but I don't mind changing to another.

Also, no matter if what I'm asking is possible or not, I would like to congratulate for the great work on this project!

**Comment by ConsoleTVs** [comment]
Charts 6 is out, you may do that on it :)

**Comment by ConsoleTVs** [comment]
And by the way, thanks a lot for the words!

**Comment by imhugos** [comment]
Thanks a lot! I upgraded to Charts 6: Changed the composer file to "consoletvs/charts": "6.*", ran "composer update" but I get the following error when I access the charts: Class 'ConsoleTVs\Charts\Facades\Charts' not found in AliasLoader.php (line 79).

Clearly I'm doing something wrong but don't know what... Can you help? ("Already tried composer dump-autoload -o"). Thanks in advance!

**Comment by ConsoleTVs** [comment]
Yes, you're not reading the official docs...

**Comment by ConsoleTVs** [comment]
Just to be clear, it's not an "upgrade" version. It's a package we-write. Everything is diferent, everything is new and maintainable.

**Comment by imhugos** [comment]
Hi, I tried to follow the instructions (not as an upgrade, but from new) on https://erik.cat/projects/charts but I get the error "Class 'ConsoleTVs\Charts\Facades\Charts' not found" in AliasLoader.php (line 79)

This exception is raised in the blade view... any idea why? I know I must be doing something wrong, but I can't figure out what!

**Comment by ConsoleTVs** [comment]
Don't lie :p You still got 5.X alias / provider in the config/app.php

**Comment by imhugos** [comment]
No, I commented it out! :) 
Only left the provider...

**Comment by ConsoleTVs** [comment]
Well you clearly see in the exception that is trying to load an alias by the name of the old facade.. no facades at all or aliases in 6.0...

**Comment by imhugos** [comment]
Yes I know what you mean, and this is driving me nuts, but if I do a search all files in my project, the only reference to the alias is the one I commented (if I delete it, the problem continues). I dindn't deleted the 5.0 version before installing the 6.0 version. I just changed the version on composer.json and ran composer update. Can that be a problem?

**Comment by imhugos** [comment]
MY BAD!!! The problem was that I was leaving the calls to Chart:: styles and scripts! So sorry!! Thanks!

**Comment by ConsoleTVs** [comment]
Sure :)

**Comment by imhugos** [comment]
Promise won't bother anymore :) but, back to my original question: how can I display the value on top of each each bar in a bar chart? I'me currently using chart,js library...

**Comment by ConsoleTVs** [comment]
Chartjs does not support this feature out of the box, It can only be used with plugins and we currently don't support that :c 

On the other hand, highcharts does support this for example: https://api.highcharts.com/highcharts/plotOptions.bar.dataLabels

So the way to go is set ur chart to highcharts and:

```php
$this->options([
    'plotOptions' => [
        'bar' => [
            'dataLabels' => true",
        ],
    ],
]);
```
