### ISSUE TITLE
Improvement: for multidataset carts add a datasets method

### ISSUE THREAD

**Issue by dopyoman** [ConsoleTVs/Charts#315]
So working with this library there was a feature that seemed intuitive but missing, and that is the ability to add an array of data sets.

What I propose is for the api to look something like this:

```php
$chart = \Charts::multi('line', 'highcharts')
            ->title('Temperature Time Series')
            ->template('material')       
            // Setup the diferent datasets (this is a multi chart)
            ->datasets($formatted_readings)
            // Setup what the values mean
            ->labels($timestamp);
```

Where datasets takes an associative array, the keys are the labels and the values the arrays of data

```
array:7 [▼
  "sensor1_0" => array:6 [▶]
  "sensor2_0" => array:6 [▶]
  "sensor3_0" => array:6 [▶]
  "sensor4_0" => array:6 [▶]
  "sensor5_0" => array:6 [▶]
]
```

Another option is do it kind of the laravel way and let the first param of `dataset` be either a string or an array.

**Comment by ConsoleTVs** [comment]
Datasets are now added in a similar way, may you check out Charts 6 and give me your opinion ? Thanks! Will keep this issue open meanwhile

**Comment by ConsoleTVs** [comment]
Problem in here, is that datasets have it's own class now, this might be not worth at all...

**Comment by dopyoman** [comment]
I had a quick look at the new version. I agree with you that my proposal now doesn't make much sense since it was in the context of multiline charts. Reading through the documentation I'm not exactly sure how this update handles multiline charts.

**Comment by ConsoleTVs** [comment]
Add different datasets with line type ;) it will work out of the box
