### ISSUE TITLE
Publishing templates proposal

### ISSUE THREAD

**Issue by VladimirBerezkin** [ConsoleTVs/Charts#32]
Your package is great, but it is missing some functions. For example, making a "stacked-column chart", like [this](http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/column-stacked/) one.
It can be achieved by editing the templates, but package is missing a function to publish assets into the resources folder and using them instead of the ones in vendor folder. 

Also it would be great to have a function like 'setTemplateFile' for chart to use specific template in any folder.

**Comment by ConsoleTVs** [comment]
A lot of new charts will keep beeing added in time! would be great if you could bring us some templates to have this things! 

Will keep an eye on that anyway, thanks!

**Comment by BlueTeck** [comment]
Not only stacked bars, also stacked/cumulativ lines please :)

**Comment by ConsoleTVs** [comment]
From now one I need to work on adding more stuff as well as keeping everything working. More libraries / charts will still come, dont worry about it! Just give me some time since I'm a student as well!

**Comment by faustbrian** [comment]
Should be solved via https://github.com/ConsoleTVs/Charts/pull/44/commits/d17dd46036c3f7a06e8cb7115fc086416d4f3fa3
