### ISSUE TITLE
Document that rendering fails if number of labels does not match data points

### ISSUE THREAD

**Issue by Phylu** [ConsoleTVs/Charts#320]
When a chart has a dataset defined, but the number of datapoints in the dataset is not the number of defined labels (or no labels have been defined), the chart is just empty, as the JavaScript code does not contain the 'data' array.

It might be good, to add this to the documentation.

**Comment by ConsoleTVs** [comment]
Yep, the chart is meant to be used with the labels, so, additional dataset values will be ignored and only the first count($chart->labels) will be used. Will be adding it to the docs. Thanks!

**Comment by ConsoleTVs** [comment]
Added under the dataset example :) Thanks for pointing it out!
