### ISSUE TITLE
Docs: Change reference from $this to $chart

### ISSUE THREAD

**Issue by Phylu** [ConsoleTVs/Charts#322]
In the documentation in the following sections, the examples state `$this->dataset()`:
* Dataset()
* Setting Dataset Options
* Using A Preset (second example only)

However this is in the Controller class where the Chart gets created with `$chart = new SampleChart;`. Therefore the command should be `$chart->dataset()`.

**Comment by ConsoleTVs** [comment]
Fixed! Thanks for the spot, I've written it quite fast :p

**Comment by Phylu** [comment]
Yeah. I am really impressed by the speed. :)

**Comment by ConsoleTVs** [comment]
I prefer to keep the docs as clear as possible, It's not easy to write them. :3 Thanks for the help reading & reporting!
