### ISSUE TITLE
ErrorException in AliasLoader.php line 66: Class 'ConsoleTVs\Charts\Facades\Charts' not found

### ISSUE THREAD

**Issue by trialrun1** [ConsoleTVs/Charts#323]
I have followed the instruction on how to include it on my laravel app. In my localhost it works perfectly but once I have uploaded to my production it gives me me this error.

ErrorException in AliasLoader.php line 66: 
Class 'ConsoleTVs\Charts\Facades\Charts' not found

In my config/app.php
providers
` ConsoleTVs\Charts\ChartsServiceProvider::class,`

Aliases
`'Charts' => ConsoleTVs\Charts\Facades\Charts::class,`

in my controller 
`use Hash;
use Session;
use Redirect;
use Charts;
use DB;`

In my production I have run the command 

composer require consoletvs/charts

and 

php artisan vendor:publish

php artisan vendor:publish --tag=charts_config

**Comment by ConsoleTVs** [comment]
First of all, nor version 5 or version 6 tells you to composer require without a fixed version. Second, that's because you installes charts 6 instead of 5. Please check the official docs...
