### ISSUE TITLE
php artisan make:chart returns exception

### ISSUE THREAD

**Issue by hichamhargal** [ConsoleTVs/Charts#326]
Hello,
at first thanks for this usefull package.

I am trying to upgrade Charts package from v5 to v6.

after making a composer update, I tried to launch the command `php artisan make:chart SuperficieChart Highcharts` but it gives me: 
`  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method ConsoleTVs\Charts\Commands\ChartsCommand::arguments()
`
to go on, I created the file manually as descripted in the documentation, but, `$chart->dataset('Sample', 'line', [100, 65, 84, 45, 90]);` gives this error: `Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Undefined property: Illuminate\Support\Collection::$each (View: /var/www/html/app/vendor/consoletvs/charts/src/Views/highcharts/script.blade.php)`.

can you help me please? 

PS: the charts works perfectly with the v5 of the package.

Regards,

**Comment by ConsoleTVs** [comment]
Laravel version? Php version?

**Comment by hichamhargal** [comment]
Laravel 5.2 and PHP 7.1.2

**Comment by ConsoleTVs** [comment]
Sorry to bother you but.. seems like your laravel version is obsolete. Will update dependency of laravel. Your laravel version does not support either new commands or higher order taps... Sorry... I suggest you upgrade :)

**Comment by hichamhargal** [comment]
Ah ok.

thank you so much :)

**Comment by ConsoleTVs** [comment]
I've research a bit... let me keep that open

**Comment by hichamhargal** [comment]
ok if you want :)

**Comment by ConsoleTVs** [comment]
- May fix the arguments() error with argument()
- May fix the $each higher order tap with a normal each(function ($element) { ... })

**Comment by hichamhargal** [comment]
argument() gives `
  [ErrorException]
  Illegal string offset 'name'
`

**Comment by hichamhargal** [comment]
it's ok for argument(), I had to use argument('name') instead of argument('name')['name.'].

I will check the second point.

**Comment by hichamhargal** [comment]
Hi again,
 in BaseChart.php I put 
`return Collection::make($this->datasets)
                ->each(function ($item) {
                    $item->matchValues(count($this->labels));
                })->map(function ($item) {
                    $item->format($this->labels);
                })->toJson();`
instead of : 
`return Collection::make($this->datasets)
            ->each
            ->matchValues(count($this->labels))
            ->map
            ->format($this->labels)
            ->toJson();`

and it works.
now I have a problem with showing the chart. that gives me this error:
`TypeError: e[h] is null` in highcharts.js. 
do you have any idea?

thanks again for your help.

**Comment by hichamhargal** [comment]
and with Chartjs it gives `TypeError: n is null` if that can help.

**Comment by ConsoleTVs** [comment]
Chartjs version ?

https://erik.cat/projects/charts in the end, it requires version: 2.7.1

**Comment by hichamhargal** [comment]
Indeed I copied this call of js class from the documentation to be sure that I use the right version.

**Comment by ConsoleTVs** [comment]
Paste the view, the layout, the controller and the chart class please!

**Comment by hichamhargal** [comment]
chart.blade.php:
`@extends('layouts.app')

@section('head')
@stop
@section('content')
<div class="container">
    <div class="row">
      <div class="panel panel-default">
          <div class="panel-heading">Tableau de Bord -> Statut Foncier</div>
            <div class="panel-body">
                <div id="ca_graph">
                  {!! $chart->container() !!}
                </div>
			</div>
		</div>
	</div>
</div>
@stop
@section('script')
  <script src=//cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js charset=utf-8></script>
  {!! $chart->script() !!}
@stop`

TerrainController.php:
` <?php
namespace App\Http\Controllers;

use App\Terrain;
use App\Http\Requests\TerrainRequest;
use Html;
use App\Charts\SuperficieChart;

class TerrainController extends Controller {
	
	public function __construct()
    {
        $this->middleware('auth');
    }

	public function addChart()
	{
		$chart = new SuperficieChart;
		$chart->dataset('Sample', 'line', [100, 65, 84, 45, 90]);

		return view('chart', ['chart' => $chart]);

	}
}

?>`

SuperficieChart.php:
`<?php

namespace App\Charts;

use ConsoleTVs\Charts\Classes\Chartjs\Chart;

  class SuperficieChart extends Chart {

    public function __construct()
    {
        parent::__construct();
    }
  }

?>`

**Comment by hichamhargal** [comment]
It's OK now. the problem was in my adaptation of formatDatasets() for Laravel 5.2. it was returning an empty Dataset.

thanks a lot for your assistance.

**Comment by ConsoleTVs** [comment]
Oh I see! Happy you fixed it :)

**Comment by hichamhargal** [comment]
Hi again,

The chart does not draw!! at first I had doubts about the data preparation from DB, but now I am using a very simple static example, but no chart rendered.

can you please confirm if my modification of formatDatasets() do the same thing as your's?

ExpoChart.php:
```<?php

namespace App\Charts;

use ConsoleTVs\Charts\Classes\Chartjs\Chart;

class ExpoChart extends Chart
{
    /**
     * Initializes the chart.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
        $this->labels(['One', 'Two', 'Three', 'Four', 'Five'])
        ->options([
          'legend' => [
            'display' => false
          ]
        ]);
    }
}
```
ChartController.php:
```<?php

namespace App\Http\Controllers;

use App\Charts\ExpoChart;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ChartController extends Controller{
  public function chart()
  {
    $chart = new ExpoChart;
    $chart->dataset('Sample', 'line', [100, 65, 84, 45, 90])->options(['borderColor' => '#ff0000'])->color('#ff0000');
    return view('chart_view', ['chart' => $chart]);
  }
}
```
chart_view.blade.php:
```<!DOCTYPE html>
<html>
 <body>

  <div>{!! $chart->container() !!}</div>

 <script src=//cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js charset=utf-8></script>
 {!! $chart->script() !!}
 </body>
</html>
```
formatDatasets():
```    /**
     * Formats the datasets for the output.
     *
     * @return string
     */
    public function formatDatasets()
    {
        // return Collection::make($this->datasets)
        //     ->each
        //     ->matchValues(count($this->labels))
        //     ->map
        //     ->format($this->labels)
        //     ->toJson();

            $data = Collection::make($this->datasets)->each(function ($item) {
                    $item->matchValues(count($this->labels));
                  });
            $data->map(function ($item) {
                    $item->format($this->labels);
                })->toJson();

            return $data;
    }
```
the generated script:
```
    let arxucvqjtkeylbpogmndifwhs_rendered = false;
    let arxucvqjtkeylbpogmndifwhs_load = function () {
        if (document.getElementById("arxucvqjtkeylbpogmndifwhs") && !arxucvqjtkeylbpogmndifwhs_rendered) {
            arxucvqjtkeylbpogmndifwhs_rendered = true;
            window.arxucvqjtkeylbpogmndifwhs = new Chart(document.getElementById("arxucvqjtkeylbpogmndifwhs").getContext("2d"), {
                type: "line",
                data: {
                    labels: ["One","Two","Three","Four","Five"],
                    datasets: [{"name":"Sample","type":"line","values":[100,65,84,45,90],"options":{"borderWidth":2,"borderColor":"#ff0000"},"undefinedColor":"#22292F"}]
                },
                options: {"maintainAspectRatio":false,"legend":{"display":false}}
            });
        }
    };
    window.addEventListener("load", arxucvqjtkeylbpogmndifwhs_load);
    document.addEventListener("turbolinks:load", arxucvqjtkeylbpogmndifwhs_load);
```
what does this render:
![image](https://user-images.githubusercontent.com/9398646/36634078-292b5cc8-1997-11e8-81f2-1bcca287174c.png)

Thanks again.

**Comment by ConsoleTVs** [comment]
```
    public function formatDatasets()
    {
        // return Collection::make($this->datasets)
        //     ->each
        //     ->matchValues(count($this->labels))
        //     ->map
        //     ->format($this->labels)
        //     ->toJson();

            return Collection::make($this->datasets)->each(function ($item) {
                    $item->matchValues(count($this->labels));
                  })->map(function ($item) {
                    return $item->format($this->labels);
                })->toJson();
    }
```

**Comment by hichamhargal** [comment]
It works!! thank you very much :) @ConsoleTVs

**Comment by ConsoleTVs** [comment]
This will be fixed in charts 6.1. I already patched it, but waiting to release API loaded charts.

**Comment by umunnah** [comment]
Call to undefined method ConsoleTVs\Charts\Classes\Chartjs\Dataset::container()..... please help am using the latest version

**Comment by umunnah** [comment]
homecontroller.php


private function chart() 
	{
		$chart = new MainChart;
		$chart = $chart->dataset('Sample', 'line', [100, 65, 84, 45, 90]);
	
	return $chart;
	}


Mainchart.php

public function __construct()
    {
        parent::__construct();
		$this->labels(['One', 'Two', 'Three', 'Four', 'Five'])
        ->options([
          'legend' => [
            'display' => false
          ]
        ]);
    }
