### ISSUE TITLE
Localize the Assets

### ISSUE THREAD

**Issue by mdestafadilah** [ConsoleTVs/Charts#327]
Hi, I'm new here with Laravel, can i put localize libraries (js or css) in to local server? how i do ? thanks

**Comment by ConsoleTVs** [comment]
What? I don't understand this question and how it's releated to charts

**Comment by mdestafadilah** [comment]
in short, how if we load javascript and style asset in config chart, in localhost not internet.

yaya.. i just try figure out your library

**Comment by ConsoleTVs** [comment]
You are the one responsible of importing the supported library. The supported ones are at the end of the docs page

**Comment by mdestafadilah** [comment]
Yaps
