### ISSUE TITLE
Formatting labels with v6.x

### ISSUE THREAD

**Issue by sigmoidal** [ConsoleTVs/Charts#328]
How can I format labels of a chart built using Highcharts, using consoltvs 6.x ?

I want, for example, to rotate the labels of the xAxis.

**Comment by ConsoleTVs** [comment]
This things are explained in the docs, you can use ANY option of the desired charting library:

https://api.highcharts.com/highcharts/xAxis.labels.rotation

```php
$chart->options([
    'xAxis' => [
        'labels' => [
            'rotation' => -45
        ]
    ]
]);
```

**Comment by sigmoidal** [comment]
thanks I already tried that like so:

```
$myChart->labels($timestamps)
               ->dataset($datapoints)
               ->options([
                                'xAxis' => [
                                    'labels' => [
                                        'rotation' => -45
                                    ]
                                ]
                            ]);
```

Shouldn't this work? Because it doesn't. 
It does work if I do this:

```
$myChart->labels($timestamps)
               ->dataset($datapoints);

$myChart->options([
                                'xAxis' => [
                                    'labels' => [
                                        'rotation' => -45
                                    ]
                                ]
                            ]);
```


Am I using the library wrong?

**Comment by ConsoleTVs** [comment]
As a note;

calling $chart->dataset() does return a dataset instance rather than the chart again.

so always try calling it apart

```php
$chart->labels(...)->options(...);
$chart->dataset(...);
$chart->dataset(...);
```

**Comment by sigmoidal** [comment]
ah, I wasn't aware it works like that. thanks this is very useful! 

I know you just released the new version, but whenever you find time to add a couple of more examples would really help.

thanks for your effort, the new interface is much easier to use.

**Comment by ConsoleTVs** [comment]
Thanks a lot, yes, I will add a lot of examples once I have time of course.. it's just a brand new release, and it's quite diferent to use... much easier to be aware.. much easier to maintain (I almost have no JS / HTML) :)

**Comment by ConsoleTVs** [comment]
Letting you know I've added a preset for this :)

https://github.com/ConsoleTVs/Charts/commit/8fa39186f245ac11086304a36a0bdd53190dd498

$chart->labels(...)->labelsRotation(-45);
