### ISSUE TITLE
Setting Up a fix Range for Y-axis

### ISSUE THREAD

**Issue by kniteshsri** [ConsoleTVs/Charts#330]
Hi,
i am working with Bar chart to show performance reports and its working fine except that i want to show the range in y-axis from 0 to 100. but it is acting dynamically  and not showing from 0 hence the minimum value fetched from database is the lowest value in the chart yAxes also.

**Comment by ConsoleTVs** [comment]
Charts version?
Library used?
Type of chart (normal or ajax)?

**Comment by kniteshsri** [comment]
Chart version 6.0
Library used :- ConsoleTVs\Charts\Classes\Chartjs\Chart;
Bar Chart

**Comment by hichamhargal** [comment]
try to add a chart option as below:

``` 
          'scales' => [
                    'yAxes' => [
                            'ticks' => [
                                'beginAtZero' => true,
                                'steps' => 10,
                                'stepValue' => 5,
                                'max' => 100
                            ]
                        ]
                ],
```

**Comment by fbc** [comment]
I'm using this with a horizontalbar graph. I can't get the xAxis to start at 0
```
$chart->options([
    'scales' => [
        'xAxes' => [
            'ticks' => [
                'beginAtZero' => true,

            ]
        ]
    ]
]);
```
