### ISSUE TITLE
How to have unspecified amounts of datasets for multi?

### ISSUE THREAD

**Issue by perfk** [ConsoleTVs/Charts#331]
Hi, i was wondering how i could produce the below result, but where i may have multiple ->datasets as i won't know how many users i have data from.
It could be the below 3 (+ server) or it could be 100 users.

Example:
```
$chart = Charts::multi('line', 'highcharts')
    ->labels($dates)
    ->dataset('Server',[125,125,107,125,126,141,146,141,135,125,114,142,132,103,135,128,121,110])
    ->dataset('Name 1', [125,112,124,152,152,123,122,112,145,125,112,152,114,112,116,192,129,122])
    ->dataset('Name 2', [130,104,106,107,146,120,147,132,104,135,137,137,105,136,145,106,128,134])
    ->dataset('Name 3', [114,107,127,139,113,124,132,129,132,124,105,124,112,135,142,125,138,110]);
```
Produces: 
https://imgur.com/a/eeamw

My example data: - remember that i could have many more "name x" sets.

```
$data = [
    ['Server',[125,125,107,125,126,141,146,141,135,125,114,142,132,103,135,128,121,110]],
    ['Name 1',[125,112,124,152,152,123,122,112,145,125,112,152,114,112,116,192,129,122]],
    ['Name 2',[125,112,124,152,152,123,122,112,145,125,112,152,114,112,116,192,129,122]],
    ['Name 3',[114,107,127,139,113,124,132,129,132,124,105,124,112,135,142,125,138,110]]
];
$dates = ['2018-02-26 18:24:54','2018-02-26 18:27:15','2018-02-26 18:30:00','2018-02-26 18:30:00','2018-02-26 18:30:16','2018-02-26 18:30:16','2018-02-26 18:36:14','2018-02-26 18:36:14','2018-02-26 18:36:47','2018-02-26 18:36:47','2018-02-26 19:05:15','2018-02-26 19:05:37','2018-02-26 19:06:31','2018-02-26 19:08:18','2018-02-26 19:09:18','2018-02-26 19:10:55','2018-02-26 19:11:31','2018-02-26 19:11:49'];
```

Example code thats not working, but i felt it was worth a try.
```
$chart = Charts::multi('line', 'highcharts')
    ->labels($dates)
    foreach ($data as $key) {
        ->dataset($key[0],$key[1])
    }
    ->dataset('test',[0,0]);
```

In case it may be easier to take it straight from the database. my database looks like this:

id | playersname | playersping | created_at | updated_at | deleted_at
------------ | ------------ | ------------ | ------------ | ------------ | ------------
1 | Server | 125 | 2018-02-26 18:24:54 | 2018-02-26 18:24:54 | NULL
2 | Name 1 | 125 | 2018-02-26 18:24:54 | 2018-02-26 18:24:54 | NULL
3 | Name 2 | 107 | 2018-02-26 18:24:54 | 2018-02-26 18:24:54 | NULL
4 | Name 3 | 125 | 2018-02-26 18:24:54 | 2018-02-26 18:24:54 | NULL
5 | Server | 126 | 2018-02-26 18:27:15 | 2018-02-26 18:27:15 | NULL
6 | Name 1 | 141 | 2018-02-26 18:27:15 | 2018-02-26 18:27:15 | NULL
7 | Name 2 | 146 | 2018-02-26 18:27:15 | 2018-02-26 18:27:15 | NULL
8 | Name 3 | 141 | 2018-02-26 18:27:15 | 2018-02-26 18:27:15 | NULL
9 | Server | 135 | 2018-02-26 18:30:00 | 2018-02-26 18:30:00 | NULL
10 | Name 1 | 125 | 2018-02-26 18:30:00 | 2018-02-26 18:30:00 | NULL
11 | Name 2 | 114 | 2018-02-26 18:30:00 | 2018-02-26 18:30:00 | NULL
12 | Name 3 | 142 | 2018-02-26 18:30:00 | 2018-02-26 18:30:00 | NULL
13 | Server | 132 | 2018-02-26 18:30:16 | 2018-02-26 18:30:16 | NULL
14 | Name 1 | 103 | 2018-02-26 18:30:16 | 2018-02-26 18:30:16 | NULL
15 | Name 2 | 135 | 2018-02-26 18:30:16 | 2018-02-26 18:30:16 | NULL
16 | Name 3 | 128 | 2018-02-26 18:30:16 | 2018-02-26 18:30:16 | NULL
17 | Server | 121 | 2018-02-26 18:36:14 | 2018-02-26 18:36:14 | NULL
18 | Name 1 | 110 | 2018-02-26 18:36:14 | 2018-02-26 18:36:14 | NULL
19 | Name 2 | 114 | 2018-02-26 18:36:14 | 2018-02-26 18:36:14 | NULL
20 | Name 3 | 107 | 2018-02-26 18:36:14 | 2018-02-26 18:36:14 | NULL
21 | Server | 127 | 2018-02-26 19:05:15 | 2018-02-26 19:05:15 | NULL
22 | Name 1 | 139 | 2018-02-26 19:05:15 | 2018-02-26 19:05:15 | NULL
23 | Name 2 | 113 | 2018-02-26 19:05:15 | 2018-02-26 19:05:15 | NULL
24 | Name 3 | 124 | 2018-02-26 19:05:15 | 2018-02-26 19:05:15 | NULL
25 | Server | 132 | 2018-02-26 19:10:55 | 2018-02-26 19:10:55 | NULL
26 | Name 1 | 129 | 2018-02-26 19:10:55 | 2018-02-26 19:10:55 | NULL
27 | Name 2 | 132 | 2018-02-26 19:10:55 | 2018-02-26 19:10:55 | NULL
28 | Name 3 | 124 | 2018-02-26 19:10:55 | 2018-02-26 19:10:55 | NULL

Thank you for this awesome package!

**Comment by ConsoleTVs** [comment]
Sorry, but this is an obsolete charts version. Please upgrade to 6.X

**Comment by perfk** [comment]
Hi,

Sorry for being blind :D its almost impressive that i was able to not see the big "documentation". I just saw blue link "Charts 5.X documentation" and off i went.

I have it working now with 6.X, thanks.

**Comment by ConsoleTVs** [comment]
You're welcome!

**Comment by vesper8** [comment]
@perfk could you by any chance share an example of how you got multi datasets working with V6 please? I'm having trouble upgrading as well

many thanks

**Comment by ConsoleTVs** [comment]
Multi datasets comes by default now. simply use ->dataset() multiple times. It accepts diferent types as well.

**Comment by ingmontoya** [comment]
Hi @ConsoleTVs, can you please help me on this,  I want to build my chart as follows:

![image](https://user-images.githubusercontent.com/17322788/73405427-df423180-42c1-11ea-81c1-a8b1adf337ef.png)
how to add multiple datasets in this way?
thanks in advance!
