### ISSUE TITLE
Composer Require issue 

### ISSUE THREAD

**Issue by roarkmccolgan** [ConsoleTVs/Charts#332]
Copy / Paste installation instructions:

`composer require consoletvs/charts:6.* `

Results in error:
zsh: no matches found: consoletvs/charts:6.*

I just used:

`composer require consoletvs/charts `

**Comment by hichamhargal** [comment]
Add `alias composer='noglob composer'` in your .zshrc.

**Comment by ConsoleTVs** [comment]
This is prob because of ZSH. Check the alias as @hichamhargal suggested!

**Comment by andru-h** [comment]
If anyone is having this issue, just add quotation marks like this
`composer require "consoletvs/charts:6.*"`

**Comment by ConsoleTVs** [comment]
Thanks @andru-h
