### ISSUE TITLE
Ideas and Questions V6

### ISSUE THREAD

**Issue by nam-co** [ConsoleTVs/Charts#333]
Hi, once again, thanks for the work you put into this package, 

I got some questions I hope you can help me with:

1. Is ->dataset(__('Payments'), $payments)->lastByMonth(12, true) still available in V6? I hope, its very cool

2. Is it possible to erase the grid and just leave the chart line?

3. Can chart lines and areas be gradient?

Thanks for your time

**Comment by ConsoleTVs** [comment]
1. No, it's not but it will in a future have a similar function.
2. Yes
3. Yes

2 and 3 depend on the library you're using. It actually depends a lot on it, but most of them do. Check the official docs of the one you're using and add the required options. Also check the chart presets (features) in the following folder: https://github.com/ConsoleTVs/Charts/tree/master/src/Features

it may already have a preset for what you want ^^

**Comment by nam-co** [comment]
Thanks for the quick answers Erik, I was wondering what do you currently use to excecute something like this in the new version? ->dataset(__('Payments'), $payments)->lastByMonth(12, true)

Sorry to bother you so much

**Comment by Phylu** [comment]
You can do something like this (very hacky solution):
```php
for ($i = 11; $i >= -1; $i--) {
  $j = $i - 1
  $firstDayOfNextMonth = date("Y-m-01", strtotime(date('Y-m-01')." -$i months"));
  $firstDayOfMonth = date("Y-m-01", strtotime(date('Y-m-01')." -$j months"));
  $months[] = date("m-Y", strtotime(date('Y-m-01')." -$i months"));
  $monthlyData[] = number_format(with(clone $data)->where('created_at', '>=', $firstDayOfMonth)->where('created_at', '<', $firstDayOfNextMonth)->count());
 }
$this->labels($months);
$this->dataset($key, 'line', $monthlyData);
```

**Comment by robertkingkira** [comment]
What do you mean by most of the do 

> 1. No, it's not but it will in a future have a similar function.
> 2. Yes
> 3. Yes
> 
> 2 and 3 depend on the library you're using. It actually depends a lot on it, but most of them do. Check the official docs of the one you're using and add the required options. Also check the chart presets (features) in the following folder: https://github.com/ConsoleTVs/Charts/tree/master/src/Features
> 
> it may already have a preset for what you want ^^

What do you mean by most of them do 2 and 3 ? I am searching for hours trying to find a way to add linear gradient to my chart js and there's not documentation about this. So can you please tell me how can i do that ?

**Comment by ConsoleTVs** [comment]
This deoends on what frontend library you are using. Not all libraries support gradients. The docs explain how to pass options to the datasets using ->options(), so you just need to know the frontend lib and where does it want the gradient.
