### ISSUE TITLE
how to use this when your front-end is separated from your back-end? meaning no laravel on the front-end

### ISSUE THREAD

**Issue by vesper8** [ConsoleTVs/Charts#335]
So basically I have been using this package to generate my charts for over a year and I love it.

But now in a new project I have my front-end completely separated from the back-end. It even lives on a different server, and it uses Vue and vue-router

It is still powered by laravel, but strictly through API calls.

I want to show the same graphs which are already configured and ready to go. I don't want to have to start over with a different package. As I understand it, this package's rendering does two things, first it outputs all the necessary html and links the dependencies.. which should be easy to do in my setup. And the 2nd thing is how it actually transfers the data from the server to the front-end.. and here's where I think I'll face a problem.

Is it possible to do this via an api call ?

If not exactly.. can you suggest something a solution that doesn't require me to abandon this wonderful package ?

Thanks much!

**Comment by ConsoleTVs** [comment]
Well, this package is purely done in PHP, yet yes, there are the API calls to the server to get the data, but the HTML is purely printed with PHP using {!! $chart->container() !!} so it's impossible (almost) to transfer everything into a new frontend.

I myself use vue but don't use this package if so. In a future, this package may include a npm version for pure JS. But that makes fewer sense to be honest, because if you're working with vue (JS) you can already create cool charts natively with JS. I use vue-chartjs for vue.

I would not loose time trying to figure out how to make it work with this library :)

**Comment by vesper8** [comment]
I took a lot at vue-chartjs and nope, it's nowhere near the quality and flexibility of this package and like I said the last thing I want to do is start over from scratch, I already spent many months fine-tuning how my graphs data gets generated using your library, having to translate that to a new library would be a waste specially considering I'm very happy with this library and what I want to do should not be difficult

In fact I just took a closer look to what actually happens with this library and it seems pretty easy. Including the correct scripts in the head is trivial.

I also transferred your "chart loader" code to a vue function

```
    renderCharts() {
      $(() => {
        $('.charts').each(function () {
          const chart = $(this).find('.charts-chart');
          const loader = $(this).find('.charts-loader');
          const time = loader.data('duration');
          if (loader.hasClass('enabled')) {
            chart.css({
              visibility: 'hidden',
            });
            loader.fadeIn(350);
            setTimeout(() => {
              loader.fadeOut(350, () => {
                chart
                  .css({
                    opacity: 0,
                    visibility: 'visible',
                  })
                  .animate(
                    {
                      opacity: 1,
                    },
                    350,
                  );
              });
            }, time);
          }
        });
      });
    },
```

The only tricky part really is getting the data itself from the server to the front-end. This too would be trivial if only your app was making actual API calls instead of rendering it via a blade service directive. So this is the part I was inquiring about, and this is the part I guess I will have to fork and hack a method for.

On the back-end the data is calculated and then an object like this is generated

```
{
          chart: {
            renderTo: 'luOKPRfBTp',
            height: 400,
          },
          title: {
            text: 'Daily Activity last 14 days',
            x: -20, // center
          },
          credits: {
            enabled: false,
          },
          xAxis: {
            categories: [
              'Monday 19th Feb, 2018',
              'Tuesday 20th Feb, 2018',
              'Wednesday 21st Feb, 2018',
              'Thursday 22nd Feb, 2018',
              'Friday 23rd Feb, 2018',
              'Saturday 24th Feb, 2018',
              'Sunday 25th Feb, 2018',
              'Monday 26th Feb, 2018',
              'Tuesday 27th Feb, 2018',
              'Wednesday 28th Feb, 2018',
              'Thursday 01st Mar, 2018',
              'Friday 02nd Mar, 2018',
              'Saturday 03rd Mar, 2018',
              'Sunday 04th Mar, 2018',
            ],
          },
          yAxis: {
            title: {
              text: 'Element',
            },
          },
          legend: {},
          series: [
            {
              name: 'Matches',
              color: '#2196F3',
              data: [23, 18, 23, 39.5, 22, 11, 19, 24, 26, 6, 0, 0, 0, 0],
            },
            {
              name: 'Requests',
              color: '#F44336',
              data: [85, 77, 56, 74, 45, 48, 43, 84, 39, 25, 0, 0, 0, 0],
            },
            {
              name: 'Messages',
              color: '#FFC107',
              data: [313, 341, 444, 273, 216, 213, 297, 260, 176, 246, 0, 0, 0, 0],
            },
          ],
        }
```

I just need a way to get this data back to my Vue instance via a GET API call.. shouldn't be too hard

I don't think you need to make a npm package, simply adding a way to pull the data via an API would be fantastic and just what I need. Anyway I'll be doing just that now.. I'll share my code when I figure out a way to do it

Thanks for your advice

**Comment by ConsoleTVs** [comment]
Did you consider checking out what the $chart->api() returns?

**Comment by vesper8** [comment]
oh my.. no.. to be honest i'm still on v5, i think that must be new with v6.. sorry I totally missed that. But still you seemed to say that what I wanted to do wouldn't be easy.. enough that you said I should switch to another library.. hrmm.. well I'll see what I can do with $chart->api(), either way I'll get this to work, and if I have to modify the behaviour I'll post back here and let you know so you can consider modifying your implementation so that it's friendlier to a pure-js <-> laravel setup.. which I think is becoming increasingly popular thanks to vue-cli and the awesomeness of vue-router

In another thread I mentioned Turbolinks, but now that I've had a good proper taste of vue-router I feel that all my future apps will have a completely separate front-end and I won't be using Blade much anymore if at all

cheers thanks for letting me know about ->api() and thanks for adding that functionality

**Comment by ConsoleTVs** [comment]
Thaks, turbolinks is supported in 6.X by default, will check things out for vue as spa in a future :)
