### ISSUE TITLE
upgrading from V5, is everything from V5 still possible in V6?

### ISSUE THREAD

**Issue by vesper8** [ConsoleTVs/Charts#338]
I'm trying to upgrade from V5 and I'm finding the documentation for V6 lacking in comparison.

There were a lot of things I was doing in V5 which is not clear if it's still possible in V6

For example I was using multiDatabase a lot with things like lastByDay and aggregateColumn

I looked at the source for V6 and these methods are no longer available.

As a simple example:

```
            $threads = Thread::all();
            $messages = Message::all();

            $chart = Charts::multiDatabase('line', 'highcharts')
            ->title("Daily Activity")
            ->aggregateColumn('count', 'sum')
            ->dataset('Threads', $threads)
            ->dataset('Messages', $messages)
            ->lastByDay(14, true);
```

Is this still possible in V6?

If so, it would be nice if you could share how to write it in V6. I know things are very different in V6, I have the basic example working

It's just that the V6 docs don't make any mention of using multi datasets and aggregate methods

**Comment by ConsoleTVs** [comment]
Docs mention the only way of adding data is using ->dataset(). Try calling it multiple times to add many.

Also, the database methods (includes database and multidatabase) are no longer available. perhaps they will in a future but the library itself it's not made for this. You should grab the data yourself. This is better, for you and for the library itself. Fear not, classes makes ur code organized now :)

And no, V6 is a complete re-write, nothing to do with V5. There's no upgrade guide for a reason!

In a future, new things will keep beeing added. Also, the charts are now 100% customizable, to the CORE. You can output exactly what you want.

**Comment by vesper8** [comment]
I see.. well I've begun the process of adapting all my charts to V6.. I understand that we have to do the aggregation ourselves now.. which I suppose makes things clearer. The helpers were useful and time saving but I appreciate that this new way of doing things is more flexible

Since Highcharts is still supported, does that mean that ALL of Highcharts is currently supported? For example, are the 'area' and 'geo' charts still working?

**Comment by ConsoleTVs** [comment]
Never tested geo, so it perhaps not work yet. Others should yes :) (if u try strange charts let me know so I can check them out)

But yes, most should :)

**Comment by vesper8** [comment]
Well I'm still at it.. this is proving harder than I thought.. those helper aggregate methods were doing a lot of heavy lifting!

One thing I can't seem to figure out how to change.. before the pie charts would display both the int value as well as the percentage value... now with the same highcharts pie chart.. it only displays the int value.. do you know how to (re)-enable the percentage ?

**Comment by vesper8** [comment]
Figured it out... using your 5.4.0 as a reference is very helpful...

Still.. a lot of work just to get back to what I already had!

```
        $this->options([
            'tooltip' => [
                'pointFormat' => '{point.y} <b>({point.percentage:.1f}%)</strong>',
            ],
            'plotOptions' => [
                'pie' => [
                    'dataLabels' => [
                        'format' => '<b>{point.name}</strong>: {point.y} ({point.percentage:.1f}%)',
                    ]
                ]
            ],
        ]);
```

**Comment by vesper8** [comment]
Can't for the life of me get the area opacity to be anything but full opaque

if I don't set any color at all and it uses the default then it uses the default opacity which is 0.75

but if I set a color, either by using ->color on the dataset()

or by using the plotOptions below

```
        $this->options([
            'plotOptions' => [
                'series' => [
                    'color' => '#9400D3',
                ],
            ],
        ]);
```

Then no matter what I do (I tried adding fillOpacity in many places, as described in the highcharts docs, the opacity is always full and never semi-transparent

I looked at how you did it on 5.4.0.. and I don't see you doing anything special there

in area.blade.php

```
            @if($model->colors)
                plotOptions: {
                    series: {
                        color: "{{ $model->colors[0] }}"
                    }
                },
            @endif
```

You don't do anything with the opacity.. it just worked.. but now I can't get it to work.. any advice would be appreciated

**Comment by ConsoleTVs** [comment]
It will be so much worth, trust me. You're not limited on how your chart will now look, as before you were.

Now, the aggregate methods were of help. yes, but not intended to be part of the library... as I stated, it may be possible in a future to add functionalities like that, it's not the main goal anyway.

I need more information for the last question regarding to the opacity. Highcharts V6 version vs V5 version? Photo of the expected result vs current result?

Thanks!

**Comment by vesper8** [comment]
well.. regardless of how it worked in V5.. I can't get it to work in V6

Here's what the area chart looks like if you don't specify any color. So it uses the default and you see it is 0.75 opacity and you can see the vertical lines behind the area

<img width="513" alt="screenshot 2018-03-07 17 28 11" src="https://user-images.githubusercontent.com/816028/37122088-2a965a24-222d-11e8-95a0-e0f358b9661c.png">

Here's the same chart with a color specified

<img width="503" alt="screenshot 2018-03-07 17 27 11" src="https://user-images.githubusercontent.com/816028/37122102-32d6d894-222d-11e8-9789-83a8831ceefd.png">

Whether you set the color like this:

```
$this->dataset('Members', 'area', array_values($ages))->color('#9400D3');
```

or like this:

```
        $this->options([
            'plotOptions' => [
                'series' => [
                    'color' => '#9400D3',
                ],
            ],
        ]);
```

The opacity is 100 and you don't see the lines behind.

Now I tried a few things to set the fillOpacity.. but nothing worked so far

```
        $this->options([
            'plotOptions' => [
                'area' => [
                    'fillOpacity' => '0.75'
                ]
            ],
        ]);
        // or
        $this->options([
            'plotOptions' => [
                'series' => [
                    'fillOpacity' => '0.75'
                ]
            ],
        ]);
```

**Comment by Phylu** [comment]
What works for me is defining a colorcode which contains transparency: 
```php
$this->dataset('Members', 'area', array_values($ages))
        ->color('#9400D3')
        ->backgroundColor('#9400D375');
```

**Comment by ConsoleTVs** [comment]
![image](https://user-images.githubusercontent.com/6124435/37219778-bff8c604-23c4-11e8-9a8c-83d06bf1b769.png)

![image](https://user-images.githubusercontent.com/6124435/37219787-c760714e-23c4-11e8-8943-b90ef610b245.png)


Hum...
