### ISSUE TITLE
unable to set the chart title for highcharts

### ISSUE THREAD

**Issue by vesper8** [ConsoleTVs/Charts#339]
I've dug pretty deep trying to figure out what's wrong

Setting the label works (for yAxis). But setting the title just does nothing.

I've tried both of these methods:

```
        $this->options([
            'title' => [
                'text' => 'test',
            ],
        ]);

        $this->title('test');
```

I've even verified that $this->title('test') does indeed enter the method in ConsoleTVs\Charts\Features\Highcharts\Chart::title()

It does go in, but if you inspect the source for the html the title is always set to null

**Comment by ConsoleTVs** [comment]
Will test it later :) can u post pic of the null value you inspect?

**Comment by vesper8** [comment]
![screenshot 2018-03-05 14 04 36](https://user-images.githubusercontent.com/816028/36994154-34349be6-207e-11e8-8e2d-fb28b09fed7b.png)

**Comment by ConsoleTVs** [comment]
I do see the title...

![image](https://user-images.githubusercontent.com/6124435/36994339-16d0afa8-20b1-11e8-9a1f-77f984da505d.png)

![image](https://user-images.githubusercontent.com/6124435/36994344-1f2fd5c0-20b1-11e8-9c4e-07e0213024ab.png)

**Comment by vesper8** [comment]
ahhh.. interesting

I am used to calling the parent constructor at the very end.. not before

so I was running it like this

```
    public function __construct()
    {
        $this->prepareChart();
        parent::__construct();
    }

    private function prepareChart()
    {
        $threads = Thread::all();
        $messages = Message::all();

        $labels = collect($threads->pluck('created_at'))->map(function ($date) {
            return $date->format('l jS M, Y');
        });

        $this->title("Daily Activity last {$this->metricDefaults['lastBy']['days']} days");

        $this->labels($labels);
        $this->dataset('Threads', 'line', $threads->pluck('count'))->color($this->colorTemplates['material'][0]);
        $this->dataset('Messages', 'line', $messages->pluck('count'))->color($this->colorTemplates['material'][1]);
    }
```

But if I run the parent::__construct() FIRST then it works:

```
    public function __construct()
    {
        parent::__construct();
        $this->setChartData();
    }
```

But everything else works if you call the parent::__construct(); last (which I thought was the usual and common way to do it?)

So I guess calling parent::__construct(); overrides the title

**Comment by ConsoleTVs** [comment]
It's because of the default options:

https://github.com/ConsoleTVs/Charts/blob/master/src/Classes/Highcharts/Chart.php#L36
