### ISSUE TITLE
[FEATURE] highcharts geo map not working in V6

### ISSUE THREAD

**Issue by vesper8** [ConsoleTVs/Charts#340]
So I was able to convert all my charts from V5 to V6 (I use Highcharts exclusively) except for the geo chart

For starters, looking at V5's geo.blade.php and looking at V6's script.blade.php, I can see that V6 only uses 

```
new Highcharts.Chart()
```

but V5's geo.blade.php used

```
new Highcharts.Map()
```

So right off the bat I can see it's not able to render it

Upon further debugging, it looks like in order to use Highchart's geo chart you need to load additional js scripts. And the way the series is initialized also differs.

Here's to hoping you add it back soon!

Let me know if you need anything else from me

Many thanks

**Comment by ConsoleTVs** [comment]
Thanks! Will check it out soon!
