### ISSUE TITLE
Charts as image/pdf attachments

### ISSUE THREAD

**Issue by kiiya** [ConsoleTVs/Charts#342]
Hi din't know where to ask this question so I hope this is the right place. Is there a way to attach generated charts to emails in Laravel.

**Comment by hichamhargal** [comment]
you must use an export server. if we take Highcharts for exemple, you may take a look at [this](https://github.com/highcharts/node-export-server).

**Comment by kiiya** [comment]
@hichamhargal Hi thanks for the heads up.
