### ISSUE TITLE
Time Axis

### ISSUE THREAD

**Issue by jyoansah** [ConsoleTVs/Charts#343]
Can I get some help in creating charts with time axis labels (using chartjs). How do I get the library to recognize and format timestamps on the axes. I have tried something like:

```
$chart->labels($chart_labels)->options([
			'scales' => [
				'xAxes' => [
					'type' => 'time',
					'time' => [
						'displayFormats' => [
							'hour' => 'hA'
						]
					]
				]
			]
		]);
```

The ```$chart_labels``` is a timestamp from the database. 

Thanks

**Comment by hichamhargal** [comment]
what is the output of your code?
