### ISSUE TITLE
Load All JS Chart

### ISSUE THREAD

**Issue by mdestafadilah** [ConsoleTVs/Charts#346]
Hi, I just need "Highcharts" and "Fusioncharts" ... like your examples.. but nothing show the chart
`{!! Charts::scripts(['morris','highcharts','fusioncharts']) !!}`

If i put this : `{!! Charts::scripts() !!}`
But all JS are loaded... it's too big only need highchart and fusionchart, any suggestion?

**Comment by ConsoleTVs** [comment]
There is no Charts:: in this library anymore. Read the docs. Specially in the end.
