### ISSUE TITLE
Background colors on dataset

### ISSUE THREAD

**Issue by ditsbroefs** [ConsoleTVs/Charts#347]
Wonderful module!

Question: how do I get background colors array on a chartjs dataset like here [http://www.chartjs.org/docs/latest/](url) ?

**Comment by ConsoleTVs** [comment]
I do not understand the question, but there are presets for colors and background colors for chartjs here:

https://github.com/ConsoleTVs/Charts/blob/master/src/Features/Chartjs/Dataset.php#L16

https://github.com/ConsoleTVs/Charts/blob/master/src/Features/Chartjs/Dataset.php#L34

simply call them:

```php
$chart->dataset('test', [1,2,3])->color('#ff0000')->backgroundColor('#00ff00');
```

**Comment by ditsbroefs** [comment]
That is a quick response! I did see the color(), but missed the backgroundColor(). That answers my question. Thanks.
