### ISSUE TITLE
The ability to include 2 or more years in "groupByMonth" charts

### ISSUE THREAD

**Issue by salehahmedZ** [ConsoleTVs/Charts#348]
Is it possible to include more then one year in the below code? 2017 and 2018 for example in the same chart.

```
$chart = Charts::database(User::all(), 'bar', 'highcharts')
    ->elementLabel("Total")
    ->dimensions(1000, 500)
    ->responsive(false)
    ->groupByMonth('2016', true);
```

**Comment by ConsoleTVs** [comment]
This is an outdatd and version, I am not able to help on this. I will keep it open if anybody wants to answer but i will close it after few days/weeks. Please update.
