### ISSUE TITLE
Can't hide color label

### ISSUE THREAD

**Issue by jfelipeara** [ConsoleTVs/Charts#35]
Hello!
Thank you for your package it has been really helpful. I want to hide the color label so the line can't be hidded. I can do that using chartjs but i don't know how to do it using your package.
Really man your package is awesome! Thanks a lot!
![image](https://cloud.githubusercontent.com/assets/10985977/19673669/919f6978-9a47-11e6-9f7f-2490acfee75b.png)

**Comment by ConsoleTVs** [comment]
Hola, hablo en español ya que veo que eres de colombia. Las opciones especificas de cada libreria aun no son soportadas, por lo que tendras que esperar alguna actualizacion posterior para añadir esos detalles. Las opciones actuales son generalizadas para ser funcionales en todas las linrerias. Este jueves podre seguir trabajando en esto. Gràcias por el apoyo!!

If you don't understand spanish and my guess was wrong, please tell me so I can translate it for you!

**Comment by jfelipeara** [comment]
Muchas gracias!

**Comment by ConsoleTVs** [comment]
De nada, cualquier otra duda no dudes en preguntar!
