### ISSUE TITLE
[FEATURE] Charts in Bootstrap tabs

### ISSUE THREAD

**Issue by etesan** [ConsoleTVs/Charts#350]
Hi!, 

I need to insert a Chart in a html tab. Is that possible?, i've tried everything but nothing. I'm using laravel 5.5. Is there any way to do this? a kind of 'tip' or something? the idea is insert a chart into multiple tabs in a single web page.

I hope you could help me!
Thanks

**Comment by ConsoleTVs** [comment]
This is a hard question due to tabs having a width of 0 while invisible. Will be keeping this open for posible solutions.

**Comment by ckissi** [comment]
This is something that I need too. Any idea?

**Comment by HdbKing** [comment]
It seems they need add a  function when cilck the tab they need render again. current src just render when page opened.
