### ISSUE TITLE
I have to refresh URl to load chart and also my sub menu is not working.

### ISSUE THREAD

**Issue by SwetaKhasale** [ConsoleTVs/Charts#351]
I am using Laravel Admin, I have created charts and it is working fine,  but it doesn't get loaded when i selected it from menu, i have to refresh my URl to load chart, and also my sub menus of left panel is not working once chart is loaded.
Please give solution
Thank you.

**Comment by ConsoleTVs** [comment]
Don't expect me to solve anythong if you don't tell me what tools are you using, no code pasted, no photos, no front end frameworks written, etc.

**Comment by atswe** [comment]
Sorry but I am new this so. 
I am using 
Laravel Admin 
 Laravel 5.3
My Flow is I will select Inventory->insights
Then the Chart should get loaded
But i have to refresh my url to load chart, it is not loading automatically.
Other thing once i refresh url and chart is loaded my sub-menu of admin panel are not working

Report Controller

public function index()
    {
         return Admin::content(function (Content $content) { 
         $ch = Inventory::where(DB::raw("(DATE_FORMAT(created_at,'%Y'))"),date('Y'))->select('created_at AS created_at')->get();

         $chart = Charts::database($ch, 'bar', 'highcharts')

            ->title("Monthly new Register Student")

            ->elementLabel("Total Student")

            ->dimensions(1000, 500)

            ->responsive(false)

            ->groupByMonth(date('Y'), true);
            
             return $content->body(view('ims.insight', ['chart' => $chart]));
           });
     }  
Report.blade.php
   {!! Charts::assets() !!}

<div>	
		{!! $chart->render() !!}
</div>

**Comment by ConsoleTVs** [comment]
Did you notice this charts version is old, right?

**Comment by atswe** [comment]
Okay then i will use new version
Thank You

**Comment by atswe** [comment]
Okay I have also new Charts 5.X documentation but still i have  same issue

**Comment by ConsoleTVs** [comment]
We are at charts 6.x...

**Comment by atswe** [comment]
Okayy I should try this now
