### ISSUE TITLE
Line chart help

### ISSUE THREAD

**Issue by yamin27** [ConsoleTVs/Charts#353]
Hi, 

I want to build a chart according to a monthly total amount. It looks like 
![screenshot from 2018-03-28 14-38-42](https://user-images.githubusercontent.com/10800658/38021754-8a6541b8-329f-11e8-86bf-d7301efd1e57.png)

how to do this?

**Comment by ConsoleTVs** [comment]
Did you even try reading the docs?

**Comment by yamin27** [comment]
yes, but I could not build this using database value. 

My Table : Payment 

Column: id, amount, status, created_at, etc

$chart = Charts::database(Payment::all(), 'line', 'highcharts')
    ->elementLabel("Total")
    ->dimensions(1000, 500)
    ->responsive(false)
    ->groupByMonth();

Do you please tell me, where i provide the monthly total amount?

**Comment by ConsoleTVs** [comment]
Ok, you clearly did not resd the docs. This is the old outdated version xd. You need to read the latest version and build the data yourself
