### ISSUE TITLE
Duplicate months in ConsoleTVs/Charts 5.x

### ISSUE THREAD

**Issue by jcadima** [ConsoleTVs/Charts#354]
<img width="1129" alt="screen shot 2018-03-30 at 8 40 50 pm" src="https://user-images.githubusercontent.com/2554115/38158020-efa4352c-345a-11e8-8e0d-f727776bd431.png">
instructions from:
https://github.com/ConsoleTVs/Charts/tree/5.4.0/docs/5#installation

WelcomeController:

```php
namespace App\Http\Controllers;

use App\User;
use Charts;
use Illuminate\Http\Request;

class WelcomeController extends Controller
{
    public function index()
    {
        $user_chart = Charts::database( User::all() , 'bar', 'highcharts')
			      ->title("Monthly User Registrations")
			      ->elementLabel("Total Users")
			      ->dimensions(1000, 500)
                  ->responsive(true)
                  ->groupByMonth(date('Y'), true);

        return view('welcome')->with('user_chart', $user_chart) ;
    }
}
```

**Comment by tpharaoh** [comment]
I don't know if it is your case, but that happened to me once when I had a
timezones discrepancy.

The timestamp was off by a few hours in my case causing overlap if any data
was too close to the cutoff time.

**Comment by jcadima** [comment]
i was going to try and change the default timezone but i noticed that the months are displaying fine now, 2 days ago i got duplicated months , didnt matter if the dates were too close to each other, i even tested in a new laravel install and got repeated months, but everything seems fine now.

Before the months were displaying fine i changed the option to list by last 6 months and it displayed perfectly fine with no repeating months( it was the only option ) :
```
public function index()
{
    $user_chart = Charts::database( User::all() , 'bar', 'highcharts')
    ->title("Monthly User Registrations")
    ->elementLabel("Total Users")
    ->dimensions(1000, 500)
    ->responsive(true)
    ->lastByMonth(6, true);

    return view('welcome')->with('user_chart', $user_chart) ;
}
```

**Comment by shreya-14-may** [comment]
I am facing this issue in production #
![image](https://user-images.githubusercontent.com/69234158/118349147-996bb400-b56c-11eb-9e5a-3d6807d13dfc.png)



But In my Local its working perfectly fine

<img width="1231" alt="Screenshot 2021-05-15 at 11 00 01 AM" src="https://user-images.githubusercontent.com/69234158/118349171-b6a08280-b56c-11eb-9266-fb8c2805400a.png">
