### ISSUE TITLE
Blade issue with Charts::scripts

### ISSUE THREAD

**Issue by robertnicjoo** [ConsoleTVs/Charts#355]
Hi,

When I use

```javascript
{!! Charts::scripts() !!}
```
my blade will mess up, what should i do?

![3](https://user-images.githubusercontent.com/8672823/38353883-0b23b080-38e2-11e8-825c-6775a899e7bb.png)

**Comment by robertnicjoo** [comment]
# SOLVED

I commented my unused libraries from `config/charts.php` and now my view loads as it supposed to.

but, main issue is by this line:

```php
'global' => [
  'scripts' => [
      'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js',
  ],
],
```

Thanks.

**Comment by ConsoleTVs** [comment]
You can pass an array to scripts function to output only libraries you want.

Also this is the old unsupported version. take care.

**Comment by robertnicjoo** [comment]
hi,
i had tried something like 
```
{!! Charts::scripts(['chart i use', 'other chart i use']) !!}
```

it gave ne error, that's why i comment scripts from config file.

1- how can i use array like you suggested?
2- what do you means by `Also this is the old unsupported version` what should I do?

thanks.

**Comment by ConsoleTVs** [comment]
Scriprs::(['chartjs'])

And click the link on the readme where it say docs in a big image.... You are using v.5. we are at 6.

**Comment by robertnicjoo** [comment]
@ConsoleTVs Hi,

I have removed old version and installed new version.

I'm a bit confused with new version the way it handles functions, in version 5 i used 2 scripts `highcharts` and `fusioncharts` all in `one controller` and `one function` now base on version 6 documents I have create 2 new controller in `App/Charts` folder with below details:

```php
<?php

namespace App\Charts;

use ConsoleTVs\Charts\Classes\Fusioncharts\Chart;

class providerusers extends Chart
{
    /**
     * Initializes the chart.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }
}
```
and

```php
<?php

namespace App\Charts;

use ConsoleTVs\Charts\Classes\Highcharts\Chart;

class sixmonths extends Chart
{
    /**
     * Initializes the chart.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }
}
```

# my questions are:

1. what is this and is that required to have?
```php
public function __construct()
    {
        parent::__construct();
    }
```

2. below i shared one of my functions in old version, `should i make new function in my new files (above)` ?
```php
$siteinfo = Charts::multiDatabase('line', 'highcharts')
          ->title("Site in last 6 months")
          ->dataset('users', User::all())
          ->dataset('products', Product::all())
          ->dataset('posts', Post::all())
          ->dataset('orders', Invoice::all())
          ->responsive(true)
          ->colors(['#3498db', '#f1c40f', '#2ecc71', '#2c3e50'])
          ->lastByMonth(6, true);
```

3. now that i have several controller `each for one of my scripts` how can I have all of them in one page?


Thank you.

**Comment by ConsoleTVs** [comment]
Depends on the aproch you lead when creating the chart (described in the docs) you may or not need the parent construct. If you need to do anything common shared in all charts and you need to do it in the class parent, then you need to czll the construxtor of the herited class (check how class extension works) to setup basic chart info.


Multidatabase or database charts are now not supported. You will need to build the data yourself. Reasons? Too many limitations and missundertanding / usage of it. Future? Perhaps a redisigned version may come one day.

Nobody tells you to create 1 controller for each chart. Theese are just examples. Charts are now classes. I think you missunderstand the power and the usage of classes with controllers.

**Comment by robertnicjoo** [comment]
Well thanks, I don't need `__construct()` understood now i can remove it,

but basically  what you say is version 5 much much more better (in my opinion)! why? because i was able to use 

1. `Charts::database('my model')`  and now i'm not anymore.
2. I was able to make multiple database data chart and now i'm not anymore.


> Nobody tells you to create 1 controller for each chart. Theese are just examples. Charts are now classes. I think you missunderstand the power and the usage of classes with controllers.

I don't want to make 1 controller for each chart, **what i want is to have all my charts within 1 controller as i had in version 5**. but now documents suggests to have `classes` outside of controllers folder.

**The questions i have is:**

1. how do i call my classes in my controller in order to load them in my view?
2. now what should i do with my `Charts::multiDatabase` & `Charts::create` cause apparently `Chart::` is not supported anymore and i get


```php
use ConsoleTVs\Charts\Classes\Fusioncharts\Chart as Charts;

Call to undefined method ConsoleTVs\Charts\Classes\Fusioncharts\Chart::database()
```

or

```php
use Charts;

Class 'Charts' not found
```

**Comment by AlexMalikov94** [comment]
Need remove this line that don't need  
```'fusioncharts' => [
            'scripts' => [
                //'https://static.fusioncharts.com/code/latest/fusioncharts.js',
                //'https://static.fusioncharts.com/code/latest/themes/fusioncharts.theme.fint.js',
            ],
        ],```
