### ISSUE TITLE
line highcharts backgroundColor not working

### ISSUE THREAD

**Issue by Yosef7908** [ConsoleTVs/Charts#356]
Hi,

I'm using Laravel 5.4 charts v5.

I set a backgroundColor of #f9f9f9, and the color will only be applied while the chart is loading. Once the chart is loaded, the color will go back to #ffffff.

my code
```
$today = Carbon::today();
$rmaData = Rma::where('created_at', '>', $today->subDays(7))->get();

        $rmaChart = Charts::database($rmaData, 'line', 'highcharts')
            ->title('RMA Tickets From The Last 7 Days')
            ->elementLabel("RMA Tickets")
            ->backgroundColor('#f9f9f9')
            ->dimensions(1000, 500)
            ->responsive(true)
            ->lastByDay(7, false);
```

**Comment by ConsoleTVs** [comment]
Line charts have no background color. Use color.

**Comment by Yosef7908** [comment]
I tried using color and I get this undefined method ```Call to undefined method ConsoleTVs\Charts\Builder\Database::color()```
