### ISSUE TITLE
Responsive Graphic

### ISSUE THREAD

**Issue by gersonsamayoa** [ConsoleTVs/Charts#360]
my graphic does not adapt to the width of my div

Controller 
 $chart = Charts::multi('bar', 'material')
            // Setup the chart settings
            ->title("Alumnos Perdidos por Curso")
            // A dimension of 0 means it will take 100% of the space
           ->responsive(true)
            // This defines a preset of colors already done:)          

            ->template("material")
            // You could always set them manually
            // ->colors(['#2196F3', '#F44336', '#FFC107'])
            // Setup the diferent datasets (this is a multi chart)
            ->dataset('Element 1', [5,20,100])
            // Setup what the values mean
            ->labels(['One', 'Two', 'Three']);

view
<div class="row">
	<div class="col-md-12">
		{!! $chart->html() !!}
	</div>
</div>

**Comment by ConsoleTVs** [comment]
This is the old version of the library!!
