### ISSUE TITLE
Uncaught SyntaxError: Unexpected token &

### ISSUE THREAD

**Issue by brysonreece** [ConsoleTVs/Charts#361]
Calling 
```php
$this->type('line'); 
```
in the __construct method of a Chart.js chart results in

```javascript
...
type: &#039;line&#039;,
...
```

in the generated JS, which leads to a 

```
Uncaught SyntaxError: Unexpected token &
```
error

**Comment by ConsoleTVs** [comment]
Forget what you know about charts 5.X. Learn how 6.X works. Charts do not have a "type" (well they do but just for render purposes), in fact, they do have DATASETS, and each dataset have a type. So if you want a single dataset chart, you'll need to call the dataset method once and add a line dataset for chartjs.

Setting the type of the chart is useless unless you know what you're doing.

Charts now work like a multiChart (from 5.X) all the times.

**Comment by brysonreece** [comment]
Then that would suggest the 6.X documentation is incorrect/incomplete, as seen here where I learned of the type method:
![ch](https://user-images.githubusercontent.com/4043157/38602404-3e97b162-3d30-11e8-8063-4025c4545433.PNG)

**Comment by ConsoleTVs** [comment]
It's not incorrect, the api have the type fuction because some libraries require it. You do not need to type it because the library sets it based on your datasets. So its ok to display it in the docs, but never suggested to be used. :) Following the tutorial you'll find I don't use it
