### ISSUE TITLE
Need Help As Soon As Possible

### ISSUE THREAD

**Issue by CELLDRAG** [ConsoleTVs/Charts#362]
I was trying to implement Chart with Laravel

For that I was trying to implement the row one with daily date and the column with daily collection ..But I'm not getting proper output means I was getting daily no of transaction not the total amount collected daily.

This is the code.

public function chartTwo()
    {
        $data = DB::table('members')
            ->select('members.created_at', DB::raw('sum(members.payment) as sum'))
            ->groupBy('members.created_at')
            ->get();

        $chart1 = Charts::database($data,'area', 'highcharts')
            ->elementLabel("Total")
            ->title('Monthly Collection')
            ->dimensions(1000, 500)
            ->responsive(false)
            ->groupByDay();
                return view('Charts.ChartTwo', ['chart1' => $chart1]);
    }

**Comment by ConsoleTVs** [comment]
Sorry but this is not the actual charts version and i'm not supporting anymore, it's obsolete and slow.

**Comment by ConsoleTVs** [comment]
I never used DB facade in laravel and part of the databse code was not developed by me. I'm sorry
