### ISSUE TITLE
Horizontal line with only a single value

### ISSUE THREAD

**Issue by Sebi94nbg** [ConsoleTVs/Charts#363]
Hi,
I've a lot of values, which I display and I would like to add an additional line which is just on the same value all the time, so that it shows a horizontal line, like this green one here:
![Line Chart - Highchart](https://i.imgur.com/YJUSZQh.png)
I couldn't find a solution / an option for creating such a line using a simple option with only one value.

I'm using `line` charts / `highcharts`.

Is this possible and if yes, how?

**Comment by Sebi94nbg** [comment]
Ok, so there is no function, only a workaround. :(

**Comment by ConsoleTVs** [comment]
It's not a workaround.

The library expects data. Data in a certain way. Arrays to be precise.

You're responsible of handling the data. Not me. Everybody have different data, everybody needs different things. This is a generic library, I won't solve your issues with managing data, laravel have collections to speed it up. either learn it and simply use the library or you'll need to do the same + implement all the JS logic. It's up to you.

**Comment by ConsoleTVs** [comment]
is it really that hard to add a constant line? It's what it is.

**Comment by Sebi94nbg** [comment]
Nope, it isn't that hard - I had already a solution.

I just thought, there is maybe an option to get such a line quicker.

Anyway: Thanks for your reply!

**Comment by ConsoleTVs** [comment]
Well, this library does not have either pure contact with the JS library nor the JS libraries probably support such thing without this hacks, so I dunno why did you expect it
