### ISSUE TITLE
Dataset matchValues breaks Chart.js line charts

### ISSUE THREAD

**Issue by brysonreece** [ConsoleTVs/Charts#372]
When adding datasets to a Chart.js time-type line chart, (if the datasets don't have the same number of datapoints), matchvalues in DatasetClass.php can lead to inconsistent behavior.

A solution I've gotten working is changing 
```php
while (count($this->values) < $values) {
    array_push($this->values, 0);
}
```

to

```php
while (count($this->values) < $values) {
    array_push($this->values, null);
}
```

Since I'm not sure how this affects other charts, I'm not going to attempt to make a pull request to avoid breakage.

However, would it be possible for this be implemented (if it works consistently), or could we get a possible ```treatEmptyValueAsNull``` configuration option in ```config/charts.php```? (Or some other way of configuring that behavior)

**Comment by ConsoleTVs** [comment]
What about overwritting the method in chartjs class only? This wont break the other charts, would it work?

**Comment by brysonreece** [comment]
That seems as if it would work. However in testing yesterday I noticed that while this does treat 0 values as null, the method of appending null values to $values doesn't account for ordering the data properly, along with matching the datapoint to the correct label.

For instance, if I have the following two arrays of data:

```php
$dataOne = [
    '10' => Carbon::now()->subDays(5)->toDateTimeString(),
    '20' => Carbon::now()->subDays(4)->toDateTimeString(),
    '40' => Carbon::now()->subDays(3)->toDateTimeString()
];

$dataTwo = [
    '30' => Carbon::now()->subDays(3)->toDateTimeString(),
    '50' => Carbon::now()->subDays(2)->toDateTimeString(),
    '60' => Carbon::now()->subDays(2)->toDateTimeString(),
    '70' => Carbon::now()->subDays(1)->toDateTimeString()
```

The resulting datasets **should** look like:

```php
$datasetOne = [10, 20, null, 40, null, null, null];
$datasetTwo = [null, null, 30, null, 50, 60, 70];
$labels = [
    Carbon::now()->subDays(5)->toDateTimeString(),
    Carbon::now()->subDays(4)->toDateTimeString(),
    Carbon::now()->subDays(3)->toDateTimeString(),
    Carbon::now()->subDays(3)->toDateTimeString(),
    Carbon::now()->subDays(2)->toDateTimeString(),
    Carbon::now()->subDays(2)->toDateTimeString(),
    Carbon::now()->subDays(1)->toDateTimeString()
];
```

However, the result is:
```php
$datasetOne = [10, 20, 40, null, null, null, null];
$datasetTwo = [30, 50, 60, 70, null, null];
$labels = [
    Carbon::now()->subDays(5)->toDateTimeString(),
    Carbon::now()->subDays(4)->toDateTimeString(),
    Carbon::now()->subDays(3)->toDateTimeString(),
    Carbon::now()->subDays(3)->toDateTimeString(),
    Carbon::now()->subDays(2)->toDateTimeString(),
    Carbon::now()->subDays(2)->toDateTimeString(),
    Carbon::now()->subDays(1)->toDateTimeString()
];
```

I can't think of any way to preserve order-matching between the datapoints and the labels without changing how datasets are constructed (perhaps by accepting key-value pairs of the datapoint and label), other than manually padding the data arrays outside of Chart construction and then later adding the correct arrays to a dataset.

**Comment by ConsoleTVs** [comment]
You can't set the null values to 0 when trying to call the chart?

**Comment by brysonreece** [comment]
You can, what I was getting at is that the label/data order is not preserved after ```matchValues``` is called.

**Comment by ConsoleTVs** [comment]
Well, cosnidering that the initial data is [0,0,0] and the match value is 4, a new 0 will be appended. This means that initial values are preserved... isn't it?

I don't have much time to look at this tho...

The only thing matchvalues does is increes the length of the array until they match. The initial array is not modified, so in fact, the error should be somewhere else?

**Comment by brysonreece** [comment]
Sort of, I'm pointing out that there's no way of preserving the _ordering_ of data, matching a specific datapoint to the corresponding label; so when matchValues() is ran, it simply appends 0s to fill the remaining space, but doesn't take into account what order those datapoints/0s should be in.
