### ISSUE TITLE
Pie and vertical bar examples

### ISSUE THREAD

**Issue by ibrunotome** [ConsoleTVs/Charts#374]
Hi, i've see your advertise about the "the docs are not that clear" ... "specially if you come from 5.X.", that is my case.

Can you provide any example of pie chart (can be chartjs or highcharts) and a vertical bar chart too?

Thanks for the great package.

**Comment by ConsoleTVs** [comment]
Yes. I will soon provide a video tutorial (a long one) with a complete tutorial. From installing the package to create cool charts in diferent libraries and types and customize them.
