### ISSUE TITLE
ChartsJS Plugins

### ISSUE THREAD

**Issue by pursehouse** [ConsoleTVs/Charts#379]
System is missing a way to set Plugins for ChartsJS

https://www.chartjs.org/docs/latest/developers/plugins.html

I'm switching to another js chart library but this'll hopefully help future people in need of the same thing. Good luck

**Comment by ConsoleTVs** [comment]
This package is not a chartjs package. It supports it, but not the extras are supported here. This package is meant for people who want a simple chart. If you need extra features of a single library, learn to use it with pure js.
