### ISSUE TITLE
Need help in laravel radar chart

### ISSUE THREAD

**Issue by ronyhendiartoo** [ConsoleTVs/Charts#380]
I've see and read the chart docs on how to create the radar chart. And the chart already created, but how can i use MySQL to connect with the radar chart. Still confusing right now.

The code on my controller is just like this: `$chart->dataset('*Employees Name*', 'radar', ['openness', 20, 100, 80, 90])->color('#ff0000');`
to show the radar chart. and it goes like this

![issue1](https://user-images.githubusercontent.com/34225677/41517740-779c0e4e-72e7-11e8-957b-040a3edb2a06.PNG) That is image number 1 ^

but, what im hoping is just like this
![hoping1](https://user-images.githubusercontent.com/34225677/41517753-980a508c-72e7-11e8-9f8a-cb39a5454763.PNG)

But all the data is connecting with MySQL. This 2nd image i created with manually input the data, not from the db.
Thankyou for your help, im sorry for having a bad English in this content.

**Comment by luccazx** [comment]
hii dude, did you resolved it ? 
if yes, how you do it ? i having dificult to use this graphic
