### ISSUE TITLE
Line chart with point data set

### ISSUE THREAD

**Issue by ghost** [ConsoleTVs/Charts#383]
How do I implement a line chart with a point dataset?

http://www.chartjs.org/docs/latest/charts/line.html#data-structure

I have an array of datetime/integer (x,y) points I would like to plot.

I tried passing $data in as array of x,y co-oords but that gave me a blank chart.

Great library! Thanks for the good work!

**Comment by bluedymension** [comment]
if you are using version 6, try this
$chart = new SampleHighChart;
$chart->title('Chart title')->labels([x-axis values array]);
$chart->dataset(SerieName', 'line', [y-axis values array])->color('#FF0000');
