### ISSUE TITLE
How to configure "lang"options to Highcharts?

### ISSUE THREAD

**Issue by bluedymension** [ConsoleTVs/Charts#385]
Hi, I would like to configure a thousands separator of values, and I read Highcharts docs, they said we need to configure the parameter in "lang" options like this https://api.highcharts.com/highcharts/lang.thousandsSep

How to configure it?

**Comment by ConsoleTVs** [comment]
Try 

```
$chart->options(['lang' => ['thousandsSep' => "here"]]);
```

**Comment by letrii** [comment]
> Try
> 
> ```
> $chart->options(['lang' => ['thousandsSep' => "here"]]);
> ```

This not working :(
