### ISSUE TITLE
Load AJAX chart with parameters

### ISSUE THREAD

**Issue by ched-7cups** [ConsoleTVs/Charts#386]
I must be missing something but how do I pass parameters to the load() function?  For example I want pass in a date range for my chart which I am loading over AJAX.  The last example on the docs just seems to be a GET request 

public function chart()
 {
  $chart = new SampleChart;
  $api = url('/test_data');  <-- I want to pass a date range here for example
  $chart->labels(['test1', 'test2', 'test3'])
   ->load($api) 
  return view('chart_view', ['chart' => $chart]);
 }

Anyway to get data with a POST?

**Comment by ConsoleTVs** [comment]
Why not using get parameters??

url("/test", ['param' => 1]) // /test?param=1

**Comment by cdric0701** [comment]
thanks for this advice, how to reload the chart with this ajax call ?

**Comment by digitlimit** [comment]
I have a form on the page for manipulating chart.
For example one can select a date range and I need API to return only records within the selected dates.

Now the problem is how to trigger a reload, and also send the selected dates to backend

**Comment by sardoj** [comment]
Now it is possible with the new 6.5 release.
Here is the documentation about this new feature: https://charts.erik.cat/api_charts.html#update-the-chart-after-rendering
