### ISSUE TITLE
Hiding gridlines

### ISSUE THREAD

**Issue by thierrymaasdam** [ConsoleTVs/Charts#387]
Good morning,

First of all thank you for the great package you've written. It really makes it easy for developers of Laravel apps to add charts to their projects.

Despite my gratitude, I've encountered a problem while attempting to get rid of the X and Y light-grey gridlines in the charts, as indicated in this image:

![screen shot 2018-06-23 at 13 48 51](https://user-images.githubusercontent.com/19410581/41816589-7611e908-7789-11e8-93c4-88fd6f1c2215.png)

Regardless of the settings I pass along with the chart, the lines stay the same. I am using **ChartJS**.

These are the options I've tried so far:

```
$chart['countrywide']
      ->labels(array_keys($data['countrywide']->toArray()))
      ->dataset('Logins', 'line', array_flatten($data['countrywide']->toArray()))
      ->options([
        'scales' => [
          'xAxes' => [
            'display' => false,
            'gridLines' => [
              'display' => false,
              'lineWidth' => 0,
            ],
            'scaleLabel' => false,
          ],
          'yAxes' => [
            'display' => false,
            'lineWidth' => 0,
            'gridLines' => [
              'display' => false,
              'lineWidth' => 0,
            ],
          ]
       ]
      ]);
```
Yet the lines still show. I've also opened an issue on Stackoverflow (https://stackoverflow.com/questions/51000938/how-to-get-rid-of-axis-lines-in-chartjs).

Any help will be appreciated. Thank you in advance.

**Comment by myurtsev** [comment]
in your chart class ;

`public function __construct()
    {
        parent::__construct();
        
        $this->displayAxes(false);
    }`

**Comment by thierrymaasdam** [comment]
Hmm, ok, that did the trick. Thanks a lot!

**Comment by ConsoleTVs** [comment]
There's a whole section in the docs dedicated to this....

![image](https://user-images.githubusercontent.com/6124435/41911033-ca7ffa66-794b-11e8-9263-3245c92d2490.png)

**Comment by thierrymaasdam** [comment]
Well, I couldn’t get it working at first, directly through the options. Thanks anyways!
