### ISSUE TITLE
start y axis value

### ISSUE THREAD

**Issue by Karpengold** [ConsoleTVs/Charts#388]
Hi, where I can find list of chart options? I tried scaleStartValue like in chartjs for start point for Y axis but this didn't work

**Comment by Karpengold** [comment]
```
$chart_followers = new \App\Charts\Followers();
 $chart_followers->options([
        'legend' => [
            'display' => false
        ],
        'scaleStartValue' => 100
    ]);
```

**Comment by ConsoleTVs** [comment]
Can you provide me with the official link in the chartjs docs where this "scaleStartValue" is located please?

**Comment by alexkarpxb** [comment]
@ConsoleTVs Sorry, I can't found it in official chartjs docs, only in some stackoverflow issues. In this case maybe do you know solution for setting start y value?

**Comment by ConsoleTVs** [comment]
That means oit does not exist in the latest version. Check the chartjs docs, I'm sure there was a similar setting like suggested min or something :)

**Comment by Karpengold** [comment]
Thanks, it was fixed by this strange solution:

` $chart->options([
        'scales' => [
            'yAxes' => [
             'display' => true,

            ]
        ]

    ]);`
