### ISSUE TITLE
Set the same color to bar chart

### ISSUE THREAD

**Issue by jfelipeara** [ConsoleTVs/Charts#39]
Hola!
Existe alguna forma de seleccionar un solo color en específico para todas las barras en el gráfico?
![image](https://cloud.githubusercontent.com/assets/10985977/19703902/425fe9bc-9acb-11e6-9e8e-2270db0f4a8a.png)

Este es mi código
```php
$chart_precipitacion = Charts::create('bar', 'chartjs')
    ->setElementLabel("Precipitación")
    ->setTitle('Precipitación')
    ->setColors(['#048B9A'])
    ->setLabels($lecturas_precipitacion_labels)
    ->setValues($lecturas_precipitacion_valores)
    ->setDimensions(1000,500)
    ->setResponsive(true);
```

**Comment by ConsoleTVs** [comment]
Hola! A peticion de ciertos usuarios, en el metodo "create" en las barras se tiene k especificar el color de cada una de las barras, individualmente. Aun asi, si no quieres repetir tanto codigo, puedes crear un grafico "multi" con un solo dataset, y este tendra pues, el primer color que le pases en todas las columnas (ya que los colores el los "multi" son para cada dataset)

**Comment by jfelipeara** [comment]
Perfecto muchas gracias!

**Comment by ConsoleTVs** [comment]
Otras cosas; te recomiendo siempre la opcion setResponsive(false) y las dimensiones, con la width a 0 (esto adapta el grafico horizontalmente, pero verticalmente tendra la altura que le indiques)

Asi se adapta a distintos tamaños de pantalla. Recuerda que si la opcion responsive esta a true (que es por defecto) ignorara por completo las dimensiones!!
