### ISSUE TITLE
Issue when populating labels from array 

### ISSUE THREAD

**Issue by CharlesBilbo** [ConsoleTVs/Charts#390]
Its seems that populating a label from array fails to work while using the same array to populate values works just fine. is this issue fixed in future versions as I'm using an older package, thank you. 

the returned data from the $date variable

`"2018-07-06,2018-06-29,2018-05-31,2018-04-30,2018-03-29,2018-02-28,2018-01-31,2017-12-29,2017-11-30,2017-10-31,2017-09-29,2017-08-31,2017-07-31,2017-06-30,2017-05-31,2017-04-28,2017-03-31,2017-02-28"`

        ```
$date = [];
        foreach ($result as $key) {      
                    $date = $key;  
           }
           $date = array_keys($date);
           $date = implode(' ' , $date);
        
        $data = implode(" ,", $data);
        $line =  Charts::create('line', 'highcharts')
        ->title('dates')
        ->labels([$date])
        ->values([$data])
        ->dimensions(0,500);
```

**Comment by ConsoleTVs** [comment]
From my view, this is an horrible code.

1. The date variable is beeing replaced serveral times. When calling array keys, it gets replaced with an array of keys, potentially, array of integers.
2. adding ->labels([$variable]) only adds 1 element to the labels. Not as many as $variable.
3. Same for values

**Comment by CharlesBilbo** [comment]
Thank you for your comment but the data that date contains is listed above if the same format works in values why does it not work in labels. The array keys does not return until but returns dates such as 2018-07-06 if these are separated by a comma why does it not act the same than if I manually put in the dates.

**Comment by ConsoleTVs** [comment]
so this:

```
"2018-07-06,2018-06-29,2018-05-31,2018-04-30,2018-03-29,2018-02-28,2018-01-31,2017-12-29,2017-11-30,2017-10-31,2017-09-29,2017-08-31,2017-07-31,2017-06-30,2017-05-31,2017-04-28,2017-03-31,2017-02-28"
```

is the result of $data just before entering the chart creation??

If so:

1. The values need an array of data, not strings
2. You just need to split the data separated by , and pass all the array to the labels.

```php
->labels(explode(',', $data))
```

**Comment by CharlesBilbo** [comment]
Correct that is the data that is listed just before date is called in label. Its strange because if I put date into value everything works as intended but labels seems to not but I will try your solution when I get home

**Comment by CharlesBilbo** [comment]
thank you for your time, your solution worked well for me. Also would you happen to have a link for the old documentation  ?

**Comment by ConsoleTVs** [comment]
Nope, but luckly it's hosted on github. So get to an old repository tag and you'll see a docs folder
