### ISSUE TITLE
Wrong path is you use php artisan make:chart VerticalBar chart.js

### ISSUE THREAD

**Issue by esorone** [ConsoleTVs/Charts#395]
Hey There,

The default path in Laravel is shown as:
use ConsoleTVs\Charts\Classes\Chart.js\Chart;

In stat of use ConsoleTVs\Charts\Classes\Chartjs\Chart;

So the will give you a wrong start

**Comment by ConsoleTVs** [comment]
Type Chartjs or leave it blank. Its default already. The docs tell u to look the folder name to specify it. It turns our ir have no '.' so you're just making it wrong :)

**Comment by esorone** [comment]
Sorry for the confusion. This happend while Creating the controller. I Geus I called the library Chart.js
