### ISSUE TITLE
RuntimeException : fatal : reference is not a tree

### ISSUE THREAD

**Issue by rkarmann** [ConsoleTVs/Charts#396]
Hi, 

I'm trying to retrieve consoleTVs chart library on a 5.2.29 Laravel installation. But as soon as I run the 
`composer require consoletvs/charts:6.*`
I get the following error : 

>  [RuntimeException]
  Failed to execute git checkout 'c404b7fc0e04ddf5d298e53105c5fc306f523195' -
> && git reset --hard 'c404b7fc0e04ddf5d298e53105c5fc306f523195' --

> fatal: reference is not a tree: c404b7fc0e04ddf5d298e53105c5fc306f523195`

Composer is up-to-date (1.6.5) and i'm using a Linux 16.2 web server.

Thanks in advance

**Comment by rkarmann** [comment]
Just so you know, by default, composer try to install 6.2 version, which gives a RuntimeException Error. 

I tried : 
`composer require consoletvs/charts:6.1`

And it worked perfectly.

**Comment by ConsoleTVs** [comment]
OK few things:

- The error is caused by your git. Not releated to this I guess?
- Linux have no web server. You're probably using either apache or nginx.

Be more specific.

**Comment by soemoethunyaunggaing** [comment]
@ConsoleTVs 
how to solve consoletvs/charts my local is find ,but error on server 

![Screenshot from 2020-02-04 17-09-02](https://user-images.githubusercontent.com/34773575/73737704-86ffa980-4771-11ea-87c1-0c89a743bd0a.png)

**Comment by ConsoleTVs** [comment]
You need bcmath enabled in your phpini file

**Comment by soemoethunyaunggaing** [comment]
thanks bro
