### ISSUE TITLE
Only show one data

### ISSUE THREAD

**Issue by radityaputranto** [ConsoleTVs/Charts#398]
![image](https://user-images.githubusercontent.com/18069998/43595269-74467bac-96a6-11e8-9ef9-7a6456e3885b.png)

my chart only show one data

![image](https://user-images.githubusercontent.com/18069998/43595348-9d6ce3ae-96a6-11e8-9179-1603bafd881c.png)

![image](https://user-images.githubusercontent.com/18069998/43595395-be952258-96a6-11e8-809c-7fc78e5e7c79.png)

**Comment by davodsaraei** [comment]
@radityaputranto You must add label method
like below
`$chart->label(['One','Two'])`
