### ISSUE TITLE
ChartJS on mobile

### ISSUE THREAD

**Issue by ronnievisser** [ConsoleTVs/Charts#400]
Hi,

Thank you for the package. I'm using it with chartjs and it works fine on laptop. However when I try to view the charts on a mobile device I only see the preloader. the actual chart is not coming.

I this something you have heard before? any ideas what I could do to fix this?

thanks

**Comment by ConsoleTVs** [comment]
Never heard that before. What OS and browser are u using?

Want me to be honest? This package uses fetch(). It is available in the major browsers nowadays. Update yours ;)

**Comment by ConsoleTVs** [comment]
I have no apple device to test this on... Are they both updated? What about firefox? Have u got a way to see js console?

**Comment by ronnievisser** [comment]
All is on latest versions. Will try Firefox ASAP.
