### ISSUE TITLE
Chart command

### ISSUE THREAD

**Issue by davodsaraei** [ConsoleTVs/Charts#401]
@ConsoleTVs I change the default laravel app path and when I use `make:chart` command an app folder created as default and no way to change it.

**Comment by ConsoleTVs** [comment]
I'll mark this but it's on the low proiority...

**Comment by Naoray** [comment]
@davodsaraei how did u change the default laravel app folder? (Asking to understand how to implement your request)

**Comment by Kenneththumi** [comment]
Got this error where i installed the package following the instr. from the installation page. '                                  
  Command "make:chart" is not defined.  
                                        
'

**Comment by Naoray** [comment]
@Kenneththumi have you added `ConsoleTVs\Charts\ChartsServiceProvider::class,` to your `config/app.php` in the `providers` array?

**Comment by Kenneththumi** [comment]
Yeah...after installing the package

**Comment by Naoray** [comment]
Then you have to provide us with more information. Show us that you really added the provider to the config. Show us the `php artisan` output...
