### ISSUE TITLE
How do  Line chart start in 0..?

### ISSUE THREAD

**Issue by vinothabc** [ConsoleTVs/Charts#406]
Hi,
How do line chart start  in 0..
My input 

$date= array(0,'8 Aug 2018');
$amount_array = array(0,1150);

My coding 
$this->view_data['earning_chart'] = Charts::multi('line', 'highcharts')
			->title("Earnings")
			->dimensions(0, 500)
			->elementLabel(" ")
			->dataset('Earnings', @$amount_array)
			->labels(@$date)
			->colors(['#43A422']); 

Please refer this screen short.

<img src="http://i.prntscr.com/MaqMCsaQTWWeVXS6Q5XRGA.png">

**Comment by ConsoleTVs** [comment]
```php
$amount_array = array(0,1150);
```

Because you tell it to.
