### ISSUE TITLE
Nothing work except chartjs

### ISSUE THREAD

**Issue by mohamedsabil83** [ConsoleTVs/Charts#408]
I just installed the latest version of charts in my laravel 5.6
Copy and paste all js library source. When I make a chart for Chartjs it's working like a charm. but when I try same with other it's returned chart type not supported.

Does only Chartjs is working for now or what?

**Comment by tpharaoh** [comment]
There is a list of supported charts and features on his page

**Comment by mohamedsabil83** [comment]
It's clear I know that cause I said just **chartjs** work, not others. Any requirement to other chart work maybe license from its original site?

**Comment by ConsoleTVs** [comment]
Paste the code of a non-working code with another supported library.

**Comment by makuser** [comment]
> Paste the code of a non-working code with another supported library.

Sure. Lets look at Echarts for example @ConsoleTVs.

```php
$chart = new Echart;
$chart->labels(['Date', 'Liter/Day']);

$dataset = collect([]);
foreach ($transactions as $transaction) {
    $dataset->push([$transaction->date, $transaction->volume]);
}

$chart->dataset('My dataset', 'line', $dataset);
```

Actually I wanted to use the type 'scatter' instead, with the coordinate system 'calendar' instead (https://ecomfe.github.io/echarts-examples/public/editor.html?c=calendar-effectscatter), but since that did not work, because it is impossible to use your 'options' function to set the appropriate options (because we need to add something to the series array itself, not to the outer array), I tried the 'line' type.  
I expected at least this was something that would work OOTB, because of this:
> Echarts in the other hand is a great library. It have a lot of customization and support for long datasets. It also have an easy API.
https://charts.erik.cat/supported_libraries.html#echarts-4-0-2

But no, not even the line chart works with the x-axis being a date.

**Comment by ConsoleTVs** [comment]
![imagen](https://user-images.githubusercontent.com/6124435/53707751-8e675600-3e30-11e9-8818-7d2c76ae15ab.png)
![imagen](https://user-images.githubusercontent.com/6124435/53707755-945d3700-3e30-11e9-8e49-2355876214bd.png)
![imagen](https://user-images.githubusercontent.com/6124435/53707763-99ba8180-3e30-11e9-972b-23d534d83197.png)
![imagen](https://user-images.githubusercontent.com/6124435/53707773-a17a2600-3e30-11e9-9b21-5f927884abf2.png)

**Comment by ConsoleTVs** [comment]
Additionaly:

Is it really that hard to calculate 2 arrays. 1 of strings and 1 of values? Like, hell, they are dates, okay, so what, represent them as strings and map it to a value?

**Comment by ConsoleTVs** [comment]
Oviously, this library supports the basic types of chars + all their config. This includes lines, bars, pies, etc. A calender isn't even part of most of the charting libraries. However, it could be possible to add it with modifications to how the echarts specifically is handled. Pull requests are welcome, but understand a few things:

1. All the libraries have been tested with at lest pie, line, area and bar.
2. The library is a generic implementation of the real JS code and it injects the array where it needs it.
3. For really complicated things (well, I'm looking at you mr.calendar) Go for a full JS implementation.
4. The documentation says "supported types" it means supported by the JS library, not this one. Most likely can be confusing and will change that.

This library solves most ocmmon cases of charts + the needed customization needed. For really wierd stuff or other releated matters, a full js implementation would actually be ideal and yet preferable to tunning this library.
