### ISSUE TITLE
Failed to make a stacked bar chart using Chartjs 

### ISSUE THREAD

**Issue by husonghua** [ConsoleTVs/Charts#409]
I use "consoletvs/charts": "6.2". I tried to make a stacked bar chart using chartjs and failed. Below is my code and the chart generated. I cannot get the bars to stacked. In stead, the bars are side-by-side. Cannot figure out why. Please help.

```php
    public function generate_chart()
    {
        $chart = new DefaultChart;
        $chart->title('Chart Title');
        $chart->labels(['one', 'two', 'three']);
        $chart->dataset('Count 1', 'bar', [1,2,3]);
        $chart->dataset('Count 2', 'bar', [1,2,3]);
        $chart->options([
            'scales' => [
                'yAxes' => [
                    'stacked' => true
                ],
                'xAxes' => [
                    'stacked' => true
                ]
            ]
        ]);
        return $chart;
    }
```

![work factory v2](https://user-images.githubusercontent.com/844636/44625579-91055380-a8c1-11e8-9f89-b829b385df73.png)

**Comment by ConsoleTVs** [comment]
Do me a favour. Check what's the generated JS in the rendered page, and compare it with your working JS solution. The thing is that it's a multi char (http://www.chartjs.org/samples/latest/charts/combo-bar-line.html) and idk if the stacked bar is supported on a multi one. Just paste the generated code here and try to compare it with a working solution

**Comment by oheck** [comment]
`'scales' => [
                'xAxes' => [
                    ['stacked' => true]
                ],
                'yAxes' => [
                    ['stacked' => true]
                ],
            ]`

@husonghua ... the array definition for stacked is wrong. that is the problem.
