### ISSUE TITLE
syntax error, unexpected ' ' (T_STRING), expecting ';' or '{'

### ISSUE THREAD

**Issue by rzkyfirdaus** [ConsoleTVs/Charts#411]
i have been following the steps , Is there something wrong? thank you
![untitled](https://user-images.githubusercontent.com/28534844/44710809-2d547380-aad7-11e8-9228-e447b64094e9.png)

**Comment by ConsoleTVs** [comment]
Your array on line 15 have to be an array of numbers, not an array of 1 string.

[1, 2, 3, 4]

You have 

['1, 2, 3, 4']

**Comment by rzkyfirdaus** [comment]
sorry i wrong image , this is true
![sss](https://user-images.githubusercontent.com/28534844/44718386-123f2f00-aaea-11e8-9c96-e15017dca8e2.png)

**Comment by ConsoleTVs** [comment]
Can u copy the whole thinf by hand in another file? Sometimes copy-paste do this. You're not the firsr with this error but I see nothing wrong...

**Comment by AfiMorgan** [comment]
@ConsoleTVs 
I ran into this issue recently.  It is a white-space issue caused by copying and pasting.

@rzkyfirdaus
To fix it, remove all indentation inside the class and then manually add it back.

**Comment by ConsoleTVs** [comment]
https://twitter.com/ErikCampobadal/status/1034820996098875392?s=19

**Comment by rzkyfirdaus** [comment]
oke thanks you
