### ISSUE TITLE
[BUG] Chartjs Unix Timestamp format

### ISSUE THREAD

**Issue by wildbillharris** [ConsoleTVs/Charts#412]
Hello,

I'm having trouble setting up a line chart in chartjs whereby the x-axis input is a time/date format. I would like to set up the step sizing between x-axis dates. The chartjs documentation explains that it supports all momentjs formats which include Unix timestamp. However, when I enter these into the graph it does not convert the int unix value into date format. 

<img width="950" alt="screen shot 2018-09-02 at 9 06 15 pm" src="https://user-images.githubusercontent.com/20120576/44955280-0db4b500-aef4-11e8-9b98-e9fa08f08ba6.png">

<img width="418" alt="screen shot 2018-09-02 at 9 05 09 pm" src="https://user-images.githubusercontent.com/20120576/44955271-e958d880-aef3-11e8-816e-fb2919f911e7.png">

**Comment by engineeve** [comment]
Did you find a solution to this issue? I have the same problem !

**Comment by Mahmood-Hussain** [comment]
@wildbillharris did you find any solution this problem finally?
