### ISSUE TITLE
Error Type atribute: NO string escape therfore script error

### ISSUE THREAD

**Issue by bouwehand** [ConsoleTVs/Charts#415]
In your file /consoletvs/charts/src/Views/chartjs/script.blade.php on line 8 string escape is missing. Therefore, javascript is displayed as:             

`type: &#039;bar&#039;,`

correct line in  /consoletvs/charts/src/Views/chartjs/script.blade.php on line 8 should be:

`8.            type: {!! $chart->type ? "'$chart->type'" : 'data[0].type' !!},`

**Comment by ConsoleTVs** [comment]
Fixed!

**Comment by bouwehand** [comment]
nice!
