### ISSUE TITLE
Can't hide x-axis labels on ChartJs

### ISSUE THREAD

**Issue by eoghan27** [ConsoleTVs/Charts#417]
Hi there,

I'm having trouble hiding the x-axis labels using Chartjs library. I've attempted to add it in the options like so:

`$chartVisitors->options([
                    'scales' => [
                        'xAxes' => [
                            'ticks' => [
                                'display' => false
                            ]
                        ]
                    ]
            ]);`

I've confirmed it shows in the script on the page, but the labels still show. I can confirm that the minimalist method hides both axes well, but I need to show the Y axis labels and hide the X. 

Can you please help?

**Comment by renardudezert** [comment]
Hi,

If you only want to hide the X axis (and labels), this line should work :
$chartVisitors->options([ 'scales' => [ 'xAxes' => [ 'display' => false ] ] ]);

**Comment by nestorrecinosUCA** [comment]
It doesn't work for me. When I do it, it hides the whole chart
