### ISSUE TITLE
ReferenceError: Chart is not defined

### ISSUE THREAD

**Issue by marufmax** [ConsoleTVs/Charts#421]
I follow everything what said in documentation. I've called the `{!! $chart->script() !!}` method. But I am still getting

>  ReferenceError: Chart is not defined

I am using: Laravel 5.7 and PHP 7.1 

Is anything I missed? 
Thanks

**Comment by ConsoleTVs** [comment]
I need you to post a screenshot of the error please.

**Comment by marufmax** [comment]
Error: [https://i.imgur.com/EXJlygO.png](https://i.imgur.com/EXJlygO.png)
View: [https://i.gyazo.com/d24da68715f0033e0f22069d6ec172f2.png](https://i.gyazo.com/d24da68715f0033e0f22069d6ec172f2.png)
Controller: [https://i.gyazo.com/1588704e0c01c2216a26853ec2a19904.png](https://i.gyazo.com/1588704e0c01c2216a26853ec2a19904.png)
Package.json: [https://i.gyazo.com/c402f5386c29183bf2f57fc6edd8c307.png](https://i.gyazo.com/c402f5386c29183bf2f57fc6edd8c307.png)

**Comment by marufmax** [comment]
Solve it. I have to put the charting script before. Thanks for reply.
