### ISSUE TITLE
 API/Ajax Charts not working

### ISSUE THREAD

**Issue by therealartz** [ConsoleTVs/Charts#425]
Basic example from [docs](https://charts.erik.cat/api_charts.html) doesn't works.

Installed last version `composer require consoletvs/charts:6.*`.
Created chart `php artisan make:chart MyChart`.

Test routes:
```
Route::get('/', function() {
    $chart = new MyChart();
    $chart->labels(['test1', 'test2', 'test3'])
        ->load(url('/data'));
    return view('home', compact('chart'));
});

Route::get('/data', function () {
    $chart = new MyChart();
    $chart->dataset('Sample Test', 'bar', [3,4,1]);
    $chart->dataset('Sample Test', 'line', [1,4,3]);
    return $chart->api();
});
```

Test view:

```
@extends('layouts.app')

@section('content')
    {!! $chart->container() !!}
@endsection

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js" charset="utf-8"></script>
    {!! $chart->script() !!}
@endsection
```

Everything loads. No errors in console.

/data route returns response:
```
[{"borderWidth":2,"data":[3,4,1],"label":"Sample Test","type":"bar"},{"borderWidth":2,"data":[1,4,3],"label":"Sample Test","type":"line"}]
```

On the screen nothing but loading spinner:

![image](https://user-images.githubusercontent.com/21292595/47150883-c4bc9280-d2e0-11e8-8ded-9d1b5de76df5.png)

What is wrong and how to resolve it?

**Comment by ConsoleTVs** [comment]
They work. Can you post the JS error that probably prompted on the console?

**Comment by therealartz** [comment]
Unfortunately no errors or any outputs in console

**Comment by ConsoleTVs** [comment]
What about the network tab? any failed request?

**Comment by therealartz** [comment]
No failed requests too.

Maybe I missed something on setup?

**Comment by ConsoleTVs** [comment]
Does the request hit? Can you spot the correct request in the network tab? A screenshot would help :)

Also, paste the generated view code (only the container and the script section)

**Comment by therealartz** [comment]
Yes, request are hitted and finished with code 200. It returns correct json (I pasted it in first message).

**Comment by therealartz** [comment]
This problem exists only with debugbar (barryvdh/laravel-debugbar package) enabled.

Solved with disabling debugbar for api request.

**Comment by rafael1delgado** [comment]
> Basic example from [docs](https://charts.erik.cat/api_charts.html) doesn't works.
> 
> Installed last version `composer require consoletvs/charts:6.*`. Created chart `php artisan make:chart MyChart`.
> 
> Test routes:
> 
> ```
> Route::get('/', function() {
>     $chart = new MyChart();
>     $chart->labels(['test1', 'test2', 'test3'])
>         ->load(url('/data'));
>     return view('home', compact('chart'));
> });
> 
> Route::get('/data', function () {
>     $chart = new MyChart();
>     $chart->dataset('Sample Test', 'bar', [3,4,1]);
>     $chart->dataset('Sample Test', 'line', [1,4,3]);
>     return $chart->api();
> });
> ```
> 
> Test view:
> 
> ```
> @extends('layouts.app')
> 
> @section('content')
>     {!! $chart->container() !!}
> @endsection
> 
> @section('scripts')
>     <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js" charset="utf-8"></script>
>     {!! $chart->script() !!}
> @endsection
> ```
> 
> Everything loads. No errors in console.
> 
> /data route returns response:
> 
> ```
> [{"borderWidth":2,"data":[3,4,1],"label":"Sample Test","type":"bar"},{"borderWidth":2,"data":[1,4,3],"label":"Sample Test","type":"line"}]
> ```
> 
> On the screen nothing but loading spinner:
> 
> ![image](https://user-images.githubusercontent.com/21292595/47150883-c4bc9280-d2e0-11e8-8ded-9d1b5de76df5.png)
> 
> What is wrong and how to resolve it?

A possible solution would be to return as follows:

`return $chart->api(); with return json_decode($chart->api());`
