### ISSUE TITLE
multi line highchart with varying count of points fills with zeroes.. why ?

### ISSUE THREAD

**Issue by vesper8** [ConsoleTVs/Charts#426]
I've noticed that if you add multiple datasets to a multiline, if some of your datasets contain more points than others, it will cause the shorter datasets to be filled with 0s

dataset1=1,2,3,4,5
dataset2=1,2,3

in the resulting chart data generated by using the ->dataset() functions, dataset2 will contain 1,2,3,0,0

this makes the line drop to zero instead of just stopping early.. which is undesired

not quite sure what is causing this to happen.. but I'm betting you have an idea!

**Comment by ConsoleTVs** [comment]
Yes I do, this is intentional. Not all libraries support the line to stop a certain point, I will be happy to accept any PR for specific library changes. Each library is now in it's own class so it can be modified :)

**Comment by vesper8** [comment]
I see.. well at least it would be useful to be able to pass an optional parameter to dataset() so that it doesn't do this

for now I've resorted to filtering out the zeros in my javascript like so

```
    setChartData() {
      this.chartOptions = this.chartData.options;

      this.chartOptions.chart = {
        renderTo: this.renderTo,
        height: 400,
      };

      this.chartOptions.xAxis = {
        categories: this.chartData.labels,
      };

      this.chartOptions.series = JSON.parse(this.chartData.datasets);

      // filter out any 0 values from datasets
      for (let index = 0; index < this.chartOptions.series.length; index += 1) {
        this.chartOptions.series[index].data = this.chartOptions.series[index].data.filter(i => i !== 0);
      }

      this.chart = new window.Highcharts.Chart(this.chartOptions);
    },
```

**Comment by Otsoko** [comment]
Faced the same problem. I solved this by using no categories (not using the `$chart->labels()` method), but I think this is only suitable for _datetime_ charts where there is no need of hand-made labels. (I am using _datetime_ charts).

This generates the default `categories: []` code on the `xAxis` options field.

This default behaviour breaks the way Highcharts generates datetime labels. I will comment this on its own issue.
