### ISSUE TITLE
[BUG] PHP 7.2 countable error?

### ISSUE THREAD

**Issue by liharsw** [ConsoleTVs/Charts#427]
issue php 7.2 in file init.blade.php

im running on php **PHP 7.2.10 (cli) (built: Sep 11 2018 11:22:20) ( NTS )**

"consoletvs/charts": "6.*",
"laravel/framework": "5.6.*",

`
Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: count(): Parameter must be an array or an object that implements Countable (View: /usr/share/nginx/html/resources/views/vendor/charts/init.blade.php) (View: /usr/share/nginx/html/resources/views/vendor/charts/init.blade.php)
`

thank you sir.

**Comment by ConsoleTVs** [comment]
"PHP 7.2.10 (cli) (built: Sep 11 2018 11:22:20) ( NTS )" This is the CLI version of PHP, not the server version.

I never expirienced this error before... I will need more information. Perhaps the system you're running it on, and a bit of debugging on your side will help

**Comment by liharsw** [comment]
i think the error from function script() in class BaseChart, my temporary solved downgrade php for now sir., 

countable maybe.

`
if (count($this->datasets) == 0 && !$this->api_url) {
            throw new \Exception('No datasets provided, please provide at least one dataset to generate a chart');
        }
`
