### ISSUE TITLE
php artisan make:chart error

### ISSUE THREAD

**Issue by EmanSayma** [ConsoleTVs/Charts#428]
hi
when I try to write php artisan make:chart MonthlySales Highcharts
and choose any charts library this error appears : 

In ChartsCommand.php line 51:                                                                       
  Call to undefined method Illuminate\Console\GeneratorCommand::handle()  

so whats the problem

**Comment by Otsoko** [comment]
Perhaps that error arises because of your laravel version.

Same happened to me with laravel 5.4; after updgrade to laravel 5.5 the `make:chart` command worked for me.

Whats is your laravel version?

**Comment by floppyfish212** [comment]
Works on Laravel 5.6.

**Comment by Naoray** [comment]
Seems like `GeneratorCommand` had a `fire` method in 5.4 instead of a handle.
