### ISSUE TITLE
datetime highcharts

### ISSUE THREAD

**Issue by Otsoko** [ConsoleTVs/Charts#430]
¡Hola!

I am using version 6 of ConsoleTVs/Charts, and using it to render _datetime_ charts with highcharts.

The way highcharts takes the data is easy, the series must be an array of `[timestamp, value]` as follows:

`"data":[[1540232762000,0.45],[1540232777000,2.37],[1540232792000,1.94]]`

After that, highcharts itself calculates the best representation for the ticks taking into account the lengh in time of that data (seconds, days, months, years, ...) and generates the labels based on that.

Well, this only works if the highcharts option `xAxis.categories` is not present, or it is present as `categories: null`

The problem is that ConsoleTVs/Charts generates a `categories: []` code when the `$chart->labels()` is not used, which invalidates highcharts label based on timestamp generation.

I think the simplest way to solve this is enable the `xAxis.categories` option **only** when there is any label. I propose the following code change that worked for me:

In \vendor\consoletvs\charts\src\Classes\Highcharts\Chart.php change method `formatOptions` as follows:

```    /**
     * Format the options for highcharts.
     *
     * @return string
     */
    public function formatOptions(bool $strict = false, bool $noBraces = false)
    {
        if(count($this->labels)>0) {
            $this->options([
                'xAxis' => [
                    'categories' => json_decode($this->formatLabels()),
                ],
            ]);
        }

        return parent::formatOptions($strict, $noBraces);
    }
```
Just adding the `if` statement to check if there is any label for the chart.

Hope someone finds this useful : )

**Comment by joeelia** [comment]
@Otsoko  Nice your solution really helped me!

To convert the standard Laravel timestamp from DB to 13 digit epoch UNIX timestamp (required by Highcharts) I used this code:

`    	$sales = Sale::select('price','created_at')->get();
		foreach ($sales as $sale)
    		{
    			$timestp = Carbon::createFromFormat('Y-m-d H:i:s' ,$sale->created_at ,'America/Chicago')->timestamp*1000;
    			$values[] = array($timestp,$sale->price);
    		}
		$chart = new Test;
		$chart->dataset('My dataset', 'line', $values);
		$chart->options([
			'xAxis'=> [
    			'type' => 'datetime',
        		'dateTimeLabelFormats' => [
            		'millisecond' => '%H:%M:%S.%L',
   	 				'second' => '%H:%M:%S',
    				'minute' => '%H:%M',
    				'hour' => '%H:%M',
    				'day' => '%e. %b',
    				'week' => '%e. %b',
    				'month' => '%b \'%y',
    				'year' => '%Y'
        		]
    		]
		]);

        return view('chart', ['chart' => $chart]);`

Maybe somebody should submit a PR and add to the documentation....for your fix when you do not define labels.

**Comment by ConsoleTVs** [comment]
Thank you! This was finally added: https://github.com/ConsoleTVs/Charts/blob/master/src/Classes/Highcharts/Chart.php#L48
