### ISSUE TITLE
Amended title size in Chart code was not reflected in rendered page

### ISSUE THREAD

**Issue by floppyfish212** [ConsoleTVs/Charts#432]
Hi all,

I've changed $font_size from 14 (default) to 48, but this was not reflected in the rendered page. Any ideas?

```
  /**
     * Set the chart title.
     *
     * @param string $title
     * @param int    $font_size
     * @param string $color
     * @param bool   $bold
     * @param string $font_family
     *
     * @return self
     */
    public function title(
        string $title,
        **int $font_size = 14,**
        string $color = '#666',
        bool $bold = true,
        string $font_family = "'Helvetica Neue', 'Helvetica', 'Arial', sans-serif"
    ) {
        return $this->options([
            'title' => [
                'display'    => true,
                'fontFamily' => $font_family,
                'fontSize'   => $font_size,
                'fontColor'  => $color,
                'fontStyle'  => $bold,
                'text'       => $title,
            ],
        ]);
    }
```

**Comment by diegoeduardorios** [comment]
Try this
`    /**
     * Set the chart title.
     *
     * @param string $title
     * @param int    $font_size
     * @param string $color
     * @param string $font_weight
     * @param string $font_family
     *
     * @return self
     */
    public function title(
        string $title,
        int $font_size = 14,
        string $color = '#666',
        string $font_weight = 'bold',
        string $font_family = "'Helvetica Neue', 'Helvetica', 'Arial', sans-serif"
    ) {
        return $this->options([
            'title' => [
                'display'    => true,
                'fontFamily' => $font_family,
                'fontSize'   => $font_size,
                'fontColor'  => $color,
                'fontStyle'  => $font_weight,
                'text'       => $title,
            ],
        ]);
    }
`
fontStyle need to be string

**Comment by ConsoleTVs** [comment]
Please file a new issue with more info like laravel version, php version, frontend used, etc.
