### ISSUE TITLE
Laravel 5.7 ChartJS, Simple Example rendering an infinite height chart

### ISSUE THREAD

**Issue by JuanDeLeon** [ConsoleTVs/Charts#434]
Hi, I'm trying to render the Simple Example from the docs. I put this in my controller:
```
$chart = new YearlyStatementsChart;
$chart->labels(['One', 'Two', 'Three', 'Four']);
$chart->dataset('My dataset', 'line', [1, 2, 3, 4]);
$chart->dataset('My dataset 2', 'line', [4, 3, 2, 1]);
```

And in my view:
```
{!! $chart->container() !!}

{!! $chart->script() !!}
```

However, when going into the view, the chart starts rendering and never stops, it infinitely grows in height (see the scroll bar at the right). No issues are thrown in javascript console. Any ideas?

![captura de pantalla 2018-10-30 a la s 18 15 32](https://user-images.githubusercontent.com/13142634/47758281-f4b84e00-dc6f-11e8-9020-a47a43b0e747.png)

UPDATE:
Just tried same example with Highcharts and it works fine!

**Comment by ConsoleTVs** [comment]
In a simple html, the chartjs works. Have you tried setting a fixed height for the chart?

**Comment by JuanDeLeon** [comment]
I figured it out. I had the container() and script() calls inside a bootstrap "card" div, but out of the card-header and card-body.

I put it inside of the card-body element and it works great.
That was a pretty weird behavior though.
Thank you!

**Comment by ConsoleTVs** [comment]
Great! So strange tho yes!
