### ISSUE TITLE
Cannot change pie chart colors

### ISSUE THREAD

**Issue by ivan-atanasov** [ConsoleTVs/Charts#436]
I am using Laravel 5.7 with Charts 6.* I cannot seem to change the colors for the pie chart. I can change the line and column chart colors, but not the pie chart. It's always stuck to black. What I tried so far:

```
$pieChart = new ExpensesChart();
        $pieChart->formatOptions(true);
        $pieChart->title('Grouped by category')
            ->labels(['Food', 'Bills', 'Entertainment', 'Eat outside', 'Work Lunch', 'Others'])
            ->options([
                'plotOptions' => [
                    'series' => [
                        'allowPointSelect' => true,
                    ],
                    'pie'    => [
                        'dataLabels' => [
                            'enabled' => true,
                            'format'  => '<b>{point.name}</b><br>{point.percentage:.1f} %',
                        ],
                        'colors'      => ["#ff0000","#00ff00","#ff00ff","#0000ff","#f00f0f","#fd0df0"],
                    ]
                ]
            ])
            ->dataset('My dataset 1', 'pie', [263, 809, 55, 70, 133, 92]);
```

The generated javascript I get is the following:

```
window.bmqfnyjwczghxadisrvotlkue = new Highcharts.Chart("bmqfnyjwczghxadisrvotlkue", {
    series: data,
    "credits":{"enabled":false},
    "title":{"text":"Grouped by category"},
     "xAxis":{
            "categories":["Food","Bills","Entertainment","Eat outside","Work Lunch","Others"]
     },
     "plotOptions":{"series":{"allowPointSelect":true},
     "pie":{
          "dataLabels":{
              "enabled":true,
              "format":"<b>{point.name}<\/b><br>{point.percentage:.1f} %"},
              "colors":["#ff0000","#00ff00","#ff00ff","#0000ff","#f00f0f","#fd0df0"]}}
});
```

The graph is shown, but it's always black. Any help would be much appreciated.

**Comment by ConsoleTVs** [comment]
Have you managed to get it working using normal highcharts?

**Comment by cryogenfx** [comment]
I had this exact issue. Turn out I was missing some styles from highchart in my web pack file. Somehow it only affected my pies, not area and charts. Can’t remember what file I needed, but dig around in the vendor file and you’ll see it

**Comment by Naoray** [comment]
@ivan-atanasov can you please check if @cryogenfx's advice solves the issue?

**Comment by ivan-atanasov** [comment]
@cryogenfx @Naoray I will check later and comment if it fixes the issue. Thanks a lot for looking into it

**Comment by ivan-atanasov** [comment]
Ok, I figured it out after some more digging in the code. In your chart class when you set the dataset data, you need to explicitly call a color() method like so:

`$this->dataset("Chart Title", 'pie', array_values($data))->color(['#f00', '#f0f', '#ff0', '#0f0']);`

Notice that if the number of colors you pass is different than the number of items in the dataset, some of the items will be colored in the undefined color value (which is almost dark by default).

I know this is offtopic, but I just want to leave my solution for generating random colors for any dataset count in case anyone's interested

    ```
private function generateColors(array $dataset): array
    {
        $colors = [];
        for ($i = 0; $i < count($dataset); $i++) {
            $randomColor = $this->randomColor();
            if (in_array($randomColor, $colors)) {
                continue;
            }

            $colors[] = $this->randomColor();
        }

        return $colors;
    }

    private function randomColor(): string
    {
        return '#' . $this->randomHex() . $this->randomHex() . $this->randomHex();
    }

    private function randomHex(): string
    {
        return str_pad(dechex(rand(50, 100)), 2, '0', STR_PAD_LEFT);
    }
```
