### ISSUE TITLE
Call to undefined method ConsoleTVs\Charts\Classes\Chartjs\Chart::multi()

### ISSUE THREAD

**Issue by EskindirA** [ConsoleTVs/Charts#438]

**Comment by ConsoleTVs** [comment]
Reading the documentation helps

**Comment by Kaishiyoku** [comment]
The documentation says nothing about multi charts.

**Comment by ConsoleTVs** [comment]
Read it. You'll see how it works. You just add datasets. All charts are now of a similar multi chart that was used.

**Comment by Kaishiyoku** [comment]
I found the solution, you're right. At some point I had to set a type directly to the chart class.

**Comment by ConsoleTVs** [comment]
Yeah, there's no need for that anymore :D
