### ISSUE TITLE
[FEATURE] Chart with missing values for the X axis

### ISSUE THREAD

**Issue by jordiprats** [ConsoleTVs/Charts#439]
Hi,
Is it possible to have a chart with missing values for the X axis like in this chartjs example?

https://www.chartjs.org/samples/latest/scales/time/line.html

My code is:

```
  public function show($id)
  {
    $product = Product::findOrFail($id);

    $chart = new WebPricesChart;
    $chart->height(500);

    Log::info(WebPrice::distinct()->where([['product_id', '=', $id]])->orderBy('data')->get()->pluck('data'));
    $chart->labels(WebPrice::distinct()->where([['product_id', '=', $id]])->orderBy('data')->get()->pluck('data'));
    foreach(WebPrice::distinct()->select('website')->where('product_id', '=', $product->id)->groupBy('website')->get() as $website)
    {
      Log::info(WebPrice::where([ ['product_id', '=', $id], ['website', '=', $website->website]])->get()->pluck('price', 'data')->toArray());

      $chart->dataset($website->website, 'line', WebPrice::where([ ['product_id', '=', $id], ['website', '=', $website->website]])->get()->pluck('price', 'data')->toArray());
    }

    return view('products.show')
            ->with('product', $product)
            ->with('chart', $chart);
  }
```

And my data:

```
[2018-11-16 18:54:48] local.INFO: ["2018-11-08 23:02:38","2018-11-15 18:04:32","2018-11-16 08:00:03","2018-11-16 09:06:01","2018-11-16 10:10:33","2018-11-16 12:00:12","2018-11-16 18:31:02","2018-11-16 18:31:11"]  
[2018-11-16 18:54:48] local.INFO: array (
  '2018-11-08 23:02:38' => '85.80',
  '2018-11-16 18:31:02' => '85.80',
)  
[2018-11-16 18:54:48] local.INFO: array (
  '2018-11-15 18:04:32' => '85.95',
  '2018-11-16 08:00:03' => '85.95',
  '2018-11-16 09:06:01' => '85.95',
  '2018-11-16 10:10:33' => '85.95',
  '2018-11-16 12:00:12' => '85.95',
  '2018-11-16 18:31:11' => '85.95',
)  
```

I'm getting an empty chart. How do you get more info of what's going on when you end up with an empty chart?

many thanks,

**Comment by ManojKiranA** [comment]
i had a same situation to get the count of records created per hour 

but for the the some the time the no records will be generated so the the value count will be mismatched


For example i have 24 hous per day but the data created  is occured in only 5 hours means that you need to set all the other hours to value 0

**Comment by ConsoleTVs** [comment]
Oksy let's see.

This library supports multiple datasets in the same chart, meaning that you cant have doferent datasets with diferent values, this makes no sense. To fix that, each dataset contains only the values of it. And the labels are set only once.

That means you need to set the labels first and them the datasets with the number of points needed. I don't see an issue here.

Different datasets with diferent labels makes no sense to be in the same chart. You first need to adapt the data in such a way that the values of each dataset always match the labels you have. You can dynalically create the labels and the values each time if they are never the same, but they need to match in length.

**Comment by jordiprats** [comment]
You have two sensors, one humidity and another for temperature, each sends data at it's own peace. Does it make sense to have a charts with the two values that have data at different a time(ie label), definitely YES

Does your library support it? NO, but this doesn't mean this could make sense under different circumstances

kind regards,

**Comment by jordiprats** [comment]
or even easier: two temperature sensors at two different rooms, etc etc etc

**Comment by ConsoleTVs** [comment]
I'll dig into it. Will post back later

**Comment by jordiprats** [comment]
Hi Erik,
Have this been implemented? If so, there's anything we need to take into account?

regards,

**Comment by ConsoleTVs** [comment]
Bon dia Jordi!

Aquesta llibreria només actua com a wrapper sobre Chartisan, Chartisan es un dels meus altres projectes. Aixo et dona 100% de control sobre com es renderitza la grafica, i pertant, si, el que demanes es pot fer amb un "custom hook". Tens tota la documentacio a https://chartisan.dev.

Tot aixo significa que es un major version i com a tal no es compatible amb les anteriors i requereix refactoring.

Qualsevol dubte, fes-ho saber!
