### ISSUE TITLE
Can not display lables in C3 charts 

### ISSUE THREAD

**Issue by anilherath** [ConsoleTVs/Charts#440]
Hi,
I tried to generate a bar chart in c3 library with following dataset in controller,

`$chart2->labels(['One', 'Two', 'Three', 'Four']);
 $chart2->dataset('My dataset 3', 'bar', [60,70,40,79]);`

However the lables are not displaying in the generated chart. 
Is there anything wrong I did in the dataset?

**Comment by ConsoleTVs** [comment]
Perhaps you need to activate the labels by passing the option to it. Check what is the option to enable labels and pass it using ->options([...]);
