### ISSUE TITLE
How do I change fontColor of labels and legends with ChartJS ?

### ISSUE THREAD

**Issue by CharlieEtienne** [ConsoleTVs/Charts#442]
How do I change labels and legends font color ? 

Using:
- Area OR Bars charts
- ChartJS
- Standard loading
- Charts version 6.3.4

**Comment by ConsoleTVs** [comment]
We use the same API as the official.

https://charts.erik.cat/customize_charts.html#generic-customization

"Charts accepts what's said to be the whole JS library API. That means that you can inject any option to the chart configuration directly with PHP."

Just read how it's done in chartjs and you're set :)
