### ISSUE TITLE
Chart Classes

### ISSUE THREAD

**Issue by mprythero** [ConsoleTVs/Charts#443]
I was more curious than anything, as it doesn't appear explained in the documentation, but what would be the point of creating different chart classes? Do most users only create one chart class or do users have many?

Thanks!

**Comment by ConsoleTVs** [comment]
It can be up to you. You may have diferent line charts (colors, shapes, libraries) that are grouped in diferent areas. For example; a lineChart class for the admin panel with some colors and shapes and a diferent lineChart2 for the public area. It actually depends on the use you want to give it. It's more flexible and still powerfull without any pentalties.
