### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by SphiwokuhleS** [ConsoleTVs/Charts#444]
please make new tutorial video. lots of things changed

**Comment by ConsoleTVs** [comment]
Have you tried reading the documentation?

**Comment by SphiwokuhleS** [comment]
yes i did, it is lacking for me. not enough examples.. trying to display a
graph of racial groups, i tried groupBy() not working. and on the old video
it works on he's test

**Comment by SphiwokuhleS** [comment]
This is what i'mm trying to do bro,

![screenshot at 2018-12-01 11-57-27](https://user-images.githubusercontent.com/22741612/49326924-eeb0d800-f561-11e8-95a0-285665a1e401.png)
![screenshot at 2018-12-01 11-57-39](https://user-images.githubusercontent.com/22741612/49326925-f4a6b900-f561-11e8-812a-7f1ff7e7fbbb.png)

**Comment by SphiwokuhleS** [comment]
i'm trying to this but, for ethnicity. i have no clue on how to do it on the latest one

**Comment by ConsoleTVs** [comment]
I think you need to know how laravel works first, and then start using libraries.

The new version does not support auto generating data for a simple reason. It's not the library's goal to format your data, it's the developer's fault. in fact, you are the responsible of that. Your data is the users? Right use a collection, read it's docs and groupBy them. https://laravel.com/docs/5.7/collections#method-groupby

```php
$users = User::all()->groupBy('game')->map->count();

$chart = new myChart();
$chart->labels($users->keys());
$chart->dataset('Sample Dataset', 'line', $users->values());
```

What's unclear about that? I mean, you are the one who formats the data, you just need to give the library the right stuff... Again, it's not my library's fault to format it, check how laravel (specially collections) can help you out.

**Comment by SphiwokuhleS** [comment]
Okay thanks,
