### ISSUE TITLE
Loading labels through Api

### ISSUE THREAD

**Issue by tintamarre** [ConsoleTVs/Charts#446]
Hello Erik, Thank you for the quality of your library and support! It's really good work. :-)

**Question:**
I'm looking to load labels through the API, is that possible? Thank you!

Example of API output:
```json
{
datasets: [
{
data: [
773,
165
]
},
{
dataset_label: "Group A"
}
],
labels: [
"Male",
"Female"
]
}```

**Comment by ConsoleTVs** [comment]
You're looking for this: https://charts.erik.cat/api_charts.html#building-the-chart :)

**Comment by tintamarre** [comment]
I tried the following but the chart _labels_ are not present -- only the _labels of the datasets_

```php
public function forecastChartJson()
{
$chart = new FinanceForecast;
$chart->labels(['test1', 'test2', 'test3']);
$chart->dataset('Sample Test', 'bar', [3,4,1]);
$chart->dataset('Sample Test', 'line', [1,4,3]);

return $chart->api();
}
```
Result
-----------------

```json

[
{
borderWidth: 2,
data: [
3,
4,
1
],
label: "Sample Test",
type: "bar"
},
{
borderWidth: 2,
data: [
1,
4,
3
],
label: "Sample Test",
type: "line"
}
]
```

In my case, I need to run a big Query to get the datasets and the labels. I don't want to run it twice to get the labels. 

Did I miss something ? Thank you for your help.

**Comment by tintamarre** [comment]
> I managed to make it work using the following Api output:
> 
> ```
> public function financeApiChart()
> 
> $data = $this->financeRepository->getStatistics();
> 
> $chart = new FinanceForecast;
> $chart->dataset('Invoices sent', 'line', $data->pluck('invoices_sent'));
> $chart->dataset('Invoices paid', 'line', $data->pluck('invoices_paid'));
> $chart->dataset('Expenditures', 'line', $data->pluck('expenditures_paid'));
> 
>     return response()->json([
>       'errors' => false,
>       'labels' => $data->pluck('month'),
>       'datasets' => json_decode($chart->api()),
>     ]);
> }
> ```
> 
> And replacing script and init blades files: [master...tintamarre:master](https://github.com/ConsoleTVs/Charts/compare/master...tintamarre:master)
> 
> But, It only works for Chartjs. I do not use any other libraries for the moment.
