### ISSUE TITLE
Chart.js Options Not Working?

### ISSUE THREAD

**Issue by mprythero** [ConsoleTVs/Charts#448]
I have the following in my controller:

```
$chart = new DataChart;
			$chart->dataset('', 'line', $pluckedClaimsCounts)->options([
					'legend' => [ 'display' => false ],
					'tooltips'=>[ 'display' => false ],
					'fill' => false,
					'title' => [ 'display' => false ],
					'scales' => [ 'yAxes' => [ 'display' => false ], 'xAxes' => [ 'display' => false ] ],
			]);

			$chart->labels($pluckedClaimsDates);
```

But when it is rendered, it looks like this:

![ssss](https://user-images.githubusercontent.com/19898458/49695278-fa019600-fb55-11e8-9b65-98238dfca7ab.jpg)

Both axis' appear in the chart, and the legend is displayed. I want it all gone so that only a basic line will remain. Can anyone help?

Thanks!

**Comment by ConsoleTVs** [comment]
I'm sure you're doing something wrong, inspect the generated code by using "inspect element" and see the output

**Comment by Naoray** [comment]
@mprythero you probably want to set the options on the chart instance and not on the dataset itself. When you call `->dataset(...)` the dataset itself is returned and not the chart instance, therefore you have to call `$chart->options(...)` seperately.
