### ISSUE TITLE
Suggestion: Add function to set chart options

### ISSUE THREAD

**Issue by matriphe** [ConsoleTVs/Charts#45]
Sometime we need to set chart options, for example to disable animation in a chart library. I think it will be handy if there's a method to set this.

Probably like this:
```php
Charts::create('line', 'chartjs')->setOptions(['animation' => false])
```

**Comment by ConsoleTVs** [comment]
We already know this, but atm we dont have anythin like that, you can read more here:

https://github.com/ConsoleTVs/Charts/issues/33
