### ISSUE TITLE
Class 'Charts' not found

### ISSUE THREAD

**Issue by usmanciklum** [ConsoleTVs/Charts#450]
as I follow the docs https://charts.erik.cat/installation.html#composer install pack and add provider. when i run publish command it's shown onthing to publish. so help me

![capture](https://user-images.githubusercontent.com/44262032/49815393-821db080-fd8d-11e8-828f-350f43eb4a99.PNG)

**Comment by cdric0701** [comment]
Try to run php artisan config:clear and re-run php artisan vendor:publish --tag=charts_config

**Comment by usmanciklum** [comment]
done that several time nothing update. Even delete vendor folder and rerun composer install and then composer update.

**Comment by cdric0701** [comment]
Does the provider exist ?
Are you sure you are running the right php version from the cli? You can test it by running php -v

**Comment by usmanciklum** [comment]
yes i have 7.2 php version and provider is also exist.

**Comment by ConsoleTVs** [comment]
Tun the same command without the --tag option. Does it show the charts somewhere in the list?

**Comment by mbseasy1997** [comment]
Just ran through the installation process on a Laravel 5.7 project, and are not encountering any issues along the way.

![](https://i.gyazo.com/b22ca8f6c1252bb75d36cd994ca8a5c9.png)

Can I ask what version of Laravel you trying to install this package on @usmanciklum?

**Comment by usmanciklum** [comment]
version 5.1 don't know why is not publish. but i already start working by manually pull high-charts in view
