### ISSUE TITLE
Nova Support?

### ISSUE THREAD

**Issue by Otienoh** [ConsoleTVs/Charts#453]
So Nova has metrics class, but there is still need for having proper chart support especially on the bar charts with proper x & y-axis, labels etc.

**Comment by ConsoleTVs** [comment]
I don't have nova purchased. So i cannot inplement this. However, somebody might be able to add support for it?

**Comment by Naoray** [comment]
@Otienoh I am still up for it... waiting for your answer

**Comment by ConsoleTVs** [comment]
I agree. As far as I know, I told you (@Otienoh) via twitter taht @Naoray was able to do such thing for you and you needed to contact him.
