### ISSUE TITLE
unexpected token 

### ISSUE THREAD

**Issue by kristoferzz** [ConsoleTVs/Charts#456]
Shows error Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 138. Published vendor files and changed in charts/chartjs/init.blade.php:

fetch("{!! $chart->api_url !!}")
                .then(data => data.json())
                .then(data => { {{ $chart->id }}_create(data) })

to:
axios.get("{!! $chart->api_url !!}")
                        .then(response => {
                            {{ $chart->id }}_create(response.data)
                        });

Now it works. Posting in case somebody has the same issue.

**Comment by ConsoleTVs** [comment]
you might be using a too old browser for that. Axios is an external library that should not be included with this library.
