### ISSUE TITLE
Echart pie chart issues

### ISSUE THREAD

**Issue by joveice** [ConsoleTVs/Charts#459]
So when I try to load my page I get this

```
Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Undefined offset: 0 (View: /home/vagrant/code/moscowdb/vendor/consoletvs/charts/src/Views/init.blade.php) (View: /home/vagrant/code/moscowdb/vendor/consoletvs/charts/src/Views/init.blade.php)
```

```
$total_chart = new ChartEchart();
$total_chart->dataset('test', 'pie', [2]);
```

it fails on this
```
{!! $total_chart->script() !!}
```
Now if I change "pie" to lets say "spaceship"
it does not fail, but the JS which loads does, obviously.

Now I tried to find out what was going on.
In Echarts/Dataset.php there is this
```
/**
     * Store the private datasets that contains a special formating.
     *
     * @var array
     */
    public $specialDatasets = ['pie'];
```

What is so special about "pie" here?
I used the same code before for a C3 chart and donut instead of pie and it worked.

**Comment by ConsoleTVs** [comment]
Well pie and donut simply group the data in a diferent way, refer to how the dataset values are formated when a special dataset is found and compare it to the real echarts docs. You will see the values are placed in a diferent way than traditional charts.
