### ISSUE TITLE
Where do you control responsiveness in this version?

### ISSUE THREAD

**Issue by fbc** [ConsoleTVs/Charts#465]
This:
$chart->setResponsive(true);
or
$chart->responsive(true);

Doesn't seem to work. Will anything?

**Comment by ConsoleTVs** [comment]
You have to change the desired optionson your frontend js library. If the library support responsiveness you can thenet it up. Check the presets, they might have what you need:)

**Comment by fbc** [comment]
> You have to change the desired optionson your frontend js library. If the library support responsiveness you can thenet it up. Check the presets, they might have what you need:)

And where would one find those presets?

**Comment by ConsoleTVs** [comment]
I checked for you. Seems you'll need to inject it using ->options()

https://www.chartjs.org/docs/latest/general/responsive.html

https://charts.erik.cat/customize_charts.html#generic-customization

**Comment by fbc** [comment]
I'm using Fusion charts. The chartJS work fine right out of the box.
