### ISSUE TITLE
Requires refresh/hard refresh to show chart

### ISSUE THREAD

**Issue by nickdavies791** [ConsoleTVs/Charts#466]
I seem to be having difficulties in getting my charts to display without a hard refresh (ctrl+shift+r).

I have included the `<script src="{{ asset('js/Chart.min.js') }}"></script>` in my `<head>` and below that I have the scripts loading for the charts `{!! $chartA->scripts() !!}` and `{!! $chartB->scripts() !!}`

The charts show sporadically though; most of the time they need a hard refresh to show.

No errors in the console either. 

It usually happens when I click the link with the charts, rather than refresh the page. They don't seem to show first time when the page is clicked.

Any advice?

Here's an example of what's happening:- [Demo](https://gifyu.com/image/wfay)

**Comment by ConsoleTVs** [comment]
May you first try to use another frontend library? If the proboem persists and no error is output is probably due something else in your page, maybe some other script or an extension

**Comment by nickdavies791** [comment]
@ConsoleTVs Thanks for your reply. 

I've narrowed it down to the `require('bootstrap');` line in the `app.js` file. Commenting that line out allows the charts to work, but then my Bootstrap etc. doesn't work. Do you know what could be causing the conflict?

**Comment by ConsoleTVs** [comment]
Well, I don't use bootstrap...

**Comment by nickdavies791** [comment]
No problem. I’ve removed the package and just written a Vue component for Chartjs instead.

**Comment by ConsoleTVs** [comment]
If you're using vue, you should not use thid package. There are client side alternatives.
