### ISSUE TITLE
Pie Chart  colour doesnt work

### ISSUE THREAD

**Issue by Marpxz** [ConsoleTVs/Charts#468]
I cant change default colour en Frappe charts using         

`$chart_c1->dataset('Sample', 'pie', [$Deficiente_c1,$Regular_c1,$Muy_Bueno_c1])->color(['#f00', '#f0f', '#ff0']);`

The error says

`Argument 1 passed to ConsoleTVs\Charts\Classes\Frappe\Dataset::color() must be of the type string, array given`

help please

**Comment by Naoray** [comment]
The error speaks for itself. You can only use string as parameters for this method. But since this method simply adds the `color` param to the `$options` array you may just call the `options()` method and set the colors array there.

```php
/**
     * Determines the color of the dataset.
     *
     * @param string $color
     *
     * @return self
     */
    public function color(string $color)
    {
        return $this->options([
            'color' => $color,
        ]);
    }
```

=> `->options(['color' => ['#f00', '#f0f', '#ff0'])`
