### ISSUE TITLE
Use Chart in intranet offline application

### ISSUE THREAD

**Issue by hbarakat** [ConsoleTVs/Charts#469]
Hi, 
I want make to use charts work offline in my intranet application.
i already change my charts.php with local file instead url
`<?php
 -----------
    'assets' => [
        'global' => [
            'scripts' => [
                asset('js/charts/jquery.min.js'),
                // 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js',
            ],
        ],

        'canvas-gauges' => [
            'scripts' => [
                asset('js/charts/gauge.min.js'),
                // 'https://cdn.rawgit.com/Mikhus/canvas-gauges/gh-pages/download/2.1.2/all/gauge.min.js',
            ],
        ],

        'chartist' => [
            'scripts' => [
                asset('js/charts/chartist.min.js'),
                // 'https://cdnjs.cloudflare.com/ajax/libs/chartist/0.10.1/chartist.min.js',
            ],
            'styles' => [
                asset('css/charts/chartist.min.css'),
                // 'https://cdnjs.cloudflare.com/ajax/libs/chartist/0.10.1/chartist.min.css',
            ],
        ],

        'chartjs' => [
            'scripts' => [
                asset('js/charts/Chart.min.js'),
                // 'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js',
            ],
        ],

        'fusioncharts' => [
            'scripts' => [
                asset('js/charts/fusioncharts.js'),
                asset('js/charts/fusioncharts.theme.fint.js'),
                // 'https://static.fusioncharts.com/code/latest/fusioncharts.js',
                // 'https://static.fusioncharts.com/code/latest/themes/fusioncharts.theme.fint.js',
            ],
        ],

        'google' => [
            'scripts' => [
                asset('js/charts/jsapi.js'),
                asset('js/charts/loader.js'),
                // 'https://www.google.com/jsapi',
                // 'https://www.gstatic.com/charts/loader.js',
                "google.charts.load('current', {'packages':['corechart', 'gauge', 'geochart', 'bar', 'line']})",
            ],
        ],

        'highcharts' => [
            'styles' => [
                // The following CSS is not added due to color compatibility errors.
                // 'https://cdnjs.cloudflare.com/ajax/libs/highcharts/5.0.7/css/highcharts.css',
            ],
            'scripts' => [
                asset('js/charts/highcharts.js'),
                asset('js/charts/offline-exporting.js'),
                asset('js/charts/map.js'),
                asset('js/charts/data.js'),
                asset('js/charts/world.js'),
                // 'https://cdnjs.cloudflare.com/ajax/libs/highcharts/5.0.7/highcharts.js',
                // 'https://cdnjs.cloudflare.com/ajax/libs/highcharts/5.0.7/js/modules/offline-exporting.js',
                // 'https://cdnjs.cloudflare.com/ajax/libs/highmaps/5.0.7/js/modules/map.js',
                // 'https://cdnjs.cloudflare.com/ajax/libs/highmaps/5.0.7/js/modules/data.js',
                // 'https://code.highcharts.com/mapdata/custom/world.js',
            ],
        ],

        'justgage' => [
            'scripts' => [
                asset('js/charts/raphael.min.js'),
                asset('js/charts/justgage.min.js'),
                // 'https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.6/raphael.min.js',
                // 'https://cdnjs.cloudflare.com/ajax/libs/justgage/1.2.2/justgage.min.js',
            ],
        ],

        'morris' => [
            'styles' => [
                asset('css/charts/morris.css'),
                // 'https://cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css',
            ],
            'scripts' => [
                asset('js/charts/raphael.min.js'),
                asset('js/charts/morris.min.js'),
                // 'https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.6/raphael.min.js',
                // 'https://cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js',
            ],
        ],

        'plottablejs' => [
            'scripts' => [
                asset('js/charts/d3.min.js'),
                asset('js/charts/plottable.min.js'),
                // 'https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js',
                // 'https://cdnjs.cloudflare.com/ajax/libs/plottable.js/2.8.0/plottable.min.js',
            ],
            'styles' => [
                asset('css/charts/plottable.css'),
                // 'https://cdnjs.cloudflare.com/ajax/libs/plottable.js/2.2.0/plottable.css',
            ],
        ],

        'progressbarjs' => [
            'scripts' => [
                asset('js/charts/progressbar.min.js'),
                // 'https://cdnjs.cloudflare.com/ajax/libs/progressbar.js/1.0.1/progressbar.min.js',
            ],
        ],

        'c3' => [
            'scripts' => [
                asset('js/charts/d3.min.js'),
                asset('js/charts/c3.min.js'),
                //  'https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js',
                // 'https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.11/c3.min.js',
            ],
            'styles' => [
                asset('css/charts/c3.min.css'),
                //  'https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.11/c3.min.css',
            ],
        ],

        'echarts' => [
            'scripts' => [
                asset('js/charts/echarts.min.js'),
                // 'https://cdnjs.cloudflare.com/ajax/libs/echarts/3.6.2/echarts.min.js',
            ],
        ],

        'amcharts' => [
            'scripts' => [
                asset('js/charts/amcharts.js'),
                asset('js/charts/serial.js'),
                asset('js/charts/export.min.js'),
                asset('js/charts/light.js'),
                // 'https://cdnjs.cloudflare.com/ajax/libs/amcharts/3.21.2/amcharts.js',
                // 'https://cdnjs.cloudflare.com/ajax/libs/amcharts/3.21.2/serial.js',
                // 'https://cdnjs.cloudflare.com/ajax/libs/amcharts/3.21.2/plugins/export/export.min.js',
                // 'https://cdnjs.cloudflare.com/ajax/libs/amcharts/3.21.2/themes/light.js',
            ],
            'styles' => [
                
                asset('css/charts/export.css'),
               //'https://cdnjs.cloudflare.com/ajax/libs/amcharts/3.21.2/plugins/export/export.css',
            ],
        ],
    ],
];
`
bu i still have a problem especially  in the loader.js 
because inside this fili there is cal of an other js file
and when this fille call others... 

Is there any solution for this problem ?
thanks

**Comment by ConsoleTVs** [comment]
https://github.com/ConsoleTVs/Charts/blob/master/src/Config/charts.php

Older versions are not supported / maintained.
