### ISSUE TITLE
screenshot not loading in documentation

### ISSUE THREAD

**Issue by vesper8** [ConsoleTVs/Charts#470]
In your Getting Started section of your docs: https://charts.erik.cat/getting_started.html

The screenshot is not loading: https://image.prntscr.com/image/FDJCr7ywShKMUlFitEc_Ww.png

403 Forbidden

Also.. there are no examples at all :(

https://charts.erik.cat/full_example.html

I enjoy your library a lot, hope you keep updating it from time to time

**Comment by ConsoleTVs** [comment]
I think the docs and the few example yutorial id enough to understand it all... I am currently busy with my thesis atm...

**Comment by ConsoleTVs** [comment]
@vesper8 new update will come at the end / start of the year when php 7.4 comes out with typed class props.
