### ISSUE TITLE
Echarts appear blank

### ISSUE THREAD

**Issue by fbc** [ConsoleTVs/Charts#476]
I made a chart with this:
```
        $realtime_consumption_chart = new Echarts;
        $realtime_consumption_chart->labels(['One', 'Two', 'Three']);
        $realtime_consumption_chart->dataset('My dataset', 'line', [1, 2, 3, 4]);
```
passed the chart to the view and use this in the view to try to visualize the chart:
```
                            {!! $realtime_consumption_chart->container() !!}
                            {!! $realtime_consumption_chart->script() !!}
```
but it just gives be a blank space in the area the chart should appear. no error.

**Comment by ConsoleTVs** [comment]
I assume you also imported echarts, right?

https://charts.erik.cat/supported_libraries.html#echarts-4-0-2

**Comment by fbc** [comment]
yes, it was in the controller and the script was in the view.

I gave up on it and just decided to switch to ChartJS.

**Comment by ConsoleTVs** [comment]
I'll look at this on my free time (if i have any...) Will be marked.

**Comment by ConsoleTVs** [comment]
![imagen](https://user-images.githubusercontent.com/6124435/53707751-8e675600-3e30-11e9-8818-7d2c76ae15ab.png)
![imagen](https://user-images.githubusercontent.com/6124435/53707755-945d3700-3e30-11e9-8e49-2355876214bd.png)
![imagen](https://user-images.githubusercontent.com/6124435/53707763-99ba8180-3e30-11e9-972b-23d534d83197.png)
![imagen](https://user-images.githubusercontent.com/6124435/53707773-a17a2600-3e30-11e9-9b21-5f927884abf2.png)
