### ISSUE TITLE
Class 'Charts' not found

### ISSUE THREAD

**Issue by thunder87** [ConsoleTVs/Charts#48]
I can see that you made a change to the assets (CDN), missing an update to the documentation? Because now I can't get it to work and when i publish the assets, nothing is published..

**Comment by ConsoleTVs** [comment]
Hello! What version are you using? The current commits are not released yet.

**Comment by thunder87** [comment]
I'm using 5.2

**Comment by ConsoleTVs** [comment]
I mean about charts version, latest one is: https://github.com/ConsoleTVs/Charts/releases/tag/2.0.2

**Comment by thunder87** [comment]
arrh.. 2.0.2

**Comment by ConsoleTVs** [comment]
What exact error do you get and when?

**Comment by thunder87** [comment]
If i do: 
{!! ConsoleTVs\Charts\Charts::assets() !!}

Failed to load resource: the server responded with a status of 404 (Not Found)
http://laravel/vendor/consoletvs/charts/chartjs/Chart.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://laravel/vendor/consoletvs/charts/fusioncharts/fusioncharts.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://laravel/vendor/consoletvs/charts/canvas-gauges/gauge.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://laravel/vendor/consoletvs/charts/jquery-3.0.0.min.js Failed to load resource: the server responded with a status of 404 (Not Found)

If i do:
{!! Charts::assets() !!}
Class 'Charts' not found (View: \resources\views\admin\statistics\index.blade.php)

**Comment by ConsoleTVs** [comment]
Let's see;

Give me a second to try it out. The second error seems more to be an alias problem

**Comment by thunder87** [comment]
Yeah,
Nothing to publish for tag [charts_assets].
Nothing to publish for tag [charts_config].

**Comment by ConsoleTVs** [comment]
hum.... I'll check it out

**Comment by ConsoleTVs** [comment]
As far as I see, right now

```
{!! ConsoleTVs\Charts\Charts::assets() !!}
```

This renders all the libraries:

```

<script src='http://localhost/web/Laralum3/public/vendor/consoletvs/charts/jquery-3.0.0.min.js'></script>
<script src='http://localhost/web/Laralum3/public/vendor/consoletvs/charts/canvas-gauges/gauge.min.js'></script>
<script src='http://localhost/web/Laralum3/public/vendor/consoletvs/charts/chartist/chartist.min.js'></script><link rel='stylesheet' type='text/css' href='http://localhost/web/Laralum3/public/vendor/consoletvs/charts/chartist/chartist.min.css' />
<script src='http://localhost/web/Laralum3/public/vendor/consoletvs/charts/chartjs/Chart.js'></script>
<script type='text/javascript' src='http://localhost/web/Laralum3/public/vendor/consoletvs/charts/fusioncharts/fusioncharts.js'></script><script type='text/javascript' src='http://localhost/web/Laralum3/public/vendor/consoletvs/charts/fusioncharts/themes/fusioncharts.theme.fint.js'></script>
<script type='text/javascript' src='https://www.gstatic.com/charts/loader.js'></script><script type='text/javascript' src='https://www.google.com/jsapi'></script><script type='text/javascript'>google.charts.load('current', {'packages':['corechart', 'gauge', 'geochart', 'bar', 'line']});</script>
<script src='http://localhost/web/Laralum3/public/vendor/consoletvs/charts/highcharts/js/highcharts.js'></script><script src='http://localhost/web/Laralum3/public/vendor/consoletvs/charts/highcharts/js/modules/exporting.js'></script><script src='http://localhost/web/Laralum3/public/vendor/consoletvs/charts/highmaps/js/modules/map.js'></script><script src='http://localhost/web/Laralum3/public/vendor/consoletvs/charts/highmaps/js/modules/data.js'></script><script src='http://localhost/web/Laralum3/public/vendor/consoletvs/charts/highmaps/maps/world.js'></script>
<script src='http://localhost/web/Laralum3/public/vendor/consoletvs/charts/justgage/raphael-2.1.4.min.js'></script><script src='http://localhost/web/Laralum3/public/vendor/consoletvs/charts/justgage/justgage.js'></script>
<link rel='stylesheet' href='http://localhost/web/Laralum3/public/vendor/consoletvs/charts/morris/morris.css'><script type='text/javascript' src='http://localhost/web/Laralum3/public/vendor/consoletvs/charts/morris/raphael.min.js'></script><script type='text/javascript' src='http://localhost/web/Laralum3/public/vendor/consoletvs/charts/morris/morris.min.js'></script>
<script src='http://localhost/web/Laralum3/public/vendor/consoletvs/charts/d3/d3.js'></script><link rel='stylesheet' href='http://localhost/web/Laralum3/public/vendor/consoletvs/charts/plottable/plottable.css'><script src='http://localhost/web/Laralum3/public/vendor/consoletvs/charts/plottable/plottable.js'></script>
<script src='http://localhost/web/Laralum3/public/vendor/consoletvs/charts/progressbar/progressbar.min.js'></script>

```

**Comment by ConsoleTVs** [comment]
The CDN stuff is not yet released. it's not yet in the 2.0.2 version.

**Comment by thunder87** [comment]
Re-installed and ran "php artisan config:clear", got it working

**Comment by ConsoleTVs** [comment]
Cool! Sorry for any caused problems!

**Comment by thunder87** [comment]
No problem, great package - keep up the good work!

**Comment by Johnny1210** [comment]
hello,

i'm using laravel 5.6 and i'm getting 
     **Class 'ConsoleTVs\Charts\Charts' not found**
my code

**use ConsoleTVs\Charts\Charts;**

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $chart = **Charts**::new('ber', 'Highcharts')
            ->setTitle('Title')
            ->setLabels('BD', 'IND', 'PK')
            ->setValues('100', '80', '50')
            ->setElementLabel('Total Users');
        return view('home', compact('chart'));
    }
}

**Comment by ConsoleTVs** [comment]
Please read the docs at charts.erik.cat

I need to make a new youtube video about it haha

**Comment by Johnny1210** [comment]
okay, this work for me, but I couldn't find out how to use **PRESETS**
I've created two Trait, **DatasetTrait**,**ChartTrait** in **App\Traits**.

can you give me **an example how to use** those from my  controller??

**Comment by Johnny1210** [comment]
**How to use multiple bar for single labels**
When my code is:
public function index()
    {
        $chart = new SampleChart;
        $chart->labels(["January", "February", "March", "April", "May", "June"])->options([
            'legend' => ['display' => true],
        ])
            ->dataset('Order', 'bar', [190, 65, 84, 45, 90, 55])->options([
                'label' => '# of Votes',
                'borderColor' => '#ff0000',
                'borderWidth' => 1,
                'backgroundColor' => [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
            ]);
        return view('home', compact('chart', 'chart1'));
    }
i have this--
![image](https://user-images.githubusercontent.com/36806969/45810564-b2086b00-bcec-11e8-8979-1edb959ee73c.png)

what should I do for getting Delivery data with Order for January, February etc.

say, for order 190,delivery is 100

**Comment by Conquerer** [comment]
![2018-11-14](https://user-images.githubusercontent.com/18400955/48461278-f6018300-e7f8-11e8-9840-4a6706abdbdf.png)
![my_function](https://user-images.githubusercontent.com/18400955/48461280-f6018300-e7f8-11e8-976f-b29372e55e99.JPG)

I followed your instruction u said,also gone through the documentation of the laravel charts as well ,at first I want to say,When I did composer require for charts it had downloaded version 6.3 of consoletvs/charts..so I followed the dynamic approach of my datas to represent in donut representation,But as of now it shows

ErrorException (E_WARNING)

Class ‘ConsoleTVs\Charts\Facades\Charts’ not found

please help in this regard.

**Comment by ConsoleTVs** [comment]
You clearly did not follow the docs :) check above, I've added the answer to this loooots of times

**Comment by Conquerer** [comment]
Ok I will...try to find and understand , Thank for the web tutorial links really  helpful.Happy Coding

**Comment by SlaraMk** [comment]
Hi
I get this error Call to undefined method App\Charts\BloodChart::labels()
