### ISSUE TITLE
I can not change color of Pie charts in Highcharts

### ISSUE THREAD

**Issue by sefrima** [ConsoleTVs/Charts#481]
I've followed documentation at https://www.highcharts.com/demo/pie-basic on how to plot pie chart.
Here below is my code

```php
$pie_chart = new KnowUsChart;
        $pie_chart->labels($channel_types);
        $pie_chart->dataset('Subscribers', 'pie', $types_count);
        $pie_chart->options([
                                'plotOptions' => [
                                    'pie' => [
                                        'allowPointSelect' => true,
                                        'cursor' => 'pointer',
                                        'dataLabels' => [
                                            'enabled' => true,
                                            'format' => '<b>{point.name}</b>: {point.percentage:.1f} %',
                                            'style' => [
                                                'color'=> "(Highcharts.theme && Highcharts.theme.contrastTextColor)" || 'blue'
                                            ],
                                        ],
                                    ],
                                ],
                                'title' => [
                                    'text' => 'Pie Chart',
                                ],
                                'tooltip' => [
                                    'pointFormat' => '{series.name}: <b>{point.percentage:.1f}%</b>'
                                ]
                            ]);
```

What I get is whole black pie chart with no single slice colored.

What could be wrong ?

**Comment by moh586** [comment]
i had same problem.after 2 days tracing code i found the sloution.
after adding dataset to chart use $chart->datasets[0]->color(['color1','color2',...]);
if you have more than one dataset you offset 1,2,3.
this is my full code
` $chart=new Charts;
        $chart->labels($labels);
        $chart->dataset(Lang::get('message.customer.report.buy'), 'pie',$scoredpoint);
        $chart->dataset(Lang::get('message.customer.report.sell'), 'pie',$spendpoint);
        $chart->options([
            'chart'=>[
                'plotBackgroundColor'=> null,
                'plotBorderWidth'=> null,
                'plotShadow'=> false,
                'type'=> 'pie',
                'style'=>[
                    'fontFamily'=>'B Yekan'
                ]
            ],
            'plotOptions' => [
                'colors'=> ['#058DC7', '#50B432', '#ED561B', '#DDDF00', '#24CBE5', '#64E572', '#FF9655', '#FFF263', '#6AF9C4'],
                'pie' => [
                    'center'=> ['50%', '50%'],
                    'allowPointSelect'=> true,
                    'cursor'=> 'pointer',
                    'colors'=> ['#058DC7', '#50B432', '#ED561B', '#DDDF00', '#24CBE5', '#64E572', '#FF9655', '#FFF263', '#6AF9C4'],
                   /* 'center'=> ['50%', '50%'],*/
                    'innerSize'=> '60%',

                ],
            ],

            'title' => [
                'verticalAlign'=> 'middle',
                'floating'=> true,
                'text' => 'Pie Chart',
            ],
            'tooltip' => [
                'pointFormat' => '{series.name}: <b>{point.percentage:.1f}%</b>'
            ]
        ]);

        $chart->datasets[0]->color(['#581845', '#C70039', '#900C3F', '#DDDF00', '#FFC300', '#FF5733', '#DAF7A6', '#0082C7', '#C70088']);
        $chart->datasets[1]->color(['#581845', '#C70039', '#900C3F', '#DDDF00', '#FFC300', '#FF5733', '#DAF7A6', '#0082C7', '#C70088']);`

**Comment by ConsoleTVs** [comment]
There's no need to do that considering ->dataset() returns the dataset object already. So:

```php
$pie_chart = new KnowUsChart;
        $pie_chart->labels($channel_types);
        $pie_chart->dataset('Subscribers', 'pie', $types_count)
                         ->color(['#581845', '#C70039', '#900C3F', '#DDDF00', '#FFC300', '#FF5733', '#DAF7A6', '#0082C7', '#C70088']);
        $pie_chart->options([
                                'plotOptions' => [
                                    'pie' => [
                                        'allowPointSelect' => true,
                                        'cursor' => 'pointer',
                                        'dataLabels' => [
                                            'enabled' => true,
                                            'format' => '<b>{point.name}</b>: {point.percentage:.1f} %',
                                            'style' => [
                                                'color'=> "(Highcharts.theme && Highcharts.theme.contrastTextColor)" || 'blue'
                                            ],
                                        ],
                                    ],
                                ],
                                'title' => [
                                    'text' => 'Pie Chart',
                                ],
                                'tooltip' => [
                                    'pointFormat' => '{series.name}: <b>{point.percentage:.1f}%</b>'
                                ]
                            ]);
```
