### ISSUE TITLE
Error composer require consoletvs/charts:5.* 

### ISSUE THREAD

**Issue by cryp24** [ConsoleTVs/Charts#482]
Please tell me how to avoid this error on the 5th version?

`
In Date.php line 386:

  Declaration of Jenssegers\Date\Date::add($interval) must be compatible with Carbon\Carbon::add($unit, $value = 1, $overflow = NULL)

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255
`

P.S. https://devhub.io/repos/ConsoleTVs-Charts Found your instruction as everything is simply written. Why was it so hard to complicate 6 version. To understand haven.

**Comment by ConsoleTVs** [comment]
I don't think this is an issue on my side tbh. However, version 5 was about 2 years ago, I am the only maintainer and I have serveral other packages in diferernt languages. I cannot maintain diferent versions of the software thus making v.5 obsolete. You should move to v.6. The documentation explains everything you need to know, read it out! charts.erik.cat

**Comment by cryp24** [comment]
hi, help to cope with the console TVs / graphics 6* (problems with the 6th version)

The situation has created a class of services mychart according to instructions, then the ranting and not to split hairs, write the following
<lang code= "php">
Route:: get ('/test', function () {

    $table = new \ app \ charts\mychart services();
    $table - >labels (['one', 'two', 'three', 'four']);
    $chart - >dataset ('my dataset', 'line', [1, 2, 3, 4]);
    $chart - >dataset ('my dataset 2', 'Line', [4, 3, 2, 1]);

    return view ("test", compact ("chart"));
});
</code>

next, the output template is inserted in place 
<lang code= "php">
{!! $chart - >container ()!!}
</code>

and connect the script at the end of the page 
<lang code= "php">
{!! $chart - >script ()!!}
</code>

In the end, get a blank white square, maybe wrong settings exhibited at the 6th version of the little example. Can someone help with an example of a line chart?

**Comment by ConsoleTVs** [comment]
What library are you using? Chartjs?

Have you included the CDN library?

**Comment by cryp24** [comment]
Oh understood, will place who could be useful. You need to create a chart as php artisan make: chart MyChart Highcharts (if you use Highcharts when you create something on the template file, you must additionally place the script <script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/6.0.6/highcharts.js" charset= "utf-8" >< / script> )

**Comment by ConsoleTVs** [comment]
This is already in the docs: https://charts.erik.cat/render_charts.html#render-the-script Read the warning!

**Comment by shreya-14-may** [comment]
I couldn't get a single function or options to change tooltip x-y axis labelling  with consoletvs chart version 6.5. Could you please suggest for that
<img width="1440" alt="Screenshot 2020-09-02 at 10 54 29 AM" src="https://user-images.githubusercontent.com/69234158/91935162-b0ce7e00-ed0a-11ea-9a28-d67f040af93f.png">
