### ISSUE TITLE
Add nonce to Chart script

### ISSUE THREAD

**Issue by MilenaSchmidt** [ConsoleTVs/Charts#483]
Hi,
I want to add Content-Security-Policy to my Laravel app but I have few charts genereated like in example from doc (https://charts.erik.cat/render_charts.html#load-the-js-library). Is there some way to add nonce to those scripts? (without changing any vendor file) Thanks in advance :)

**Comment by ConsoleTVs** [comment]
As far as I know there should be no issue :D

**Comment by MilenaSchmidt** [comment]
So how can I achive this? There is no method to add parameters to chart script (at least I didnt find it in docs).

**Comment by Naoray** [comment]
You can do this by simply adding an option to your chart `$chart->options(['nonce' => 'someRandomString'])`

**Comment by MilenaSchmidt** [comment]
@Naoray Still no effect. This option only adds attributes to chart code but 'nonce' atribute needs to be added in script tag (like so: <script nonce="somehash"></script>) . And because its generated like in docs ($somechartvariable->script()) this script is loaded automaticly from chartjs/script.blade.php.

**Comment by ConsoleTVs** [comment]
Oh hold on! I thought u were talking about the cdns. About the chart script, you're right! This will be added quickly then!

**Comment by MilenaSchmidt** [comment]
Ok, so for now I just change script.blade.php file.

**Comment by ConsoleTVs** [comment]
@MilenaSchmidt Hello, just a quick question, since the server needs to generate a random hash on each request, does the same nounce hash apply to different script elements? More like, can the same hash be used in multiple script elements?

How / When do you obtain that hash? Should a middleware be used or any other mechanism?

**Comment by ConsoleTVs** [comment]
This is done and will be published for 6.4.0 and documented as well

For you to know how, you'll be able to add individual attributes to the script tag as follows:

```php
$chart->setScriptAttribute("nonce", "1234");
```

**Comment by MilenaSchmidt** [comment]
@ConsoleTVs Thanks! Sorry for the late reply... To generate CSP I use https://github.com/spatie/laravel-csp or manualy created middleware more or less like in that article: https://christoph-rumpel.com/2018/03/content-security-policy-101

**Comment by ConsoleTVs** [comment]
Not to worry. Hope the new version suits you well :3
