### ISSUE TITLE
Add Labels to X and Y axis

### ISSUE THREAD

**Issue by ManojKiranA** [ConsoleTVs/Charts#486]
Laravel Version: `5.7.28`
Chart Version : `6.3.5`

i have tried the solution that is given for the issue 204

[issue](https://github.com/ConsoleTVs/Charts/issues/204)

My code

`$chartObj->y_axis_title("Sample");`

and 

`$chartObj->yAxisTitle("Sample");`

But both giving me the same error 

> Call to undefined method App\Charts\ChartClass::y_axis_title()
> Call to undefined method App\Charts\ChartClass::yAxisTitle()

But it is not Working for me

**Comment by ConsoleTVs** [comment]
Can you post the whole contents? You're doing something wrong using ChartClass

**Comment by ManojKiranA** [comment]
My Chart Class

```
<?php

namespace App\Charts;

use ConsoleTVs\Charts\Classes\Chartjs\Chart;

class UserLastNDaysRecord extends Chart
{
    /**
     * Initializes the chart.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }
}
```

Any My Logics

```
$lastThirdydaysObj = new UserLastNDaysRecord;
$lastThirdydaysObj->labels(array_keys( $punchInList));
$thiryDaysLog = $lastThirdydaysObj->dataset('Punch In', 'line', array_values( $punchInList));
// $thiryDaysLog->backgroundColor(collect([ '#11bf71']));
$thiryDaysLog->color(collect([ '#11bf71']));
$thiryDaysLog = $lastThirdydaysObj->dataset('Punch Out', 'line', array_values( $punchOutList));
// $thiryDaysLog->backgroundColor(collect(['rgba(0, 158, 251, 0.5)']));
$thiryDaysLog->color(collect([ '#db542e']));
```
