### ISSUE TITLE
Alter display of values in charts

### ISSUE THREAD

**Issue by Kovah** [ConsoleTVs/Charts#49]
First of all thank you for this awesome package! 👍 

I currently have the problem that I would have to modify how the values for charts. Let me explain this with an example:
I have a pie chart with different items that have numeric values:
```
Element 1 - 120
Element 2 - 87
Element 3 - 12
```
I know that charts need numeric values to be displayed but these raw values may confuse the user. It would be better if the values would be displayed like this:
```
Element 1 - 2 hours
Element 2 - 1 hour 27 minutes
Element 3 - 12 minutes
```
The computed values are already available but there's currently no way to pass them to the charts. Can this be implemented in a future version?

**Comment by ConsoleTVs** [comment]
Most of the libraries, as far as I know, only accept numeric values. You're not able to change this and even less on a pie chart. The tooltip will display the element, followed by it's value. In some cases (like line charts) you may use ->setElementLabel($string) to determine what the value means. For example; 

->setElementLabel('Total Hours')

I'm afraid it's just too complicated to hack each library's code to inject something diferent than a number!
