### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by timp999** [ConsoleTVs/Charts#490]
I get that you're busy and this is open source... so I'm hoping you take this as constructive criticism... your package is unusable as it is because of the poor documentation. It appears that previous releases were documented much better, but that's not useful now because you've completely refactored the application. Please consider improving them.

**Comment by ConsoleTVs** [comment]
Would you mind explaining what you find to be incomplete? Is there anything that is not explained?

Also, the docs are also open source... https://github.com/ConsoleTVs/ChartsDocs

So any help will also be very welcome!

**Comment by timp999** [comment]
As an example: This bit from customizing datasets:

![image](https://user-images.githubusercontent.com/13512240/56094324-4e6ca780-5ea1-11e9-87ad-1778c4244a8e.png)

Doesn't work at all. See the example below:

This code
> 

        $burndown = new burndown;
        $burndown->labels($labels);
        $burndown->dataset('Planned', 'line', $plan)->color('blue');
        $burndown->dataset('Actual', 'line', $actual)->options([
            'color' => '#0000FF', 'spanGaps' => false ]);
        $burndown->dataset('Daily', 'line', $avel)->color('green');
        $burndown->options([
            'tooltip' => [
                'show' => true // or false, depending on what you want.
            ]
        ]);
>

 gives this:
![image](https://user-images.githubusercontent.com/13512240/56094138-9fc76780-5e9e-11e9-9122-7e6e32e822ad.png)

but the actual line should be blue, not black - and there should be breaks in the line, so the array appears be be ignored entirely. If I remove the spanGaps from the array, the chart renders in exactly the same way.

Also, it appears to be an array of options, but then you refer to stacking them. Why would you want to stack them vs putting them into a single array?

The presets work, but there's not enough of them to do what I need. Also, the chart lines look like they've been drawn in crayon and I can't seem to get them to be actual lines despite this being a line chart with line datasets. 

it may be my skillset limiting me here, and so don't take any of this personally. I'm just an intermediate coder, not a Laravel pro. I can get a chart created, but styling and customization, at least to me, is a complete mystery. 

Thanks for putting this package together, and for the reply.

**Comment by ConsoleTVs** [comment]
> Doesn't work at all. See the example below:

Of course it does not work, chartjs have no "line" option. As the docs say:

![imagen](https://user-images.githubusercontent.com/6124435/56096060-81378f80-5ee3-11e9-87e2-19ed3054e5bd.png)

The line option is in the highcharts api, not the chartjs api. chartjs have borderColor. That's why if you're lazy, you can use the preset since I've already added the most common ones.

I have no clue what you might be doing, but if the presets work, so do the code. The presets just add options to the chart. For example: https://github.com/ConsoleTVs/Charts/blob/master/src/Features/Chartjs/Dataset.php#L16

Also; here's my result:

![imagen](https://user-images.githubusercontent.com/6124435/56096181-0e2f1880-5ee5-11e9-9d8b-6f60cadbd759.png)

For that code:

```php
$chart->labels(['One', 'Two', 'Three', 'Four']);
    $chart->dataset('My dataset 1', 'line', [1, 2, 3, 2])->options([
        'borderColor' => '#0000FF', 'backgroundColor' => '#00FFFF'
    ]);
    $chart->dataset('My dataset 2', 'line', [3, 2, 1, 5])->options([
        'borderColor' => '#FF00FF', 'backgroundColor' => '#FFFF00'
    ]);
    $chart->dataset('My dataset 3', 'line', [2, 3, 2, 6])
        ->color('#00FF00')
        ->backgroundColor('#FF0000');
```

Can you test it?

**Comment by timp999** [comment]
Yeah, by the time I got to the bottom of that I was pretty clearly convinced the problem was with me by far. Thanks very much for the patient reply.

**Comment by ConsoleTVs** [comment]
@timp999 I also understand it's a bit tricky. Considering that the last version of this library was much easier to use, but at the same time much more limiting. This version require a bit more of understanding but at the same time gives much more power :)
