### ISSUE TITLE
Grouping data by date

### ISSUE THREAD

**Issue by Emily-J-Hall** [ConsoleTVs/Charts#491]
I want to have a line chat which shows a number of levels according to the date inputted by the user and stored in a database. I can't seem to get it to display properly, where am I going wrong?
My code:

`public function index(BloodSugar $bloodSugar)
    {

        $data = \DB::table('blood_sugars')
            ->select('date', \DB::raw('blood_sugar_level'))
            ->groupBy('date')
            ->get();

        $line = Charts::database($data, 'line', 'highcharts')
            ->title("Blood Sugars")
            ->elementLabel('Blood Sugar Levels')
            ->groupByDay();

        return view('bloodsugars.index', compact ('bloodSugar' ,  'line'));
`

**Comment by Emily-J-Hall** [comment]
The error I'm getting is: 

SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'fyp.blood_sugars.blood_sugar_level' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (SQL: select `created_at`, blood_sugar_level from `blood_sugars` group by `created_at`)

**Comment by ConsoleTVs** [comment]
I will leave this open, but we currently offer no support for outdated versions of charts. Consider upgrading.

**Comment by Emily-J-Hall** [comment]
Is this possible with a newer version? Is there an easy way for me to upgrade?

**Comment by ConsoleTVs** [comment]
> Is this possible with a newer version?

The new version just handles data. Any array / collection is welcome. That said, the user (you) is responsible for the data. You are the one who needs to sort and get the data you need (even orders etc). It just needs a plain array. There are 2 SQL examples on the docs here: https://charts.erik.cat/adding_datasets.html#database-eloquent-example-2

There's no easy way to migrate. It's a major change that's not backwards compatible.

**Comment by Emily-J-Hall** [comment]
Hi there, I've updated my version but I'm a little confused at where I should put the 
{!! $chart->container() !!} and the {!! $chart->script() !!} I have an index.blade where my graph will be but a master blade file too. Thanks

**Comment by ConsoleTVs** [comment]
1. In your master.blade add the CDN for the frontend you want. (https://charts.erik.cat/render_charts.html#load-the-js-library)
2. Add the container() in the exact place you want your chart to be displayed.
3. Add script() at the end of that file or add a @yeid in master after the body to add scripts and then use @section to place the script.

This is however, not releated to this library. Container has the HTML of the chart and script() the JS logic of that chart. You can even place them side by side.

**Comment by Emily-J-Hall** [comment]
It says Undefined variable in my master.layout even though I have defined the variable in the controller. 
`return view ('bloodsugars.index' , compact ('chart')`

**Comment by ConsoleTVs** [comment]
1. In master.blade before the end of the body tag add:
```
@yield('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js" charset="utf-8"></script>
```

Replace <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js" charset="utf-8"></script> with the CDN of your frontend library found at: https://charts.erik.cat/supported_libraries.html

2. in your bloodsugars.index, add:

```
@section('js')
{!! $chart->script() !!}
@endsection
```

It must be outside the main section.

**Comment by Emily-J-Hall** [comment]
Okay we seem to be getting somewhere - but now I'm getting that SampleChart isn't recognised and I noticed this:
![image](https://user-images.githubusercontent.com/43569024/56867500-cd9fc680-69dd-11e9-8de1-b4de7be25ad5.png)

I followed the documentation and even uninstalled and reinstalled the package.

**Comment by ConsoleTVs** [comment]
Post the contents of app\Charts\SampleChart.php

if it does not exist, it means you did not create it. https://charts.erik.cat/create_charts.html#create-a-chart-class

Have you considered this: https://charts.erik.cat/getting_started.html#youtube-series-on-this-library ?

**Comment by Emily-J-Hall** [comment]
Yep I totally see what went wrong. The videos make way more sense. I seem to just be having problems with my queries now so I'll close this
