### ISSUE TITLE
is this even possible?

### ISSUE THREAD

**Issue by vvp242424** [ConsoleTVs/Charts#494]
Can I compare two columns and group them by month?     

  $membershipCompare = Charts::multiDatabase('line', 'highcharts')
            ->title('Membership Totals')
            ->elementLabel('Total Membership')
            ->colors(['#feb2c2',
            '#698b58'])
            ->dataset('Signups', Woossub::all()->dateColumn('date_created'))
            ->dataset('Cancelations', Woossub::all()->dateColumn('end_date'))
            ->lastByMonth(5, true);

**Comment by ConsoleTVs** [comment]
I do not provide support for older versions of this library due my limited time and the inexistence of backwards compatibility.

The new version opts out of the database world to allow the user to 100% take control of the chart and the data you have. So a bit of manual data tweak to get the right data is necessary.
