### ISSUE TITLE
[BUG] Creating a guage chart.

### ISSUE THREAD

**Issue by dan3460** [ConsoleTVs/Charts#496]
I'm testing the package i'm able to create graphs using diferent charset. The one that i have not been able to get the gauge chart. I have the followiing but doesn't work:
```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Charts\TestChart;
use App\Charts\HighChart;

class ChartController extends Controller
{
    public function index()
    {
        // $chart1 = new TestChart;
        $chart1 = new HighChart;

        $chart1->labels(['One']);
        $chart1->dataset('First','gauge',[20,18,15]);

        return view('welcome',compact('chart1'));
    }
}
```
I created the class HighChart this way:
```
$ php artisan make:chart HighChart Highcharts
```
Thanks for your help.

**Comment by ConsoleTVs** [comment]
Hello! Sorry for trouble, I've only tested the basic ones. I will get back to php / charts this december, when php 7.4 comes out with typed props.

I will mark this as an issue and see if I can resolve it. However, for complex charts it's sometimes best to use the native implementation using pure JS + Highcharts in your case.
