### ISSUE TITLE
How can I use the Formatter?

### ISSUE THREAD

**Issue by apapazisis** [ConsoleTVs/Charts#498]
Hello,

I would like to use the Formatter option like in JS. How this is possible?

   series : [
        {
        type : 'bar',
        itemStyle :{
            normal : {
                label : {
                        formatter : function (params){
                        return 100 - params.value + '%';
                    },
                    textStyle: {
                        baseline : 'top'
                    }
                }
            }
        },
    ]

**Comment by Naoray** [comment]
s. #462 & #369
