### ISSUE TITLE
Click event

### ISSUE THREAD

**Issue by snehal-addweb** [ConsoleTVs/Charts#499]
Wonder if this plugin offers a click event on the bar chart and whenever end-user will click on any bar we've to redirect to user on specific page.

**Comment by ConsoleTVs** [comment]
This library is not responsible for the front end code, however, if the chosen frontend supoorts callbacks for specific events, you may use the json raw encoder to provide it. There are other issues wiin this repo with callback examples

**Comment by ConsoleTVs** [comment]
There's a JSON raw encoder where you can encode JS functions and bind them to native events on the supported library. This library is not responsible for creating events like that, so the frontend JS that you use must have it.
