### ISSUE TITLE
[BUG] Composer install fails for v6.5.5

### ISSUE THREAD

**Issue by azaricstefan** [ConsoleTVs/Charts#5]
**Required information**
 - Charts Version [6.5.5] 
 - Laravel Version [8]
 - PHP Version [7.4]
 - Frontend JS Library Used:  [Chart.js]

**Describe the bug**
Composer install fails with this error:

  - Installing consoletvs/charts (6.5.5): Downloading (connecting...)Downloading (0%)               Failed to download consoletvs/charts from dist: The "https://codeload.github.com/ConsoleTVs/Charts/legacy.zip/0005d14e4fe6715f4146a4dc3b56add768233001" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing consoletvs/charts (6.5.5): Cloning 0005d14e4f from cache
    0005d14e4fe6715f4146a4dc3b56add768233001 is gone (history was rewritten?)

                                                                                                                                                  
  [RuntimeException]                                                                                                                              
  Failed to execute git checkout '0005d14e4fe6715f4146a4dc3b56add768233001' -- && git reset --hard '0005d14e4fe6715f4146a4dc3b56add768233001' --  
                                                                                                                                                  
  fatal: reference is not a tree: 0005d14e4fe6715f4146a4dc3b56add768233001    

**To Reproduce**
composer install

**Expected behavior**
Library is successfully downloaded.

**Comment by tabacitu** [comment]
@azaricstefan how about if you try `composer update consoletvs/charts` - does that fix it for you?

**Comment by azaricstefan** [comment]
Thanks for quick reply @tabacitu !
Yes, this does help.
(closing issue)
