### ISSUE TITLE
[BUG] Echarts map not render values on the map

### ISSUE THREAD

**Issue by IbrahimEzat** [ConsoleTVs/Charts#500]
first I'd like to thank you for this amazing effort ,
i tried to use Echarts map ,but unfortunately it fails to render the values on map except that every thing seems normal, here is my code 
model method
`    public static function visitorCountryStatistics($todayCountry){
        
        $today_array=[];
        foreach($todayCountry as $today){
            $today_array[]=([
                'name'   =>$today[0],
                'value'  =>(int) $today[2]
            ]); 
        }

        $today_country = new ECharts;
        
        $today_country->dataset('Visitors distribution', 'map', $today_array);
        $today_country->theme('light');
        $today_country->displayLegend(true);
        $today_country->displayAxes(false);
        $today_country->tooltip(true);
        $today_country->options([
            'tooltip'=>[
                'show'=>true,
                'formatter'=>'<div class="text-center">{a}<span class="text-info">{b}</span><br/>{c}<br/>( {d} % )</div>'
            ],

            'geo'=>[
                'map'   => 'world',
                'roam'  => true, //if want zoom by mouse
                // 'data'=>$today_array,
                'itemStyle'=>[
                    'areaColor' => '#eee',//map Color

                    'emphasis'  =>[ //behaviour when hover area
                        'label'=>[
                            'show'=>true
                        ],
                        'areaColor' => '#28a745',
                        'shadowColor'=> 'rgba(0, 0, 0, 0.8)',
                        'shadowBlur'=> 10
                    ]
                ],
            ],
            'visualMap'=>[
                'type'  => 'continuous',
                'min'   => 0,
                'max'   => $todayCountry['totalsForAllResults']["ga:pageviews"],
                'left'  => 'right',
                'text'=>['Max','Min'],
                'calculable'=>true,
                'inRange'=>[
                    'color'=> ['#ffc107', '#28a745']
                ],

            ],
            'toolbox'   =>[
                'show'      =>true,
                'orient'    =>'vertical',
                'feature'   =>[
                    
                    'restore'=>[
                        'show'  =>true,
                        'title' =>'restore'
                    ],
                    'saveAsImage'=>[
                        'show'  =>true,
                        'title' =>'Save'
                    ],
                ]
            ],
            'title' =>[
                'show'      =>true,
                'text'      =>'Traffic Today',
                'bottom'    => 0,
                'left'      =>'center',
                
                'textStyle' =>[
                    'color'         =>'#17a2b8',
                ],
            ],
        ]);

        return ($today_country);
    }
`
of course import the map and echarts.min.js in blade , it work normally and render the map but not the values on the map !

**Comment by ConsoleTVs** [comment]
hello! Sorry to see this happening. I've had no time to test the map one. However, for complex charts it's best to use a native implementation without libraries with pure echarts. 

I will get back to PHP / Charts this december when PHP 7.4 comes out with typed props. Meanwhile, I can only mark this as a bug for me to seek an solution afterwards.
