### ISSUE TITLE
Using ajax for filtering

### ISSUE THREAD

**Issue by iamkatta** [ConsoleTVs/Charts#502]
Hello,

I am using ajax to filter data between two dates, but its throwing errors, help me in solving this issue.

**$users=  DB::table('users')->whereDate('tests.created_at','<=',somedate)->orderBy('id','desc')	
		->get();

$usersChart = Charts::database($users, 'bar', 'highcharts')
								->title("all users")
								->elementLabel("User")
								->dimensions(1000, 500)
								->responsive(true)
								->groupByHour(date('d'),date('m'),date('Y'), true);

return $usersChart;**

This is my code.

Thanks

**Comment by ConsoleTVs** [comment]
This version of charts is like 2-3 years old. Please update.
I do not support older versions due to the amount of API changes and my limited time.
