### ISSUE TITLE
Using Heatmap

### ISSUE THREAD

**Issue by o---** [ConsoleTVs/Charts#503]
I am trying to get your library for Laravel to generate a Heatmap chart using Frappe.  

Basically I have amended the following code:
`    public $special_datasets = [
        'pie', 'percentage', 'heatmap',
    ];`

and I am generating the data in my Controller as follows:
`        $xChart = new HeatmapChart;
        $xChart->title('Test Heatmap');
        foreach ($data as $key => $value) {
            $values['dataPoints'][strtotime($value->date)] = $value->sum;
        }
        $values['start'] = strtotime('02.01.2019');
        $values['end'] =  strtotime('12.06.2019');
        $values['countLabel'] = 'kg';
        // $values['discreteDomains'] = 0;
       // $values['type'] = 'heatmap';

        $xChart->dataset('HeatMap', 'heatmap', $values)->color('#ebedf0', '#c0ddf9', '#73b3f3', '#3886e1', '#17459e');`

This is the resulting Javascript generated by Charts:

`<script  type="text/javascript">
    function phlxrzgyonqfdwisukbjeavtm_getType(data) {
        var special_datasets = ["pie","percentage","heatmap"];
        for (var i = 0; i < special_datasets.length; i++) {
            for (var k = 0; k < data.length; k++) {
                if (special_datasets[i] == data[k].chartType) {
                    return special_datasets[i];
                }
            }
        }
        return 'axis-mixed';
    }
    function phlxrzgyonqfdwisukbjeavtm_create(data) {
        phlxrzgyonqfdwisukbjeavtm_rendered = true;
        document.getElementById("phlxrzgyonqfdwisukbjeavtm_loader").style.display = 'none';
        window.phlxrzgyonqfdwisukbjeavtm = new frappe.Chart("#phlxrzgyonqfdwisukbjeavtm", {
            height: 400, 
            labels: [],
            type: phlxrzgyonqfdwisukbjeavtm_getType(data),
            data: {
                labels: [],
                datasets: data
            },
            "barOptions":{"spaceRatio":0.75},"title":"Test Heatmap","colors":["#ebedf0"]
        });
    }
        let phlxrzgyonqfdwisukbjeavtm_rendered = false;
let phlxrzgyonqfdwisukbjeavtm_load = function () {
    if (document.getElementById("phlxrzgyonqfdwisukbjeavtm") && !phlxrzgyonqfdwisukbjeavtm_rendered) {
                    phlxrzgyonqfdwisukbjeavtm_create([{"values":{"dataPoints":{"1546387200":"80784","1546473600":"828","1546646400":"7887","1546905600":"9029","1546992000":"1234","1547164800":"1888","1547683200":"15083","1547769600":"6535","1548028800":"466","1548115200":"989","1548201600":"6527","1548288000":"81926","1548374400":"17910","1549065600":"98","1549152000":"984","1549238400":"8170","1549324800":"34","1549497600":"99","1549584000":"345","1549670400":"345","1549756800":"468","1549929600":"635","1550016000":"234","1550102400":"5046","1550620800":"800","1550707200":"798","1551052800":"6777","1551744000":"1033","1552003200":"2930","1553731200":"26923","1554076800":"870","1554163200":"354","1554249600":"1231","1554336000":"1764","1554422400":"3342","1554854400":"1233","1555286400":"18308","1555372800":"16927","1555459200":"46533","1556755200":"1389","1556841600":"2544","1560038400":"1652","1560297600":"25000"},"start":1546387200,"end":1560297600,"countLabel":"kg"},"name":"HeatMap","chartType":"heatmap"}])
            }
};
window.addEventListener("load", phlxrzgyonqfdwisukbjeavtm_load);
document.addEventListener("turbolinks:load", phlxrzgyonqfdwisukbjeavtm_load);

</script>
`

Now the result is, that the chart is generated, but all values are ignored - showing as 0. 

**Can you please suggest how to resolve?**

**Comment by VinceSanityyy** [comment]
cant get an answer T_T

**Comment by ConsoleTVs** [comment]
Please create a new issue with the bug report template and post codes accordingly to avoid messy codes like the one here.
