### ISSUE TITLE
How to use function in options 

### ISSUE THREAD

**Issue by noonenew** [ConsoleTVs/Charts#508]
Hi, 

I am trying to build a chart with a custom tooltip, how can i add a function in to the options of the tooltip like :

```
    options: {
        tooltips: {
            callbacks: {
                label: function(value, context) {
                    var values = Number(value.yLabel)
    
                                    return ' $' + values.toFixed(2).replace(/\d(?=(\d{3})+\.)/g, '$&,') + " Disbursed of $" + Total + " in " + context.labels[value.index];;
                                }
            }
        }
    }
```

Can you help me please

**Comment by ConsoleTVs** [comment]
There are other issues with the same stuff. The solution is around aomething called json raw encoder or something, its included in the library. I have no time now, maybe I can check it out later. Check similar issues, its tyere somewhere

**Comment by wilkerdevsquad** [comment]
I'm trying to use the chart.js onClick right now and I'm using this issue as a guide: #369. It contains the RAW enconder that @ConsoleTVs pointed.
