### ISSUE TITLE
[QUESTION] How to change the tooltip using ChartJs?

### ISSUE THREAD

**Issue by BrunoFelipeAlbuquerque** [ConsoleTVs/Charts#512]
Hi there,

I'm trying to change my tooltip in ChartJS using [this example](https://stackoverflow.com/questions/43604597/how-to-customize-the-tooltip-of-a-chart-js-2-0-doughnut-chart). But it doesn't work at all.

My option code is the following:
` $connection->options([
      'elements' => [
        'line' => [
          'tension' => 0.000001
        ],
        'point' => [
          'radius' => 0
        ]
      ],
      'scales' => [
        'xAxes' => [
          ['ticks' => [
            'autoSkip' => false
            ]
          ]
        ]
      ],
      'tooltips' => [
        'callbacks' => [
          'afterLabel' => function(tooltipItem, data) {
            let dataset = data['datasets'][0];
            return dataset;
          }
        ]
      ]
    ])`

I'm having trouble to implement this because the js syntax in the PHP code. How can I do it?

**Comment by ConsoleTVs** [comment]
Check this issue on how to handle callbacks in JS from PHP:

https://github.com/ConsoleTVs/Charts/issues/508

**Comment by ConsoleTVs** [comment]
Specially this answer: https://github.com/ConsoleTVs/Charts/issues/369#issuecomment-386657051

**Comment by BrunoFelipeAlbuquerque** [comment]
Gonna try it, thanks.
