### ISSUE TITLE
[QUESTION] How to add presets to chart class?

### ISSUE THREAD

**Issue by CristianEstiber** [ConsoleTVs/Charts#513]
Hi, I have few questions, what's the point on creating multiple charts for each task with php artisan make chart? I mean you can use that template for every chart right? It's just an empty class, so I don't get the point of having multiple instances for everything.

And the other question is if its possible to predefine something on that classes, for example instead of handle it on controller do it on that classes and then call it on controller or give colors by default for that specific class

**Comment by ConsoleTVs** [comment]
> what's the point on creating multiple charts for each task with php artisan make chart? I mean you can use that template for every chart right? It's just an empty class, so I don't get the point of having multiple instances for everything.

https://github.com/ConsoleTVs/Charts/issues/507

> And the other question is if its possible to predefine something on that classes, for example instead of handle it on controller do it on that classes and then call it on controller or give colors by default for that specific class

That's the purpose 😅

This questions are like:

Why does laravel have Jobs (classes that can be dispatched) when you can directly dispatch a closure...

I hope this helps!

**Comment by AnaliaFelten** [comment]
hi friend!  this preset don work for me:

$char->presetTitle('My Title');

or 

$char->title('My Title');

the documentation is not clear
