### ISSUE TITLE
[QUESTION] How to create a multiple axis chart using chartjs

### ISSUE THREAD

**Issue by collinkoornstra** [ConsoleTVs/Charts#527]
I just started using this amazing bundle. The problem i run in to at the moment is that i can't find any documentation on how to make a multiple y axis graph. 

Can someone point me in the right direction or show me a example on making a graph with multiple y axis.

**Comment by raisonon** [comment]
Looks like it was decided not to support this in 2017: https://github.com/ConsoleTVs/Charts/issues/63

ChartJS outline how to have multiple Y axis here: https://canvasjs.com/docs/charts/how-to/multiple-y-axis/

Looks like we need to pass a param called axisYIndex for each dataset.

eg.

`    data: [{
        type: "line",
        axisYIndex: 0, //defaults to 0
        dataPoints : [
            { label: "apple",  y: 10  },
            { label: "orange", y: 15  },
            { label: "banana", y: 25  },
            { label: "mango",  y: 30  },
            { label: "grape",  y: 28  }
        ]
        },
        {
        type: "column",
        axisYIndex: 1,
        dataPoints : [
            { label: "apple",  y: 10  },
            { label: "orange", y: 15  },
            { label: "banana", y: 25  },
            { label: "mango",  y: 30  },
            { label: "grape",  y: 28  }
        ]
        }
    ]
`

I'm experimenting but no luck so far.

**Comment by raisonon** [comment]
Perhaps @ConsoleTVs will reconsider adding support now as it's supported by ChartJS as per link above.

For me I want to chart revenue and days worked for different months.

So I have my X-axis as months: Jan, Feb, Mar etc.
Y-axis as
1) Revenue per month
2) Days worked per month

We could use the axisYIndex to send two datasets...

**Comment by ConsoleTVs** [comment]
Your link is not even releated to chartjs...

This library is getting a major rework in a few days time. Before feb 15.

**Comment by raisonon** [comment]
Sorry about the wrong link - think I'd been looking at the screen too long to see difference between CanvasJS and ChartJS.

Here's a correct link where multiple axes for ChartJS: https://www.chartjs.org/docs/latest/axes/

Excited to hear about major rework - do you think multiple Y-Axes will be a feature?

Thanks for the hard work!

**Comment by mauriciogrupoc** [comment]
> Your link is not even releated to chartjs...
> 
> This library is getting a major rework in a few days time. Before feb 15.

Hi @ConsoleTVs, I really appreciate if you can support the multiple axes, I've been stuck for a while trying to figure it out how to do that, when can we expect that major rework?

Thanks!

**Comment by ConsoleTVs** [comment]
I'm still working on it... Documentation and much is under development... https://github.com/Chartisan

**Comment by ConsoleTVs** [comment]
The new rework will use Chartisan's PHP backend and add some laravel specific features to it :D

**Comment by ingmontoya** [comment]
> I'm still working on it... Documentation and much is under development... https://github.com/Chartisan

Any estimated release date?

**Comment by ConsoleTVs** [comment]
It's released already (I mean ,you can install and use it), but it's not documented and I won't release it until I feel confident that the documentation is correct and can be used without issues.

**Comment by raisonon** [comment]
Looks really good @ConsoleTVs 👍

**Comment by ConsoleTVs** [comment]
Keep in mind chartisan's php backend require php 7.4. And so does the new version of this lib.

**Comment by ingmontoya** [comment]
> It's released already (I mean ,you can install and use it), but it's not documented and I won't release it until I feel confident that the documentation is correct and can be used without issues.

Hi @ConsoleTVs, sorry if this are dumb questions:

1)  the Multi axes support are already included in the lib?
2) How do I install the latest update? so far I've used the composer update command, can you please help me a little bit?

**Comment by ConsoleTVs** [comment]
As I've written previously, it's released but it does not have documentation, so I can't help you here till I get all the docs online. Also, this particular package has not been updated, chartisan have a PHP backend you can use already, again without docs. So you should wait till I release chartisan and then I will update this lib (won't take much time) to use chartisan's PHP backend and add laravel features on the top of it.

**Comment by ConsoleTVs** [comment]
I am about to launch a new version of this library. I never tried that, but I am certain this IS possible in the new version :). Follow update on the upcoming days / weeks.
