### ISSUE TITLE
A Weird Infinite loop in curve in blade[BUG]

### ISSUE THREAD

**Issue by AhmedHamzawy** [ConsoleTVs/Charts#528]
- Charts Version [e.g. 6]
 - Laravel Version [e.g. 5.8]
 - PHP Version [e.g. 7.2]
 - Frontend JS Library Used:  [e.g. Chart.js]

After finishing all model & controller Procedures as described in the document
it leads me to a weird infinite loop in last point through curve :( :( 

first time since i used the package that happened to me
and even happens if i used static regular numbers => ex. [1,2,4,5,8,5,2] 
that only happens in the last point through curve 

Thx in advance , God Bless

**Comment by ConsoleTVs** [comment]
Can you post your code? (The different parts of it relevant to the chart)

Also, please fill in the data:

Charts Version [e.g. 6]: ??
Laravel Version [e.g. 5.8]: ??
PHP Version [e.g. 7.2]: ??
Frontend JS Library Used: [e.g. Chart.js]: ??

Otherwise, I'm not able to help in here :/

**Comment by AhmedHamzawy** [comment]
$a = []
        for($i = 1; $i <= 12; $i++){
            $r = A::whereYear('created_at' , Carbon::now()->year)->whereMonth('created_at' , $i)
                     ->count();
            array_push($a, $r);
        }
        
        $b = [];

        for($i = 1; $i <= 12; $i++){
            $r = B::whereYear('created_at' , Carbon::now()->year)->whereMonth('created_at' , $i)
                    ->count();
            array_push($b, $r);
        }        

        $ab = new AB;
        $ab->labels(['يناير', 'فبراير', 'مارس', 'إبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر']);
        $ab->dataset('My dataset', 'line', $a);
        $ab->dataset('My dataset', 'line', $b);


Charts Version : "6.*.*"
Laravel Version : "5.8"
PHP Version : "7.2"
Frontend JS Library Used: Tried With Chart.js And HighCharts.js

Thx In Advance

**Comment by M0ter** [comment]
@AhmedHamzawy If you wrap your `{!! $chart->container() !!}` in a div it works for me

ex: `<div>{!! $chart->container() !!}</div>`

**Comment by mMahdiMorshedi** [comment]
I am having the same issue, all the data is in the page source but the chart isn't showing a loading circle SVG is looping in the page

**Comment by ConsoleTVs** [comment]
Csn you post the js console log?

**Comment by MoatazAbdAlmageed** [comment]
Thanks, @M0ter this help me https://github.com/ConsoleTVs/Charts/issues/528#issuecomment-540092168

**Comment by AhmedHamzawy** [comment]
Sorry For Late Response But Thanks So Much @M0ter It Solved My Issue Here
