### ISSUE TITLE
migration on live server inquiry

### ISSUE THREAD

**Issue by pongskie** [ConsoleTVs/Charts#530]
Good day Sir I need some assistance, I already created and luckily I executed well the latest chart version 6 with laravel 5.8 following the documentation. My problem is when I deploy/migrated it on live server using cpanel I got this error:

![image](https://user-images.githubusercontent.com/15688352/65858052-ae93cf00-e397-11e9-9bda-d3eea73416ab.png)

I am new with laravel as well in creating charts, what I did is as follows:

- php artisan cache:clear
- php artisan config:clear
- then I zip the whole folder then copy it
- configure env file for database connection

Maybe I am missing some steps, hoping for some help , Thank you in advance and more power to you.

**Comment by ConsoleTVs** [comment]
You must install charts on the live server. Run:

`composer install`

At the root of your live server laravel app.

If you dont have ssh acces, make sure you are copying the vendor folder as well...

**Comment by pongskie** [comment]
Thank you sir on your immediate response, unfortunately yes I do not have ssh access on the live server, but I do have copied the vendor folder as well.

![image](https://user-images.githubusercontent.com/15688352/65947487-00f1f000-e46b-11e9-8fc8-8c679e845ca8.png)

**Comment by Naoray** [comment]
@pongskie srsly this is not a problem related to this package, but to the general installation of a laravel project. Please refer to the [installation guide](https://laravel.com/docs/6.x/installation) and a [suggestion on how to use composer when not having ssh available](https://stackoverflow.com/questions/46612585/how-to-install-use-composer-without-ssh)
