### ISSUE TITLE
[QUESTION] Combine static chart and API/Update

### ISSUE THREAD

**Issue by Albvadi** [ConsoleTVs/Charts#533]
Hi,
first of ll, thanks for this awesome package!

Is it possible to configure the first dataset of the chart statically and then update the dataset using the API?

Currently, at the time you configure the api method, all loads are made using ajax, including the first load when the data was already coming from the controller. In this way, when the data is passed to the view for the first time, I already have the correct dataset, but still, we have to make a new request to get back the same data I already had.

And in this way, you have to make extra queries to get the dataset, a first query for the labels and a second query when you call the api method to get the dataset.

Example:
```php
public function index()
{
    // First query only for labels
    $allusers = Users::all();
    
    $users = $allUsers->mapWithKeys(function ($user) {
        return [$user->name => $user->level];
    });
    
    $chartUsers = new SampleChart;
    $chartUsers->labels($users->keys());

    // This not working, because the next line
    $chartUsers->dataset('My dataset', 'doughnut', $users->values());

    // This force to load the first dataset from an ajax call
    $chartApps->load(route('chart.dataset'));
    
    return view('dashboard.index', compact('chartUsers'));
}

public function chartDataset()
{
    // Second query only for values
    $allusers = Users::all();
    
    $users = $allUsers->mapWithKeys(function ($user) {
        return [$user->name => $user->level];
    });
    
    $chartUsers = new SampleChart;
    $chartUsers->dataset('My dataset', 'doughnut', $users->values());
    
    return $chartApps->api();
}
```

Thanks!

P.S: sorry for the explanation... It´s diffficult explain very precise things when it´s not your first language... :see_no_evil:

**Comment by ConsoleTVs** [comment]
I understand your concerns, and yes, you're right that there could be an improvement on the first load. Currently, this behavior is not in this library, however, I plan to make a new update soonish (I am very busy with my master to be precise about it) and this is one of those features worth adding, so I will add this as a feature for the next version!

Thanks a lot for the ideas / contributions!

PS; If you have some free time and want to participate on https://hacktoberfest.digitalocean.com/ you might want to help the development of this library and submit a PR! I normally accept all PRs and this will speed up the feature time and grant your a t-shirt hehe!
