### ISSUE TITLE
Group By Month Data set v5 vs v6

### ISSUE THREAD

**Issue by jcadima** [ConsoleTVs/Charts#534]
I dont see in the examples or API a method that was available in v5, for example "groupByMonth" where it displayed data not only for last month, last 6 months etc, and it printed the labels and data.

In v6 this requires to manually set the labels and get the counts compared to v5 which had these methods out of the box.

```php
        $chart = Charts::database($users, 'bar', 'highcharts')
			      ->title("Monthly new Register Users")
			      ->elementLabel("Total Users")
			      ->dimensions(1000, 500)
			      ->responsive(false)
			      ->groupByMonth(date('Y'), true);

```

**Comment by ConsoleTVs** [comment]
Yes exactly. This is a charting lib. Not a data processing lib.

**Comment by jcadima** [comment]
> Yes exactly. This is a charting lib. Not a data processing lib.

For Laravel 6.* Which is LTS, is it safe to still use the v.5 ? Or will it break sometime in the life cycle of point releases of Laravel 6 and it's just better to stick with the v.6

**Comment by ConsoleTVs** [comment]
What's wrong with your writing literally 3 lines to get the data you need?

You can use the version you want, beware tho, that the latest one is the only supported by me.

**Comment by jcadima** [comment]
> What's wrong with you writing literally 3 lines to get the data you need?
> 
> You can use the version you want, beware tho, that the latest one is the only supported by me.

I'm supporting an application that is heavily customized with v5 and will need to be updated to Laravel 6 and involves more than just a couple of queries to get lots of analytics and make heavy use of the API processing method calls.
Thanks for letting me know about support for versions < 6

**Comment by ConsoleTVs** [comment]
> involves more than just a couple of queries to get lots of analytic

The v5 just performs a little query. You can check it on the source code. You may replicate and still get all the benefits of v6.
