### ISSUE TITLE
[QUESTION] API Passing Authentication Headers

### ISSUE THREAD

**Issue by xitude** [ConsoleTVs/Charts#536]
Our system uses JWT Tokens (Bearer) to make API requests. Currently, I moved the chart pathing outside it but I'm trying to find a way to include headers in the request correctly.

**Comment by ConsoleTVs** [comment]
Hello @xitude , stay tunned. I might take a loot at it shortly. If this is not yet possible, it will be.

**Comment by ConsoleTVs** [comment]
This is now possible in the next release: https://github.com/Chartisan
