### ISSUE TITLE
[QUESTION] What is the theory behind the raw plugins line?

### ISSUE THREAD

**Issue by ccsliinc** [ConsoleTVs/Charts#537]
I am using the datalabels plugin, I would like to set some global options via the options key.  I do not undertand the thought behind this line of code, can you please explain or can we do

```php
        if (!empty($options['plugins']) && gettype($options['plugins']) != 'array') {
            $options['plugins'] = new Raw(trim(preg_replace('/\s\s+/', ' ', $options['plugins'])));
        }
```

**Comment by ConsoleTVs** [comment]
Since the library is close to a major release, I will leave this here meanwhile:

https://github.com/ConsoleTVs/Charts/pull/471
