### ISSUE TITLE
[QUESTION] Multiple bars or lines

### ISSUE THREAD

**Issue by gbaltazar** [ConsoleTVs/Charts#538]
Hi!

How can I get a bar chart with multiple bars or series? I need to add many datasets? Can you help me with some sample code?

My code is:

```
        $securityChart = new Echarts;

        $dataSet = getSecurityData();

        $series = $dataSet->pluck('securityName')->unique();

        $securityChart->labels($dataSet->pluck('printDate')->unique());

        foreach ($series as $key => $value) {
            $securityChart
            ->dataset($value, 'bar', $dataSet->where('securityName', $value)->pluck('total'))
            ->color($this->backgroundColors[$key]);
        }

```

My data in JSON format looks like

`[{"securityName":"Seguridad del paciente","theDate":"2019-01-01","printDate":"enero 2019","total":2},{"securityName":"Seguridad hospitalaria","theDate":"2019-02-01","printDate":"febrero 2019","total":1},{"securityName":"Seguridad hospitalaria","theDate":"2019-03-01","printDate":"marzo 2019","total":1},{"securityName":"Seguridad del paciente","theDate":"2019-04-01","printDate":"abril 2019","total":1},{"securityName":"Seguridad del paciente","theDate":"2019-05-01","printDate":"mayo 2019","total":2},{"securityName":"Seguridad hospitalaria","theDate":"2019-06-01","printDate":"junio 2019","total":1},{"securityName":"Seguridad hospitalaria","theDate":"2019-08-01","printDate":"agosto 2019","total":1},{"securityName":"Seguridad del paciente","theDate":"2019-08-01","printDate":"agosto 2019","total":3}] 
`

But my chart looks like 

![image](https://user-images.githubusercontent.com/24255772/69414063-97a69480-0cd7-11ea-8ef4-beee78e8a096.png)

As you can see the data on the chart is wrong. Can you help me to fix the chart?

Thank you so much.

**Comment by mafalda2007** [comment]
Hola, también quiero implementar adaptar los graficos y comence como vos. 
Cree grafico con make:chart GraficoChart? 
La versión 7 de consoleTv cambia con la 6.
Este código es de \App\Charts\GraficoChart
public function handler(Request $request): Chartisan
    {
$datos = DB::table('TABLA DE LOS DATOS')
        ->select(DB::RAW(" date_format(FECHA,'%Y%m') as FECHA, SUM(Paciente) as paciente, SUM(hospitalaria) as hospitalaria"))
        ->groupBy('fecha')
        ->get();
        $pacientes= $datos->pluck('paciente')->toArray();
        $hospitalarias = $datos->pluck('hospitalaria')->toArray();
        $fecha = $datos->pluck('fecha')->toArray();
        return Chartisan::build()
            ->labels($fecha)
            ->dataset('Pacientes', $pacientes)
            ->dataset('Sample 2', $hospitalarias);
}
Tengo otros problemas pero por ahi te sirve
![image](https://user-images.githubusercontent.com/18195074/85877006-e60b9c80-b7ac-11ea-8352-3fbe76c4e9c5.png)

**Comment by ConsoleTVs** [comment]
Espero que te guste la nueva version :) @mafalda2007 

Estoy desarollando Chartisan paralelamente y es muchissimo mas flexible y rapido de lo que era esta libreria.
