### ISSUE TITLE
[chart proposal] C3 JS libary

### ISSUE THREAD

**Issue by BlueTeck** [ConsoleTVs/Charts#54]
Hi all,

the charts of http://c3js.org are very nice, maybe someone has time to add the templates.

Regards,
Timo

**Comment by ConsoleTVs** [comment]
I will once 3.0 gets released & stable since we first need to have a base.

**Comment by ConsoleTVs** [comment]
Done in 3.0!

**Comment by BlueTeck** [comment]
Thanks :) (just missing in the readme)

**Comment by ConsoleTVs** [comment]
Nope, the readme ia currentlt at 2.0.2

3.0 version / docs are not out yet

**Comment by BlueTeck** [comment]
ah okay ;)
