### ISSUE TITLE
Error - Class 'ConsoleTVs\Charts\Classes\ChartJs\Chart' not found - Solved

### ISSUE THREAD

**Issue by savanihd** [ConsoleTVs/Charts#540]
When i installed your package for chart and trying to create simple example first. I found issue as "Class 'ConsoleTVs\Charts\Classes\ChartJs\Chart' not found" 
After long time search on google i din't find solution but then last i saw your namespace and you added small latter on js. You can see on bellow screenshot:
![Screenshot from 2019-12-10 12-18-19](https://user-images.githubusercontent.com/6205405/70502580-2b38eb80-1b47-11ea-82da-9e2ca0dc215d.png)

Now if you change code like as bellow then it will solve your issue:
```
use ConsoleTVs\Charts\Classes\ChartJs\Chart;
To 
use ConsoleTVs\Charts\Classes\Chartjs\Chart;
```

Bellow Code:
```
<?php

namespace App\Charts;

use ConsoleTVs\Charts\Classes\Chartjs\Chart;

class UserLineChart extends Chart
{
    /**
     * Initializes the chart.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }
}
```
I hope it can help you...

**Comment by ConsoleTVs** [comment]
Read this: https://charts.erik.cat/create_charts.html#create-a-chart-class, specially *Possible values are explained in the supported libraries.*

As turns out, https://charts.erik.cat/supported_libraries.html#library-name, the name must be: "Chartjs"

This is not an issue, you just misspelled it when creating the chart

**Comment by ahmad219** [comment]
I have followed the procedure in laravel 6.x
1.	Add  to app.php
ConsoleTVs\Charts\ChartsServiceProvider::class,  
......
'Charts' => ConsoleTVs\Charts\Charts::class, to app.php

2.	UserChart.php
<?php
namespace App\Charts;
use ConsoleTVs\Charts\Classes\Chartjs\Chart;
class UserChart extends Chart
{
    /**
     * Initializes the chart.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }
}
3. Make controller
<?php

3.	Conroller
namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\User;
use App\Charts\UserChart;
use Charts;

class GrafiksdmController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $chart = Charts::new('line', 'highcharts')
            ->setTitle('My nice chart')
            ->setLabels(['First', 'Second', 'Third'])
            ->setValues([5,10,20])
            ->setDimensions(1000,500)
            ->setResponsive(false);
        return view('grafik.index', ['chart' => $chart]);  
    }

4.	Route 
Route::get('/grafik','GrafiksdmController@index');

But ErrorException still comes out The 'ConsoleTVs \ Charts \ Charts' class was not found. Please ask for an explanation and a solution.
