### ISSUE TITLE
[BUG] Chart is not loaded on a page loaded with ajax

### ISSUE THREAD

**Issue by DanielMalmgren** [ConsoleTVs/Charts#541]
**Required information**
 - Charts Version 6.5.3
 - Laravel Version 6.7.0
 - PHP Version 7.2.9
 - Frontend JS Library Used:  Chart.js

**Describe the bug**
It doesn't work having a chart on a page that is loaded using Ajax. The loading spinner is never replaced with the real chart.

**To Reproduce**
1. Make a page with something like the following:

`<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js" charset="utf-8"></script>`
`<div>`
`    {!! $chart->container() !!}`
`</div>`
`{!! $chart->script() !!}`

This page will now work when displayed "on its own".
2. Make a page which loads the above page in a div using Ajax, something like this:
`$.get(loadurl, function(data) {`
`            $(targ).html(data);`
`});`
(loadurl is the url to the page to be loaded, targ is the target div into which to load)

**Expected behavior**
The graph should be displayed

**Additional context**
I've concluded that the problem is that the "load" event is never fired on a page loaded using Ajax, so the {{$chart->id}}_load function is never triggered.

Putting this piece of very ugly workaround code just below the chart makes it work, but it's obviously not preferred:
`<script type="text/javascript">`
`  $(document).ready(function(){`
`    $('canvas').each(function() {`
`        var id = $(this).attr('id');`
`        eval(id + '_load()')();`
`    });`
`  });`
`</script>`

**Comment by ConsoleTVs** [comment]
Hi @DanielMalmgren, Thanks for the detailed bug report!

I don't know what does Jquery behind the back, but I assume calling `.html(data)` does only load some html in the page. Consider that the blade template where you call `{!! $chart->script() !!}` does in fact include a script tag. I assume the issue is that .html does not execute that script tag. I will take a look at this.

Also, the workaround code is a bit messy, I understand. Please note that charts provide a way to access the chart id using blade (by the use of `{{ $chart->id }}`) but I think this is not really applicable in your case.

**Comment by DanielMalmgren** [comment]
Doh. Didn't know that. It means at least I can do a much nicer workaround:
`    $(document).ready(function(){
        {{$chart->id}}_load()
    });`

Still a workaround, but much more decent.

**Comment by ConsoleTVs** [comment]
May I ask why do you need to load a blade template using ajax? It's not very common to load a page like that I would say. I've only seen that on turbolinks and this lib is compatible with it. However manualy loading it is not something I took into consideration.

**Comment by DanielMalmgren** [comment]
Well, I do that a lot... Say for example I have a page where the user is supposed to choose a company in a dropdown and then there is a div below the dropdown showing statistics for that company, then I load a blade template with the correct information into that div. Maybe there is a simpler way that I don't know about?

**Comment by kdion4891** [comment]
If you want the charts to display via AJAX you'll have to use JS `eval()` on the content that is loaded. I have the same issue with datatables I display inside modals.

Heres what I use:

    $(this).find('script').each(function () {
        eval($(this).text());
    });

**Comment by ConsoleTVs** [comment]
This is supported in the new version. The current one won't have that.
