### ISSUE TITLE
[QUESTION] PDF Help

### ISSUE THREAD

**Issue by ingmontoya** [ConsoleTVs/Charts#542]
Hi, 

I'm working with laravel charts and i need to include them in a pdf report, until now, i've been trying to do it using wkhtmltopdf but since the chart renders on a canvas element, It doesn't convert it.

Any thoughts?
Thanks

**Comment by ConsoleTVs** [comment]
PDF is a server thing, you should use a server chart. Charts currently have no support for server rendered charts. Your best bet is to generate the chart on the server as an image.

**Comment by ingmontoya** [comment]
Thanks for your quickly response :)

Would you recommend a way to do it? So far the one that can be added to a pdf is using google charts.

**Comment by ConsoleTVs** [comment]
I would go with this: https://jpgraph.net/. You can create the chart and render it as an image on the PDF.

**Comment by ConsoleTVs** [comment]
I am working on a new version of charts at the moment, considerations like this are welcome, but this is more server driven.
