### ISSUE TITLE
[QUESTION] How to set the nested options of ChartJS?

### ISSUE THREAD

**Issue by Thomasvdw** [ConsoleTVs/Charts#543]
Hi all, 

How to access and set the options (e.g. axis title)? 

Using "Options" to do something like this works:

->options([
            'borderColor' => 'black',
        ]);

But how to access deeper down the options? (JS structure)

_options : {
      scales: {
        yAxes: [{
          scaleLabel: {
            display: true,
            labelString: 'probability'

**Comment by ConsoleTVs** [comment]
By using PHP?

```php
[
    'a' => [
        'b' => [
            'c' => true
        ]
    ]
];
```

Equals to:

```js
{
    a: {
        b: {
            c: true
        }
    }
}
```
