### ISSUE TITLE
[QUESTION] Showing empty message if data is empty?

### ISSUE THREAD

**Issue by kdion4891** [ConsoleTVs/Charts#544]
Is there a way to show an empty message if the chart currently has no data?

Or how would you recommend I do this?

**Comment by ConsoleTVs** [comment]
@if ?

I mean, just wrap the `$chart->container()` between an if / else depending on your data....

**Comment by kdion4891** [comment]
Yeah I put all of the data inside of the chart classes, though.

Would be cool if there was a $chart->isEmpty() method or something to determine if the chart actually has data or not. This would make things a lot more concise in views etc.

Now I'm going to have to remove all of the data stuff from the chart class where it is nicely contained just so I can check it inside views.

Other than that I love this package so far and thank you for all your time.

**Comment by ConsoleTVs** [comment]
I agree there could be something like that. However, please note I'm working on this: https://github.com/chartisan

This option is cool to have it there tho, thanks!
