### ISSUE TITLE
How to modify other chart customisations

### ISSUE THREAD

**Issue by cambothecambo** [ConsoleTVs/Charts#547]
Hi,

I am successfully using laravelcharts and chart.js.  I am struggling with chart customisation though.  I have the basics sorted like customising displaylegend, etc the stuff thats in here: https://github.com/ConsoleTVs/Charts/blob/master/src/Features/Chartjs/Chart.php  

What I am struggling with is customising things that are not in chart.php  but are available in chart.js How would I for example remove the grid lines in a bar graph or format of the number on the Y axis?

All help is appreciated.

**Comment by ConsoleTVs** [comment]
What you are asking is something you should ask in the chart.js project and not here. As you noted I added a few presets for you to use, but when more advanced things are needed you need to look it up at chart.js project. Therefore, find the options needed and just pass them to the options() method on the chart instance like every other preset in the file you showed me.

**Comment by cambothecambo** [comment]
Awesome thanks for the help.

Cam
