### ISSUE TITLE
[QUESTION] Updating the labels

### ISSUE THREAD

**Issue by tonhal** [ConsoleTVs/Charts#548]
Hi! I am generating a chart.js horizontalBar chart which will show me datas between two dates for employees who has data for that time interval. I use the load() and api() methods to refetch the datas after changing the date input fields. 

However, only the datasets are updated, but not the labels. Is there a way to update the labels everytime I send a request? I included the label() method but it does not seem to do anything at that point, it always shows the labels which were declared before the load() method.

**Comment by ConsoleTVs** [comment]
Yeah, I understand. This is done in the new version. Expect a release very soon :), However, it will be hosted here: https://github.com/chartisan

It will feature all the features of this lib + a lot of new improvements (including the thing you suggested)

**Comment by tonhal** [comment]
Thank you for the prompt response. Keep up the good work!
