### ISSUE TITLE
[QUESTION] Is it possible to add Vertical Line?

### ISSUE THREAD

**Issue by ahmadsyamim** [ConsoleTVs/Charts#550]
Hi,

Is it possible to create vertical line as below?

![image](https://user-images.githubusercontent.com/14102774/73241039-28bc4f00-41e4-11ea-82e5-b7000046d95a.png)

**Comment by ConsoleTVs** [comment]
This library supports so many frontends. Choose a frontend that supports it and add it as an option. The new versions of charts will come soon anyway, but that's all you have to do xD
