### ISSUE TITLE
[BUG] Loader always displayed

### ISSUE THREAD

**Issue by shankiflang** [ConsoleTVs/Charts#551]
**Required information**
 - Charts Version : 6.5
 - Laravel Version : 5.8
 - PHP Version : 7.2
 - Frontend JS Library Used: Chart.js

**Describe the bug**
Hello, I followed your tutorial to set up a ChartJs but the problem is that the loader does not come off. It is always posted. Do you know where the problem may come from?

**Comment by ConsoleTVs** [comment]
I am sure you forgot to add the CDN. At least provide me (paste it here) the error log on the console.

**Comment by shankiflang** [comment]
I added <script src = "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"> </script> at the beginning of my html file. And for the console I have no errors. I just have no graph that shows up with infinite loading

**Comment by shankiflang** [comment]
Oh, I should add {!! $viewsChart->script() !!} att the end. My bad

**Comment by ConsoleTVs** [comment]
I am glad you solved it hahaha
