### ISSUE TITLE
Syntax Error on IE11

### ISSUE THREAD

**Issue by frifrafry** [ConsoleTVs/Charts#554]
I'm using consoletvs/charts to display charts in my Laravel application.

This works fine in all modern browsers, but I get an syntax error (and no charts displayed) in Internet Explorer 11 and below. Tracing it down it seems this line (from consoletvs/charts, e.g. in init.blade.php line 8) is causing the (initial) error:

data => data.json()
So the culprit is the arrow operator, not supported in IE11. Using a polyfill seems to impossible (see Is there a polyfill for es6 arrow function?).

Now my questions:

- Did I miss a feature in consoletvs/charts?
- Is there a "Laravel" way to solve this (e.g. using babel/babel)?
- Anybody got consoletvs/charts running on IE11?

**Comment by ConsoleTVs** [comment]
I will be changing this library to use my other tool: https://github.com/Chartisan

This have a babel compilation step on the front-end or a pre-compiled one. Also, the only thing needed will be the fetch() function. This can be polyfilled.

Just stay tunned. I am writting the docs of Chartisan, and this lib will soon be ported to that.

**Comment by ConsoleTVs** [comment]
This has been done on v.7 ;)
