### ISSUE TITLE
[BUG] Laravel 7 Support

### ISSUE THREAD

**Issue by hmrneves1** [ConsoleTVs/Charts#555]
**Required information**
 - Charts Version [...]
 - Laravel Version [e.g. 7]
 - PHP Version [e.g. 7.2.19]
 - Frontend JS Library Used:  [Chart.js]

**Describe the bug**
Hello, I rebuilded a project with Laravel 7, but can't install charts, since the composer gives tons of errors. Will the package be updaded?

Best Regards

**Comment by ConsoleTVs** [comment]
You did not fill the required information I need.

Did you install the correct version?

For laravel 7: Charts 6.5.4

**Comment by hmrneves1** [comment]
Hi, Im so sorry, yes I tried the latest. O have the charts working on laravel 6. But installed laravel 7 to rebuild a project.

**Comment by ConsoleTVs** [comment]
Could you please post the errors from composer?

**Comment by hmrneves1** [comment]
Hello @ConsoleTVs , sorry to bother you with this. I have run `composer clearcache` and after this, I could install charts.  Thanks for the help/availability.

Regards, Helder

**Comment by ConsoleTVs** [comment]
I'm happy you solved it :). This lib will soon be updated (I'm working on the weekends on it)

**Comment by hmrneves1** [comment]
Hello, We could use pure js to draw the chart, but this library makes things so easy, that we can’t simply ignore it.

 

Should be part of laravel package since almost everyone was a chart on their app.

 

Best Regards

_________________________________________________________

Melhores Cumprimentos,

Helder Neves,

Técnico de Redes e Sistemas Informáticos

 

De: Erik Campobadal Forés <notifications@github.com> 
Enviada: 5 de março de 2020 10:18
Para: ConsoleTVs/Charts <Charts@noreply.github.com>
Cc: Helder Manuel Rocha Neves <hmrneves@gmail.com>; State change <state_change@noreply.github.com>
Assunto: Re: [ConsoleTVs/Charts] [BUG] Laravel 7 Support (#555)

 

I'm happy you solved it :). This lib will soon be updated (I'm working on the weekends on it)
