### ISSUE TITLE
Geo Chart Availability 

### ISSUE THREAD

**Issue by AhmedHamzawy** [ConsoleTVs/Charts#556]
In Previous Version The Geo Chart Was Available, But In This Version I Didn't Find Anymore
Is There Any Method To Use Geo Chart ?!

**Comment by ConsoleTVs** [comment]
Thanks for asking!

This is not yet something that I have considered.

Nevertheless, it's a very interesting topic.

Can you add this issue to the Chartisan Repo please? This library is now just a wrapper around my other library Chartisan.
