### ISSUE TITLE
[QUESTION] How can i add linear gradient color to Chartjs ?

### ISSUE THREAD

**Issue by robertkingkira** [ConsoleTVs/Charts#557]
Is there a way to do it from laravel controller ? or from the blade file ?

**Comment by ConsoleTVs** [comment]
When you fill an issue, it requires some information. You didnt even provide it.

Laravel version, charts version, frontend library (chartjs, echarts, ...)?

Not all front libraries support gradients.

**Comment by JemCdo** [comment]
Greetings @ConsoleTVs  , Am using laravel 7.10.2 , chart version 6.*,  All my charts (charts) are grey In color (I've attached a sample pic) I was wondering is there where to distinguish colors, Thanks.
![Capture](https://user-images.githubusercontent.com/40404495/81129022-9b5b6a00-8f4b-11ea-8821-7f77926e0ced.PNG)

**Comment by ConsoleTVs** [comment]
@JemCdo https://charts.erik.cat/customize_datasets.html#chartjs

**Comment by JemCdo** [comment]
@ConsoleTVs Working Fine, Thank you!

**Comment by zKoz210** [comment]
@ConsoleTVs How can I change all these parameters in ChartJS?
<img width="881" alt="image" src="https://user-images.githubusercontent.com/28255085/81828669-b6793b80-9542-11ea-9168-c51999d084ec.png">

**Comment by ConsoleTVs** [comment]
@zKoz210 check the features folder in this repo, some of thode options have presets already, and you can check the preset codes to get and understanding of how to change those

**Comment by ConsoleTVs** [comment]
We now have direct access to chartjs config using Chartisan hooks!
