### ISSUE TITLE
[BUG] use ConsoleTVs\Charts\Classes\\Chart Problem

### ISSUE THREAD

**Issue by cod3cruncher** [ConsoleTVs/Charts#558]
- Charts Version  6.5
 - Laravel Version 7
 - PHP Version 7.2
 - Frontend JS Library Used:  Chart.js

**Describe the bug**
I started with your installation instructions via composer and tried
to create a new Chart called NutritionPie. The class NutritionPie is created with
<?php

namespace App\Charts;

**use ConsoleTVs\Charts\Classes\\Chart;**

class NutritionPie extends Chart
{
    /**
     * Initializes the chart.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }
}

and I get the error on: use ConsoleTVs\Charts\Classes\\Chart;

**To Reproduce**
1) composer require "consoletvs/charts:6.*"
2) php artisan vendor:publish --tag=charts_config
3) php artisan make:chart NutritionPie

**Desktop (please complete the following information):**
 - OS:Mac Os

**Comment by LoBlanc** [comment]
I think this bug is happening because you created the chart class with
`php artisan make:chart {Name} {Library?}`
but did not specify as library.
