### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by dennohdee** [ConsoleTVs/Charts#561]
I am trying to display a doughnut chart on my laravel view but it is showing a spinner, 
My Controller:
$chart = new CustomerChart;
        $chart->minimalist(true);
                $chart->labels(['Income','Spend']);
                $chart->dataset('Income & Expenditure', 'doughnut',[$income,$expenditure])
                ->color($borderColors)
                ->backgroundcolor($fillColors);
        return view('customer-dashboard',compact('income','expenditure','users','myclients','mybatches','today_income','today_expenditure'),['chart' => $chart]);

My View:
                                               div class="col-md-8">
							{!! $chart->container() !!}
						</div>
@section('scripts')
	{!! $chart->script() !!}
@endsection

**Comment by ConsoleTVs** [comment]
I hope the new version fixes this ^^
