### ISSUE TITLE
[QUESTION] How to change color of axis labels?

### ISSUE THREAD

**Issue by maksakoviliya** [ConsoleTVs/Charts#563]
![image](https://user-images.githubusercontent.com/16371638/79383199-750a6600-7f6d-11ea-94ca-06265cd40b1d.png)

I mean this...Hope you can help)

**Comment by arnonm-intel** [comment]
Here's an example:
$chart->options([
                'legend'    =>
                    ['position' =>  'top',
                    'labels'     => 
                        ['fontColor' => 'white', 'fontSize' => 16]
                    ],
                'scales'    => [
                    'xAxes' => [[
                        'ticks' => [
                            'fontColor'         =>  'white',
                            'backgroundColor'   =>  'white',
                            'fontSize'          =>  16
                        ]],
                    ],
                    'yAxes' => [[
                        'ticks' => [
                            "beginAtZero"       => true,
                            'fontColor'         =>  'white',
                            'backgroundColor'   =>  'white',
                            'fontSize'          =>  16
                        ],
                    ]],
                ],
                ]);

**Comment by maksakoviliya** [comment]
Thks
