### ISSUE TITLE
[BUG] aspectRatio is not usable due to height always being set

### ISSUE THREAD

**Issue by RyanPriceDotCa** [ConsoleTVs/Charts#566]
**Required information**
 - Charts Version [6.5.4]
 - Laravel Version [e.g. 7.0]
 - Frontend JS Library Used:  Chart.js

**Describe the bug**
It is current not possible to use the aspectRatio setting.  The chartjs document states that it is only useable if height is not set.  See https://www.chartjs.org/docs/latest/general/responsive.html

BaseChart.php sets height as an integer and does not allow us to give it a null value.

**To Reproduce**
Set the aspect ratio to 1, it will not work without a null height.

**Expected behavior**
Ability to null the height in order for aspectRatio to take effect.

**Comment by ConsoleTVs** [comment]
Can you check the new version and post a new issue if this still happens?
