### ISSUE TITLE
[QUESTION] Why i can't install? 

### ISSUE THREAD

**Issue by EleaFederio** [ConsoleTVs/Charts#567]
Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info

  [Composer\Downloader\TransportException]
  The "http://repo.packagist.org/p/provider-latest%24265a6433e49422d52a16480e121e0f6789c367bf15e231a316e12ec769a208b7.json" file could not be downloaded: php_network
  _getaddresses: getaddrinfo failed: No such host is known.
  failed to open stream: php_network_getaddresses: getaddrinfo failed: No such host is known.

**Comment by ConsoleTVs** [comment]
This issue has no relation to this library.
