### ISSUE TITLE
[BUG] Installing in production server

### ISSUE THREAD

**Issue by abdosaeedelhassan** [ConsoleTVs/Charts#569]
**Required information**
 - Charts Version [6.*]
 - Laravel Version [^6.0]
 - PHP Version [7.2]
 - Frontend JS Library Used:  [Chart.js]
![composer](https://user-images.githubusercontent.com/15355610/83897676-2cde1780-a756-11ea-8693-a1f620a2c081.png)
it worked correct in local dev enviroment, the error in the production server, i think the error cased by [balping/json-raw-encoder] , i searched for it, i see that it moved from github to gitlab, is this make the error

**Comment by ConsoleTVs** [comment]
I answered on the mail you sent me. However, I find it distubring that you have to contact me on my personal / business email to get your job done when aparently, you just have to read. It literally tells you to enable allow_url_fopen on your php.ini and this error does not even come from this library, but from json-raw-encoder.

As you suggested, they moved the project. And as you can see, your composer installation attempts to clone if from the cache. Remove the composer cache then?

```
composer clearcache
```

**Comment by abdosaeedelhassan** [comment]
thank you for your reply, i am sorry about sending in your business email because firstly i am searched  for last reply on this repo it its very old, i think this packege great additional to laravel

**Comment by ConsoleTVs** [comment]
> thank you for your reply, i am sorry about sending in your business email because firstly i am searched for last reply on this repo it its very old, i think this packege great additional to laravel

Guess who is updating the package to a new major release today... :)
