### ISSUE TITLE
ChartsServiceProvider.php line 23: double arrow

### ISSUE THREAD

**Issue by hmrneves1** [ConsoleTVs/Charts#572]
Hi, after installation, I'm getting an error.

```
In ChartsServiceProvider.php line 23:

syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ',' or ')'

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

This happened to anyone?

Thanks

**Comment by Naoray** [comment]
Hi @hmrneves1, this happens because this library uses [arrow functions)[https://www.php.net/manual/en/functions.arrow.php] and therefore you need at least PHP 7.4 to run it

**Comment by ConsoleTVs** [comment]
@hmrneves1 As exolained above, this lib requires php 7.4. there are no plans to make it compatible with lower versions. Composer should have warned u since php 7.4 is a requirement. Consider upgrading, not only for this lib but for the overall features and type safety you get.
