### ISSUE TITLE
php artisan vendor:publish --tag=charts -> Unable to locate publishable resources.

### ISSUE THREAD

**Issue by jazuligh** [ConsoleTVs/Charts#575]
Publish the configuration file error
`php artisan vendor:publish --tag=charts`
Result:
-> `Unable to locate publishable resources.`
-> `Publishing complete.`

**Comment by barfrakud** [comment]
I have the same result.

**Comment by ConsoleTVs** [comment]
Let me check this out!

**Comment by ConsoleTVs** [comment]
I've updated this, try to update to 7.0.2 and try again!
