### ISSUE TITLE
Composer install issues

### ISSUE THREAD

**Issue by raisonon** [ConsoleTVs/Charts#576]
Exciting to see the new work. However I'm getting the following problem using the install process from the docs:

⚡ composer require consoletvs/charts:7.*
zsh: no matches found: consoletvs/charts:7.*

⚡ composer require consoletvs/charts
Using version ^7.0 for consoletvs/charts
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 266240 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Decisions.php on line 38

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 266240 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Decisions.php on line 38

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.%

**Comment by raisonon** [comment]
This seemed to work:

COMPOSER_MEMORY_LIMIT=-1 composer require consoletvs/charts

**Comment by ConsoleTVs** [comment]
I fixed vendor publish at 7.0.2. Can you update and try again? thanks!
