### ISSUE TITLE
[QUESTION] How to create a chart from controller?

### ISSUE THREAD

**Issue by barfrakud** [ConsoleTVs/Charts#577]
I want to create a chart in controller like it was in the previous version. Is it still possible? Any advice will be appreciated.

**Comment by ConsoleTVs** [comment]
This is no longer possible.

Chartisan is optimized for performance. The old way made controller methods bolated and slow.

However, you can treat the handle() method of the charts as a controller method. You even get the `Request $request` as a parameter for you to determine different options. You can learn more about how chartisan makes requests to laravel at:

https://chartisan.dev/documentation/frontend/creating#HTTP-Request and https://chartisan.dev/documentation/frontend/updating#HTTP-Request

You can include headers (for instance: the authentication token), or query parameters, etc.
