### ISSUE TITLE
Code to fill in blanks

### ISSUE THREAD

**Issue by c-harris** [ConsoleTVs/Charts#58]
I came across your package and built something very similar recently, the charting package I built was focused on integration with laravel and NodeJS focusing mainly on finance charts and indicators. 

I thought i would raise an issue to see if there are any bits you might need help with. I have a rather complete work load at the moment but would be happy to donate chunks of code to handle more complex issues (like web-gl support) but may not be able to find time to integrate them into your package.

**Comment by ConsoleTVs** [comment]
Hello! I would love to hear more from this, what is your package currently working like?

**Comment by c-harris** [comment]
At the moment it works well, it has a few minor issues mostly relating high flow data (more than 25 new inputs per second). it is only used in a single project. I have seperate plugin systems for indicators and data feeds. and a css parser to facilitate easy customization of the look and feel of the finished chart based on css values.

**Comment by ConsoleTVs** [comment]
But is it a laravel package as well?

**Comment by c-harris** [comment]
Intergration with Laravel exists but is lacking, that is why i thought i would offer to help with your project. because it meets the major shortcoming on my set.

**Comment by ConsoleTVs** [comment]
Yeah, feel free to help us! We love it!
