### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Evanzsnr** [ConsoleTVs/Charts#581]
Hello, I am attempting to install this package without any success. When I install I get the error below:

```
[InvalidArgumentException]
  Package consoletvs/charts at version 7.* has a PHP requirement incompatible with your PHP version (7.3.11)
```

My php version is 7.3.11 but the package is failing to install, what could be the problem raising this issue?

Thanks

**Comment by Evanzsnr** [comment]
I am using laravel 7, so when I change the package version as described [here](https://github.com/ConsoleTVs/Charts/issues/555#issuecomment-594512080), the package is installed successfully, but  when I publish, I get the following error:

```
Unable to locate publishable resources.
Publishing complete.
```

And no file is added to the config folder.

**Comment by ConsoleTVs** [comment]
This package requires php 7.4.

https://www.php.net/supported-versions.php
