### ISSUE TITLE
Chart Registration

### ISSUE THREAD

**Issue by Evanzsnr** [ConsoleTVs/Charts#583]
After successful installation and publishing, when I try to register the chart in the AppServiceProvider shown below,

```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Schema;
use ConsoleTVs\Charts\Registrar as Charts;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot(Charts $charts)
    {
        Schema::defaultStringLength(191);
        $charts->register([
            \App\Charts\ServiceRequestChart::class
        ]);
    }
}
```
I get the following error.

```
Error
Only arrays and Traversables can be unpacked
```
What could be going wrong?

**Comment by ConsoleTVs** [comment]
What php version are you using?

**Comment by ConsoleTVs** [comment]
Did you modify globalMiddlewares prop on the config?

**Comment by Evanzsnr** [comment]
I am using php 7.4.7, and I did not modify anything like a middleware prop

**Comment by Evanzsnr** [comment]
How do I modify the globalMiddlewares prop?

**Comment by ConsoleTVs** [comment]
You peaked my curiosity @Evanzsnr !

Your PHP seems to be on the correct version.

Can you share the ServiceRequestChart file please?

If I can't spot the misstake there I might ask you to modify a line in a vendor file to see if that works. Please help me identify the issue of this, because that's indeed a bug somewhere.

**Comment by Evanzsnr** [comment]
Here is the ServiceRequestChart.php

```
<?php

declare(strict_types = 1);

namespace App\Charts;

use Chartisan\PHP\Chartisan;
use ConsoleTVs\Charts\BaseChart;
use Illuminate\Http\Request;

class ServiceRequestChart extends BaseChart
{
    /**
     * Handles the HTTP request for the given chart.
     * It must always return an instance of Chartisan
     * and never a string or an array.
     */
    public function handler(Request $request): Chartisan
    {
        return Chartisan::build()
            ->labels(['First', 'Second', 'Third'])
            ->dataset('Sample', [1, 2, 3])
            ->dataset('Sample 2', [3, 2, 1]);
    }
}
```

**Comment by ConsoleTVs** [comment]
Alright lets try the first thing then:

-  Go to your vendor folder and locate this package:
    `vendor/ConsoleTVs/Charts`

- Locate the file: `src/Registrar.php`

- Comment the line 71 show here: https://github.com/ConsoleTVs/Charts/blob/master/src/Registrar.php#L71

- Try again (note that this will disable middlewares for the charts, but I want to know if the error comes from here).

**Comment by ConsoleTVs** [comment]
Also, if you could post a screenshot of the error, this will be great!

**Comment by Evanzsnr** [comment]
When I disable the line 71, the error goes away.

**Comment by ConsoleTVs** [comment]
Alright, I need you to do the following:

type:

```php
dd($globalMiddlewares);
```

at line https://github.com/ConsoleTVs/Charts/blob/master/src/Registrar.php#L58

(in the empty line before the foreach).

Paste the output here please

**Comment by Evanzsnr** [comment]
This is the output in the browser.
```
// 20200621162341
// http://localhost:8000/home

null
```

**Comment by ConsoleTVs** [comment]
As expected!

Thanks a lot for the quick replies.

I've released a new version: https://github.com/ConsoleTVs/Charts/releases/tag/7.0.4

You should update charts to 7.0.4 and this issue should be fixed. Let me know if otherwise, I'll still keep this open to see why this was happening.

**Comment by Evanzsnr** [comment]
Thanks for your help, it works after updating to version 7.0.4. But I need to know something, how do I create a chart in my controller? Every method I try gives me errors,  and I can't find any help in the documentation.

**Comment by ConsoleTVs** [comment]
You should not!

The new version is made for performance reasons in mind. Charts should be independent.

Each chart have a handle() method, think of this as controller method.

Chartisan does make a request to your server when it needs a chart to be generated, this will execute the handle() method and you'll get the Request on it.

This library is no longer independent, meaning that it is now a wrapper to a much bigger library I made called Chartisan.

You should read the docs of it to understand how it works:

https://chartisan.dev

I'll start adding examples and probably a video soon. This is a very early project, but much different that what it used to be. By using Chartisan, we are now able to do much more stuff that was unavailable before!

**Comment by Evanzsnr** [comment]
I have been reading through the Chartisan library but it looks complicated and not easy to understand since we do not have enough examples. But I will be waiting to see how to implement charts using this library. So does this mean if I use the older version, the package will work as expected earlier?

**Comment by ConsoleTVs** [comment]
Yes of course it still works as expected. However, it's not maintained anymore and the docs are down. You can still access the docs in the github repo and read it here:

https://github.com/ConsoleTVs/ChartsDocs/tree/fd537ee2a3f2652925b106274ff7031bef0c9585/docs

**Comment by mafalda2007** [comment]
Hi, is it possible to use Livewire to be able to update the graph dynamically every so often?

**Comment by ConsoleTVs** [comment]
THat's indeed something I will add to the todos. Livewire is on my list of things, so will keep that in mind. Meanwhile, I can tell you that Chartisan does indeed have a update() method to update the chart on demand using javascript.
