### ISSUE TITLE
How do I change the type of graph from line to Pie or any other?

### ISSUE THREAD

**Issue by surewood** [ConsoleTVs/Charts#587]
I was able to successfully create a hello world project, which implements the charts from this repository. I just followed the guide outlined in the documentation. I've got a line chart graph, but I'm interested in other types as well.

My question is: can someone please point me in the right direction? I was not able to find other tutorials that would help me out.

**Comment by ConsoleTVs** [comment]
Hello!! Thabks for the feedback.

Chartisan is still beeing loaded up, will take me a couple of days moed but I'll eventually add an example page with all sorts lf customization examples.

Meanwhile, you must consider reading the entire hooks page. Thats'how you can tell the chart what to render based on the selected frontend api!

**Comment by ConsoleTVs** [comment]
Ill keeo this open till i can close it!

**Comment by ssmusoke** [comment]
@ConsoleTVs I have looked in all the documentation and I cannot see how to generate a pie chart, let alone changing the default chart from bar to a line one. 

Can you provide an example, I will be happy to contribute a PR to the documentation

**Comment by kinnngg** [comment]
> @ConsoleTVs I have looked in all the documentation and I cannot see how to generate a pie chart, let alone changing the default chart from bar to a line one.
> 
> Can you provide an example, I will be happy to contribute a PR to the documentation

I hope the documentation is completed soon. For now, this should help you a bit.

```
const chart = new Chartisan({
            el: '#chart',
            url: "@chart('sample_chart')",
            hooks: new ChartisanHooks()
                .colors(['#80b587', '#ff9c9c'])
                .responsive()
                .beginAtZero()
                .legend({ position: 'bottom' })
                .datasets('line')
                .title('This is a sample chart using chartisan!')
        });
```

**Comment by ssmusoke** [comment]
@kinnngg Thank you very much!!

**Comment by ConsoleTVs** [comment]
I've started to add some examples here: https://chartisan.dev/documentation/examples

More will be added soon.

**Comment by hossamwheed** [comment]
Uncaught TypeError: (intermediate value).colors(...).responsive is not a function
