### ISSUE TITLE
Chart Disaapearsafter some seconds

### ISSUE THREAD

**Issue by othmaan100** [ConsoleTVs/Charts#588]
After following the documentation and not understanding much. I reported the problem on stackoverflow on this link
https://stackoverflow.com/questions/62498660/loading-laravel-chart-consoletvs-charts7/62715897#62715897
On resolving the problem, My Chart appears for few seconds and then disappear when the page finishes loading. 
There is no problem shown in the console. I dont know what is causing the problem. I am stucked

**Comment by ConsoleTVs** [comment]
I don't think this issue is about Chartisan, there's something in your page causing trouble...
