### ISSUE TITLE
Documentation for version 6.5

### ISSUE THREAD

**Issue by woodspire** [ConsoleTVs/Charts#589]
The documentation for version 5.x can be found in the repository.
But for version 6.5, which is used by https://github.com/fidum/laravel-dashboard-chart-tile

cannot be found since it was hosted outside the repo and you have updated it to version 7.x

How can we get the previous documentation ?

**Comment by ConsoleTVs** [comment]
https://github.com/ConsoleTVs/ChartsDocs/tree/fd537ee2a3f2652925b106274ff7031bef0c9585/docs

**Comment by dmason30** [comment]
@woodspire I have just released a v7 compatible version (3.0.0) of the [tile](https://github.com/fidum/laravel-dashboard-chart-tile). Let me know if you have any problems.

**Comment by woodspire** [comment]
> @woodspire I have just released a v7 compatible version (3.0.0) of the [tile](https://github.com/fidum/laravel-dashboard-chart-tile). Let me know if you have any problems.

Thanks. I updated my code and it seems to work fine.
