### ISSUE TITLE
Excluding imports

### ISSUE THREAD

**Issue by hawkleaf** [ConsoleTVs/Charts#59]
Hello, I love your package so far.

I have a problem with my application where I want to use your library but I'm also including Highcharts in my own App.js for custom usage. I've noticed that the rendering of assets includes all libraries, and not only the ones that are going to be used (say if I use your library for rendering a google chart it still loads highcharts)

This prevents me from using your package, is there a way that I can disable certain libraries from being rendered on my page? This would fix my conflict and prevent unnecessary assets added to my page.

**Comment by ConsoleTVs** [comment]
This is already documented:

```php
<?php echo Charts::assets(); ?>

// Using blade
{!! Charts::assets() !!}

// Only certain libraries
{!! Charts::assets(['google', 'chartjs']) !!}
```

**Comment by hawkleaf** [comment]
Oops, I must've missed it. Sorry.

**Comment by ConsoleTVs** [comment]
Haha no problem! Feel free to ask anything else if needed
