### ISSUE TITLE
Chart class not able to pick [Auth::user]

### ISSUE THREAD

**Issue by Nizzy94** [ConsoleTVs/Charts#591]
Everything else works for me with the package except I can't work with the **Auth** facade or the `auth()` helper. The errors displayed are always the same and I can't figure out what the exact issue is. 
Eg: I'm able to fetch posts with this code:
```
$posts = Post::all()->countBy('status')->toArray();
```
but the one below doesn't work:
```
$posts = Auth::user()->posts()->get()->countBy('status')->toArray();
```

It works in my controller perfectly and fetches exactly what i want, but gives an error in the handler method in the Chart class.

Is there a way around it?

**Comment by awebartisan** [comment]
I have added a global middleware of 'auth' but it keeps redirecting the chart request to login. 

So, there is something going on with Auth middleware.

**Comment by ConsoleTVs** [comment]
Will give this a shot later

**Comment by cursosdesarrolloweb** [comment]
> Everything else works for me with the package except I can't work with the **Auth** facade or the `auth()` helper. The errors displayed are always the same and I can't figure out what the exact issue is.
> Eg: I'm able to fetch posts with this code:
> 
> ```
> $posts = Post::all()->countBy('status')->toArray();
> ```
> 
> but the one below doesn't work:
> 
> ```
> $posts = Auth::user()->posts()->get()->countBy('status')->toArray();
> ```
> 
> It works in my controller perfectly and fetches exactly what i want, but gives an error in the handler method in the Chart class.
> 
> Is there a way around it?

Temporarly you can create your own route like this instead use Chartisan class:

```php 
Route::group(['prefix' => 'teacher', 'as' => 'teacher.', 'middleware' => ['teacher']], function () {
    Route::name("profits.chart")->get("/profits/chart", "TeacherController@renderChart");
});
```

Then, from your controller simply you can return a Chartisan on JSON format:
```php
\Debugbar::disable(); // <-- disable Debugbar if need
        return Chartisan::build()
            ->labels($data["labels"])
            ->dataset(__("Profit"), $data["dataset"])
            ->toJSON();
```

Hope this help.

**Comment by ConsoleTVs** [comment]
Can you please provide the error you are getting? I will try to fix this soon, PRs are welcome meanwhile. This is on my top priority because as you noted, this is an important issue thst should work. Thanks!

**Comment by cursosdesarrolloweb** [comment]
> Can you please provide the error you are getting? I will try to fix this soon, PRs are welcome meanwhile. This is on my top priority because as you noted, this is an important issue thst should work. Thanks!

Hi @ConsoleTVs, I love Chartisan! 

The issue is related to the middlewares on the Chart class, it not applied and the identified user cannot be obtained.

On my opinion, I prefer define my own routes and controllers for render the chart content.

**Comment by ConsoleTVs** [comment]
Oh well, this makes sense. However charts render the contex as an api, I think it would make sense to apply thr api middleware and the auth:api one. Thoughts?

**Comment by cursosdesarrolloweb** [comment]
> Oh well, this makes sense. However charts render the contex as an api, I think it would make sense to apply thr api middleware and the auth:api one. Thoughts?

<img width="1859" alt="imagen" src="https://user-images.githubusercontent.com/40883537/87219760-65c56980-c35e-11ea-8c84-03a14902082a.png">

With the web and auth middlewares all works fine.
Thanks for your attention @ConsoleTVs

**Comment by ConsoleTVs** [comment]
I'll make some tests and decide the best use case. However the web middleware does have additional middlewares that are not needed in the chartisan api. Will check it out. Thanks for the help!

**Comment by awebartisan** [comment]
I can confirm that following works:

`public ?array $middlewares = ['web', 'auth'];`

**Comment by ConsoleTVs** [comment]
Thanks for the confirmation @awebartisan !

**Comment by ConsoleTVs** [comment]
I've added `web` as a default global middleware in the config file (https://github.com/ConsoleTVs/Charts/blob/master/src/Config/charts.php#L31). Keep in mind that you will need to manually address this change in case your config file was already published. You'll then be able to just add `auth` as a chart middleware.

**Comment by Nizzy94** [comment]
sorry i'm replying late, but my problem was not really with the middleware. I want to get some data related to the current logged in user and i tried using `Auth::user()` and `auth()->user()` but they both don't retrieve any data but give an error instead.

**Comment by ConsoleTVs** [comment]
Because the web middleware must be present to use php's session (used by auth). Just update and try again

**Comment by arborrow** [comment]
I'm not sure I understand how charts v7 is intended to work by default; however, it seems that the api routes are not secured (do not require authentication) which would then leak data from the application to anyone pinging the api. Virtually all of my web routes require authentication. Would I be better served to create my own routes and not use the API routes? It strikes me as a rather insecure way of handling the default behavior. I'd be curious what others think.

**Comment by ConsoleTVs** [comment]
You can literally define the middlewares of your chart route (?)

**Comment by arborrow** [comment]
Thanks for the reply. Unfortunately I get lost in middleware and have not been able to find good examples to resolve the issue. I have v6 working on my production site but am looking to upgrade to v7 but running into trouble because the default suggestion to use api as the endpoint would make things insecure.

When I add:

public ?array $middlewares = ['auth'];

to the chart the endpoint stops working - I suspect because I'm using the api endpoint which has different middlewares and the documentation points to using sanctum for api authentication. I suspect I should avoid complicating things by using a web route but from what I can tell the documentation does not really provide good examples of that. 

I don't really want to abuse this issue for support so no need to reply further; however, hopefully my experience (or more accurately inexperience) can be useful in knowing where someone might get tripped up.

**Comment by ConsoleTVs** [comment]
> I've added `web` as a default global middleware in the config file (https://github.com/ConsoleTVs/Charts/blob/master/src/Config/charts.php#L31). Keep in mind that you will need to manually address this change in case your config file was already published. You'll then be able to just add `auth` as a chart middleware.
> 
> Release at: 7.0.5

@arborrow yes. the web middleware was added here.

**Comment by arborrow** [comment]
Excellent - much appreciated. I am making some progress on getting things upgraded.
