### ISSUE TITLE
Generated routes

### ISSUE THREAD

**Issue by ericnsimba** [ConsoleTVs/Charts#593]
when i run command php artisan route:list -c  i dont see any route which correspond to charts ,which gives me an error when i load a view with chart
i am following documentation from https://charts.erik.cat/guide/create_charts.html#register-the-chart

**Comment by ConsoleTVs** [comment]
That's because you did not register the chart...

```php
<?php

namespace App\Providers;

use ConsoleTVs\Charts\Registrar as Charts;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    // ...

    /**
     * Bootstrap any application services.
     */
    public function boot(Charts $charts)
    {
        $charts->register([
            \App\Charts\SampleChart::class
        ]);
    }
}
```
