### ISSUE TITLE
Route [.name_of_route] not defined.

### ISSUE THREAD

**Issue by aaron-za-dev** [ConsoleTVs/Charts#595]
I am trying to create a chart but i always get the same error Route [.name_of_route] not defined when access directly works fine!

blade.php
![blade](https://user-images.githubusercontent.com/16365508/87007815-73c19180-c188-11ea-92f0-6161d108d142.PNG)

direct access
![directaccess](https://user-images.githubusercontent.com/16365508/87007818-745a2800-c188-11ea-87ac-a90ae192f8ef.PNG)

name of route
![route](https://user-images.githubusercontent.com/16365508/87007819-745a2800-c188-11ea-9d95-326b8f3ec820.PNG)}

AppServiceProvider
![service](https://user-images.githubusercontent.com/16365508/87007821-745a2800-c188-11ea-9735-07136e4709a8.PNG)

**Comment by ConsoleTVs** [comment]
Paste the chart code and another full screenshot of the name of the route, you didnt show that on it. When you list routes, it also tells you the chart route name.

**Comment by aaron-za-dev** [comment]
I need to create a route for the chart? Or do you use the route that is generated through the php artisan make:chart command?

**Comment by ConsoleTVs** [comment]
It is nessesary. That's how Chartisan works.

Did you find the chart route name? You can also pass in a normal url to the chart:

```
url: "{{ url('api/chart/students_chart') }}"
```

**Comment by aaron-za-dev** [comment]
I solve it! only change: `url: "@chart('charts.students_chart')"` for `url: "{{ route('charts.students_chart') }}"`
