### ISSUE TITLE
THERE WAS AN ERROR

### ISSUE THREAD

**Issue by SantoshiBhujel** [ConsoleTVs/Charts#596]
THERE WAS AN ERROR
UNEXPECTED TOKEN < IN JSON AT POSITION 0

when the view loads, shows the error

**Comment by awebartisan** [comment]
Can you share more information? Check in the logs?

Are you using Auth middleware?

**Comment by SantoshiBhujel** [comment]
![Screen Shot 2020-07-12 at 7 21 40 PM](https://user-images.githubusercontent.com/53636560/87247695-0efe8380-c475-11ea-8416-6f7702c993f8.png)

this is what i get on rendering the chart view

**Comment by ConsoleTVs** [comment]
Open the chrome dev tools, ooen the network tab, and paste the response of the network request that chartisan made to your chart. This includes the response body and headers please.

**Comment by SantoshiBhujel** [comment]
Error solved

**Comment by ConsoleTVs** [comment]
Could you give more info here on what was the issue and how you solved it? Some people in the future may encounter the same issue.

**Comment by Yismen** [comment]
> Error solved

How?

**Comment by basri27** [comment]
![image](https://user-images.githubusercontent.com/51488169/152319423-45e48156-5327-4349-a4e6-b0482aaa5538.png)
how solve this?
