### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by w00p** [ConsoleTVs/Charts#6]
Hi,

Is it possible you can help me a little bit? If i want do view total registered users per month?
how would you do that in the controller?

I am using the default Laravel 5.3 auth.

Thax.

**Comment by ConsoleTVs** [comment]
Hello! I can help you!!

Let's see, First think you should do is get the ammount of users per month using the count() PHP function and filtering results inside the database. You can use the App\User Model and find the users filtering them per months. Then you simply need to add those values to the chart!!

If you are still lost, add me on skype so I can help!
Skype: ErikCampobadal

**Comment by w00p** [comment]
I will try :) i dont have Skype. Is it possible to give me some code examples here? Then i will work more with that example :)

**Comment by ConsoleTVs** [comment]
Sure, give me a second! meanwhile try to watch this video, maybe it helps you a bit! https://www.youtube.com/watch?v=IEhZTcpbknA

**Comment by ConsoleTVs** [comment]
Did you find urself a solution or I may continue developing the example?

```
Charts::new('line', 'highcharts')
            ->setTitle("My website users")
            ->setLabels(['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'])
            ->setValues([100, 50, 100, 50, 100, 50, 100, 50, 100, 50, 100, 50])
            ->setElementLabel("Total users");
```

You just need to change the values to the corresponding ones!

**Comment by w00p** [comment]
if you can make me a real example, that would be great. I tried something like this, but did not work.

```
    public function charts()
    {

        $users = User::where('created_at', '>=', \Carbon\Carbon::now()->subMonth())
            ->groupBy('date')
            ->orderBy('date', 'DESC')
            ->get(array(
            DB::raw('Date(created_at) as date'),
            DB::raw('COUNT(*) as "value"')
            ));
        
        $chart = Charts::new('line', 'highcharts')
            ->setTitle('My nice chart')
            ->setLabels($users['date'])
            ->setValues($users['value'])
            ->setDimensions(1000,500)
            ->setResponsive(false);
            
        return view('charts', ['chart' => $chart]);
    }   
```

**Comment by ConsoleTVs** [comment]
Ok, I need to finish some important work from university right now, I'll be back in around 30 minutes and I'll try to look forward it! (I never filtered the users by months)

**Comment by w00p** [comment]
Thax, but no need to filter users by month. If thats to hard. But for example show total users registered for the last 5 days. Like you use on laralum :)

/Kjetil

Den 26. sep. 2016 kl. 21.31 skrev Erik Campobadal <notifications@github.com<mailto:notifications@github.com>>:


Ok, I need to finish some important work from university right now, I'll be back in around 30 minutes and I'll try to look forward it! (I never filtered the users by months)

-

**Comment by ConsoleTVs** [comment]
Oh yeah that's easy, check it out:

https://github.com/ConsoleTVs/Laralum/blob/master/app/Http/Controllers/Laralum/Data/WidgetsOperations.php

```
$latest_users_graph['labels'] = array_reverse([
    date("F j, Y"),
    date("F j, Y", strtotime("-1 Day")),
    date("F j, Y", strtotime("-2 Day")),
    date("F j, Y", strtotime("-3 Day")),
    date("F j, Y", strtotime("-4 Day")),
]);
$latest_users_graph['values'] = array_reverse([
    count(App\User::whereDate('created_at', '=', date("Y-m-d"))->get()),
    count(App\User::whereDate('created_at', '=', date("Y-m-d", strtotime("-1 Day")))->get()),
    count(App\User::whereDate('created_at', '=', date("Y-m-d", strtotime("-2 Day")))->get()),
    count(App\User::whereDate('created_at', '=', date("Y-m-d", strtotime("-3 Day")))->get()),
    count(App\User::whereDate('created_at', '=', date("Y-m-d", strtotime("-4 Day")))->get()),
]);
$latest_users_graph['element_label'] = "Total Users";
$latest_users_graph['title'] = "Latest users in the last 5 days";
```

Then to create the chart:

```
Charts::new('line', 'highcharts')
            ->setTitle($latest_users_graph['title'])
            ->setLabels($latest_users_graph['labels'])
            ->setValues($latest_users_graph['values'])
            ->setElementLabel($latest_users_graph['element_label']);
```

I recommend setting the App\User in the class usage like:

```
use App\User;
```

Then you can simply replace all ```App\User``` with ```User```

**Comment by w00p** [comment]
Sweet! Thank you :) good job on Laralum! I like it!

/Kjetil

Den 26. sep. 2016 kl. 21.47 skrev Erik Campobadal <notifications@github.com<mailto:notifications@github.com>>:


Oh yeah that's easy, check it out:

https://github.com/ConsoleTVs/Laralum/blob/master/app/Http/Controllers/Laralum/Data/WidgetsOperations.php

$latest_users_graph['labels'] = array_reverse([
    date("F j, Y"),
    date("F j, Y", strtotime("-1 Day")),
    date("F j, Y", strtotime("-2 Day")),
    date("F j, Y", strtotime("-3 Day")),
    date("F j, Y", strtotime("-4 Day")),
]);
$latest_users_graph['values'] = array_reverse([
    count(App\User::whereDate('created_at', '=', date("Y-m-d"))->get()),
    count(App\User::whereDate('created_at', '=', date("Y-m-d", strtotime("-1 Day")))->get()),
    count(App\User::whereDate('created_at', '=', date("Y-m-d", strtotime("-2 Day")))->get()),
    count(App\User::whereDate('created_at', '=', date("Y-m-d", strtotime("-3 Day")))->get()),
    count(App\User::whereDate('created_at', '=', date("Y-m-d", strtotime("-4 Day")))->get()),
]);
$latest_users_graph['element_label'] = "Total Users";
$latest_users_graph['title'] = "Latest users in the last 5 days";


Then to create the chart:

Charts::new('line', 'highcharts')
            ->setTitle($latest_users_graph['title'])
            ->setLabels($latest_users_graph['labels'])
            ->setValues($latest_users_graph['values'])
            ->setElementLabel($latest_users_graph['element_label']);


I recommend setting the App\User in the class usage like:

use App\User;


Then you can simply replace all App\User with User

-

**Comment by ConsoleTVs** [comment]
Thanks a lot! I'm currently recoding it into modules that can be installed just like this package! We'll see what i can do!

I'm willing to see some damn good graphics in your projects with this package!

**Comment by ConsoleTVs** [comment]
Hey! I'm writting you to notify that database charts are here! You'll be able to output charts filtered by years, months and days! Check it out! https://github.com/ConsoleTVs/Charts#database-charts

**Comment by w00p** [comment]
Thats awesome! good job man! I will test it! I am working on a new design for StartUp 5.3.. will use your Charts package :)

**Comment by ConsoleTVs** [comment]
Awesome! Just making you know!
