### ISSUE TITLE
syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')'

### ISSUE THREAD

**Issue by Nizzy94** [ConsoleTVs/Charts#600]
I deployed my application but i got an error: ***syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')'***. This is actually from a vendor file located in **vendor/consoletvs/charts/src/ChartsServiceProvider.php**, on line 23. There is a double arrow but the debugger expectes ')'. I don't get what the problem is because it works perfectly on my local server. Any help?

**Comment by ConsoleTVs** [comment]
You need at least php 7.4.
