### ISSUE TITLE
 - The requested package guzzlehttp/guzzle (locked at 6.5.5, required as ^7.0) is satisfiable by guzzlehttp/guzzle[6.5.5] but these conflict with your requirements or minimum-stability.

### ISSUE THREAD

**Issue by Gellish** [ConsoleTVs/Charts#601]
- The requested package guzzlehttp/guzzle (locked at 6.5.5, required as ^7.0) is satisfiable by guzzlehttp/guzzle[6.5.5] but these conflict with your requirements or minimum-stability.
i cant adjust my package version to  guzzlehttp/guzzle 6.5.5 because its required laravel auth api

**Comment by Gellish** [comment]
please support guzzlehttp/guzzle 7.0

**Comment by ConsoleTVs** [comment]
Can u check if this is still an issue with version 7.1 ?
