### ISSUE TITLE
eCharts works - ChartJS does not work

### ISSUE THREAD

**Issue by DominikGeimer** [ConsoleTVs/Charts#602]
Hello,

I have a Laravel 7 app.

I followed the instruction from https://charts.erik.cat/ and everything works fine, when I use the eChart library like the example here: https://charts.erik.cat/guide/render_charts.html

But when I change the CDNs from eChart to ChartJS like the example here: https://chartisan.dev/documentation/installing#Installing-the-front-end-adapter

```
<!-- Charting library -->
<script src="https://unpkg.com/chart.js/dist/Chart.min.js"></script>
<!-- Chartisan -->
<script src="https://unpkg.com/@chartisan/chartjs/dist/chartisan_chartjs.js"></script>
```

I get an error in the chrome console and the chart does not render. Any idea?

```
Uncaught ReferenceError: require is not defined
    at chartisan_chartjs.js:1
```

Thanks!

**Comment by ConsoleTVs** [comment]
This is fixed now. I've updated the docs, please check them out! Sorry, echarts will follow a similar change in the upcomming days / weeks.
