### ISSUE TITLE
Infinite loading - Data returned from @charts but yAxis empty in hooks

### ISSUE THREAD

**Issue by JapSeyz** [ConsoleTVs/Charts#606]
Hi,

This is a rather odd issue, the Charts worked great in $project1, but copying it over to replace Charts 6.5 w/ Chartisan, I am getting some strange bugs.

1) The loading animation appears to run infinitely, never getting replaced by the data.
2) The data is returned from the url: "@chart" call in JS.
3) in hooks.custom I am logging ```
hooks.custom(({ data, merge }) => {
            console.log({ data })
          return merge(data, { /* Some new configuration */ })
        })
```
where the data has two series, and an X-axis, but the yAxis is empty
```

```javascript
{data: {…}}
data:
series: Array(2)
0:
data: (7) [27, 112, 107, 78, 54, 64, 25]
name: "foo"
type: "bar"
__proto__: Object
1: {name: "bar", type: "bar", data: Array(7)}
length: 2
__proto__: Array(0)
xAxis: {data: Array(7)}
yAxis:
__proto__: Object
__proto__: Object
__proto__: Object
```

The data returned from the call has both labels and values, so I am unsure of why the yAxis is empty, and theorize that this could be the cause of the infinite loading.

```html
<div id="chart" style="height: 300px;"></div>
```

```html
 <script src="https://unpkg.com/echarts/dist/echarts.min.js"></script>
    <script src="https://unpkg.com/@chartisan/echarts/dist/chartisan_echarts.js"></script>

    <script>
    const hook = new ChartisanHooks()
          .legend({ bottom: 0 })
          .tooltip()
          .datasets([
            {
              type: 'line',
              smooth: true,
              lineStyle: { width: 3 },
              symbolSize: 8,
              animationEasing: 'cubicInOut',
            },
        ])

        new Chartisan({
            el: '#chart',
            url: "@chart('foo_chart')?timeframe={{ $timeframe }}",
            hooks: hook,
        });
    </script>
```

**Comment by JapSeyz** [comment]
(Disabling Vue from loading, gives me an actual error, CANNOT CONVERT UNDEFINED OR NULL TO OBJECT, which is most likely just my test-hook.)

But even though this is not run through Vue. Vue doesn't even have a single component on the page, just binding Vue to the #app container, seems to mess up Chartisan

**Comment by JapSeyz** [comment]
Sure enough, disabling Vue from loading entirely, fixes the issue.

Somehow, binding Vue to #app and doing nothing else, is enough to cause Chartisan to load indefinitely

**Comment by ConsoleTVs** [comment]
Chartisan will release a new Vue 3 adapter when it's on stable release...

What you should NEVER attempt is to use a JS library that manipulates the DOM inside a Vue component. 

In fact, chartisan provides an API to load charts on demand. You just need to run that new Chartisan stuff on the mounted() or created() method (don't really know witch atm) and use a vue `ref` as the `el` parameter on the Chartisan constructor.

I understand this is beyond common understanding...

Related: https://github.com/ConsoleTVs/Charts/issues/579

Again, my answer will be to create an official Vue 3 adapter like I already did with Laravel and React.

**Comment by iMusicJJ** [comment]
It is not run in a vue component. Not a single vue component is loaded.

Vue is simply included globally and mounted, nothing else is done, no component is mounted or loaded, and the charts are loaded in global js via scripts tags in blade

**Comment by iMusicJJ** [comment]
But simply having vue mounted,even when charts is called in global js via script tags in blade, completely separate from vue, it is getting messed up

**Comment by iMusicJJ** [comment]
> I understand this is beyond common understanding

I'm sorry you take it as criticism or belive that I don't just want to help you figure out what is causing this infinite loading and instead resort to belittle me, without having read my comments and seeing that I never called anything from a, nor even loaded a single vue component.

Either way, the best of luck. I found the flaw and fixed it, and I don't want to contribute more time to this repo because of the toxic replies.

Best of luck

**Comment by ConsoleTVs** [comment]
lol. You are loading vue, and adding a chsrt inside that manipulstes the dom and just calling its api using plain js. Of course it will break. I just said that understanding vue refs and intehrating a dom library on vue its not something everybody knows. Nobody insulted you, but best of luck!
