### ISSUE TITLE
Class 'ConsoleTVs\Charts\Classes\Chartjs\Chart' not found in Laravel 7

### ISSUE THREAD

**Issue by akaleniuszka** [ConsoleTVs/Charts#607]
Hi everyone, I just updated my Laravel 6 app to Laravel 7, when I want to display a chart it gives me this error:
![image](https://user-images.githubusercontent.com/23175453/88302816-4b7f7a00-ccd4-11ea-94a3-dee75ed2cfe8.png)

my composer.json has:
![image](https://user-images.githubusercontent.com/23175453/88303110-9dc09b00-ccd4-11ea-86cf-cf9dcfc03293.png)

Can anyone help please, Thanx!

**Comment by royallife88** [comment]
Hi, 
v7 requires php version 7.4. it looks you have 7.2.5

**Comment by ConsoleTVs** [comment]
Read the docs. https://charts.erik.cat

There's 0 mention of "ConsoleTVs\Charts\Classes\Chartjs\Chart" anywhere.
