### ISSUE TITLE
 highcharts-yaxis-title

### ISSUE THREAD

**Issue by muralidharan143** [ConsoleTVs/Charts#61]
Please tellme how can i change  highcharts-yaxis-title

**Comment by ConsoleTVs** [comment]
->setElementLabel("Text");

**Comment by RMK147** [comment]
Hello, I have the same question, for a bar chart, ->setElementLabel('Text'); sets the X-axis title, while the Y-axis is set as "Values" by default. Is there any way to change this? Thanks!

**Comment by ConsoleTVs** [comment]
X axis is set usigng the ->setLabels, and the yAxis is set using setElementLabel. Could you give me a screenshot of your issue? thanks

**Comment by RMK147** [comment]
How would I change the Y-axis label which defaults to "values" currently?

![chart](https://cloud.githubusercontent.com/assets/6298631/20246461/0fa77632-a9af-11e6-8961-137a9062ec07.PNG)

**Comment by ConsoleTVs** [comment]
Seems like an issue I think, but the "Referrer" Should be the element label, and it should be displayed in the vertical axis, will look into it.

As you might notice, Refferer is **not** the x axis, as it's color is blue, and blue is the height of the bar, that means it's the Y axis. So the Refferer text should be ommited and it should be "Views" or somerthing, that will be added in the Y axis, Again, thanks for the report, will look into it this week before 3.0 release.

**Comment by ConsoleTVs** [comment]
It was only the bar chart from highcharts, fixed!

**Comment by minedun6** [comment]
Hey, Erik problem still persisting when using the 
```
Charts::multi 
```
it still outputs 'Values' even with me adding the elementLabel.
```
            $chart = Charts::multi('bar', 'highcharts')
            ->elementLabel('My nice label')
            ->title('Income in ' . config('app.currency'))
            ->labels($data[0])
            ->dataset($currentMonth->format('m') . ' - ' . $currentMonth->year, $data[1])
            ->dataset($lastMonth->format('m') . ' - ' . $lastMonth->year, $secondData[1])
            ->responsive(true);

```

**Comment by mansouralex** [comment]
@ConsoleTVs Thanks for this great package. I noticed that the highcharts-yaxis-title is not changed in case of Multi Line chart. I have tried ->elementLabel('My nice label') but the "values" still as the "highcharts-yaxis-title".

**Comment by ConsoleTVs** [comment]
Will look into it

**Comment by ConsoleTVs** [comment]
Should be fixed in here:

https://github.com/ConsoleTVs/Charts/releases/tag/4.5.1

**Comment by mansouralex** [comment]
@ConsoleTVs Great, thanks.

**Comment by ConsoleTVs** [comment]
You're welcome!
