### ISSUE TITLE
Turbolinks - Chartisan is not defined

### ISSUE THREAD

**Issue by DominikGeimer** [ConsoleTVs/Charts#610]
Hello,

I have a Laravel 7 app and Chartisan works without any problem if I hit the page directly or refresh the page. But when I visit the page via a turbolink, the chart does not get rendered.

This is the script tag with my chart.

```
const chart = new Chartisan({
            el: '#chart',
            url: "@chart('analytics_chart')",
            loader: {
            color: '#1c64f2',
            size: [50, 50],
            type: 'bar',
            textColor: '#4b5563',
            text: 'Loading...',
        },
            hooks: new ChartisanHooks()
                .colors(['#1c64f2'])
                .datasets([{ type: 'line', fill: false }])
                .minimalist()
        });
```

And this is the error from Google Chrome console:

```
Uncaught ReferenceError: Chartisan is not defined
    at <anonymous>:2:23
    at o.assignNewBody (turbolinks.js?33cb:5)
    at o.replaceBody (turbolinks.js?33cb:5)
    at eval (turbolinks.js?33cb:5)
    at o.e.renderView (turbolinks.js?33cb:5)
    at o.render (turbolinks.js?33cb:5)
    at Function.e.render (turbolinks.js?33cb:5)
    at t.renderSnapshot (turbolinks.js?33cb:5)
    at t.render (turbolinks.js?33cb:5)
    at r.render (turbolinks.js?33cb:6)
```

Can anyone help?

**Comment by ConsoleTVs** [comment]
I suppose you readed the turbolinks docs on how to handle JS scripts:

- https://github.com/turbolinks/turbolinks#working-with-script-elements
- https://github.com/turbolinks/turbolinks#reloading-when-assets-change
- https://github.com/turbolinks/turbolinks#installing-javascript-behavior

**Comment by DominikGeimer** [comment]
Oh, thanks for the hint! I fixed my problem in the fast way and disabled turbolinks for the specific link.

**Comment by ConsoleTVs** [comment]
I mean those kind of issues are non-related to this lib how rather how turbolinks in this case handles javascript logic to perform the transitions. Other people for instance complained about similar issues when they use this lib with Vuejs. Vue also requires anything inside the element it's controlling (normally #app) that manipulated the dom (like this lib) to be initialized in the mounted() method. People often forget and come complaining here. I'm sure you could still take a look at the turbolinks and fix this issue the good way while still having the turbolinks experience :)

**Comment by DominikGeimer** [comment]
You are right; that was not an issue of this lib. I just couldn't find a solution by myself. You gave me a right hint! Thanks so much for your help and this great lib! You are doing great!

**Comment by ConsoleTVs** [comment]
Good to hear! If you find any other issues related to front-end, please post them here instead: https://github.com/Chartisan/Chartisan

This repo is only a thin wrapper around chartisan's php package. You're lucky I'm the author of both things :D
