### ISSUE TITLE
PHP 7.3 support 

### ISSUE THREAD

**Issue by trollfalgar** [ConsoleTVs/Charts#614]
Version 7.0.5 requires PHP 7.4 or higher.
Would be possible support at least PHP 7.3 ?

`"require": {
        "php": ">=7.4",
}`

Thanks!

**Comment by aliene-ctrl** [comment]
I'd also like to know the reasons for jumping from 7.0 to 7.4?

**Comment by SamuelNitsche** [comment]
> I can't see anything in this commit [9603702](https://github.com/ConsoleTVs/Charts/commit/960370227cdd16ec30c7185a767ea017c837e535) that would require a minimum PHP version of 7.4

Version 7 uses typed properties for example. (https://github.com/ConsoleTVs/Charts/blob/master/src/Registrar.php#L20).

These are available in 7.4 only.

**Comment by ConsoleTVs** [comment]
You want me to support a PHP version that will not get any active support after 3 months from now? That's a no...

Is it that hard to update? I am also using tons of features from 7.4, there's no reason to stay behind at that point. 

https://www.php.net/supported-versions.php

**Comment by ConsoleTVs** [comment]
Laravel will probably keep like thst till php 8 (not far to come). I will also change all my libs to php 8 once it comes out. There are too many features I use from them. Php 7.4 is a must now, i really dislike coding without types, and its the only release to support typed properties. It's the only reason why i came back to php. Nevertheless, this is also a dependency from chartisan, not this wrapper only. Expect to have similar changes when 8.0 comes in with union types.

https://twitter.com/GrahamJCampbell/status/1297849655712190469?s=19

**Comment by Barmunksu** [comment]
>  It's the only reason why i came back to php
in the world of TypeScript have not heard of lts and enterprise development?

**Comment by ConsoleTVs** [comment]
Have you heard of open source? It's my free time, my own project and if I don't feel confortable coding without decent amount of types, like php 7.3 have, I won't. This is MIT licenced. You are free to clone this repo, remove the type anotations and strict types and downgrade php version.
