### ISSUE TITLE
docs for charts v6

### ISSUE THREAD

**Issue by Barmunksu** [ConsoleTVs/Charts#615]
Hello! Where are can find docs for Charts v6?

**Comment by EmilioBravo** [comment]
I need this too!

**Comment by tabacitu** [comment]
Just needed them myself, and I found https://github.com/ConsoleTVs/Charts/issues/589#issuecomment-653821781 where the author says to use this link for the v6 docs: https://github.com/ConsoleTVs/ChartsDocs/tree/fd537ee2a3f2652925b106274ff7031bef0c9585/docs

**Comment by tabacitu** [comment]
Update: @ConsoleTVs confirmed that we're getting the v6 docs back, as they were before!

@ConsoleTVs please let me know when that's done, I'll sprinkle the links to the docs in a few places:
- [ ] in the README.md file on the `master` branch (as a notice to go the the `v6` branch for the old version)
- [ ] in the README.md file on [the `v6` branch](https://github.com/ConsoleTVs/Charts/tree/v6)

**Comment by ConsoleTVs** [comment]
@tabacitu Here you go everybody: http://v6.charts.erik.cat/

**Comment by tabacitu** [comment]
Awesome, thanks a lot @ConsoleTVs ! 

I've just submitted https://github.com/ConsoleTVs/Charts/pull/620 which will also mention v6 docs and branch on the main (v7) readme. This should provide a clear way for v6 users to keep using v6, while still nudging them to upgrade to v7.

So I think we can close this.
