### ISSUE TITLE
Highchart's Donut / Pie Chart

### ISSUE THREAD

**Issue by geekspeek** [ConsoleTVs/Charts#62]
Highcharts donut chart includes a pie in the center of it. I looked through the code but can't find where this is potentially supported. Is there a plan to support this?

**Comment by ConsoleTVs** [comment]
"Highcharts donut chart includes a pie in the center of it"

may you give us a sample of this? a demo page or something?

**Comment by geekspeek** [comment]
Sorry about that, see link below. Might be Highcharts specific, I forked dev-master to write it in  but found that the current dev-master will only work with Laravel 5.3.

I am working on a fix for version 2.0.2 to work with Highcharts donut supporting their features.

[http://www.highcharts.com/demo/pie-donut](url)
[http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/pie-donut/](url)

**Comment by ConsoleTVs** [comment]
After analizing the chrat:

I think it will be too hard to code it with the standards we have right now. Remember that we are not subject to a chart library, instead, the code must be reusable for other libraries and as far as I've seen few to none of the other libraries support that kind of chart. I like the idea, so if in a future we need innovations I'll br happy to implement it. If you need to code something and will like to pull request us, its ok! 

You said the 3.0 only works with laravel 5.3?? I'll need to look into it.

**Comment by geekspeek** [comment]
This is a chart we use I figure my fork will be for us only. I will start a separate bug for the 5.1 incompatibility. So far I have tracked down to one call to resource_path() which is only implemented in 5.3.
