### ISSUE TITLE
Failed to load ServiceProvider

### ISSUE THREAD

**Issue by jskramer909** [ConsoleTVs/Charts#623]
Hello

This one is throw when the ServiceProvider is tried to be loaded.

```
/**
     * Register any application services.
     */
    public function register(): void
    {
        // Merge the configuration files.
        $this->mergeConfigFrom(__DIR__.'/Config/charts.php', 'charts');
        // Register the Chart Registerer singleton class to avoid resolving it
        // multiple times in the application.
    $this->app->singleton(Registrar::class, fn (Application $app) => new Registrar(
            $app,
            $app->make(Repository::class),
            $app->make(RouteRegistrar::class)
        ));
    }
```

syntax error, unexpected '$app' (T_VARIABLE), expecting ')'

Any chance to get around that?

Using following versions of Laravel and Charts:
"require": {
        "php": "^7.2.5", => actual version used 7.4.10
        "consoletvs/charts": "7.*", => resolving in 7.1.0
        "laravel/framework": "^7.0", => resolving in 7.28.3
    },

**Comment by ConsoleTVs** [comment]
I doubt you are using php 7.4. check the cli and server versions of php, and bumo to 7.4 min. Also, what line does it fail?

**Comment by jskramer909** [comment]
$this->app->singleton(Registrar::class, fn (Application $app) => new Registrar(

This one is failing when it tries to resolve the fn (Application $app) part.

Just doublechecked. Nginx is using the php7.4-fpm and cli is also at 7.4

**Comment by ferryfernandez** [comment]
I solve this issue with change to php7.4-fpm at Nginx server block then restart Nginx and working

**Comment by mdrashedulislam11** [comment]
Also I facing similar problem on

Laravel version : 8.* 
Charts:  7.*
My PHP  version: 7.4

**Comment by ConsoleTVs** [comment]
Guys, there is 2 PHP versions that need to be at 7.4.

The PHP CLI (used to install dependencies using composer or run php artisan) and PHP itself (used by nginx).

You need BOTH at 7.4.

The error you guys are facing is because whatever php version is parsing the laravel app is lower than 7.4 as is unable to understand short closures like:

```php
fn (Application $app) => new Registrar(...)
```
