### ISSUE TITLE
"Loading Chart" just spins

### ISSUE THREAD

**Issue by godsgood33** [ConsoleTVs/Charts#627]
I followed the guide on the site, but I can't get the chart to render at all.  The Loading Charts animation just repeats.  I'm using the latest version of Laravel (8.9.0).  The data is retrieved from the chart, but nothing happens.  There is no console output or error messages.  Any help would be appreciated.  This could be an issue with Chartisan and not this.

![image](https://user-images.githubusercontent.com/1922710/96146624-801a6080-0ed4-11eb-8405-974f1e59338c.png)

**Comment by Yismen** [comment]
> I followed the guide on the site, but I can't get the chart to render at all. The Loading Charts animation just repeats. I'm using the latest version of Laravel (8.9.0). The data is retrieved from the chart, but nothing happens. There is no console output or error messages. Any help would be appreciated. This could be an issue with Chartisan and not this.
> 
> ![image](https://user-images.githubusercontent.com/1922710/96146624-801a6080-0ed4-11eb-8405-974f1e59338c.png)

Facing same issue. Any help?

**Comment by godsgood33** [comment]
> Facing same issue. Any help?

No, still nothing

**Comment by godsgood33** [comment]
I did a little bit of troubleshooting with this and figured out if I copy the exact HTML code from the Render Charts page in the guide, it will render correctly.  So my guess, this means that it is not working with blade, or there is some sort of library conflict with the JS libraries.  I tried putting the JS code in the footer so that it would load after the chart element and then execute like it should, but that didn't work.  Any idea why it won't work in blade?

**Comment by godsgood33** [comment]
Upon further investigation, if I comment out the block to link the app.js asset it will work.  With that available, it just does the loading screen.  I have add almost NOTHING to my JS, so I don't know why this is behaving this way.

Ok, tried one last thing...I removed the "defer" attribute from `<script src="{{ asset('js/app.js') }}"></script>` and that works!  Why would that work?

**Comment by ConsoleTVs** [comment]
What else are you using in your js logic? Is the code public / can you pate the js source?

**Comment by godsgood33** [comment]
> What else are you using in your js logic? Is the code public / can you pate the js source?

I am not using anything but the base Laravel 8.9 code.  So I guess I should clarify, that I have not added anything  to the JS.  I thought I had, but I double-checked and there's nothing extra there.  This is the require in the composer file.

```
"php": "^7.3",
"consoletvs/charts": "^7.1",
"fideloper/proxy": "^4.2",
"fruitcake/laravel-cors": "^2.0",
"godsgood33/csv-reader": "v0.2",
"guzzlehttp/guzzle": "^7.0.1",
"laravel/framework": "^8.0",
"laravel/tinker": "^2.0",
"laravel/ui": "^3.0",
"laraveldaily/laravel-charts": "^0.1.25"
```

**Comment by ConsoleTVs** [comment]
I'm more interested in the JS stuff. The PHP stuff works as intended (this package). What's failing is Chartisan's JS adapter.

Will need to know what adapter are you using and what other libs are included in the bundle.

Can you paste the package.json and the minimal JS code you used to create the chart?

**Comment by godsgood33** [comment]
This is what is currently in the package.json.  I used the code example from your site to create the chart. When that wasn't initially working, I tried the code example from Chartisan's site, but that didn't work either.  I tried yours again and that's when I started troubleshooting and discovered the "defer" issue.

```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --disable-host-check --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "axios": "^0.19",
        "bootstrap": "^4.0.0",
        "cross-env": "^7.0",
        "jquery": "^3.2",
        "laravel-mix": "^5.0.1",
        "lodash": "^4.17.19",
        "popper.js": "^1.12",
        "resolve-url-loader": "^2.3.1",
        "sass": "^1.20.1",
        "sass-loader": "^8.0.0",
        "vue": "^2.5.17",
        "vue-template-compiler": "^2.6.10"
    }
}
```

**Comment by ConsoleTVs** [comment]
Can you also paste the minimal JS code used to initialize the chart?

**Comment by godsgood33** [comment]
I'm using the CDN.  You can see in the screenshot of the initial post that `chartisan_echarts.js` is loading.

Here's the JS initialization code, and this now works since I removed the "defer" attribute.

```
const chart = new Chartisan({
        el: '#chart',
        url: "@chart('sample_chart')",
        hooks: new ChartisanHooks()
            .legend({position: 'bottom'})
            .colors()
            .tooltip()
      });
```

**Comment by ConsoleTVs** [comment]
Are you using Vue / React / Any other JS framework?

**Comment by Yismen** [comment]
> Are you using Vue / React / Any other JS framework?

VueJS. Just the laravel/ui default scaffold.

**Comment by godsgood33** [comment]
> Are you using Vue / React / Any other JS framework?

Vue...default scaffold.

**Comment by godsgood33** [comment]
> > Are you using Vue / React / Any other JS framework?
> 
> VueJS. Just the laravel/ui default scaffold.

@Yismen curious if you tried removing the "defer" attribute like I did to see if it worked?

**Comment by ConsoleTVs** [comment]
If you guys are using vue you can't initialize the Chartisan whenever you want, you must initialize it in the created() method. Nevertheless, I need more details on what's going on here guys, I can't just magically debug when I have no code in here.

What I need:

- Full page (layout + page) of the page containing the chart.
- Vue initialization code of the script.

**Comment by ConsoleTVs** [comment]
Just as a try in here, if you're not using "vue" and it's just there because of the initial laravel installation, try removing the vue initialization from the JS or remove the id` of the `<div id="app">`

**Comment by godsgood33** [comment]
> If you guys are using vue you can't initialize the Chartisan whenever you want, you must initialize it in the created() method. Nevertheless, I need more details on what's going on here guys, I can't just magically debug when I have no code in here.
> 
> What I need:
> 
> * Full page (layout + page) of the page containing the chart.
> * Vue initialization code of the script.

Ok...I have to say this is a complete BS response!  Why didn't you code that into your example?  You can safely presume that people will be using the default scaffold (if they aren't they already know).  You also didn't code it using blade.  Which somebody just getting into Laravel is most likely using.  I did a search the other night trying to find a similar method to jQuery's `$(function(){});`, and I did see the created method, but I couldn't understand how it worked.  If you are coding a sample for somebody using the default installations, it should be coded to work as displayed.  If you know people are probably going to be using blade, then you should code an example that includes blade.  The examples on your site say nothing initializing inside a created method.  This is my first attempt at using Laravel so consequently, my first go around with Vue. 

I will do my best to provide what you've requested, but I don't understand what you mean by "Vue initialization code of the script".  I don't have any Vue/JS code outside of what is provide by the default install.  We aren't asking you to "magically debug", we're asking you to create an example that will work with a default installation

**Comment by ConsoleTVs** [comment]
Let me be clear. You can't use any javascript library that manipulates the dom inside vue's app without manipulating the dom when vue is ready for it.

Example:

https://codesandbox.io/s/adoring-roentgen-41hfw?file=/index.html

Anything inside the division with`id="app"` must be controlled by vue. You CAN'T just use a DOM manipulation library (charting, modals, anything that manipulates the dom) without waiting for vue mounting events.

In that particular case, if you read the vue docs, you need to wait for the `mounted` event.

The issue is not about blade, but about vue.

And the default initialization code is here: https://github.com/laravel/ui/blob/ff6af4f0bc5a5bfe73352cdc03dbfffc4ace92d8/src/Presets/vue-stubs/app.js#L30

I suggest you should look how the things you use work before calling bullshit response to people helping you.

**Comment by Yismen** [comment]
> Let me be clear. You can't use any javascript library that manipulates the dom inside vue's app without manipulating the dom when vue is ready for it.
> 
> Example:
> 
> https://codesandbox.io/s/adoring-roentgen-41hfw?file=/index.html
> 
> Anything inside the division with`id="app"` must be controlled by vue. You CAN'T just use a DOM manipulation library (charting, modals, anything that manipulates the dom) without waiting for vue mounting events.
> 
> In that particular case, if you read the vue docs, you need to wait for the `mounted` event.
> 
> The issue is not about blade, but about vue.
> 
> And the default initialization code is here: https://github.com/laravel/ui/blob/ff6af4f0bc5a5bfe73352cdc03dbfffc4ace92d8/src/Presets/vue-stubs/app.js#L30
> 
> I suggest you should look how the things you use work before calling bullshit response to people helping you.

No need of the harsh responses. You are doing a great job by making this tool available and as both a developer and a packages user all I have is appreciation for the hard work. Version 6 works like a charm so I've sticked to that version untill the documentation is improved or it becomes more comprehensible of how should consumers expect this to work. 

Once again thanks for the had work and keep it up.

**Comment by ConsoleTVs** [comment]
Yes, I'm thinking to completly remove Chartisan. I mean, people are just unable to understand the power of it and prefer to get a simple set of options available.
