### ISSUE TITLE
Dual Y Axis - Feature possibility?

### ISSUE THREAD

**Issue by natelloyd** [ConsoleTVs/Charts#63]
Huge kudos for your work! 

I know I've written google charts manually with dual y axis - for example sales count and sales value on the same chart. Is this something you see as a possible future feature?

**Comment by ConsoleTVs** [comment]
I think you're reffering to the "multi dataset charts" https://github.com/ConsoleTVs/Charts#multi-datasets-charts

This charts allows you to add multiple data in the same chart, as far as your example goes; the sales value and the sales count, in a line chart for example.

**Comment by natelloyd** [comment]
I'm referring to having 2 y scales:
https://developers.google.com/chart/interactive/docs/gallery/linechart#dual-y-charts

Having multiple datasets on the same Y axis was quite straight forward from your examples.

**Comment by ConsoleTVs** [comment]
Oh sorry for my missunderstanding, we currently only support multi datasets with the same Y axis, you'll still be able to display correct data with the multi dataset, but they will use the same Y axis, I currently find it too dificult to implement this on all the libraries we support. If you have time some day or maybe I do, we can work on it :)

I'll keep this issue opened as a feature request!

Thanks!

**Comment by ConsoleTVs** [comment]
After studing the situation A lot of libraries won't support this, so I'm afraid we can't go further!
