### ISSUE TITLE
Charts Incompatible with PHP version (7.3.20)

### ISSUE THREAD

**Issue by mdrashedulislam11** [ConsoleTVs/Charts#630]
[Laravel 8](https://laravel.com/docs/8.x) require PHP version 7.3 for Installation. 

Can you please fix the issue.  we can't downgrade PHP version. 

`[InvalidArgumentException]
  Package consoletvs/charts at version 7.1.0 has a PHP requirement incompatible with your PHP version (7.3.20)  `

**Comment by ConsoleTVs** [comment]
You don't need to downgrade, you need to upgrade. This package requires PHP 7.4+. PHP 7.3 will end active support in 1 month.

**Comment by mdrashedulislam11** [comment]
ohh sorry, that was my bad. it should be can't upgrade 7.4. 

However, I change my mind and update to 7.4.

I facing similar problem on that is  failed to load Service Provider. #623 
Laravel version : 8.*
Charts: 7.*
PHP version: 7.4
