### ISSUE TITLE
Routes not being generated

### ISSUE THREAD

**Issue by WoodyNaDobhar** [ConsoleTVs/Charts#631]
I've followed the instructions to the letter, and the route for the chart is not being added.  I don't see it in the routes list, and it's not navigable.

The build is on Laravel 7.29.2, Charts v7.1

I'm noticing some other Route issues in the list, but this seems to be a different issue, tho maybe related?

**Comment by WoodyNaDobhar** [comment]
To clarify, running php artisan route:cache generates no errors, but no chart routes either.

**Comment by WoodyNaDobhar** [comment]
The problem seems to have mysteriously changed to the 'setState' issue.

**Comment by Alph44rchitect** [comment]
I'm getting the same error!

Without running `artisan:optimize` the route and everything else is running without problems.
But when I run `artisan:optimize` for production, the Plugin breaks everything throwing:

`Call to undefined method App\Charts\SampleChart::__set_state()`
inside
`bootstrap\cache\routes-v7.php`

Using laravel/framework v.8.13.0 and consoletvs/charts v.7.1.0

**Comment by ConsoleTVs** [comment]
I'll test this, there's a few related issues. Thank you.

**Comment by woodspire** [comment]
https://github.com/ConsoleTVs/Charts/pull/636
