### ISSUE TITLE
Stacked Bar Chart?

### ISSUE THREAD

**Issue by WS243593** [ConsoleTVs/Charts#634]
Is a stacked bar chart available, or is it something that's coming in the future?

**Comment by ConsoleTVs** [comment]
It is available by configuring it on the frontend adapter. This means you have to create a custom hook (or ude the options() from the hooks) to tell the adapter to use a stacked version. The options to pass to it depend on the chosen lib (echarts, chartjs, etc)

**Comment by WS243593** [comment]
Got it, thank you!
