### ISSUE TITLE
3.0 (dev-master) Incompatible with Laravel 5.1 and 5.2

### ISSUE THREAD

**Issue by geekspeek** [ConsoleTVs/Charts#64]
When attempting to copy configs and resources an Exception is through about the resources_path() function that appears to only be in 5.3. 

`consoletvs/charts/src/ChartsServiceProvider.php
Line: 27`

**Comment by geekspeek** [comment]
This was a pretty quick fix so it would be good to double check that it works. I did notice a couple calls to ->_toString() on items that are already strings that might cause breakage.

**Comment by ConsoleTVs** [comment]
I'm expecting an answer soon from the pull request, closing this!
