### ISSUE TITLE
Package doesnt have color options 

### ISSUE THREAD

**Issue by CodeNinjaUG** [ConsoleTVs/Charts#641]
please look at 6.*

**Comment by ConsoleTVs** [comment]
User haven't read documentation, hug?

https://chartisan.dev/documentation/frontend/hooks#Pre-built-hooks

**Comment by CodeNinjaUG** [comment]
$chart = new SampleChart;
        $chart->labels(['Tasks Completed', 'Tasks Pending']);
        $chart->colors(['#FF5733','#900C3F']);
        $chart->dataset('My dataset', 'pie', [$graph_complete, $graph_pending]);
        $tas_complete=Task::all()->where('completed','=','1');
        $tas_pending=Task::all()->where('completed','=','0');


well if i use it here i get an error Call to undefined method App\Charts\SampleChart::colors()

**Comment by ConsoleTVs** [comment]
![image](https://user-images.githubusercontent.com/6124435/104119826-abc1b100-5332-11eb-9fbb-309f77cb4799.png)

You need need to realize this is... front-end (javascript), right?

Let me give you the exact words on the getting started (FIRST PAGE) of the documentation:

> Chartisan is a language agnostic library that aims to make charts accessible and easy to use on the web and mobile. It provides the necessary building block to manage the chart appearance in the front-end while being able to manage the data in the back-end.

So, why are you using the back-end (PHP) to manage your chart appearance?
