### ISSUE TITLE
Customization and API is wrong

### ISSUE THREAD

**Issue by StrangerGithuber** [ConsoleTVs/Charts#659]
Hello
I don't know if this is updated or not yet. The https://charts.erik.cat/guide/chart_customization.html says if we want to make customization then we need to follow the https://chartisan.dev/ documentation. 
I am there and I have problems with hooks as if some of them don't exists. I checked here: https://chartisan.dev/documentation/frontend/hooks#Pre-built-hooks and I can't use these:

responsive
beginAtZero

I didn't try others yet. 
My problem is that the bottom numbers are not under the right line and missing some numbers.
![image](https://user-images.githubusercontent.com/1939827/110651761-086b0c00-81bc-11eb-98c4-cfba0f37a114.png)

**Comment by ConsoleTVs** [comment]
I'm going to quote the first line of the "pre-built hooks" section:

> Please make sure you selected the library you want to use on the preferences menu.

You are using echarts, and have selected chart.js. Of course it is not going to work.

**Comment by calvez** [comment]
this maybe helps

backend/app/Charts/SampleChart.php

`
namespace App\Charts;

use Chartisan\PHP\Chartisan;
use ConsoleTVs\Charts\BaseChart;
use Illuminate\Http\Request;

class SampleChart extends BaseChart
{
    /**
     * Handles the HTTP request for the given chart.
     * It must always return an instance of Chartisan
     * and never a string or an array.
     */
    public function handler(Request $request): Chartisan
    {
        return Chartisan::build()
            ->labels(['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'])
            ->dataset('Profits', [100, 145, 158, 175, 155, 228, 289, 351, 405, 478])
            ->dataset('Referrals', [1, 5, 8, 15, 16, 19, 25, 26, 29, 35]);
    }
}
`
frontend:

`
        @section('footer-scripts')
        
        <script>
            const chart = new Chartisan({
        el: '#chart',
        url: "@chart('sample_chart')",
        loader: {
            color: '#ff00ff',
            size: [30, 30],
            type: 'bar',
            textColor: '#ffff00',
            text: 'Loading chart data...',
        },
        hooks: new ChartisanHooks()
            .colors()
            .datasets([{ backgroundColor: '#7e3af2', borderWidth: 1, type: 'bar', fill: false }, 'bar']),
        });
        </script>
        @endsection
`
result:
[https://i.snipboard.io/IaVJp9.jpg](url)
