### ISSUE TITLE
Live Chart 

### ISSUE THREAD

**Issue by JoaoMoraisG** [ConsoleTVs/Charts#665]
I was able to do the smooth implementation of the library in laravel, but I would like to know if there is something about the live graphs that can be found on the homepage of the site https://chartisan.dev/, I tried to do something similar using the chart.update (), but it ends up updating the entire graph, not giving the same effect as the examples on the site, I would be very grateful if you had any example to dedicate myself to. I am using Chart.js

![imagem_2021-04-22_174823](https://user-images.githubusercontent.com/80110957/115783190-eeb00d80-a392-11eb-9105-19fe1657e29b.png)

**Comment by ConsoleTVs** [comment]
https://chartisan.dev/documentation/frontend/updating#Background-update

That's literally explained here! That's a background update!
