### ISSUE TITLE
Geocharts - setRegion option

### ISSUE THREAD

**Issue by tnaffh** [ConsoleTVs/Charts#68]
How can I set the region view for google geocharts?
Like if I want to show a certain country.

> region	
The area to display on the geochart. (Surrounding areas will be displayed as well.) Can be one of the following:

```
'world' - A geochart of the entire world.
A continent or a sub-continent, specified by its 3-digit code, e.g., '011' for Western Africa.
A country, specified by its ISO 3166-1 alpha-2 code, e.g., 'AU' for Australia.
A state in the United States, specified by its ISO 3166-2:US code, e.g., 'US-AL' for Alabama. Note that the resolution option must be set to either 'provinces' or 'metros'.
Type: string
Default: 'world'
```
[Reference](https://developers.google.com/chart/interactive/docs/gallery/geochart#configuration-options)

**Comment by ConsoleTVs** [comment]
Will look into it

**Comment by ConsoleTVs** [comment]
Done in 3.0 with ```->region("REGION_HERE")```
