### ISSUE TITLE
Cannot find "/dist/chartisan_echarts.js" in @chartisan/echarts@4.0.0-beta.2

### ISSUE THREAD

**Issue by travislykes44** [ConsoleTVs/Charts#687]
Charts are not rendering because the path for file
    <script src="https://unpkg.com/@chartisan/echarts/dist/chartisan_echarts.js"></script>
returns a 404, please check it out

**Comment by ConsoleTVs** [comment]
SHould be fixed now, but your browser or unpkg will likely have cached that, so please use:

`https://unpkg.com/@chartisan/echarts@%5E2.1.0/dist/chartisan_echarts.js` instead.

This issue was due the new upcoming version of chartisan being released in beta.

**Comment by travislykes44** [comment]
Thanks!
