### ISSUE TITLE
Don't load jquery as global asset

### ISSUE THREAD

**Issue by hafezdivandari** [ConsoleTVs/Charts#69]
I already load jquery 2.2.4 on my page in `<body>` and don't want `Charts::assets()` to load it again.
I think there should be an optional argument to not include global assets like `Charts::assets(['google'], false)`

**Comment by BlueTeck** [comment]
see #59 and #47

**Comment by hafezdivandari** [comment]
@BlueTeck I checked #59 and #47, But it doesn't solve my problem. The problem is that I use `Charts::assets(['google'])` but it includes jquery-3.0.0 too!

**Comment by ConsoleTVs** [comment]
It should not, I'm currently creating a 3.0 version right now, as I'm currently checking for lots of stuff, will take a look

**Comment by ConsoleTVs** [comment]
The new version; 3.0 already does what it have to do, did not modify anything:

https://i.gyazo.com/1daaddbc69c07aac6cee0254c52b3643.png

https://gyazo.com/3ba3342de34e0c73a38e8331925e17e2
