### ISSUE TITLE
Class 'ConsoleTVs\Charts\Charts' not found

### ISSUE THREAD

**Issue by nbalawi** [ConsoleTVs/Charts#75]
Please note that I'm using rappasoft updated boilerplate Laravel 5.3 and I'm using your installation steps but it keeps giving me this error message

FatalThrowableError in DashboardController.php line 21: Class 'ConsoleTVs\Charts\Charts' not found

```
<?php

namespace App\Http\Controllers\Frontend\User;

use App\Http\Controllers\Controller;
use ConsoleTVs\Charts\Charts;

/**
 * Class DashboardController
 * @package App\Http\Controllers\Frontend
 */
```

**Comment by ConsoleTVs** [comment]
https://github.com/ConsoleTVs/Charts/issues/13

**Comment by ConsoleTVs** [comment]
If it does not solve the issue, please tell me what version are you using, remember 3.0 is totally diferent and it's docs are not out yet, it's in pre-release

**Comment by bart** [comment]
use ```ConsoleTVs\Charts\Facades\Charts``` instead

**Comment by minedun6** [comment]
Using boilerplate package you might need to   
php artisan config:cache

**Comment by ConsoleTVs** [comment]
Thanks @minedun6

**Comment by nbalawi** [comment]
Thank you guys, I'll give a try and let you know.

@ConsoleTVs can you tell what do you mean by refresh config - I'm a newbie if you can see - 

@bart I've tried using `ConsoleTVs\Charts\Facades\Charts`but id didn't like it as well. 

@minedun6 I'll give it a try.

**Comment by minedun6** [comment]
@nbalawi what @ConsoleTVs asked you to do is the same as my idea, I think.
Basically Laravel reads from config files, cached config file to be precise, but sometimes, it's not reloaded automatically after you add a dependency so you need to rebuild that cache file by runing this:                                `php artisan confi:cache`
it will clear the cache config file and rebuild it using the new conifg (when you have installed new packages). I encountered this problem with Laravel boilerplate.

**Comment by nbalawi** [comment]
@minedun6 thanks mate...I've tried `config:clear`rather than `config:cache` when i was troubleshooting the issue earlier. I'll give it a try this afternoon and will post the result.

**Comment by nbalawi** [comment]
So when I use the face as per below

`<?php

namespace App\Http\Controllers\Frontend\User;

use App\Http\Controllers\Controller;
use ConsoleTVs\Charts\Facades\Charts;

/**
 * Class DashboardController
 * @package App\Http\Controllers\Frontend
 */
class DashboardController extends Controller
{

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $chart = Charts::create('line', 'highcharts')
            ->setView('custom.line.chart.view') // Use this if you want to use your own template
            ->setTitle('My nice chart')
            ->setLabels(['First', 'Second', 'Third'])
            ->setValues([5,10,20])
            ->setDimensions(1000,500)
            ->setResponsive(false);

        return view('frontend.user.dashboard',['chart'=>$chart]);
    }
}`

I got the following error message

`Call to undefined method ConsoleTVs\Charts\Builder\Chart::setView()
`

When I do 
`use Charts;
`

ErrorException in AliasLoader.php line 66:
Class 'ConsoleTVs\Charts\Charts' not found

I've tried PHP artisan config:cache as well!

**Comment by minedun6** [comment]
Seems like its not autloading the class.

**Comment by nbalawi** [comment]
@minedun6 is there a way to force it to autoload it?

**Comment by minedun6** [comment]
Try composer dump autoload

**Comment by ConsoleTVs** [comment]
```
composer dump-autoload
```

**Comment by ConsoleTVs** [comment]
Im waiting for my hosting to fix pdo, once this is done 3.0 will be out and ready

**Comment by nbalawi** [comment]
Thank you guys...I did composer `dump-autoload` and still facing

FatalThrowableError in DashboardController.php line 22:
Call to undefined method ConsoleTVs\Charts\Builder\Chart::setTitle()

Do you think that namespaces with the boilerplate might've caused some issues?

**Comment by BlueTeck** [comment]
Try just title instead of setTitle.

**Comment by nbalawi** [comment]
Great pick @BlueTeck , I get rid of the class not found issue, but now I got a big red  mark with

Unknown chart library / type combination

**Comment by nbalawi** [comment]
OK I got rid of ->setView('custom.line.chart.view') // Use this if you want to use your own template and the error disappeared but I'm getting blank chat instead.

**Comment by ConsoleTVs** [comment]
Seems you have 3.0 installed, what chart and library are you trying to output? Pase the code here

**Comment by nbalawi** [comment]
I'm using the example!

```
        $chart = Charts::create('line', 'google')
            ->Title('My nice chart')
            ->Labels(['First', 'Second', 'Third'])
            ->Values([5,10,20])
            ->Dimensions(1000,500)
            ->Responsive(true);
```

**Comment by ConsoleTVs** [comment]
Try to lowercase the methods

**Comment by nbalawi** [comment]
I've done that, but no luck!

```
class DashboardController extends Controller
{

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $chart = Charts::create('area', 'google')
            ->title('My nice chart')
            ->labels(['First', 'Second', 'Third'])
            ->values([5,10,20])
            ->dimensions(1000,500)
            ->responsive(false);
        return view('frontend.user.dashboard',['chart'=>$chart]);
    }
}
```

**Comment by minedun6** [comment]
There are some problems with 3.0 ?

**Comment by nbalawi** [comment]
I might have to revert back to the older version!

**Comment by ConsoleTVs** [comment]
3.0 is not stable, but seems quite rare... I've manually checked them all...  May you try it @minedun6 ?

**Comment by BlueTeck** [comment]
I have no problems with 3.0. I've just changed the setter methods and and the facade. And you have to update your config file.

**Comment by ConsoleTVs** [comment]
Yeah... quite strange right?

**Comment by minedun6** [comment]
Fresh instal 5.3 of laravel and composer require consoletv/charts worked
like a charm

Le lun. 21 nov. 2016 12:25, Erik Campobadal <notifications@github.com> a
écrit :

**Comment by ConsoleTVs** [comment]
You should make sure the Charts::assets() are beeing printed in the page BEFORE the chart render

**Comment by nbalawi** [comment]
Hey Guys...I updated composer with the latest requirement, cleared the cache, and added the assets in the right place, and it is working right not :+1: thank you very much appreciate the help and support

**Comment by ConsoleTVs** [comment]
You're welcome @nbalawi

**Comment by RushabhShah04** [comment]
FatalThrowableError in Facade.php line 221:
Call to undefined method ConsoleTVs\Charts\Builder::new()

Is the Error when I write Code 



<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use ConsoleTVs\Charts\Facades\Charts;

class chartController extends Controller
{
    public function index()
    {
    	
    	$chart = Charts::new('line','highcharts')
    	->setTitle("Testing Charts")
    	->setLabels(["test1","test2","test3"])
    	->setValues([100,500,2500])
    	->setElementLabel("TEST RUSHABH");

    	return view('welcome',['chart' => $chart]);

    }
}


Please Solve

**Comment by ConsoleTVs** [comment]
Yes, please read the documentation, this methods do not even exist in the new version

https://erik.cat/projects/Charts/docs/4

they have been  renamed.

```
`Charts::create('line', 'highcharts')
    ->title('My nice chart')
    ->labels(['First', 'Second', 'Third'])
    ->values([5,10,20])
    ->dimensions(0,500);
```

**Comment by mjames21** [comment]
removing the set works for me

**Comment by ConsoleTVs** [comment]
The "new" method does not even exist, the propper one in the latest version is create

**Comment by WeMadeItMor** [comment]
Please can somebody help me i got the same bug ErrorException in AliasLoader.php line 79:
Class 'ConsoleTVs\Charts\Charts' not found
And i tried everything

**Comment by ConsoleTVs** [comment]
I answered it already ^^

**Comment by AhmedSdiri** [comment]
syntax error, unexpected 'new' (T_NEW)

 public function chart()
    {
         
         
      /* $lava = new \Khill\Lavacharts\Lavacharts;
         $data = $lava->DataTable();*/
        $chart = Charts::new('line', 'highcharts')
            ->setTitle('My nice chart')
            ->setLabels(['First', 'Second', 'Third'])
            ->setValues([5,10,20])
            ->setDimensions(1000,500)
            ->setResponsive(false);
        return view('chart', ['chart' => $chart]);
       
    }

I am using php 5.6.25
Laravel 5.3
I did : 
-composer require consoletvs/charts
-ConsoleTVs\Charts\ChartsServiceProvider::class,
-'Charts' => ConsoleTVs\Charts\Charts::class,
-php artisan vendor:publish --tag=charts_config
-php artisan vendor:publish --tag=charts_assets --force
-php artisan vendor:publish --force
 But i am always getting : syntax error, unexpected 'new' (T_NEW)

As a solutions, i have tried all those instruction but nothing works:
-use ConsoleTVs\Charts\Facades\Charts; instead
- cache clear 
-view clear

I will be very thanksful if anyone could help me, thank you in advance!

**Comment by ConsoleTVs** [comment]
Hello, please consider reading the docs, they are there for a reason. This class does not exists and so do the ->set methods. Check the docs examples?

**Comment by Ahsankalim** [comment]
sir i faced this problem . please help [me](url
![capture3](https://user-images.githubusercontent.com/39775818/40786007-7538e2fe-6503-11e8-88f8-fcfa22bb60ab.PNG)
)
Class 'ConsoleTVs\Charts\Facades\Charts' not found

**Comment by tpharaoh** [comment]
try composer dumpautoload

Laravel 5.6?
Your composer uptodate?

Search other help topics you will see this question asked and answered a
few times...

**Comment by kahumuzabe** [comment]
I had consolotvs version 6.3 installed, I then downgraded to 5.4 and every thing is fine.

**Comment by ConsoleTVs** [comment]
@tpharaoh The issue is that they do not read the docs, they watch the youtube video (and it's outdated) and come here posting this without reading how does the new version work. There are dozens of issues like that left in the repo...

**Comment by kahumuzabe** [comment]
Thanks for the Correction @ConsoleTVs

**Comment by ConsoleTVs** [comment]
Reading the new docs will help anyone who face this same issue!

**Comment by Miguelhdz9529** [comment]
![image](https://user-images.githubusercontent.com/46543553/50932330-df5b5f00-142a-11e9-8ef7-0a537147afad.png)

**Comment by ConsoleTVs** [comment]
Claramente no has instalado la libreria. Puedes mirarlo tu mismo intentando ver si existe la carpeta vendor/consoletvs/charts. Si existe probablemente tengas una version menor a la 6. En la documentacion online te dice como instalar y usar la 6. Videotutoriales estan anticuados.

**Comment by Jerad30** [comment]
@ConsoleTVs  
Hi I'm also facing this issue i tried also ways to fix but i couldn't make it please help me to fix this issues.
Laravel version is 5.5.45
PHP version is 7.3.2
Charts version is 6.3

**Service Provider** 
ConsoleTVs\Charts\ChartsServiceProvider::class,

**Aliases**
'Charts' => ConsoleTVs\Charts\Charts::class,

In Controller i'm using like - **use Charts;**

```
$chart = Charts::new('line', 'highcharts')
            ->setTitle('My nice chart')
            ->setLabels(['First', 'Second', 'Third'])
            ->setValues([5,10,20])
            ->setDimensions(1000,500)
            ->setResponsive(false);
```
In Layout i'm using like - {!! Charts::assets() !!}
In home Blade using like - {!! $charts->render() !!}

I'm getting an error like 

![untitled](https://user-images.githubusercontent.com/7511481/53236937-7880c500-36bb-11e9-893b-1c8e6af52b08.png)

**Comment by LittleDouZi** [comment]
> @ConsoleTVs
> Hi I'm also facing this issue i tried also ways to fix but i couldn't make it please help me to fix this issues.
> Laravel version is 5.5.45
> PHP version is 7.3.2
> Charts version is 6.3
> 
> **Service Provider**
> ConsoleTVs\Charts\ChartsServiceProvider::class,
> 
> **Aliases**
> 'Charts' => ConsoleTVs\Charts\Charts::class,
> 
> In Controller i'm using like - **use Charts;**
> 
> ```
> $chart = Charts::new('line', 'highcharts')
>             ->setTitle('My nice chart')
>             ->setLabels(['First', 'Second', 'Third'])
>             ->setValues([5,10,20])
>             ->setDimensions(1000,500)
>             ->setResponsive(false);
> ```
> In Layout i'm using like - {!! Charts::assets() !!}
> In home Blade using like - {!! $charts->render() !!}
> 
> I'm getting an error like
> 
> ![untitled](https://user-images.githubusercontent.com/7511481/53236937-7880c500-36bb-11e9-893b-1c8e6af52b08.png)

Hey, I face the same problem like you last time and this is what I did to solve the problem. 
I am using: Laravel 5.8 and consoletvs/charts 6.*

1. Uninstall and reinstall. 
2. Follow all the instruction as per https://charts.erik.cat/getting_started.html#screenshots
    P.S. (Do not follow any other guide or whatever source as some of it is outdated)

Done! and you shall get your desire chart!

![image](https://user-images.githubusercontent.com/40311182/55141102-9470fe00-5174-11e9-9738-81979cf38559.png)

**Comment by Jerad30** [comment]
Hey @LittleDouZi thank you for your help but I fixed it the next day and compare to this use google chats api it's very easy handle and modify and same time google api no need to install and reinstall again and again it's one time code
