### ISSUE TITLE
[3.0] c3 x-axis date

### ISSUE THREAD

**Issue by BlueTeck** [ConsoleTVs/Charts#76]
Hi,

I've tested the new c3 libary in version 3.0. Thanks for including them.

I am using this template:
https://github.com/ConsoleTVs/Charts/blob/master/resources/views/c3/multi/line.blade.php

Everything is working fine, but I can't set the x-axis to type time:

`
axis: {
        x: {
            type: 'timeseries',
            tick: {
                format: '%Y-%m-%d'
            }
        }
    }
`

Should I add a new timeseries template? Or do you have another suggestion?

Regards,
Timo

![image](https://cloud.githubusercontent.com/assets/1961634/20462490/5c3d8818-af1f-11e6-8e5a-5a14dce46505.png)

**Comment by ConsoleTVs** [comment]
Pff tha's some big deal over there, it's not implemented in any chart, what do you suggest?

**Comment by BlueTeck** [comment]
Add new templates, something like c3/multi/line**-time**.blade.php ?

**Comment by ConsoleTVs** [comment]
Okai, may you add it then? :D

**Comment by BlueTeck** [comment]
For me the following template is working, but we have to add two parameter to the builder, to allow custom time formats:

```html
@include('charts::_partials.container.div')
<script>
    var {{ $model->id }} =
    c3.generate({
        bindto: '#{{ $model->id }}',
        data: {
            x: 'x',
            xFormat: '%d.%m.%Y', //date input format -> should be set via chart builder
            columns: [
                @foreach($model->datasets as $ds)
                    ["{{ $ds['label'] }}",@foreach($ds['values'] as $value){{ $value }},@endforeach],
                @endforeach
                ["x", @foreach($model->labels as $label)"{{ $label }}",@endforeach]
            ]
        },
        axis: {
            x: {
                type: 'timeseries',
                tick: {
                    format: '%d.%m.'  //date output format -> should be set via chart builder
                },
            },
            y: {
                label: {
                    text: "{{ $model->element_label }}",
                    position: 'outer-middle',
                }
            },
        }
    });
</script>
```

Or I will use a custom view and we leave the charts libary as it is?

**Comment by ConsoleTVs** [comment]
Will take a look into it myself, I'm finishing the docs first

**Comment by tambolishahid** [comment]
Hello,

How I can have timeseries chart with HighCharts?

Please help

**Comment by ConsoleTVs** [comment]
Hello, currently we support the charts mentioned in the docs, other charts will need to be build manually atm... I'm sorry :c
