### ISSUE TITLE
[Feature request] Override labels

### ISSUE THREAD

**Issue by bart** [ConsoleTVs/Charts#82]
Maybe it would be great to override labels on the fly either by setting them directly as an associative array or by passing data as collection instead of a eloquent object.

Example:

```
$chart = Charts::database(Account::all(), 'pie', 'highcharts')
            ->title(__('Account types'))
            ->dimensions(1000, 500)
            ->responsive(true)
            ->groupBy('type');
``` 

In this case, type is an integer where 1 stands for admin account, 2 stands for user account and 3 stands for guest account. I expect the chart to show me a pie diagram with the labels "Admin", "User" and "Guests" instead of 1, 2 and 3.

Maybe something like this?

```
$chart = Charts::database(Account::all(), 'pie', 'highcharts')
            ->title(__('Account types'))
            ->dimensions(1000, 500)
            ->responsive(true)
            ->labels([1 => 'Admin', 2 => 'User', 3 => 'Guests'])
            ->groupBy('type');
```

What do you think about it? Would it makes sense?

**Comment by ConsoleTVs** [comment]
Check the https://github.com/ConsoleTVs/Charts/blob/master/docs/3.0/readme.md#database-charts

GroupBy arguments! We have a 2nd argument that sets the labels according to a relationship

**Comment by bart** [comment]
I'm not sure if this will work for the example above. I'm not talking about relations but about something like "mutators", so that you can say: "Hey, I want the column "foo" being displayed as bar". Will this be possible with the 2nd argument? Thanks so much!

**Comment by ConsoleTVs** [comment]
Its mostly a relationship... Index = string,  the string is mostly saved in a database, don't you think?

**Comment by bart** [comment]
Yep, but in my case it's not a relation ;) It's a simple type. Another example could be the status of posts. Maybe this is a way better example here. You have posts that can have different statuses like "Published" (1), and "Draft" (0). The status is stored in column "status" as an integer (without any relation). Now I want to create a pie chart that shows me published vs. draft posts.

**Comment by ConsoleTVs** [comment]
Damn.. its a bad practice not to store them :p will see what I can do!

**Comment by bart** [comment]
Haha, thank you!

**Comment by bart** [comment]
@ConsoleTVs Created a PR for the feature request above. Please let me know as soon as you merged it and created a new release. Thanks!
