### ISSUE TITLE
Error Pic

### ISSUE THREAD

**Issue by BlueTeck** [ConsoleTVs/Charts#87]
The error image:

$img_url = 'http://www.iconsfind.com/wp-content/uploads/2015/12/20151208_56663ed552e5d.png';

is hardcoded and called via http. This should be customizable or at least callable from a https site.

Regards,
Timo

`Mixed Content: The page at 'https://XXXXX' was loaded over HTTPS, but requested an insecure image 'http://www.iconsfind.com/wp-content/uploads/2015/12/20151208_56663ed552e5d.png'. This content should also be served over HTTPS.
user_repartition:390 

GET http://www.iconsfind.com/wp-content/uploads/2015/12/20151208_56663ed552e5d.png 403 (Forbidden)`

**Comment by BlueTeck** [comment]
But it should not occur in productive system on the other hand...

**Comment by ConsoleTVs** [comment]
That's the point, it's something it should not happen, but it's not nessesary to push assets only for this. Do you have any suggestion rather than add it in the config array?

**Comment by BlueTeck** [comment]
I think it is okay how it is. I'm developing unter https, but I will imagine an awesome icon, next time I made a mistake ;)
