### ISSUE TITLE
Missing comma in chartjs bar template

### ISSUE THREAD

**Issue by jbpiacentino** [ConsoleTVs/Charts#89]
Seems chartist bar template line 25 should read
`"{{ sprintf('#%06X', mt_rand(0, 0xFFFFFF)) }}",` (added comma at end of line)

**Comment by ConsoleTVs** [comment]
There are only 22 lines in the template, where are you looking at?

https://github.com/ConsoleTVs/Charts/blob/master/resources/views/chartist/bar.blade.php#L22

We're on 3.0.1 atm

**Comment by jbpiacentino** [comment]
I'm looking at chartjs template (not chartist)
https://github.com/ConsoleTVs/Charts/blob/master/resources/views/chartjs/bar.blade.php#L25

**Comment by ConsoleTVs** [comment]
"Seems chartist bar template line 25 should read"

Damn i got baited by your spelling misstake! Indeed there needs to be a coma, fixing it now, for 3.0.2

**Comment by ConsoleTVs** [comment]
https://github.com/ConsoleTVs/Charts/commit/f85f4b2372c721d38deaaaecbffbe5d85a0745f3
