### ISSUE TITLE
Target class [ConsoleTVs\Charts\Registrar] does not exist.

### ISSUE THREAD

**Issue by vaishnavikshylaji** [ConsoleTVs/Charts#9]
**Required information**
 - Charts Version 7.3
 - Laravel Version 8.90
 - PHP Version 8.0
 - Frontend JS e.g. Chart.js

consoletvs/charts/registrar is not found

**Comment by tabacitu** [comment]
Please see https://github.com/ConsoleTVs/Charts/issues/1

**Comment by Muhannad-Drovox** [comment]
Have you figured out how to solve this? I downgraded to v6 and now I keep getting this. When I remove it I get another error Target class [App\Providers\Charts] does not exist.
Any help would be apricated
