### ISSUE TITLE
[Bug?] GroupByMonth Figures not accurate

### ISSUE THREAD

**Issue by stevepop** [ConsoleTVs/Charts#90]
Hi,

First I want to say thank you for the great work on this package. 

I have been trying it out on my project unfortunately, the charts do not seem to be accurate compared to my data. For instance I followed your manual to write the following;

```
$recentSignups = $this->user->getRecentSignups();

        $signupsChart = Charts::database($recentSignups, 'line', 'chartjs')
            ->colors(['#5cb85c', '#5cb85c', '#5cb85c'])
            ->elementLabel("Member Signups")
            ->dimensions(950, 600)
            ->responsive(false)
            ->groupByMonth('2016', true);
```
getRecentSignups() returns the user signups for the last 6 months. However when the chart renders, it displays months from January to December, which means dates not present in the data are being filled with arbitrary numbers. See rendered chart below;
<img width="926" alt="signups_chart" src="https://cloud.githubusercontent.com/assets/526063/20649719/8bc67d80-b4bd-11e6-82e8-81cdc8ad6392.png">

See below the query for user signups in September as against what displays on the chart;
<img width="697" alt="number_signups" src="https://cloud.githubusercontent.com/assets/526063/20649726/a6c791b4-b4bd-11e6-867d-98afc32d0d8b.png">

I am not sure what is going on here but I believe I followed the description in your documentation but not getting the intended result.

Thanks.

**Comment by ConsoleTVs** [comment]
Hello @stevepop Have you tried using lastByMonth instead?

**Comment by stevepop** [comment]
HI @ConsoleTVs, following your suggestion to try lastByMonth method, I used it and still did not get correct count. See below with 09-2016 highlighted. It shows member signups as 87 when correct count should be 670 from the query shown above.
<img width="783" alt="by_last_month" src="https://cloud.githubusercontent.com/assets/526063/20670084/3a21f132-b56f-11e6-98c0-0fe421a1d1c3.png">

**Comment by ConsoleTVs** [comment]
I'll take a look once I have time. You can still build the array and use a normal create function instead of the database meanwhile :)
