### ISSUE TITLE
Chart context menu icon Highcharts

### ISSUE THREAD

**Issue by leonh12** [ConsoleTVs/Charts#92]
When I want to use the highcharts library, the Chart context menu button icon doesn't show up. In the video tutorial it showed 3 horizontal lines, but mine just shows a box with border lines.
<img width="840" alt="screen shot 2016-11-28 at 17 10 02" src="https://cloud.githubusercontent.com/assets/23411290/20675713/8aaf7ade-b58d-11e6-9aa6-61d67e8cf8b9.png">

My code
<img width="468" alt="screen shot 2016-11-28 at 17 10 32" src="https://cloud.githubusercontent.com/assets/23411290/20675746/9d08e8dc-b58d-11e6-8a2f-7d72fe598d6e.png">

My version is "consoletvs/charts": "3.0.2"

**Comment by ConsoleTVs** [comment]
Yes, this is a bug since we're using CDN now, I don't really know how to fix it tho :s, will keep an eye

**Comment by leonh12** [comment]
Oh I fixed it. I just added the highcharts css to layouts/app.blade.php
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highcharts/5.0.4/css/highcharts.css">
<img width="856" alt="screen shot 2016-11-28 at 17 18 04" src="https://cloud.githubusercontent.com/assets/23411290/20676020/a855b0de-b58e-11e6-85eb-1a903ff962d1.png">

**Comment by ConsoleTVs** [comment]
Can you give me the cdn url so I can add it?

**Comment by leonh12** [comment]
Or you can do this in config/charts.php
<img width="777" alt="screen shot 2016-11-28 at 17 21 21" src="https://cloud.githubusercontent.com/assets/23411290/20676174/29f470e4-b58f-11e6-975f-55dd91e8bb2e.png">

**Comment by leonh12** [comment]
https://cdnjs.cloudflare.com/ajax/libs/highcharts/5.0.4/css/highcharts.css

**Comment by ConsoleTVs** [comment]
Added here: https://github.com/ConsoleTVs/Charts/commit/85e608fa23a953cc14a8bba2c6af7d69e5576cb5

Thanks!
