### ISSUE TITLE
[3.0] Trying to get role names in chart

### ISSUE THREAD

**Issue by leonh12** [ConsoleTVs/Charts#95]
I want to display how many admins and how many subs I have in a chart and then to display the role names on the x-axis. This is what I have.

My tables

users:
<img width="1118" alt="screen shot 2016-12-02 at 11 58 25" src="https://cloud.githubusercontent.com/assets/23411290/20831866/74219390-b887-11e6-8c8a-867ff8c813cd.png">

roles:
<img width="222" alt="screen shot 2016-12-02 at 11 58 56" src="https://cloud.githubusercontent.com/assets/23411290/20831897/934f933e-b887-11e6-8b2a-61bb183b55d7.png">

code:
<img width="535" alt="screen shot 2016-12-02 at 11 59 19" src="https://cloud.githubusercontent.com/assets/23411290/20831906/a2b5d176-b887-11e6-8188-b6a916578721.png">

result:
<img width="773" alt="screen shot 2016-12-02 at 12 01 41" src="https://cloud.githubusercontent.com/assets/23411290/20831909/ac6d5fcc-b887-11e6-8550-b956be75aeb6.png">

**Comment by ConsoleTVs** [comment]
Hi I'm sorry, I've just created the version. Use https://github.com/ConsoleTVs/Charts/releases/tag/3.0.5

(3.0.5) to use this feature!

**Comment by leonh12** [comment]
thank you it works now

**Comment by ConsoleTVs** [comment]
You're welcome :D
