### ISSUE TITLE
Formatting options for chart values

### ISSUE THREAD

**Issue by lucasvdh** [ConsoleTVs/Charts#97]
# Formatting chart values

It would be nice to provide some default formatting options for chart values.

## The use case

For this example I'll use the Morris library. 

Lets say I have a donut chart with multiple filesizes as values that I want to display in a human friendly way. 
Currently it's not possible to use formatted values because some libraries won't understand "100 MB" as a value.

## Proposal

A solution for this problem would be to make use of the formatters provided by the libraries.

**Morris donut chart example:**
```blade
@include('charts::_partials/container.div-titled')

<script type="text/javascript">
    $(function (){
        Morris.Donut({
            element: "{{ $model->id }}",
            resize: true,
            data: [
                @for($i = 0; $i < count($model->values); $i++)
                    {
                        label: "{{ $model->labels[$i] }}",
                        value: "{{ $model->values[$i] }}"
                    },
                @endfor
            ],
            @if($model->formatter->name == 'filesize')
            formatter: function (y, data) {
                return humanFilesize(y);
            },
            @elseif($model->formatter->name == 'append')
            formatter: function (y, data) {
                return y + '{{ $model->formatter->value }}';
            },
            @endif
            @if($model->colors)
                colors: [
                    @foreach($model->colors as $c)
                        "{{ $c }}",
                    @endforeach
                ]
            @endif
        })
    });
</script>
```

**Global JS:**
```javascript
function humanFilesize(bytes) {
	var thresh = 1024;

	if(Math.abs(bytes) < thresh) {
		return bytes + ' B';
	}

	var units = ['kB','MB','GB','TB','PB','EB','ZB','YB'],
			u = 0;

	do {
		bytes /= thresh;
		++u;
	} while(Math.abs(bytes) >= thresh && u < units.length - 1);

	return bytes.toFixed(1)+' '+units[u];
}
```

**Example implementations:**

```php
// Filesize
Charts::create('donut', 'highcharts')
  ->title('My nice chart')
  ->labels(['First', 'Second', 'Third'])
  ->values([1024,2048,4096])
  ->formatter('filesize')
  ->dimensions(1000,500)
  ->responsive(false);

// Appending a string
Charts::create('donut', 'highcharts')
  ->title('My nice chart')
  ->labels(['First', 'Second', 'Third'])
  ->values([1024,2048,4096])
  ->formatter('append', ' kB')
  ->dimensions(1000,500)
  ->responsive(false);
```

## Optimization

You could even define the formatter for an entire library and just include it as a view. 

**resources/views/morris/formatter.blade.php**
```blade
@if($model->formatter->name == 'filesize')
formatter: function (y, data) {
    return humanFilesize(y);
},
@elseif($model->formatter->name == 'append')
formatter: function (y, data) {
    return y + '{{ $model->formatter->value }}';
},
@endif
```

I'm not sure if other libraries than Morris support the same kind of formatting for all charts. So that might be something to look into.

## Conclusion

In my opinion this would be a huge plus. I'm currently inclined to not use the Charts package because of this missing functionality.

Another plus of the structure described above, is that more formatters can easily be added.

The best solution would be to let a user define his own formatter in javascript. But this feels kinda messy, hence a set of available formatters.

If you have any other ideas on how to solve the formatting problem, **please comment**. I'm prepared to contribute, but would like to hear your thoughs before I do.

**Comment by ConsoleTVs** [comment]
I think it's a really good idea, the points it's clear and well explained, but we need to look forward what can be done with this because; as you said, some libraries may not support it, and I'm sure some of them won't. So yes, we can go ahead with this even if some libraries don't support it, but I think the moest common ones will support this feature and this is the most important thing. If you would like to contribute I would be really happy to hear it, remember I can also help you develop it but i'm also busy! We should keep things organized because I don't want to spend a week fixing stuff like I did before 3.0 release. So yes, we should use a view for each library since it will probably be the same way on all it's charts.

**Comment by ConsoleTVs** [comment]
After studing the situation, I don't currently want to spend time on this althought it's a good idea. I thin't thing I should focus on this at the moment but I really enjoy the idea! Thanks!
